sqlmesh/core/plan/builder.py
tests/core/test_integration.py

This allows users to create new environment views for selected models only without actually backfilling anything.

Feat: Allow creating environments without changes when using selector

---

sqlmesh/core/engine_adapter/base.py
sqlmesh/core/engine_adapter/mysql.py
sqlmesh/core/engine_adapter/postgres.py
sqlmesh/core/state_sync/engine_adapter.py
sqlmesh/migrations/v0056_restore_table_indexes.py
tests/core/engine_adapter/test_base.py
tests/core/engine_adapter/test_mysql.py
tests/core/engine_adapter/test_postgres.py

Previously, we created backup state tables using the CTAS statement, which didn't retain any table indexes or constraints. 
This change fixes the issue and also adds a migration script that recreates the original indexes for those who may have restored from a backup in the past.

Fix!: Retain indexes when creating state table backups

---

sqlmesh/core/state_sync/engine_adapter.py
sqlmesh/integrations/github/cicd/command.py
sqlmesh/utils/errors.py
tests/integrations/github/cicd/test_github_commands.py

This fixes 2 issues:
* when a plan fails to apply for any reason, the bot provided no feedback and would appear running forever; this ensures that we always provide feedback by cacthing all exceptions
* when a plan fails to to a conflict, the user can typically solve this by simply `/deploy`ing again, so this handles that case by treating it like a `skipped` plan which is less scary than a failure.

fix: always provide feedback during plan execution

---

sqlmesh/dbt/model.py
tests/dbt/test_config.py

With this update, SQLMesh will no longer attempt to render queries of dbt models to extract additional dependencies that were not expressed using the `ref` macro.
As a result, this update speeds up the loading of dbt projects, as we no longer rely on unoptimized rendered queries to construct the set of dependencies needed to build the model DAG.

Fix: Prepopulate the model's depends on in-memory cache for converted dbt models

---

tests/web/conftest.py
tests/web/test_lineage.py

This PR attempts to fix flaky web/UI lineage tests (when run in parallel) by reseting FastAPI app dependency overrides in between tests and creating a new TestClient per test.

Chore: Isolate web tests

---

sqlmesh/core/config/base.py
sqlmesh/core/config/root.py
tests/core/test_config.py

Prior to this change nested updates to Gateways would only work with YAML config files. This update makes it work with Python config too. 
`test_load_yaml_config_env_var_gateway_override` passed without any changes (confirming expected behavior) while `test_load_py_config_env_var_gateway_override` fails without the change.

fix!: properly nested update gateway configs

---

Makefile

It's been observed that the engine adapter integration tests can be a bit flaky. Often this is caused by transient network issues.
Rather than trying to catch specific errors and determine which ones may or may not be retryable (and add retry logic within each engine adapter), a quick win could be to use `pytest-retry` to try the selected tests again if they fail.
Note that this was already enabled for the Trino tests, this PR just extends it to the other adapters

Chore: Add retries on engine adapter integration tests

---

sqlmesh/core/engine_adapter/bigquery.py
sqlmesh/core/engine_adapter/databricks.py
sqlmesh/core/schema_diff.py
tests/core/engine_adapter/test_base.py
tests/core/test_schema_diff.py

This update adds support for adding fields to a nested type in BigQuery without dropping the existing column by using the ([BigQuery API](https://cloud.google.com/bigquery/docs/managing-table-schemas#api_1)), fixes #2321

Feat: Support BigQuery nested column additions without dropping

---

setup.py
sqlmesh/core/console.py
sqlmesh/core/constants.py
sqlmesh/integrations/github/cicd/controller.py
web/server/console.py

Changed some type hints due to the following errors I encountered while iterating locally:
```
sqlmesh/core/constants.py:44: error: Module has no attribute "sched_getaffinity"  [attr-defined]
sqlmesh/integrations/github/cicd/controller.py:698: error: Argument "result" to "conclusion_handler" has incompatible type "TestResult | None"; expected "TestResult"  [arg-type]
sqlmesh/integrations/github/cicd/controller.py:698: error: Argument "output" to "conclusion_handler" has incompatible type "str | None"; expected "str"  [arg-type]
```

Chore!: bump sqlglot to v25.20.1

---

sqlmesh/core/model/definition.py
tests/core/test_context.py

Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1725579711884559

Fix: allow overriding blocking setting of builtin audits

---

sqlmesh/core/context.py
sqlmesh/core/loader.py

Normally, we don't load the project on `sqlmesh run` command. However, we still need to load user-defined signals in order for the run to work correctly.
This update ensures that SQLMesh loads just signals when running models.
Closes #3104

Fix: Make sure signals are loaded when running models

---

sqlmesh/dbt/target.py
tests/dbt/test_config.py

Fixes this issue due to latest dbt-sqlserver release:
```
FAILED sqlmesh/tests/dbt/test_config.py::test_db_type_to_column_class - ModuleNotFoundError: No module named 'dbt.adapters.sqlserver.sql_server_column'
```

fix: support dbt sqlserver 1.8.0

---

README.md

Pypi only renders images from external URLs, so this PR replaces the README relative image URLs with external github URLs

Chore: use external github image links in README

---

sqlmesh/core/snapshot/evaluator.py
tests/core/test_snapshot_evaluator.py

Prior to this change, making a forward-only change to a managed model only worked if you did it via a dev environment first.
Applying it directly to prod resulted in the following error on Snowflake: `SQL compilation error: Invalid operation Cannot clone from an dynamic table.` because in order to create the dev preview table (which [always gets created](https://github.com/TobikoData/sqlmesh/issues/2496) regardless of the environment), SQLMesh triggers a clone of the current prod table.
This PR does two things:
- Allows the evaluation strategy to decide if `clone()` is suitable for creating dev preview tables
- Implements `migrate()` for the `EngineManagedStrategy` now that I better understand the conditions that can trigger `migrate()` in the first place.
The usual function of …

Fix!: Dont clone managed tables to create dev previews

---

sqlmesh/core/config/scheduler.py
sqlmesh/core/context.py
sqlmesh/core/plan/evaluator.py
tests/conftest.py
tests/core/test_context.py
tests/core/test_plan_evaluator.py

Introduce a common factory method to create the builtin scheduler instead of directly constructing the `Scheduler` class.

Chore: Use factory method to create builtin scheduler

---

sqlmesh/core/analytics/collector.py
sqlmesh/core/console.py
sqlmesh/core/context.py
sqlmesh/core/plan/__init__.py
sqlmesh/core/plan/definition.py
sqlmesh/core/plan/evaluator.py
sqlmesh/schedulers/airflow/client.py
sqlmesh/schedulers/airflow/common.py
sqlmesh/schedulers/airflow/plan.py
tests/conftest.py
tests/core/analytics/test_collector.py
tests/core/test_context.py
tests/core/test_plan_evaluator.py
tests/schedulers/airflow/test_client.py
tests/schedulers/airflow/test_integration.py
tests/schedulers/airflow/test_plan.py
web/server/console.py

This update introduces a light-weight serializable version of the plan object which is used specifically for evaluation. This allows us to keep a consistent interface across various variances of plan evaluation (eg. airflow / builtin).

Chore!: Introduce the evaluatable version of a plan object

---

web/client/openapi.json
web/client/src/library/components/fileExplorer/context.tsx
web/client/src/library/pages/root/Navigation.tsx
web/server/utils.py
web/server/watcher.py

fixing https://github.com/TobikoData/sqlmesh/issues/3109
so when using `pooling` (and pooling is not default option for wathfiles). It seems to treat some files (like symlinks for example) as deleted and just keeps emitting deletion change. And that results in UI keep triggering updates and API calls (an infinite loop)

fix: switch from pooling to default method to detect changes

---

docs/concepts/models/model_kinds.md
sqlmesh/core/dialect.py
sqlmesh/core/engine_adapter/base.py
sqlmesh/core/engine_adapter/mixins.py
sqlmesh/core/model/kind.py
sqlmesh/core/model/meta.py
tests/core/engine_adapter/test_base.py
tests/core/test_model.py
tests/core/test_snapshot_evaluator.py

Prior to this PR the when matched expression only supported a single expression. This PR makes it so you can pass in multiple. We assume the underlying engine will support it (will get an error at runtime if that is not the case).

feat: support multiple when matched inc unique key

---

tests/conftest.py

This resolves the flakiness I was able to recreate locally.
If we continue to have issues, then I would suggest using `pytest-antilru` and disabling lru cache here: https://github.com/TobikoData/sqlmesh/blob/0384db3ac42c869cb9941d508037e29c055feaba/web/server/settings.py#L58
I don't want to add this if it isn't needed but it seems like it could cause issues.

chore: rescope lineage cache in tests

---

sqlmesh/core/dialect.py
tests/core/test_model.py

Prior to this PR if a user had variables in their model definition and used when_matched then they would get a parsing error. This is because after we replace variables we generate SQL with the model def and reparse it which doesn't involve the Pydantic model validators. As a result we have to generate the SQL in a format that matches what the user would have originally put in which is with the comma separating it. 
Updated the test case to include a variable to make sure this is tested going forward.

fix: correctly generate when_matched SQL

---

sqlmesh/core/dialect.py

[Public slack context](https://tobiko-data.slack.com/archives/C044BRE5W4S/p1726478874076549)
This PR overrides SQLGlot's `_warn_unsupported()` to suggest the usage of Jinja on the occasion that the (unsupported) statement is attempting to reference the physical table.

feat: Add SQLMesh warning when an exp.Command is parsed

---

sqlmesh/core/context.py
sqlmesh/core/model/definition.py
sqlmesh/utils/__init__.py

We've started building off the Python APIs and noticed that `UniqueKeyDict` has a number of methods that are not type-safe, including `__getitem__`, `values`, and `items`. This PR attempts to correct that. Correcting `UniqueKeyDict` made it necessary to make some changes elsewhere to satisfy `mypy`. Let me know if I did those correctly or not.

fix: types

---

sqlmesh/core/renderer.py
tests/core/test_model.py

Previously, the query rendering failed when the `JINJA_QUERY_BEGIN` block contained standalone comments.

Fix: Support comments in Jinja queries coming from dbt models

---

sqlmesh/core/model/kind.py
sqlmesh/core/plan/builder.py
sqlmesh/core/state_sync/engine_adapter.py
tests/core/test_plan.py

Previously, SQLMesh assigned an effective_from date to external / embedded models which led to unexpected errors.

Fix: Only set effective_from for evaluatable models

---

sqlmesh/core/context.py
tests/core/test_context.py

Otherwise invalid results are produced when rendering models downstream of unpromoted forward-only changes.

Fix: Take deployability into account when rendering a model's query with the 'render' command

---

docs/integrations/engines/gcp-postgres.md
sqlmesh/core/config/connection.py

GCP Cloud SQL client libraries supports passing credentials built from service accounts keyfiles or json https://github.com/GoogleCloudPlatform/cloud-sql-python-connector?tab=readme-ov-file#configuring-the-connector

feat: add support for GCP postgres instance authentication using IAM with service account keyfile/keyfile json

---

.circleci/continue_config.yml
.gitignore
Makefile
docs/guides/configuration.md
docs/integrations/engines/athena.md
docs/integrations/overview.md
mkdocs.yml
pytest.ini
setup.py
sqlmesh/core/config/common.py
sqlmesh/core/config/connection.py
sqlmesh/core/engine_adapter/__init__.py
sqlmesh/core/engine_adapter/athena.py
sqlmesh/core/engine_adapter/base.py
sqlmesh/core/engine_adapter/trino.py
tests/core/engine_adapter/config.yaml
tests/core/engine_adapter/test_athena.py
tests/core/engine_adapter/test_integration.py
tests/core/test_connection_config.py

Initial implementation of an Athena adapter. Addresses #1315

Feat: Athena adapter

---

sqlmesh/core/engine_adapter/athena.py

Remove the dependency on `tenacity` from the Athena adapter to prevent fresh sqlmesh installs from breaking because `tenacity` is listed as a dev dependency and not a main dependency.
This dependency is no longer needed as the issue it was added to resolve turned out to be caused by something else.

Fix: Remove dependency on tenacity from Athena adapter

---

sqlmesh/core/renderer.py
sqlmesh/core/test/definition.py
tests/core/test_test.py

This PR reverts the `normalize_identifiers` changes introduced in https://github.com/TobikoData/sqlmesh/pull/3077. Switching off identifier normalization has unintended side effects, e.g. `find_tables` treats CTE references like models if there's a casing mismatch, which can lead to more errors.
The motivation was a unit testing issue where we raised an error saying that input data for a model was missing, even though it was a CTE that we knew how to populate.
Not sure if this PR is breaking, please let me know if you think of a case where we'd need a migration and I can update the title accordingly.

Fix: regression caused by optionally normalizing identifiers in renderer

---

sqlmesh/core/engine_adapter/base.py
tests/core/engine_adapter/test_base.py

Otherwise, SQLMesh inserts values of incorrect type into the time filter.

Fix: Fix columns-to-types when inserting by time partition if the type of the time column is unknown

---

sqlmesh/core/dialect.py

I checked our overrides and I think this is the only outdated one. Perhaps we want to automate this going forward so that we don't have to manually cross-check if the arguments match between our overrides and the base parser methods. There wasn't necessarily a bug here, but figured I'd update this to avoid surprises in the future.

Fix: update _parse_table_parts to reflect latest sqlglot signature

---

docs/reference/overview.md

May be worth getting rid of this altogether, wasn't sure which API page to default to. Perhaps CLI is a good default if folks think this page is unnecessary.

Chore: remove incomplete & outdated commands from API overview doc page

---

docs/reference/cli.md
docs/reference/configuration.md
docs/reference/notebook.md
sqlmesh/cli/main.py
sqlmesh/core/config/format.py
sqlmesh/core/context.py
sqlmesh/core/dialect.py
sqlmesh/magics.py
tests/core/test_dialect.py

Allows users to change the formatter so that it always produces the `CAST(foo AS type)` syntax over `::`. This may come in handy for users that want to easily copy-paste their model queries without having to switch back the `::` manually.
Context: https://tobiko-data.slack.com/archives/C07HJH22U9Z/p1727216482891999

Feat: allow formatter to use CAST over :: syntax

---

sqlmesh/core/engine_adapter/bigquery.py

This is related to https://github.com/TobikoData/sqlmesh/issues/3184 but does not fix it. What it provides is a general function for converting a sqlglot schema to a bigquery schema. This new function is not in the codepath of altering schemas, but it should be possible to use it there to actually fix the issue.

fix: properly convert nested types to BQ schema

---

docs/integrations/dbt.md
sqlmesh/dbt/basemodel.py
sqlmesh/dbt/seed.py
tests/dbt/test_transformation.py

Add support for the `column_types` attribute for seeds in dbt, fixes: #3163 
If either or both `column_types` and `columns` are defined, they are reconciled to determine the seed configs. Additionally, support for the `quote_columns` property has been added. They can be defined in the `dbt_project.yml` file:
```yaml
seeds:
<seed name>:
+quote_columns: true
+column_types:
<column name>: <SQL data type>
```
or in the seed properties configuration file:
```yaml
seeds:
- name: <seed name>
config:
quote_columns: true
column_types:
<column name>: <SQL data type>
columns:
- name: <column name>
description: "column description"
```
[dbt docs](https://docs.getdbt.com/reference/resource-configs/column_types)

Feat: Support column types for dbt seeds

---

sqlmesh/core/config/connection.py

After some testing, we realize this actually is necessary. This is a slightly cleaned up version of the previous work I did here.

Allow clickhouse connection pool

---

sqlmesh/core/engine_adapter/base.py
sqlmesh/core/engine_adapter/bigquery.py
sqlmesh/core/engine_adapter/mysql.py
sqlmesh/core/engine_adapter/snowflake.py
tests/core/engine_adapter/test_bigquery.py

Closes #3164 
Docs: https://cloud.google.com/bigquery/docs/materialized-views-intro#limitations

Fix(bigquery): materialized views do not support column comments

---

docs/concepts/models/model_kinds.md
sqlmesh/core/engine_adapter/base.py
tests/core/engine_adapter/integration/test_integration.py
tests/core/engine_adapter/test_base.py
tests/core/engine_adapter/test_clickhouse.py

This corrects the SCD Type 2 By Column default behavior to use execution time for new rows after the table is initially loaded. This matches what the documentation example says it should behave. This does mean there is a behavior change for current users but the current behavior seems to be a bug. There is not a way for a user to maintain old behavior if they wanted it since we consider it a bug. 
From reviewing the code, `truncate` is a great way to identify if a table is being loaded for the first time. This also means that if a user issues a restatement on the table and wants to rebuild from scratch then it would also be set to `truncate` and would mimic loading the rows for the first time.

fix!: correctly use execution time on new rows for scd type 2 by column

---

sqlmesh/core/model/cache.py
tests/utils/test_cache.py

Model example:
```
MODEL (
name agreement.stg_testing,
kind FULL,
);
@DEF(filter_, txmetasource IN ('A'));
SELECT
*
FROM iceberg.dbo.table1
WHERE
@filter_
LIMIT 10
```
Prior to this fix, changing the `filter_` macro resulted in a metadata change unless the cache was manually cleaned up.

Fix: Invalidate the optimized query cache entry when a macro definition changes within the model model definition

---

sqlmesh/integrations/github/cicd/command.py

Most users use the `run-all` bot command which runs several steps at once. Since it runs several steps it only fails if the execution of those steps fails. To understand which of those steps failed then you would check the bot output. This makes it easy to differentiate all the different types of failures.
This feels less intuitive when running a single step. Since there aren't sub-steps then having the only step that ran fail and not having the bot itself fail feels less intuitive. This might feel ok when running something like "Check Required Approvers" or "Run Tests" but less intuitive when running "Deploy to Prod". 
Therefore this PR keeps the run-all behavior the same, which we haven't received any feedback on, but then makes all the individual steps fail if the step itself fails. …

feat!: bot commands that run a single step raise on failure

---

sqlmesh/core/plan/builder.py
tests/core/test_plan.py

Related to #3196 
This PR addresses the issue by marking all changes in model types as breaking even in the case of a `forward-only` plan. 
The test hopefully ensures the validity of the work, but I was also able to recreate the issue in a more "complete" environment with the following steps:
1.`sqlmesh init duckdb`
2. `sqlmesh plan` and apply
3. Changing the incremental model to 
```
MODEL (
name sqlmesh_example.incremental_model,
kind VIEW,
start '2020-01-01',
cron '@daily',
grain (id, event_date)
);
SELECT
id,
item_id,
event_date,
FROM
sqlmesh_example.seed_model 
```
4. Running `sqlmesh plan --forward-only` and apply again. This gave the error:
```
File "..../sqlmesh/sqlmesh/core/engine_adapter/base.py", line 2007, in _execute
self.cursor.execute(sql, **kwargs) …
```

Fix: mark kind changes as breaking in forward only plan

---

sqlmesh/core/engine_adapter/bigquery.py
tests/core/engine_adapter/test_bigquery.py
tests/core/test_schema_diff.py

Fix issue of constructing schema fields for nested and array types, by using the function `__get_bq_schemafield` from https://github.com/TobikoData/sqlmesh/pull/3185 when constructing a record or array schema field and the function `_build_nested_fields` to recursively build nested fields, when appending to a record
fixes: #3184

Fix: Bigquery support of complex nested types

---

sqlmesh/core/engine_adapter/snowflake.py
tests/core/engine_adapter/integration/test_integration_snowflake.py

This change allows you to update `clustered_by` on a Snowflake model, trigger a forward-only plan and have the cluster key on the table be altered.
Previously, it would be a no-op which was a bit misleading

Feat: Snowflake: Handle forward_only changes to 'clustered_by'

---

sqlmesh/core/engine_adapter/mixins.py
tests/core/engine_adapter/test_base.py

There was an issue with the mssql adapter where we'd get back a dotted column from its `columns` method, e.g. `foo.bar.baz`, and then we'd turn that into a qualified column instead of treating it as a single identifier with literal dot characters. This in turn caused problems in the context of the generated `MERGE` statement, because qualified columns are syntactically invalid within the `INSERT` clause.

Fix: avoid parsing column names into qualified columns in InsertOverwriteWithMergeMixin

---

.circleci/continue_config.yml
sqlmesh/core/config/common.py
sqlmesh/core/config/connection.py
sqlmesh/core/engine_adapter/athena.py
sqlmesh/core/engine_adapter/base.py
sqlmesh/core/engine_adapter/shared.py
sqlmesh/utils/aws.py
tests/core/engine_adapter/integration/__init__.py
tests/core/engine_adapter/integration/conftest.py
tests/core/engine_adapter/integration/test_integration.py
tests/core/engine_adapter/integration/test_integration_athena.py
tests/core/engine_adapter/test_athena.py
tests/utils/test_aws.py

Feat: Support INCREMENTAL_BY_TIME_RANGE models on Athena/Hive

---

sqlmesh/core/context.py
sqlmesh/core/loader.py

No one can use custom materializations currently as far as I can surmise because of this. 
So perhaps I am kicking in the gears before others here. But we have a nifty custom materialization use cases that requires this fix.

Fix: load custom materializations on run

---

sqlmesh/dbt/seed.py
tests/dbt/test_transformation.py

This fix addresses an issue with dbt seeds where columns defined solely by a description, or where the data type was specified for only some columns, did not trigger type inference for the rest of the columns. It ensures that explicitly declared data types are set from the declaration while the types of the remaining columns are inferred.

Fix: Infer column types when data type is omitted in dbt seeds

---

sqlmesh/dbt/seed.py
tests/dbt/test_transformation.py

Prior to this change, any DBT seeds using the `data_type` variant of indicating the column type (as opposed to the other method of using a `column_types` property) would have their `columns_to_types` set in a different order than the source data.
This caused assumptions in the seed rendering logic to fail, producing queries where the values to insert did not line up with their column names.

Fix: DBT seed column order

---

sqlmesh/core/engine_adapter/base_postgres.py
sqlmesh/core/engine_adapter/mssql.py
sqlmesh/core/engine_adapter/redshift.py
tests/core/engine_adapter/integration/test_integration_redshift.py
tests/core/engine_adapter/test_redshift.py

***NOTE: redshift integration tests won't pass until sqlglot is bumped > 25.24.4***
#2791 introduced a regression in the varchar length workaround because it assumed the `columns()` method returned data types including their length/precision. That was true for MSSQL, but wasn't for Redshift.
This PR updates Redshift's `columns()` method to attach length/precision to data types.
Note: the `_columns_query()` method allowed postgres and redshift to use different columns queries inside postgres' `columns()` method. Redshift now needs to override the entire `columns()` method, so `_columns_query()` has been removed from postgres.

Fix(redshift): regression in varchar length workaround

---

sqlmesh/core/loader.py
tests/core/test_model.py

This addresses a bug that was [reported](https://tobiko-data.slack.com/archives/C044BRE5W4S/p1728485147986839?thread_ts=1728478460.658349&cid=C044BRE5W4S) in the Slack channel.
Our override of `_parse_table_parts` for Snowflake checks whether `@some_name...` appears in the registry's macros as a heuristic, to disambiguate macro funcs/vars from staged paths. Since we're [resetting](https://github.com/TobikoData/sqlmesh/blob/main/sqlmesh/core/loader.py#L301) the macro registry to `standard_macros` after loading the macros, we won't have access to the user-defined macros when this method is called (models are loaded after macros), so there are cases where the parsing will fail, i.e. when user-defined macros are used as table functions (see added test).

Fix: reset macro registry *after* loading models

---

sqlmesh/integrations/dlt.py
tests/cli/test_cli.py

Fix issue with generated dlt incremental query for dialects that don't support using alias reference for filtering by using the table column from the from clause

Fix: Modify dlt query filter not to use alias reference

---

.circleci/continue_config.yml
sqlmesh/core/engine_adapter/bigquery.py
sqlmesh/core/engine_adapter/mixins.py
sqlmesh/core/engine_adapter/shared.py
sqlmesh/core/engine_adapter/snowflake.py
tests/core/engine_adapter/integration/test_integration_bigquery.py

Follow-up PR from https://github.com/TobikoData/sqlmesh/pull/3205
Add the ability to change `clustered_by` in BigQuery tables in a forward_only fashion. Previously, we would silently succeed

Feat: BigQuery - Handle forward_only changes to clustered_by

---

docs/concepts/tests.md
sqlmesh/core/test/definition.py
tests/core/test_test.py

Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1727713003832279
This PR enables users to specify a custom schema name for their unit tests, instead of using a random one.

Feat: support custom unit testing schema names

---

sqlmesh/core/engine_adapter/databricks.py
tests/core/engine_adapter/test_databricks.py

Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1728573925367219?thread_ts=1728490239.247289&cid=C044BRE5W4S

Fix: use parentheses for databricks' CLUSTER BY clause

---

sqlmesh/core/model/common.py
tests/core/test_model.py

Fixes a validation error when the `depends_on` is specified using parentheses, like `depends_on (foo)`.

Fix: handle Paren in depends_on validator

---

sqlmesh/core/dialect.py
sqlmesh/core/loader.py
tests/core/test_model.py

I found out that my recent [fix](https://github.com/TobikoData/sqlmesh/commit/d70092e69e5e1f8a6fdec41adc3e1d052176e6ee) wasn't complete. It works when someone's loading their SQLMesh project for the first time, but when the models are loaded from cache we fail to parse them because the global macro registry has already been reset and only contains the standard macros.
Since relying on the registry proved to be brittle, I decided to refactor the existing parsing logic altogether. For context, these are some past commits that aimed to address staged file path parsing edge cases:
- https://github.com/TobikoData/sqlmesh/commit/30071ccb009c2eebad585065b095e976ca1bf5cd
- https://github.com/TobikoData/sqlmesh/pull/2412/files
- https://github.com/TobikoData/sqlmesh/pull/2714
- …

Fix: refactor table part parsing for Snowflake

---

sqlmesh/core/snapshot/evaluator.py
tests/core/test_context.py

Fixes #3214
I couldn't reproduce the second issue, as mentioned here:
> Additionally, and perhaps separately (let me know if I should create a new issue for this), blocking audit errors won't stop plan from running. If after applying the above model, you run plan with the below:
FYI @krish-freenome @zmagauina-fn

Fix: always warn when an audit has failed

---

sqlmesh/integrations/github/cicd/command.py
tests/integrations/github/cicd/test_github_commands.py
tests/integrations/github/cicd/test_integration.py

Prior to this change the `run-all` command would report it's status as a representation if the command itself ran successfully. If you want to get the status of any sub-command, then you would check the bot output. 
This change makes is to that if a test fails, a PR environment is not updated, a prod plan is not generated, or a user has provided approval to deploy and the deploy to prod did not happen, then it will error. You will still need to check bot outputs/check status to fully understand what happened. 
If a user has configured required approvers and no one has approved, then that is a fail on the condition check but the script will still pass. The argument for this is that this can likely be an expected state and not an issue at all.

feat!: run-all bot command errors if anything within it errors

---

sqlmesh/core/model/definition.py
sqlmesh/utils/date.py
tests/core/engine_adapter/test_clickhouse.py

In some scenarios, the end of SQLMesh's incremental by time filter is created by subtracting 1 microsecond from a date, resulting in fractional seconds. For example, `2024-01-02` minus 1 microsecond = `2024-01-01 23:59:59.999999`.
Clickhouse's `DateTime` data type (and alias timestamp) only support second precision, so an error is thrown when it tries to cast fractional seconds to `DateTime`.
This PR prevents that error by removing the fractional seconds when the time column is `DateTime` or timestamp types.

Fix(clickhouse): remove fractional seconds when time column is datetime/timestamp type

---

sqlmesh/core/model/definition.py
sqlmesh/dbt/model.py
tests/core/test_snapshot.py
tests/schedulers/airflow/test_client.py

The previous workaround, which involved manually setting the `_full_depends_on` cache when converting a dbt model, didn’t work well because this logic didn’t apply when the model definition was loaded from the state, which can happen when a selector is used.

Fix: Prevent extraction of dependencies from a rendered query for dbt models

---

sqlmesh/core/engine_adapter/redshift.py
tests/core/engine_adapter/integration/test_integration_redshift.py

Motivation behind this: an issue [reported](https://tobiko-data.slack.com/archives/C044BRE5W4S/p1729069676277209) by a user in our public Slack. FYI, I've opened a [ticket](https://github.com/aws/amazon-redshift-python-driver/issues/238) and a PR for this upstream.

Fix: ensure Redshift's _fetch_native_df respects case-sensitivity

---

sqlmesh/core/macros.py
tests/core/test_macros.py

Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1729271791196899

Fix: ensure 'except' columns are always filtered out in star macro

---

sqlmesh/core/snapshot/evaluator.py
tests/core/engine_adapter/integration/test_integration.py
tests/core/test_integration.py
tests/core/test_snapshot_evaluator.py

This aims to minimise unnecessary table creation (fixes: #2496 ) by skipping the creation of dev `__temp tables` when not needed, ie if snapshot `is_deployable` and doesn't reuse previous version (`forward_only`, `indirect_non_breaking`, `metadata`). In that case only prod table is created and the dry run is performed on this.

Feat!: Create temp tables only when needed

---

sqlmesh/core/scheduler.py
sqlmesh/core/snapshot/definition.py
tests/core/test_scheduler.py

if a signal marks an interval as 'unready', then all downstream jobs should also consider than interval as unready.

fix: handle missing signals in built in scheduler closes #3094

---

tests/core/engine_adapter/integration/test_integration.py

Fix failing snowflake test due to assertion of dev table not been created anymore, due to the update from: #3258

Fix: Snowflake integration tests

---

sqlmesh/core/macros.py

Today we get the first behavior when using this macro in BigQuery, which is incorrect.
```python
>>> from sqlglot import exp
>>> exp.func("MD5", exp.Literal.string(f"Original value")).sql("bigquery")
"TO_HEX(MD5('Original value'))"
>>> exp.func("MD5", exp.Literal.string(f"Original value"), dialect="bigquery").sql("bigquery")
"MD5('Original value')"
```
Context: https://tobiko-data.slack.com/archives/C0448SFS3PF/p1729531496678999

Fix: pass dialect to MD5 func builder in generate_surrogate_key macro

---

tests/core/engine_adapter/integration/test_integration.py
tests/schedulers/airflow/test_end_to_end.py

Update to the airflow end-to-end test and the engine adapter integration tests to set the date of `yesterday` before plan execution. This is to ensure that in the unlikely event the tests are run just before midnight, the date is aligned with the `end` date that was set from `now()`.

Fix: Set yesterday before plan for the Airflow end-to-end and integration tests

---

.circleci/continue_config.yml
sqlmesh/core/engine_adapter/base.py
sqlmesh/core/model/definition.py
sqlmesh/utils/date.py
tests/core/engine_adapter/integration/test_integration.py
tests/core/engine_adapter/test_clickhouse.py
tests/utils/test_date.py

Clickhouse has two datetime types:
- `DateTime`: fixed one second precision
- `DateTime64`: user-specified precision (default of 3/millisecond when bare type passed)
Clickhouse errors if you try to cast a string containing fractional seconds to `DateTime`. 
SQLMesh time intervals are sometimes calculated as [datetime - 1 microsecond], returning values containing fractional seconds.
This PR prevents fractional second casting errors by always using `DateTime64` in incremental time filters. It uses a default precision of 6 unless the user explicitly passed `DateTime64`.
The returned type is non-nullable by default. In SCD models, however, we generate statements like `CAST(NULL AS DateTime64)` that require a nullable type. Therefore, we force nullable types when calling `to_time_column()` in …

Fix(clickhouse): use DateTime64(6) type in incremental time filter

---

sqlmesh/utils/date.py

This bug stems from https://github.com/scrapinghub/dateparser/issues/896
Before this change, on systems with a modified `/etc/localtime` which can be Docker containers or also AWS Lambda / EC2:
```
$ python -c "import sqlmesh.utils.date"
...SNIP
ValueError: Could not convert `1970-01-01` to datetime.
```
After this change:
```
$ python -c "import sqlmesh.utils.date"
$
```
Slack context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1729126261397739

Fix: hardcode dateparser to use UTC so it works in environments where /etc/localtime may have been modified

---

.circleci/continue_config.yml
sqlmesh/core/engine_adapter/base.py
sqlmesh/core/engine_adapter/clickhouse.py
sqlmesh/core/engine_adapter/mixins.py
sqlmesh/core/engine_adapter/trino.py
sqlmesh/core/model/meta.py
tests/core/engine_adapter/integration/test_integration.py
tests/core/engine_adapter/integration/test_integration_clickhouse.py
tests/core/engine_adapter/test_clickhouse.py
tests/core/engine_adapter/test_spark.py

The current Clickhouse adapter uses the delete-insert loading approach. Clickhouse is not designed for deletes/updates, so its performance may be unusably slow.
This PR replaces delete-insert with a table/partition swap approach. At a high level, it operates by creating a temp table that contains new records to insert, adding existing records that should be retained to the temp table, then swapping the temp table for the current table.
To improve performance, the swapping occurs at the partition level for partitioned tables (potentially processing much less data). Incremental by time models now automatically partition the underlying table by calendar week (`toMonday(timecol)`).
Implementation note:
- Almost all of the implementation is in the `_insert_overwrite_by_condition()` adapter …

Feat(clickhouse): use table/partition swap for insert-overwrite

---

tests/core/test_model.py

For some reason this test have been showing flaky behavior, in particular this error has come up a few times in CI:
```
>   ???
E   ImportError: cannot import name 'bar' from 'tests.core.test_model' (/home/circleci/project/sqlmesh/tests/core/test_model.py)
```
I suspect it may be triggered by global state, but I'm not sure yet what caused it (couldn't repro locally). I just rewrote this slightly in this PR with the hope it will address the flakiness.

Chore: refactor flaky test

---

docs/concepts/plans.md
sqlmesh/core/console.py
sqlmesh/core/context.py
sqlmesh/core/plan/builder.py
sqlmesh/core/plan/definition.py
sqlmesh/core/plan/evaluator.py
sqlmesh/core/scheduler.py
sqlmesh/core/snapshot/definition.py
sqlmesh/integrations/github/cicd/controller.py
sqlmesh/schedulers/airflow/plan.py
tests/core/test_integration.py
tests/core/test_plan.py

Previously, SQLMesh ignored models that depend on past when the model's start date was before the specified plan start. This logic was introduced before we had the concepts of deployability and the deployability index. In practice, it caused a lot of confusion since it wasn't always obvious why a particular model wasn't evaluated when it was supposed to.
This update removes the concept of 'ignored' models and instead treats models with an invalid plan start date as non-deployable. This means that the model will still be evaluated, and its results will be available for preview in dev but will not be reused when deploying to prod.

Feat: Treat models with unaligned start as non-deployable insted of ignoring them

---

.circleci/continue_config.yml

Since these variables created aren't used by any following steps we don't need to export them to `BASH_ENV`. That change fixes things when testing in SSH.

chore: remove bash env export for private tests

---

docs/reference/cli.md
sqlmesh/cli/main.py
sqlmesh/core/context.py
sqlmesh/core/plan/builder.py
sqlmesh/magics.py
tests/core/test_integration.py
tests/core/test_plan.py

This update lets users select specific models to backfill as part of the `sqlmesh run` command. To ensure correctness, the set of selected models always includes the upstream dependencies of models that match the provided expression, regardless of whether the leading `+` was included in the original expression.
This should allow users to split their cadence runs into multiple non-overlapping jobs, helping to improve scalability.

Feat: Add support for model selector expressions to the run command

---

docs/reference/cli.md
sqlmesh/cli/main.py
sqlmesh/core/analytics/collector.py
sqlmesh/core/context.py
sqlmesh/magics.py
tests/core/analytics/test_collector.py

Restarting the run may sometimes lead to the run job taking longer than expected. This gives users ability to terminate the run job instead of restarting it in place if an update to the target environment took place.

Feat: Support exit from the run command with a provided code when interrupted by an update to the target env

---

sqlmesh/core/plan/builder.py
tests/core/test_plan.py

This fix ensures that unrelated models will not be evaluated as part of the restatement plan even if they are behind.

Fix: Only backfill models selected for restatement when restatements are provided

---

sqlmesh/core/snapshot/evaluator.py
tests/core/test_snapshot_evaluator.py

This update aims to eliminate unnecessary calls to create schemas and tables when the required deployable or non-deployable versions already exist, by identifying if the tables that need to be created are missing, instead of checking for both versions.

Fix: Skip creation call for tables that already exist

---

sqlmesh/dbt/target.py

Port freshly merged new BigQuery quota project support on dbt
See https://github.com/dbt-labs/dbt-bigquery/pull/1345
Original quota_project implementation in SQLMesh: https://github.com/TobikoData/sqlmesh/pull/3182

feat: add quota_project conf for dbt project support

---

sqlmesh/core/engine_adapter/bigquery.py
tests/core/engine_adapter/integration/__init__.py
tests/core/engine_adapter/integration/test_integration_bigquery.py
tests/core/test_model.py

This is related to #3317 but does not completely fix it. There are two problems at hand here:
1. We're currently parsing queries like `SELECT * FROM dataset.INFORMATION_SCHEMA.SOME_VIEW` incorrectly: the `Table` node's `catalog` field gets set to `dataset`, but the correct representation is to keep it in `db` and create a `Dot` node for the `INFORMATION_SCHEMA.SOME_VIEW` part. I'm planning to look into this issue separately, as it's gonna be more involved and will probably need some new logic in SQLGlot to detect references to `INFORMATION_SCHEMA` views.
2. Even if the table was fully-qualified, i.e. `SELECT * FROM project.dataset.INFORMATION_SCHEMA.SOME_VIEW`, we would still fail because the BigQuery client's `get_table` [method](https://github.com/TobikoData/sqlmesh/blob/feb96867c7a3242e …

Fix: enable fetching schema for models querying INFORMATION_SCHEMA

---

setup.py
sqlmesh/core/engine_adapter/bigquery.py
tests/core/engine_adapter/integration/__init__.py
tests/core/engine_adapter/integration/test_integration_bigquery.py
tests/core/engine_adapter/test_bigquery.py
tests/dbt/test_transformation.py

Fixes #3317
The goal of this PR is to enable SQLMesh to correctly handle information schema view references in BigQuery. The main problem with those until now was that, in their fully-qualified form, they comprised 4 identifiers:
```sql
project.dataset_or_region.INFORMATION_SCHEMA.SOME_VIEW
```
This means that we'd end up with `Table` references of mixed nesting, e.g. model names comprise 3 identifiers:
```sql
project.dataset.model_name
```
Mixing multiple nesting levels in table references is prohibited by SQLGlot's schema module [[1](https://github.com/tobymao/sqlglot/blob/87ab8fe9cc4d6d060d8fe8a9c3faf8c47c2c9ed6/sqlglot/schema.py#L289-L293), [2](https://github.com/tobymao/sqlglot/blob/87ab8fe9cc4d6d060d8fe8a9c3faf8c47c2c9ed6/sqlglot/schema.py#L149)], in order to avoid issues related to …

Fix!: bump sqlglot to v25.29.0, fix info schema view handling in bigquery

---

sqlmesh/core/analytics/__init__.py

Functions decorated with `cli_analytics` or `python_api_analytics` are not type-safe because the decorators are essentially stripping type information from the functions they decorate. This PR fixes that.

fix: decorator type erasure

---

docs/integrations/dlt.md
docs/reference/cli.md
docs/reference/notebook.md
sqlmesh/cli/main.py
sqlmesh/integrations/dlt.py
sqlmesh/magics.py
tests/cli/test_cli.py

As part of the dlt integration, this update introduces the `dlt_refresh` command to attach to a dlt pipeline and update the SQLMesh models, either by specifying the tables to be generated or updating with all the new tables.
- **Generate all missing tables**:
```bash
$ sqlmesh dlt_refresh <pipeline-name>
```
- **Generate all missing tables and overwrite existing ones** (use with `--force` or `-f`):
```bash
$ sqlmesh dlt_refresh <pipeline-name> --force
```
- **Generate specific dlt tables** (using `--table` or `-t`):
```bash
$ sqlmesh dlt_refresh <pipeline-name> --table <dlt-table>
```

Feat: Add dlt_refresh command to update models from a dlt pipeline

---

sqlmesh/core/test/definition.py
sqlmesh/core/test/result.py
tests/core/test_test.py

Fix: always make dataframes hashable when comparing them in unit tests

---

sqlmesh/core/test/definition.py
tests/core/test_test.py
tests/integrations/jupyter/test_magics.py

Using the models' `name` attribute when generating unit tests could sometimes lead to discrepancies. For example, a BigQuery project with models named as:
```sql
`project.dataset.name`
```
Resulted in tests that looked like:
```sql
test_name:
model: ...
inputs:
'`project.dataset.name`':
```
This is problematic when, e.g., the testing adapter is DuckDB, because these references would be parsed as `"project.dataset.name"` and some weird behavior was observed when executing the model's query: the generated test had an empty output.
I think the issue was probably due to these being invalid references, but haven't fully investigated yet. Using the fully-qualified names seemed like a reasonable thing to do here, anyway.

Fix: use model fqns when generating unit tests

---

sqlmesh/core/loader.py

This [commit](https://github.com/TobikoData/sqlmesh/pull/3077/files) introduced `_update_model_schemas_parallel` which doesn't topologically sort the DAG, like the sequential one does. This results in skipping the cycle detection check hidden within `DAG.sorted`, and unfortunately crashing due to recursion issues if we _do_ get a cyclic graph, because we don't attempt to sort the project's DAG until later in the runtime. The function I noticed getting stuck in a loop is `Snapshot.from_node`, reached through `Context._snapshots`.
I decided to call `dag.sorted` as soon as the DAG is built, to avoid coupling the implicit cycle detection checks with the schema updating helpers.

Fix: always sort DAG @ load time to check for cycles

---

sqlmesh/core/snapshot/evaluator.py

SQLMesh currently only runs audits on deployable tables. 
This PR enables running audits on non-deployable forward-only cloned preview tables.

Feat: audit forward-only cloned preview tables

---

docs/concepts/macros/sqlmesh_macros.md
sqlmesh/core/macros.py

Just a small qualify-of-life improvement. Not much context here, I simply stumbled upon @mattiasthalen's [SHA256 version](https://github.com/mattiasthalen/arcane-insight/blob/main/macros/generate_surrogate_key.py) and thought it was a low lift to support this upstream and provide more flexibility.

Feat: parameterize surrogate key macro hash function

---

setup.py
tests/core/engine_adapter/test_spark.py

@tobymao note the diff in the test, it's due to https://github.com/tobymao/sqlglot/commit/45eef600064ad024b34e32e7acc3aca409fbd9c4.
EDIT: made another fix upstream so the test didn't change significantly after all.

Chore!: bump sqlglot to v25.31.2

---

docs/concepts/models/python_models.md
examples/ibis/models/ibis_full_model_python.py
examples/sushi/models/order_items.py
examples/sushi/models/raw_marketing.py
examples/wursthall/models/db/order_f.py
sqlmesh/core/context.py
sqlmesh/core/macros.py
sqlmesh/core/model/definition.py
sqlmesh/core/renderer.py
tests/core/test_context.py
tests/core/test_model.py

This is a followup to https://github.com/TobikoData/sqlmesh/commit/6a324e7ea3bba49b7e1d7feb7e3814683bb65e47. Until now, we had:
- `ExecutionContext.table` -- resolve a model's name into its physical table
- `MacroEvaluator.resolve_tables` -- same, but this was mostly used to resolved all references within query (it transforms the whole thing)
- A `resolve_table` function registered in the Jinja environment, which can be used on a single table name
This PR exposes the `resolve_table` helper to the macro evaluator and the execution context, so that all of these execution environments support it, while also deprecating `Context.table`.

Refactor: make resolve_table consistent across evaluation contexts

---

.circleci/continue_config.yml
sqlmesh/core/model/definition.py
sqlmesh/core/model/meta.py
tests/core/engine_adapter/test_clickhouse.py

The Clickhouse adapter automatically partitions incremental by time models if the time column is not included in any partitioning expression.
Clickhouse strongly recommends against fine-grained/small partitions. Therefore, the automatic partitioning "floors" the time column to weekly granularity with the `toMonday()` function.
`toMonday()` only accepts date/datetime input types, so we currently error if the time column is string type.
This PR allows non-date/datetime time columns by:
- If time column type known and date/datetime, pass column directly
- If time column type known and NOT date/datetime, cast time column to `DateTime64` before passing to `toMonday()` then cast output back to original time column type
- If time column type not known, cast time column to `DateTime64` before …

Fix(clickhouse): support non-datetime time column partitioning

---

docs/concepts/models/overview.md
sqlmesh/core/model/definition.py
sqlmesh/core/model/meta.py
sqlmesh/core/snapshot/definition.py
sqlmesh/core/snapshot/evaluator.py
sqlmesh/dbt/model.py
sqlmesh/migrations/v0059_add_physical_version.py
tests/core/test_context.py
tests/core/test_integration.py
tests/core/test_model.py
tests/core/test_snapshot.py
tests/core/test_snapshot_evaluator.py
tests/core/test_state_sync.py
tests/schedulers/airflow/test_client.py

This update introduces the following improvements:
* When a new forward-only model is added, and multiple versions of it are created concurrently without either being promoted to production, we ensure that both versions share the same physical table. This ensures that the name of the physical table remains deterministic and predictable, which is especially important when the model's data is manually backfilled outside of SQLMesh.
* Added the ability to override and pin the version of the physical table, but only for forward-only models. This is the ultimate way for users to ensure that a model's physical table remains unchanged.

Feat!: Support pinning of the physical table version for forward-only models

---

docs/integrations/engines/clickhouse.md

In the ClickHouse engine integration guide, the capitalization was adjusted to reflect the preferred spelling by the ClickHouse team.

Capitalized h's in ClickHouse's name

---

tests/core/test_model.py

This test's broke CI in main, I think it's flaky. Thought I'd rewrite it into this one to see if `tmp_path` + `write_text` is the culprit. There was another similar one recently in Snowflake that was flaky because it was implemented similarly.

Chore: attempt to fix parametric kind unit test to fix CI

---

docs/integrations/airflow.md
docs/reference/configuration.md
sqlmesh/core/config/__init__.py
sqlmesh/core/config/scheduler.py

This PR introduces a new configuration for YC Managed Airflow, enabling the use of both `username:password` credentials and an IAM token for authentication.
Documentation for the YC Managed Airflow: https://yandex.cloud/en/docs/managed-airflow/operations/af-interfaces
- Added the `YCAirflowSchedulerConfig` class to support YC Managed Airflow configuration.

Feat: Add support for YC managed Airflow

---

setup.py

Allows users to use more recent versions of starlette. I tested by opening up SQLMesh UI and running plan/apply and clicking around a bit and confirming things were working.

chore: bump fastapi

---

sqlmesh/cli/main.py
sqlmesh/core/context.py
sqlmesh/magics.py
sqlmesh/utils/config.py
tests/integrations/jupyter/test_magics.py

Only print the connection config when in verbose model. 
Default output:
```
$ sqlmesh info
`physical_schema_override` is deprecated. Please use `physical_schema_mapping` instead
Models: 17
Macros: 6
Data warehouse connection succeeded
```
Verbose:
```
$ sqlmesh info -v
Models: 17
Macros: 6
Connection:
type: duckdb
concurrent_tasks: 1
register_comments: true
pre_ping: false
extensions: []
connector_config: {}
Test Connection:
type: duckdb
concurrent_tasks: 1
register_comments: true
pre_ping: false
extensions: []
connector_config: {}
Data warehouse connection succeeded
```
Skip connection:
```
$ sqlmesh info --skip-connection
Models: 17
Macros: 6
```

Chore: Simplify the output of the info command

---

sqlmesh/core/config/connection.py

Pydantic v2 or above errors when a value is passed to the `conn_properties` connection key:
```
TypeError: cannot pickle 'pydantic_core._pydantic_core.SerializationIterator' object
```
This PR updates the type from iterable to list, fixing this issue and matching the [pymssql typing](https://github.com/pymssql/pymssql/blob/eb17b88510d0d897c2f4ef38d17e8da9f59ef5cd/src/pymssql/_pymssql.pyi#L207).

Fix(mssql): change mssql conn_properties type to List

---

sqlmesh/cli/main.py
sqlmesh/core/context.py
sqlmesh/magics.py
tests/core/test_integration.py

The new option allows users to run selected models without waiting for upstream dependencies to catch up.

Feat: Add an option to not run upstream dependencies when selecting models in the  command

---

sqlmesh/core/engine_adapter/bigquery.py
sqlmesh/core/schema_diff.py
tests/core/engine_adapter/test_base.py
tests/core/test_schema_diff.py

Even though `BIGNUMERIC` is not compatible with `FLOAT64` when it comes to column alteration, `BIGNUMERIC` values can still be safely inserted into `FLOAT64` columns. This update ensures that SQLMesh can do this without needing to drop and recreate a column.

Fix: Support coercion of BIGNUMERIC values into FLOAT64 for BigQuery

---

docs/guides/ui.md
docs/quickstart/ui.md
sqlmesh/cli/main.py
web/client/openapi.json
web/client/src/App.tsx
web/client/src/api/instance.ts
web/client/src/library/components/editor/EditorPreview.tsx
web/client/src/library/components/editor/EditorTabs.tsx
web/client/src/library/components/moduleNavigation/ModuleNavigation.tsx
web/client/src/library/pages/data-catalog/DataCatalog.tsx
web/client/src/library/pages/docs/Docs.tsx
web/client/src/library/pages/plan/Content.tsx
web/client/src/library/pages/root/Root.tsx
web/client/src/models/module-controller.ts
web/client/src/routes.tsx
web/client/vite.config.ts
web/server/models.py
web/server/settings.py
web/server/watcher.py

- Changing related routes from `docs` to `data-catalog`
- both cli commands `sqlmesh ui --mode docs` and `sqlmesh ui --mode catalog` spin up SQLMesh UI in `docs`/ `catalog` mode but with routing name `data-catalog``
- Changing internal references form `Docs` to `Data Catalog`

Fix: Rename docs to catalog to keep routes consistent

---

setup.py

Includes a SQLGlot fix that's related to `JSON_VALUE` and `JSON_QUERY` for BigQuery.

Chore!: bump sqlglot to v25.32.1

---

tests/web/test_main.py

httpx 0.28.0 got released 6 hours ago which broke one of our web tests because we rely on the deprecated `app` parameter to `AsyncClient` which got removed
i've updated the test to be compatible with the new version

Fix: httpx usage for 0.28.0

---

.circleci/continue_config.yml
sqlmesh/core/engine_adapter/athena.py
tests/core/engine_adapter/integration/test_integration_athena.py

Prior to this PR, replacing an existing partition in a Hive table where the partition column was defined as `DATE` or `TIMESTAMP` resulted in the following error:
```
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter PartitionsToGet[0].Values[0], value: 2024-11-21, type: <class 'datetime.date'>, valid types: <class 'str'>
```
The cause was the query to lookup partition values was returning typed python objects but the boto3 method to delete partitions from the metastore needs strings. This PR converts the values to strings adds some tests to show it works
Note that Iceberg tables are unaffected

Fix(athena): Fix error replacing partitions in Hive tables where the partition column is a date / timestamp type

---

setup.py
tests/web/test_main.py

This PR fixes two CI/CD issues:
1. Adds a new `type ignore` to web test `test_main.py::test_cancel` (new mypy version now flagging this)
2. Adds `setuptools` to the import requirements list for python >=3.12
The second item was added because:
- Python 3.12 no longer includes the `distutils` package
- `pyspark` imports `distutils.version`, which errors on py >=3.12
- Manually **INSTALLING** `setuptools` in a new py3.12 environment will enable importing from distutils (we can't just import, must install)
From the Python 3.12 [release notes](https://docs.python.org/3.12/whatsnew/3.12.html#summary-release-highlights):
> [gh-95299](https://github.com/python/cpython/issues/95299): Do not pre-install setuptools in virtual environments created with …

Chore: fix typing and imports for ci/cd

---

.circleci/continue_config.yml
docs/guides/configuration.md
docs/integrations/engines/duckdb.md
sqlmesh/core/config/connection.py
sqlmesh/core/config/scheduler.py
tests/core/engine_adapter/integration/__init__.py
tests/core/engine_adapter/integration/docker/compose.trino.yaml
tests/core/engine_adapter/integration/test_integration.py
tests/core/engine_adapter/integration/test_integration_duckdb.py
tests/core/test_connection_config.py
tests/core/test_context.py

The motivation for this PR is to help prevent people from getting tripped up when using DuckDB for state. The most common problem is related to SQLMesh freezing.
Prior to this PR:
- DuckDB `concurrent_tasks` was hardcoded to 1
- This ensured that its connection pool was always in single threaded mode
- If the main warehouse connection had `concurrent_tasks: 8` or something set, this causes those threads to hit the single DuckDB cursor
- DuckDB deadlocks
In the time since DuckDB support was originally added, support for [multiple thread concurrency](https://duckdb.org/docs/guides/python/multiple_threads.html) has been made available. This is based on using threadlocal cursors, which our multithreaded connection pool already does.
So this PR:
- Removes the hardcoding on `concurrent_tasks` …

Fix: Enable concurrency in DuckDB

---

sqlmesh/core/macros.py

The `dialect` argument in the `exp.func` call can lead to incorrect AST generation. For instance, prior to this PR we'd generate `MD5` in BigQuery, which returns a `BYTES` value.
The long term plan for improving this macro to properly support other hash functions is to add them in SQLGlot (e.g. `SHA256Digest`). I omitted this change because we can do it incrementally, fixing MD5 is higher ROI.

Fix!: use string func in surrogate key macro (only md5 at the moment)

---

sqlmesh/core/model/definition.py
tests/core/test_audit.py

Fixes a regression [caused](https://github.com/TobikoData/sqlmesh/blob/main/sqlmesh/core/audit/definition.py#L216) by the recent [audit refactor](https://github.com/TobikoData/sqlmesh/commit/944283bd760f67d9c2c06a1c394ef18d97567ade). Additional context can be found in [this](https://tobiko-data.slack.com/archives/C044BRE5W4S/p1732365420003479) thread.

Fix: use model dialect as fallback for audits

---

sqlmesh/core/state_sync/engine_adapter.py
sqlmesh/migrations/v0015_environment_add_promoted_snapshot_ids.py
sqlmesh/migrations/v0032_add_sqlmesh_version.py
sqlmesh/migrations/v0034_add_default_catalog.py
sqlmesh/migrations/v0037_remove_dbt_is_incremental_macro.py
sqlmesh/migrations/v0038_add_expiration_ts_to_snapshot.py
sqlmesh/migrations/v0039_include_environment_in_plan_dag_spec.py
sqlmesh/migrations/v0040_add_previous_finalized_snapshots.py
sqlmesh/migrations/v0041_remove_hash_raw_query_attribute.py
sqlmesh/migrations/v0042_trim_indirect_versions.py
sqlmesh/migrations/v0043_fix_remove_obsolete_attributes_in_plan_dags.py
sqlmesh/migrations/v0045_move_gateway_variable.py
sqlmesh/migrations/v0048_drop_indirect_versions.py
sqlmesh/migrations/v0051_rename_column_descriptions.py
sqlmesh/migrations/v0055_add_updated_ts_unpaused_ts_ttl_ms_unrestorable_to_snapshot.py
sqlmesh/migrations/v0056_restore_table_indexes.py
sqlmesh/migrations/v0058_add_requirements.py
sqlmesh/migrations/v0060_mysql_fix_blob_text_type.py

fixes #3438
I found some code that @izeigerman committed [here](https://github.com/TobikoData/sqlmesh/commit/911c745b9e616d3018e08b0de6213a3df7e0a87e) that does what we're looking for.
Since migration v0033 the migration helper `blob_text_type` hasn't been used so I can only assume that this migration was reverted.
See attached integration testing after building the wheel and running `sqlmesh migrate` against a MySQL target.
I got a bit lost looking at how to prevent this from happening in the future in unit/integration testing, any recommendations would be welcome.

Fix(mysql): Use LONGTEXT data type when storing large blobs of text

---

sqlmesh/engines/spark/db_api/spark_session.py

Databricks could hit this when the user doesn't have pyspark installed locally: https://github.com/TobikoData/sqlmesh/blob/016ab9867d2b02eb7362b32e4e31dffe20e5b76b/sqlmesh/core/engine_adapter/databricks.py#L107-L111

fix: remove top level pyspark imports

---

examples/airflow/Dockerfile.template

Quick followup to the python 3.8 deprecation, I missed this one spot it seems..

Fix: use python 3.9 for airflow dockerfile template

---

sqlmesh/core/context.py
sqlmesh/core/scheduler.py
sqlmesh/core/snapshot/evaluator.py
sqlmesh/engines/commands.py
tests/core/test_context.py
tests/core/test_scheduler.py
tests/core/test_snapshot_evaluator.py

While working on https://github.com/TobikoData/sqlmesh/issues/3461, I noticed something strange: even though the audit is blocking, after running plan I got this warning:
```
2024-12-04 19:55:59,002 - MainThread - sqlmesh.core.snapshot.evaluator - WARNING - Audit 'is_positive' for model 'test_model' failed.
Got 1 results, expected 0.
SELECT * FROM (SELECT * FROM "db"."sqlmesh__default"."test_model__3395822052" AS "test_model__3395822052") AS "_q_0" WHERE "foobar" < 0
Audit is warn only so proceeding with execution. (evaluator.py:941)
```
After digging a bit, I realized this happened due to the `raise_exception=False` flag blocking a `raise` statement. Then, I noticed that in most execution paths where we reach `_audit`, this flag should be set to `False`.

Fix!: always control error handling of audits in scheduler

---

.circleci/continue_config.yml
sqlmesh/core/engine_adapter/athena.py
tests/core/engine_adapter/test_athena.py

Prior to this change, if the Athena adapter needed to replace more than 25 partitions in a partitioned model, the following boto3 error would occur:
```
'partitionsToDelete' failed to satisfy constraint: Member must have length less than or
equal to 25
```
This PR changes the adapter to call `batch_delete_partition` in batches of 25, which is the [maximum number](https://docs.aws.amazon.com/glue/latest/webapi/API_BatchDeletePartition.html#API_BatchDeletePartition_RequestParameters) allowed at once.
Note that it's just a dumb loop, technically it could be called in parallel from multiple worker threads to reduce latency if there are a lot of partitions to drop but we could add that later if it turns out to be a problem

Fix(athena): Drop partitions in batches of 25

---

sqlmesh/core/context.py
tests/core/test_schema_loader.py
tests/integrations/jupyter/test_magics.py

Addresses #3443 
Prior to this PR, assuming a config with:
```
gateways:
local:
connection:
type: duckdb
default_gateway: local
```
Running `sqlmesh create_external_models` would produce different results than `sqlmesh --gateway local create_external_models`.
The first command, `sqlmesh create_external_models` would produce model definitions that looked like:
```
- name: foo
columns: ..etc
- name: bar
columns: ...etc
```
Whereas the second command, `sqlmesh --gateway local create_external_models` would produce:
```
- name: foo
columns: ...etc
gateway: local
- name: bar
columns: ...etc
gateway: local
```
That is, it would stamp the `gateway:` key on each model. The problem is that you can get into a situation where you have a file that looks like:
```
- name: foo
columns: { "col_a": "int } …
```

Fix!: Make `create_external_models` behave like other SQLMesh commands with respect to `--gateway`

---

sqlmesh/core/snapshot/evaluator.py
sqlmesh/utils/pandas.py
tests/core/test_snapshot_evaluator.py

When restating forward-only models, SQLMesh uses the `CREATE OR REPLACE TABLE` semantics to recreate the underlying table. 
While performing this operation, SQLMesh used `columns_to_types` mapping provided by the user, if the user explicitly mapped all columns and their types in their model definition.
However, in case of forward-only models, the order of columns supplied by the user may not match the actual order of columns in the underlying table after applying schema changes. This is because very few engines support positional column alterations.
As a result, the schema of the table after restatement can be different from what it was before. This behavior is problematic because of the following reason:
1. The restatement only suppose to change rows but not the schema, which makes this …

Fix: Prevent unintentional table schema changes during evaluation

---

.circleci/continue_config.yml
tests/core/engine_adapter/integration/test_integration.py

The redshift tests are failing on main for `test_init_project`. However, this is a symptom and doesn't really have anything to do with Redshift per se.
The issue appearts to be that:
- Redshift throws a transient error, `could not open relation with OID 8199395`
- This causes the test to fail
- pytest-retry retries the `test_init_project` test
- There is an internal failure on teardown related to the `tmp_path` fixture where pytest is expecting some key to exist in its stash that doesnt exist, so raises a KeyError
- The job fails because the error happens in teardown. If it happened in the test itself, pytest-retry would retry it
I've switched the test to use the `tmp_path_factory` fixture instead, fingers crossed

Chore: Address flaky test

---

sqlmesh/cli/main.py

Allows `SQLMESH_GATEWAY`, `SQLMESH_IGNORE_WARNINGS` and `SQLMESH_DEBUG` global options to be set via environment variables.

feat(cli): ability to set config CLI params via env vars

---

sqlmesh/core/config/connection.py
sqlmesh/dbt/target.py
tests/core/test_context.py
tests/dbt/test_config.py

See how people are using SQLMesh with Snowflake. Should look and feel like this in the query history.

Add Snowflake Tracking

---

sqlmesh/core/snapshot/evaluator.py

The current output looks like this:
```
Inserting batch (1733702400000, 1733788800000) into ...
```
This will output something like:
```
Inserting batch (2024-12-09 00:00:00, 2024-12-10 00:00:00) into ...
```
This is what the output used to look like prior to https://github.com/TobikoData/sqlmesh/pull/3405

feat: make log output more human-friendly

---

sqlmesh/core/renderer.py
tests/core/test_model.py

During the recent refactor, where `this_model` changed from a `str` into a `Table` instance, I missed the fact that we were previously [quoting](https://github.com/TobikoData/sqlmesh/commit/b00d7d40b42ff759243b161567a81547c1002486#diff-fddedea4eda285dbd51b83821f3cd54dc42d3946c0056760acdc29efc3e565afL242) it, so I didn't match that behavior.
We discovered that this led to an issue where the resolved table for `this_model` would be normalized twice, if e.g. it was interpolated in a string, and hence generated as a table with unquoted identifiers.
This PR fixes the above issue by having `_resolve_table` quote the table after resolving it, to match the semantics of `_resolve_tables`.

Fix: quote the table produced by _resolve_table

---

docs/concepts/models/model_kinds.md
setup.py
sqlmesh/core/dialect.py
sqlmesh/core/engine_adapter/base.py
sqlmesh/core/engine_adapter/mixins.py
sqlmesh/core/engine_adapter/postgres.py
sqlmesh/core/model/kind.py
sqlmesh/core/model/meta.py
sqlmesh/migrations/v0064_join_when_matched_strings.py
tests/core/engine_adapter/integration/test_integration.py
tests/core/engine_adapter/test_base.py
tests/core/test_model.py
tests/core/test_snapshot_evaluator.py

Before this PR, the `when_matched` attribute couldn't be parsed consistently. E.g., a user [reported](https://tobiko-data.slack.com/archives/C044BRE5W4S/p1733343291111989) that, even though the following definition worked, switching the two clauses so that `THEN DELETE` is first would result in a parse error.
```sql
MODEL (
name @{macro_val}.test,
kind INCREMENTAL_BY_UNIQUE_KEY (
unique_key purchase_order_id,
when_matched
WHEN MATCHED AND source._operation <> 1 THEN UPDATE SET target.purchase_order_id = 1
WHEN MATCHED AND source._operation = 1 THEN DELETE
)
);
select purchase_order_id from @{macro_val}.upstream;
```
This happened because we relied on some implicit behavior around how the clauses are consumed ([example](https://github.com/TobikoData/sqlmesh/pull/3497#discussion_r1878883456) …

Refactor!: make when_matched syntax compatible with merge syntax

---

sqlmesh/core/scheduler.py
sqlmesh/core/snapshot/definition.py
tests/core/test_integration.py
tests/core/test_snapshot.py
tests/integrations/jupyter/test_magics.py

This ensures that when multiple concurrent BREAKING versions of the same forward-only model are created, they don’t attempt to write to the same table while iterating in a development environment.

Fix: Always treat forward-only models as non-deployable

---

sqlmesh/core/context.py

It looks like that
```
model_to_test = self.get_model(model, raise_if_missing=True)
```
got introduced https://github.com/TobikoData/sqlmesh/pull/3394 but it might fail and result in an exception that would prevent the creation of the `test_adapter` that we are trying to close.
(it happened on my end as I was tinkering on my project)

Check that test_adapter exist before closing

---

tests/core/test_integration.py

Missed in this PR: https://github.com/TobikoData/sqlmesh/pull/3516

chore: add missing utc timezone to test

---

sqlmesh/core/snapshot/definition.py

Fix arg name typo:
- `discriminator` is a `Field` arg 
- `"descriminator"` was being consumed as a kwarg and ignored

Chore: fix arg name in Node Field definition

---

sqlmesh/core/macros.py
tests/core/test_model.py

Provides an easier path to migrate away from old code that used `locals["this_model"]`.

Feat: add this_model property in the macro evaluator to return a string

---

sqlmesh/core/config/connection.py
tests/conftest.py

This modifies the `MotherDuckConnectionConfig` to enable using MotherDuck in conjunction with multiple attached catalogs (e.g. postgres, local duckdb, other MotherDuck databases, etc.).  This way you can run models inside MD and join external attached data without injecting the `ATTACH` statements inside Jinja blocks.
Mostly this was done by moving most of the logic inside `DuckDBConnectionConfig` upstream into the base class `BaseDuckDBConnectionConfig` since vanilla DuckDB and MotherDuck are mostly at feature parity at the moment.
So you can configure as follows:
```yaml
gateways:
local:
connection:
type: motherduck
catalogs:
my_db:
type: motherduck
path: 'md:my_db'
local_duckdb:
type: duckdb
path: 'local.ddb'
postgres_db:
type: postgres
path: 'dbname=postgres user=postgres …
```

feat: add multiple catalogs functionality to MotherDuck connection 

---

docs/concepts/models/overview.md
sqlmesh/core/context.py
sqlmesh/core/model/definition.py
sqlmesh/core/model/kind.py
sqlmesh/core/node.py
sqlmesh/core/plan/builder.py
sqlmesh/core/scheduler.py
sqlmesh/core/snapshot/__init__.py
sqlmesh/core/snapshot/definition.py
sqlmesh/core/state_sync/base.py
sqlmesh/core/state_sync/engine_adapter.py
sqlmesh/dbt/model.py
sqlmesh/migrations/v0066_add_auto_restatements.py
sqlmesh/schedulers/airflow/state_sync.py
sqlmesh/utils/pydantic.py
tests/core/test_integration.py
tests/core/test_model.py
tests/core/test_plan.py
tests/core/test_scheduler.py
tests/core/test_snapshot.py
tests/core/test_state_sync.py
tests/dbt/test_transformation.py
tests/schedulers/airflow/test_client.py

It’s prevalent among dbt users to nuke the tables of their incremental models occasionally to ensure correctness as well as to capture late arriving data. This is because dbt models lack an idempotent way to re-process arbitrary intervals of data. 
When transitioning to SQLMesh, these users are forced to use restatement plans in order to replicate workflows they are used to in dbt. However, the restatement plans are highly invasive, as they remove intervals for all versions of the model across all environments. This negatively impacts users iterating in development environments, as they are suddenly forced to rerun models they haven’t modified.
To address this issue, we are introducing first-class support for this use case and call it Auto-Restatements. This allows users to configure a …

Feat: Add support for auto-restatements

---

sqlmesh/core/dialect.py
tests/core/test_dialect.py

Fixes #3517 -- only "case 1", I didn't prioritize fixing the `time_column` one because I thought there are many cases where we expected columns/identifiers in the model meta, so that's probably a bigger effort. The model name was low-hanging fruit to avoid inconsistent schema nesting issues.

Fix!: reject string model names

---

tests/core/test_snapshot_evaluator.py

Fix `test_snapshot_evaluator.py` by adding unique model name to avoid duplicate model in dictionary when running this test in isolation

Fix: Adapt evaluator test to use unique model names

---

sqlmesh/core/loader.py
tests/core/test_context.py

Feat: do recursive glob matching for ignore_patterns

---

docs/guides/configuration.md
sqlmesh/core/context.py
sqlmesh/core/context_diff.py
sqlmesh/core/loader.py
tests/core/test_context.py
tests/core/test_plan.py

This adds ability to opt-out some dependencies and prevent them from being included by the automatic dependency detection logic.

Feat: Add ability to exclude dependencies in the requirements lock file

---

sqlmesh/core/dialect.py
sqlmesh/core/engine_adapter/base.py
sqlmesh/core/engine_adapter/mixins.py
sqlmesh/core/engine_adapter/postgres.py
sqlmesh/core/model/kind.py
sqlmesh/core/model/meta.py
sqlmesh/core/snapshot/evaluator.py
sqlmesh/dbt/model.py
tests/core/engine_adapter/test_base.py
tests/core/test_model.py
tests/core/test_snapshot_evaluator.py
tests/dbt/test_config.py
tests/dbt/test_transformation.py

This update introduces `merge_filters` in `INCREMENTAL_BY_UNIQUE_KEY` kind models and also adds support for dbt projects with `incremental_predicates`. It updates the incremental logic for engines that support the `MERGE` strategy, by incorporating ability to filter data during the merge operation.
When using this feature, both **source** and **target** aliases can be used to distinguish between the source and target columns similar to `WHEN MATCHED`.
```sql
MODEL (
name db.test,
kind INCREMENTAL_BY_UNIQUE_KEY (
unique_key [purchase_order_id],
merge_filters (
source._operation <> 1 AND 
target.start_date > DATEADD(day, -7, CURRENT_DATE)
)
)
);
```
The above predicates are then used into SQLMesh’s `MERGE` statements:
```sql
MERGE INTO <existing_table> AS "__MERGE_TARGET__"
USING …
```

Feat!: Add support for merge_filter and dbt incremental_predicates for Incremental By Unique Key

---

examples/sushi_dlt/sushi_pipeline.py
sqlmesh/cli/main.py
sqlmesh/integrations/dlt.py
tests/cli/test_cli.py

This is an update to the dlt integration and adds support for [nested DLT tables](https://dlthub.com/docs/general-usage/destination-tables#nested-tables), fixes: #3545 
- Each row in all (root and nested) data tables created by dlt contains a unique column named _dlt_id (row key), but only parent tables contain the `_dlt_load_id`. 
- Since each dlt nested table contains a column named `_dlt_parent_id` referencing a particular row (`_dlt_id`) of a parent table (parent key), this is used to join and get the parent `_dlt_load_id` to be used for the incremental model.

Feat(dlt): Add support for generation of nested dlt tables

---

sqlmesh/dbt/project.py
tests/dbt/test_config.py
tests/dbt/test_manifest.py
tests/fixtures/dbt/sushi_test/dbt_project.yml
tests/fixtures/dbt/sushi_test/macros/test_dependencies.sql

This adds support for nested variables defined as:
```
vars:
nested_vars:
some_nested_var: 2
```

Fix: Support nested variables in dbt projects

---

docs/reference/configuration.md
sqlmesh/core/config/plan.py
sqlmesh/core/console.py
tests/cli/test_cli.py
tests/core/engine_adapter/integration/test_integration.py
tests/core/test_context.py
tests/core/test_integration.py

The default settings for the start and the end date are good enough that it should satisfy the vast majority of use cases. This should simplify the UX since it's one less thing for users to think about.
In addition to being `true` by default, the `no_prompts` flag has the following behavioral changes:
* Change categories are now printed
* Expected backfill dates are now printed
* SQLMesh prompts for confirmation to apply the plan unless the `--auto-apply` flag is specified. Previously, `no_prompts` also suppressed the confirmation prompt

Chore!: Disable date prompts by default when running the plan command

---

docs/integrations/github.md
sqlmesh/integrations/github/cicd/config.py
tests/core/analytics/test_collector.py

This is a more reasonable default which results in more predictable deployments. Otherwise, users might be confused why their deployment to prod also triggers evaluation of unrelated models.

Chore!: Set run_on_deploy_to_prod to false by default for the CICD bot

---

docs/development.md

`make install-dev` does not install the required dependencies to run the docs server locally. This PR documents the commands needed to contribute to the docs.

Docs: Add contribution commands for docs

---

sqlmesh/core/console.py
sqlmesh/core/plan/definition.py

Previously, the diff for metadata changes wasn't printed in the plan output. This updates makes it so that diff is printed unless the --no-diff flag was provided.

Fix: Show diff for metadata changes in the plan output

---

sqlmesh/core/state_sync/engine_adapter.py
tests/core/test_state_sync.py

This ensures that SQLMesh always recreates views for environments that have been invalidated (soft delete) but which haven't been garbage collected by the janitor process.

Fix: Always create views in the virtual layer for expired environments

---

sqlmesh/core/context.py
tests/core/engine_adapter/integration/__init__.py
tests/core/engine_adapter/integration/test_integration.py
tests/core/test_config.py
tests/core/test_context.py
tests/core/test_model.py
tests/core/test_test.py

This fixes an omission on the latest multi-engine feature, to create the engine adapters in cases when they're not generated in the snapshot_evaluator property, ie for the commands `render`, `table_diff` and `create_test`

Fix: Add adapters for commands that are not using the snapshot evaluator

---

docs/installation.md
docs/quick_start.md
docs/quickstart/cli.md
docs/quickstart/notebook.md
docs/quickstart/ui.md
docs/reference/notebook.md

Minor changes:
- Removes Pydantic V2 information from installation docks, made outdated by #3548 
- Adds a link to go straight to the CLI quickstart instead of watching the video quickstart.
- Quickstart is spelled two different ways. This standardizes it to "Quickstart".

Docs: Minor updates

---

sqlmesh/core/plan/evaluator.py
sqlmesh/core/scheduler.py
tests/core/test_integration.py

Otherwise, a user iterating in one dev environment may unintentionally affect other dev environments by dropping shared intervals.
It also appears that we no longer need to modify the state in order to perform restatements in dev correctly within the same plan. 
Restatements are already reflected on in-memory snapshot instances when computing missing intervals here: https://github.com/TobikoData/sqlmesh/blob/v0.141.1/sqlmesh/core/snapshot/definition.py#L1712

Fix: Don't drop intervals in state when restating models in a dev environment

---

sqlmesh/core/snapshot/definition.py
tests/core/test_snapshot.py

I've noticed that our deployability strategy for auto-restated models was a bit too aggressive. Snapshots that are downstream of snapshots with auto-restatement enabled were always classified as neither deployable nor representative. 
However, if such a child is currently promoted in production, it can be perfectly suitable for reading in dev, assuming that the snapshot consuming this data remains non-deployable.

Fix: Unpaused snapshots that are downstream of snapshots with enabled auto-restatement can still be representative

---

sqlmesh/core/scheduler.py
sqlmesh/core/snapshot/definition.py
tests/core/test_integration.py
tests/core/test_snapshot.py
tests/dbt/test_integration.py

This update makes it so that models for which `allow_partials` is set to true still respect their cron schedules. 
When running `sqlmesh run` the model won't run unless its time to run has come even if the `allow_partials` flag is set for it. However, if the `--ignore-cron` flag is specified in the `run` command, the model will run every time.
Additionally, this change has the following implications:
- Execution time is no longer rounded down to a minute
- The previous point also results in the `valid_to` column in SCD2 models being populated with millisecond precision

Fix!: Models with allow_partials set to true should respect cron

---

sqlmesh/core/plan/evaluator.py
sqlmesh/core/snapshot/evaluator.py
tests/cli/test_cli.py

The plan command's physical table creation progress bar sometimes appears even when there are no physical tables to create, with an incorrectly large number of tables listed.
This PR ensures that it only appears if there is a table to create and that the count of tables to create is correct.

Fix: plan physical tables progress bar

---

sqlmesh/core/model/definition.py
tests/core/engine_adapter/integration/test_integration_clickhouse.py
tests/core/engine_adapter/test_clickhouse.py

SQLMesh automatically partitions Clickhouse incremental by time range models, aggregating timestamps to week. If the timestamp data type is not a datetime variant, SQLMesh automatically casts it to DateTime64 in the aggregation expression.
In Clickhouse, casting to DateTime64 type requires specifying a numeric precision.
This PR specifies a precision of 9/nanoseconds (using max precision to prevent accidental truncation of timestamp digits).

Fix(clickhouse): specify DateTime64 precision for model partitioning expression

---

sqlmesh/core/dialect.py
sqlmesh/core/model/definition.py
sqlmesh/core/snapshot/evaluator.py
tests/core/test_model.py
tests/core/test_snapshot_evaluator.py

This update moves the rendering of `merge_filter` to evaluation time instead of load time, ensuring that any temporal macros (e.g. `@start_ds`) are resolved based on the evaluation time objects.

Fix: Move rendering for merge_filter to evaluation time

---

sqlmesh/__init__.py

Fixes #3603, I think this is what we originally did [here](https://github.com/TobikoData/sqlmesh/commit/ea7b37738c8a14b3c752703f6e810cd1c8b23e7d) for the same reason, but along the line the full path was refactored I guess. Not 100% sure this is the right approach but thought I'd give it a shot.

Fix: access SIGUSR1 using fully-qualified path to avoid windows issue

---

sqlmesh/core/test/definition.py
tests/core/test_test.py

Fixes #3601
@serkef I think either the test or the model in your example is incorrect, because setting the `DATETIME` cast issue aside, the `TIMESTAMPDIFF` crashes when you're trying to compare a `TIMESTAMP` (current timestamp) and a `DATETIME`.
This PR addresses the issue related to the `CAST`.

Fix: use dialect when freezing current date/time values in tests

---

docs/concepts/macros/macro_variables.md
docs/concepts/models/python_models.md
docs/concepts/models/seed_models.md
docs/concepts/models/sql_models.md
sqlmesh/core/dialect.py
sqlmesh/core/model/common.py
sqlmesh/core/model/decorator.py
sqlmesh/core/model/definition.py
sqlmesh/core/plan/evaluator.py
sqlmesh/core/scheduler.py
sqlmesh/core/snapshot/definition.py
sqlmesh/core/snapshot/evaluator.py
tests/core/test_model.py
tests/core/test_snapshot_evaluator.py

This update introduces statements that are executed after a virtual update. These can be used for example to grant privileges on views of the virtual layer. 
These expressions should be defined within a `ON_VIRTUAL_UPDATE_BEGIN; ...; ON_VIRTUAL_UPDATE_END;` block. For example:
```sql
MODEL (
name db.customers 
);
SELECT 
item_id
FROM 
db.seed_model;
ON_VIRTUAL_UPDATE_BEGIN; 
GRANT SELECT ON VIEW @this_model TO ROLE role_name;
INJA_STATEMENT_BEGIN;     
GRANT REFERENCES, SELECT ON FUTURE VIEWS IN DATABASE {{ db }} TO ROLE owner_name;  
JINJA_END;  
ON_VIRTUAL_UPDATE_END;
```
Jinja expressions are also supported within this block by properly nesting the Jinja block as shown in the example above.
In these statements table resolution occurs at the virtual level, meaning that qualified view …

Feat!: Add support for virtual statements to be executed post update

---

sqlmesh/core/model/definition.py
tests/core/test_model.py

Without this fix `this_model` is resolved to the physical table name when rendering `on_virtual_update` statements.

Fix: this_model macro usage in the on_virtual_update statements

---

.circleci/continue_config.yml
docs/concepts/models/model_kinds.md
sqlmesh/core/engine_adapter/redshift.py
tests/core/engine_adapter/test_redshift.py

This update adds native `MERGE` support for Incremental by Unique Key models in Redshift (fixes: #3316)
This required adjustments to the generated statement to accommodate for the lack of alias support for the target table and limitations of the when matched clause [Redshift MERGE Documentation](https://docs.aws.amazon.com/redshift/latest/dg/r_MERGE.html)

Feat(redshift): Add native Merge support for Redshift

---

docs/guides/projects.md

Why:
Because if you follow the guide as is, you will get:
```
sqlmesh init
Error: Default SQL dialect is a required argument for SQLMesh projects
```
and it's not immediately clear what the list of supported values should be.

Docs: Clarify "sqlmesh init" usage

---

sqlmesh/dbt/builtin.py
tests/dbt/test_transformation.py

Makes the behavior of `is_incremental()` macro more consistent with dbt.

Fix: Don't set the is_incremental flag for non-incremental dbt models

---

sqlmesh/core/snapshot/definition.py
sqlmesh/core/snapshot/evaluator.py
tests/core/test_integration.py

In very rare scenarios, there might be a snapshot of a view model that is representative but not deployable, while the corresponding physical view has not yet been created for it.
One example of this happening is the following scenario:
Model DAG: A (forward-only) -> B (non-forward-only) -> C (view).
1. Make some change to A in `dev`. Everything categorized as forward-only
2. Make a follow-up breaking change to B in dev. C is now `INDIRECT_BREAKING`. The deployable view hasn't been created at this point*
3. Deploy the 1st change to `prod` without deploying the 2nd change.
4. Make another change to B, this time non-breaking, still in `dev`. C is now `INDIRECT_NON_BREAKING`. Applying this change fails with missing view
*The view hasn't been created at this point due to a different issue …

Fix: Physical view not being created when needed for non-deployable indirect non-breaking snapshots

---

sqlmesh/core/context.py
tests/core/test_context.py
tests/core/test_integration.py

The previous logic was overly simplistic and worked well only for daily models, while yielding poor results for models with a coarser cadence (weekly, monthly).
The new logic is based on interval units of models that constitute a plan.

Fix: The inference of the default plan start

---

docs/concepts/models/python_models.md

See https://github.com/TobikoData/sqlmesh/issues/3621

Chore: fix python model audit docs

---

sqlmesh/core/snapshot/definition.py
sqlmesh/core/state_sync/engine_adapter.py
tests/core/test_snapshot.py
tests/core/test_state_sync.py

Unpausing snapshots that are deployed to prod involves fetching all snapshots that share the same version as the ones being deployed. 
Before this change, fetching snapshots with the same versions involved full parsing of snapshot objects, including their models and queries. This caused a significant performance issue for projects with a high number of models, especially forward-only models.
With this update, SQLMesh will perform only a partial parsing when fetching snapshots with the same version, falling back to parsing the full snapshot only when absolutely necessary (which should be rare).
Additionally, this should also improve the performance of deleting expired snapshots, which relies on the same method to fetch snapshots with the same version.

Fix: Reduce parsing overhead and improve performance when unpausing snapshots deployed to prod

---

docs/concepts/models/python_models.md
setup.cfg
setup.py
sqlmesh/core/context.py
sqlmesh/core/engine_adapter/_typing.py
sqlmesh/core/engine_adapter/base.py
sqlmesh/core/engine_adapter/bigquery.py
sqlmesh/core/snapshot/evaluator.py

I PR'ed the upstream lib so that they have no upper bound on their SQLGlot pin. This means the library is now fully compatible with SQLMesh. This PR adds support. Instead of bundling the extra with bigquery, I have temporarily added it to its own extra so it is opt-in. Once they cut a version release, we can add it with a proper `>=` version specifier. 
This enables many novel uses such as using Gemini / LLM capabilities at scale more effectively, using ML models (training , predicting, etc), and so on leveraging BigQuery's compute through a dataframe interface wrapped intuitively by `sqlmesh`'s python model system.
https://cloud.google.com/bigquery/docs/use-bigquery-dataframes#pandas-examples
https://github.com/googleapis/python-bigquery-dataframes/blob/main/notebooks/getting_started/ml_f …

Feat: implement support for bigframes

---

sqlmesh/core/model/decorator.py
tests/core/test_model.py

Currently, python model column data types are parsed with the default sqlglot dialect instead of the explicit model dialect or project default dialect. 
This PR updates it to use the explicit model dialect when present and default project dialect when not.

Fix: parse python model column types with dialect

---

sqlmesh/core/engine_adapter/duckdb.py

DuckDB information schema can be qualified with `system` as it is an internal table. When you `ATTACH` a database, its tables and columns also end up in `system.information_schema.*` (part of how the ATTACH feature works is that a `catalog` is necessarily supplied). Hence there is no need for an ambiguous catalog in the `_get_data_objects` method. If the search path is mutated (such as by `USE`?), this method can fail. Such is the case when using multiengine support with Bigquery. 
I venture to reason Postgres avoids this failure (since you were able to do a multiengine model with it) by having information schema in its own catalog. But Postgres' catalog is synced to DuckDB as part of ATTACH so its best to just use a fully qualified duckdb reference. …

Fix: qualify information schema query for duckdb

---

sqlmesh/core/scheduler.py
sqlmesh/core/snapshot/definition.py

When no models are ready to run, the `sqlmesh run` command issues a message stating when the next model will be ready to run.
Some model kinds, like `seed` and `symbolic`, do not have a "ready" time. Currently, we error if a project only contains these kinds of models.
This PR updates the code to handle this situation, omitting the time when next model ready from the message if it cannot be calculated.

Fix: no models ready to run message shouldn't error 

---

docs/quickstart/cli.md

A few of the line numbers referenced in the description of the quickstart outputs are incorrect

docs: fix line number references

---

docs/concepts/models/model_kinds.md

Docs incorrectly said that `invalidate_hard_deletes` was `true` by default. https://github.com/TobikoData/sqlmesh/blob/0e51dd80477142ddb295670443c6f858bb30270f/sqlmesh/core/model/kind.py#L662
Thanks @zzztimbo for pointing this out here: https://github.com/TobikoData/sqlmesh/pull/3622
Decided to not change the default behavior in order to avoid a breaking change.

fix: correctly document invalidate_hard_delete behavior

---

sqlmesh/core/config/connection.py

Context: Using MotherDuck multi-catalog configs has been failing using the Tobiko Cloud environment. Not sure if this will fix things but this missing `motherduck_token=` is certainly a bug.
cc @izeigerman

Fix MotherDuck token attach syntax

---

sqlmesh/core/context.py
tests/core/test_plan.py

This addresses the following scenario:
1. SQLMesh fetches snapshots and its intervals as part of the plan construction.
2. Right after this a concurrent `sqlmesh run` job backfills and records intervals for a certain model.
3. SQLMesh fetches maximum backfilled interval end for each model.
As a result, the intervals fetched in (3) are ahead of what's been fetched in (1), leading to inaccurate missing intervals.

Fix: Refresh snapshot intervals after determining the max interval end per model

---

sqlmesh/core/snapshot/evaluator.py
tests/conftest.py
tests/core/engine_adapter/integration/test_integration.py
tests/core/test_integration.py
tests/core/test_snapshot_evaluator.py

After adding a new forward-only model in a dev environment, the user may later iterate on it by adding or removing columns. 
If `on_destructive_change` is set to `fail`, the user might encounter an error when removing a previously existing column.
This behavior is generally expected and correct, assuming the model was previously deployed to prod. However, if this is a new model that only exists within the current dev environment, failing due to destructive changes is counterintuitive. Nothing will actually be destroyed as a result of the change, since no production copy exists yet.
This fix addresses the issue by deferring the creation of the deployable physical table for a new forward-only model until it is deployed to prod.

Fix: Defer creation of the deploable table for a new forward-only model

---

sqlmesh/core/model/definition.py
tests/core/test_model.py
tests/core/test_snapshot_evaluator.py

The motivation behind this PR is that, given this model:
```sql
MODEL (
name test_model,
kind INCREMENTAL_BY_UNIQUE_KEY (
unique_key (a, d)
),
audits (
unique_combination_of_columns(
columns = (a, d),
condition = d between @start_date and @end_date
)
),
);
SELECT
1 AS a,
CAST('2025-01-20' AS DATE) AS d
```
The audit condition renders as follows at runtime today:
```sql
"d" BETWEEN CAST('1970-01-01' AS DATE) AND CAST('1970-01-01' AS DATE)
```
The reason this happens is that the model meta is rendered at load time and we store the properties to the corresponding pydantic fields, e.g. `audits`, even though `start_date` is a variable that changes depending on the runtime stage.
Approach is similar to https://github.com/TobikoData/sqlmesh/commit/e10449184cea6369c0ac2dcd1e6b8736d2a612fb.

Fix!: render audits at runtime

---

sqlmesh/dbt/manifest.py

Prior to this change, if SQLMesh tries to load a DBT project and `dbt-core==1.9.0` or newer is in use, the following error occurs:
```
AttributeError: 'Flags' object has no attribute 'state_modified_compare_more_unrendered_values'
```
The `Flags` being referred to are the `project_flags` which we currently [hardcode to None](https://github.com/TobikoData/sqlmesh/blob/7519f431af3369a2cdf8d6cf56129a0471804e7b/sqlmesh/dbt/manifest.py#L297).
This wasn't a problem until DBT 1.9.0 added a bunch of [unguarded checks](https://github.com/dbt-labs/dbt-core/blob/1dcdcd2f52f885bbb10dd14771b7c2dc6173bb63/core/dbt/parser/base.py#L385) for `get_flags().state_modified_compare_more_unrendered_values`.
I checked where this was meant to be set in DBT and it turns out that `flags.set_from_args()` will …

Fix: prevent AttributeError when a DBT project is run with dbt-core >= 1.9.0

---

docs/integrations/engines/duckdb.md

Update docs to clarify that PostgreSQL catalog must use the actual catalog name, since the view layer relies on the actual catalog, using an alias for the catalog would not be feasible for most sqlmesh queries, closes #3663

Chore: Update docs to specify that postgres catalog should use the actual name

---

sqlmesh/migrations/v0063_change_signals.py

The migration intended to only reload the snapshots if a model was changed that contained signals. This was likely done since signals was just released and we didn't want to reload the data when this would be a no-op for most. The problem is that only rows that had adjusted signals were put into `new_snapshots` and then the entire snapshot table was deleted. This would result in a snapshot table with just signal models in it instead of all the snapshots.
The change keeps the desired behavior but uses `signal_change` to track if a signal was really adjusted and if so it then reloads. `new_snapshots` now contains all the snapshots.

fix: migration 0063 loads subset of data

---

docs/concepts/models/python_models.md

Correcting to say that variable arg values CANNOT be accessed via kwargs. And some edits.

Docs: clarify py model variable access

---

sqlmesh/core/console.py
sqlmesh/core/model/kind.py
sqlmesh/core/plan/builder.py
tests/cli/test_cli.py
tests/core/test_integration.py
tests/core/test_scheduler.py

When there are gaps in missing intervals like in the following example:
```
[1, 2) [3, 4)
```
SQLMesh ends up backfilling both `[1, 2)` and `[3, 4)` intervals even for non-incremental model kinds like `FULL` and `VIEW`. This behavior is correct for incremental models but doesn't make much sense for non-incremental ones.

Fix: Make sure that full / view models only backfilled once

---

docs/concepts/models/model_kinds.md

Adds info box "should you use this model kind?" explaining table partitioning vs. loading by partition and that other model kinds are usually a better option.
Adds warning box that all restatements fully rebuild the table and should be done with caution.

Docs: update incremental by partition concepts

---

sqlmesh/core/console.py
tests/cli/test_cli.py
tests/integrations/github/cicd/test_integration.py

New output:
```
Models needing backfill [missing dates]:
├── raw__dev.demographics: [full refresh]
├── sushi__dev.active_customers: [full refresh] (preview)
├── sushi__dev.customer_revenue_by_day: [2025-01-20 - 2025-01-20]
├── sushi__dev.customer_revenue_lifetime: [2025-01-20 - 2025-01-20] (preview)
├── sushi__dev.customers: [full refresh] (preview)
├── sushi__dev.items: [2025-01-20 - 2025-01-20]
├── sushi__dev.marketing: [2025-01-20 - 2025-01-20] (preview)
├── sushi__dev.order_items: [2025-01-20 - 2025-01-20]
├── sushi__dev.orders: [2025-01-20 - 2025-01-20]
├── sushi__dev.raw_marketing: [full refresh] (preview)
├── sushi__dev.top_waiters: [recreate view] (preview)
├── sushi__dev.waiter_as_customer_by_day: [2025-01-20 - 2025-01-20] (preview)
├── sushi__dev.waiter_names: [full refresh]
└── …
```

Chore: Improve the missing dates output by wrapping them into square brackets

---

sqlmesh/core/snapshot/definition.py
tests/core/test_snapshot.py

We noticed that when reusing the dev physical table for view models, it sometimes result in stale views that point at deleted snapshot tables.

Fix: Dont reuse the dev table version for non-materialized models

---

Makefile
docs/integrations/engines/trino.md
tests/core/engine_adapter/integration/config.yaml
tests/core/engine_adapter/integration/docker/_common-hive.yaml
tests/core/engine_adapter/integration/docker/compose.trino.yaml
tests/core/engine_adapter/integration/docker/init-metastore-db.sql
tests/core/engine_adapter/integration/docker/trino/catalog/datalake_nessie.properties
tests/core/engine_adapter/integration/test_integration.py

This addresses issue #3673
We actually already support Nessie today, it's just not clear from the docs.
Nessie can run in REST Catalog mode (`iceberg.catalog.type=rest`) which Trino's Iceberg connector can use no problem.
I've:
- Added Nessie (in REST mode) to our test suite, it's just another case for Trino which already has Hive / Delta / Iceberg+HiveMetastore (so this added Iceberg+REST)
- Updated the docs to clarify how to use Nessie with SQLMesh
Note that it looks like Trino is [abandoning](https://github.com/trinodb/trino/issues/17768#issuecomment-2139112257) the "native" Nessie catalog type in favour of the REST catalog. The "native" Nessie catalog still does not support views so cannot be used with SQLMesh.

Feat: Nessie support

---

sqlmesh/core/context.py
sqlmesh/core/scheduler.py

Moves the nothing to run message out of scheduler (which is called during `plan`) and into the context run call.

Fix: nothing to run message should not appear during plan

---

sqlmesh/core/console.py
sqlmesh/core/context_diff.py

**Adds a newline before the first message is printed**
Before
After
**Adds left side indention to the python requirements (and first newline from previous change)**
Before
After

Chore: minor plan output formatting

---

sqlmesh/core/console.py

Small lift to get rid of these warnings:
```
(.venv) ➜  playground sqlmesh init duckdb
/<path>/sqlmesh/core/console.py:892: SyntaxWarning: invalid escape sequence '\['
backfill = Tree("[bold]Models needing backfill \[missing dates]:")
/<path>/sqlmesh/core/console.py:906: SyntaxWarning: invalid escape sequence '\['
f"{display_name}: \[{_format_missing_intervals(snapshot, missing)}]{preview_modifier}"
/<path>/sqlmesh/core/console.py:1726: SyntaxWarning: invalid escape sequence '\['
self._print("\n**Models needing backfill \[missing dates]:**")
```

Chore: silence a few warnings related to string escaping

---

docs/reference/cli.md
docs/reference/notebook.md
sqlmesh/cli/main.py
sqlmesh/core/audit/definition.py
sqlmesh/core/context.py
sqlmesh/core/context_diff.py
sqlmesh/core/model/definition.py
sqlmesh/core/node.py
sqlmesh/magics.py
tests/core/test_audit.py
tests/core/test_context.py

Fixes https://github.com/TobikoData/sqlmesh/issues/1254
The default behavior of plan diff is to compare raw models i.e the original queries & statements:
```SQL
Differences from the `dev` environment:
Models:
└── Directly Modified:
└── default__dev.test
--- 
+++ 
@@ -4,13 +4,13 @@
CREATE TABLE IF NOT EXISTS foo AS
(
SELECT
-    @OR(FALSE, TRUE)
+    @AND(TRUE, NULL)
)
SELECT
-  4 + 2
+  5 + 2
CREATE TABLE IF NOT EXISTS foo2 AS
(
SELECT
-    @AND(TRUE, FALSE)
+    @OR(TRUE, NULL)
)
-DROP VIEW @this_model
+DROP VIEW IF EXISTS @this_model
```
This PR introduces the `sqlmesh plan --rendered-model-diff` which instead compares rendered queries/statements:
```SQL
@@ -4,13 +4,13 @@
CREATE TABLE IF NOT EXISTS "foo" AS
(
SELECT
-    FALSE OR TRUE
+    TRUE
)
SELECT
-  6 AS "_col_0"
+  7 AS "_col_0" …
```

Feat: Add plan option to show rendered model diff

---

docs/integrations/engines/trino.md
sqlmesh/core/config/common.py
sqlmesh/core/config/connection.py
sqlmesh/core/config/root.py
sqlmesh/core/engine_adapter/trino.py
tests/conftest.py
tests/core/engine_adapter/test_trino.py
tests/core/test_config.py
tests/core/test_connection_config.py

Currently, there is no way to instruct SQLMesh to create schemas with a specific `LOCATION` property set for Trino.
This PR introduces a **connection** property called `schema_location_mapping` that allows a user to use regular expressions to map schemas to their corresponding physical locations.
- It's a connection property because it's specific to the Trino adapter
- It follows the convention of our other mapping properties (`physical_schema_mapping` and `environment_catalog_mapping`)
- It takes catalog into account if one exists, because a schema is really a `catalog.schema` combination most of the time

Feat(trino): Add the ability to control schema locations

---

sqlmesh/utils/metaprogramming.py
tests/utils/test_metaprogramming.py

This model can't be loaded today because of the serialization order:
```python
import pandas as pd
from sqlmesh import model
def decorator(func):
def wrapper(*args, **kwargs):
return func(*args, **kwargs)
return wrapper
@decorator
def decorated_func():
return
@model("test_model", kind="FULL", columns={"id": "INT"})
def execute(context, *args, **kwargs):
decorated_func()
return pd.DataFrame({"id": [1, 2, 3]})
```
The corresponding python environment is:
```python
> /<path>/sqlmesh/utils/metaprogramming.py(419)prepare_env()
-> for name, executable in sorted(
(Pdb) python_env
{'execute': Executable<payload: def execute(context, *args, **kwargs):
decorated_func()
return pd.DataFrame({'id': [1, 2, 3]}), name: execute, path: models/python_model.py>, 'decorated_func': Executable<payload: def …
```

Fix: fix dependency extraction order when building python env

---

sqlmesh/utils/metaprogramming.py
tests/utils/test_metaprogramming.py

Reverts TobikoData/sqlmesh#3735
Temporarily reverting this because I realized that moving `env[name] = obj` after `walk(obj)` may be a little risky, e.g. we could potentially get stuck in infinite loops if for whatever reason `obj` has a dependency which contains it as a global (I think this could come up with closures). I'll make another PR if I figure out a safe way to implement this logic.

Revert "Fix: fix dependency extraction order when building python env"

---

sqlmesh/utils/metaprogramming.py
tests/core/engine_adapter/test_trino.py
tests/utils/test_metaprogramming.py

Fixes #3640
The main difficulty in solving the linked issue was making SQLMesh detect the `stop_after_attempt` reference, in order to extract and inject it into the python environment so it can be (de)serialized:
```python
@retry(stop=stop_after_attempt(3))
def fetch_data():
return "test data"
```
The decorator names themselves were already being picked up in the previous `decorators` helper. In this PR I expand that functionality by also searching for the decorator call arguments' references.
I implemented a new visitor class in order to limit the search to only the decorator sub-trees, instead of traversing the whole function tree. Without this, we'd have to do a nested `walk` within the root node traversal loop, leading to unnecessarily revisiting nodes under the decorator sub-trees. …

Fix!: include names of decorator argument references when building python env

---

sqlmesh/core/model/kind.py

Fixes #3669
Ideally I'd like to work out where these lists are coming from but seeking early feedback.
The assumptions seem to be that if the Whens value comes in as a string then it's coming from somewhere like state where the placeholders have already been substituted.
If it arrives as an exp.Whens then it's coming in from the IncrementalByUniqueKeyStrategy where the placeholders are still present.
I've extended the first assumption, that if it arrives as a list then it's a list of strings with placeholders already substituted.

Fix: handle list case in when_matched validator

---

sqlmesh/core/test/definition.py

This PR aims to silence a `FutureWarning` related to calling `to_datetime` with `errors="ignore"`. Avoiding errors in the context of unit tests is not necessarily a good choice, as it can mask underlying issues with the tested data.

Fix: silence deprecation warning in unit tests due to to_datetime errors="ignore" kwarg

---

docs/reference/model_configuration.md
sqlmesh/core/config/model.py
sqlmesh/core/model/definition.py
tests/core/test_model.py

This update extends the support for top-level properties to be enabled project wide, fixes: #3599 
- when both project-wide and model-specific properties are defined, they are combined. 
- if a property is set at the model level, it takes precedence over the project-wide setting. 
- if a user wants to unset a project-wide property on a specific model, they can do so by explicitly setting it to None.
Don't know if it makes sense to include more, as the others seem quite model-specific, but I’m happy to add them if anyone feels they’re necessary.

Feat: Support top level properties in model_defaults

---

sqlmesh/core/test/definition.py

time_machine imports pytest which takes 50 millis

chore: improve load times by making import optional

---

sqlmesh/core/context.py
tests/core/test_integration.py

When adding a new model while simultaneously modifying a forward-only model, SQLMesh may infer an incorrect default start date for the plan if the new model's cron is not aligned with the interval unit's boundary.

Fix: Improve the inference of the default plan start for new models for which cron is not aligned with interval unit boundary

---

sqlmesh/cli/example_project.py
sqlmesh/core/config/connection.py
tests/cli/test_cli.py

Fixes https://github.com/TobikoData/sqlmesh/issues/3459
Dynamically generate the engine-appropriate connection options through Pydantic's `model_fields`. The following conventions are applied:
- If the `Field` is not required, it's commented out 
- If the `Field` has a (literal) default value it's appended to the RHS

Feat: Generate per-dialect options on init project

---

sqlmesh/cli/example_project.py
tests/cli/test_cli.py

Small change to get configs to look like this instead of having a single big comment for the config connection link. Added another link to the base connection configs because they're missing from individual connection pages.
```yaml
gateways:
dev:
connection:
type: duckdb
default_gateway: dev
dialect: duckdb
start: 2025-01-30
```

Chore: put connection config link in a separate line

---

sqlmesh/utils/metaprogramming.py
tests/utils/test_metaprogramming.py

This should take care of the issue mentioned [here](https://github.com/TobikoData/sqlmesh/pull/3742) and also add support for custom decorators, e.g. this now works (fails to load in current main branch):
```python
import pandas as pd
from sqlmesh import model
def custom_decorator(_func):
def wrapper(*args, **kwargs):
return _func(*args, **kwargs)
return wrapper
@custom_decorator
def function_with_custom_decorator():
return
@model(
"test_model",
kind="FULL",
columns={"id": "INT"},
)
def execute(*args, **kwargs):
function_with_custom_decorator()
return pd.DataFrame({"id": [1, 2, 3]})
```

Feat: traverse python objects in post-order to support custom decorators

---

sqlmesh/core/test/__init__.py
sqlmesh/core/test/definition.py
tests/core/test_test.py

Motivation: when a model is disabled and there's a unit test for it, running it will result in a crash. I opted for a warning because not doing anything at all can result in masking typos in enabled models that _should_ be tested.

Chore: warn instead of raising if unit test references unknown model

---

docs/integrations/engines/databricks.md
sqlmesh/__init__.py
sqlmesh/core/config/connection.py
sqlmesh/core/engine_adapter/base.py
sqlmesh/core/engine_adapter/databricks.py
sqlmesh/utils/errors.py

Prior to this PR, if a user said they wanted to use Serverless for databricks-connect then it forced the use of databricks-connect and therefore one could not use the python sql connector. In addition the documentation said that the SQL connector did not support Databricks Serverless Compute which was misleading - although it doesn't support the workspace side Serverless, typically used by Notebooks and Jobs, it does support SQL Warehouse Serverless compute. 
Therefore a user could have wanted to use serverless across their stack - Serverless compute for jobs that require PySpark DataFrame and SQL Warehouse Serverless for their SQL queries. This PR now enables this pattern. 
One key limitation it works around was temporary objects - since serverless doesn't support global temporary …

feat: don't force db connect if using serverless

---

sqlmesh/cli/example_project.py
tests/cli/test_cli.py

This PR addresses the following issues:
- The `False` default values were not rendered due to the logical disjunction 
- The default `gateway` is renamed to `<dialect>` instead of `dev` to avoid confusion with prod/dev
- The tests freeze time to avoid sync issues with `yesterday_ds()` if the day is changed

Fix: Change gateway naming and render False values on project init

---

.circleci/continue_config.yml
.circleci/manage-test-db.sh
Makefile
tests/core/engine_adapter/integration/config.yaml

This PR attempts to debug the following issue noticed in the failing clickhouse cloud tests on main:
```
http.client.RemoteDisconnected: Remote end closed connection without response
```
It looks like Clickhouse Cloud can now go into an `idle` state. I added a pre-ping to ensure the cicd instance is running before triggering the tests.
However, the issue still occurred. So I set:
```
connect_timeout: 30
```
on the connection config (previously it was using the default value of 10).
This actually did fix the connection issue but it raised another issue:
```
DB::Exception: Too many databases. The limit (server configuration parameter `max_database_num_to_throw`) is set to 100, the current number of databases is 272.
```
So it looks like Clickhouse Cloud is now limiting the number of …

Chore: Address Clickhouse Cloud test flakiness

---

sqlmesh/core/engine_adapter/shared.py
sqlmesh/core/snapshot/definition.py
tests/core/test_context.py

Fix!: ensure unsafe catalog identifiers are quoted before parsed

---

setup.py
sqlmesh/core/config/connection.py
sqlmesh/core/engine_adapter/base.py
sqlmesh/utils/connection_pool.py

Notes
1. Added connection params:
- `database` (so users are able to connect to a specific database [MySQL schema equivalent])
- `collation` (if you're changing the charset you will likely also want to change collation)
2. Cursor buffering
- The current implementation uses buffered fetching by passing the `buffered=True` argument during cursor creation
- This is not necessary with pymysql, as the [cursor is buffered by default](https://github.com/PyMySQL/PyMySQL/blob/01af30fea0880c3b72e6c7b3b05d66a8c28ced7a/pymysql/cursors.py#L83)
Implementation detail
- We no longer need to pass the `buffered` arg during cursor creation, so I removed `_cursor_kwargs()` entirely (it was only added for and used by MySQL)

Chore: replace mysql-connector-python with pymysql

---

docs/concepts/macros/macro_variables.md
sqlmesh/core/macros.py
sqlmesh/core/snapshot/evaluator.py

We render queries when executing audits as well as `on_virtual_update` statements, however neither has a runtime stage associated with it. This PR addresses the gap.

Feat: Add 'auditing' and 'promoting' runtime stages

---

sqlmesh/core/engine_adapter/databricks.py
tests/conftest.py
tests/core/engine_adapter/test_databricks.py

Follow up to: https://github.com/TobikoData/sqlmesh/pull/3786
In our tests we had some code which references to schemas/tables without a catalog and therefore relies on the connection default catalog to resolve to the correct schema/table. This doesn't match SQLMesh code since we always fully qualify references. Therefore some tests would fail if the default catalog was set incorrectly. This could happen if the SQL connector default catalog and databricks-connect default catalog were different and produce unexpected behavior. This change forces the two to be aligned to the default catalog the user provided or the default catalog returned by the connection (with databricks-connect preferred if configured). 
If a user reports an issue with this line, then it likely means they did not have a …

fix: databricks set default catalog for both connections

---

sqlmesh/core/state_sync/engine_adapter.py
tests/core/test_state_sync.py

There was an oversight where I checked for whether the expiration timestamp was set instead of checking whether the environment was actually expired.

Fix: Only promote all snapshots if the target environment expired

---

sqlmesh/core/console.py
tests/integrations/github/cicd/test_integration.py

No longer accurate because we now display other information for non-incremental models

Chore: remove [missing dates] from CLI model backfills title

---

sqlmesh/core/plan/evaluator.py
tests/core/test_integration.py

Make sure to create physical tables for snapshots that are up for promotion and not just for the ones that were selected for backfill.

Fix: Make sure that physical tables exist for promoted snapshots

---

sqlmesh/core/engine_adapter/databricks.py
tests/core/engine_adapter/test_databricks.py

Follow up to: https://github.com/TobikoData/sqlmesh/pull/3793
The key thing that was missing in prior PR was properly supporting the `with_log_level` method. It creates a copy of the engine adapter but since it doesn't want to create a new connection is creates it with a placeholder connection. The issue is that databricks engine adapter tries to set the default engine adapter after creation and then when it tries to do that with the placeholder connection it gets an error.
I moved the set_current_catalog to the `_begin_session` method so although now it will run multiple times it does more lazily run it which gets around the `with_log_level` issue. 
I then ran the integration tests with hybrid, no databricks connect, and only databricks connect and fixed issues that came up. I got some …

fix: db properly support `with_log_level`

---

tests/core/engine_adapter/integration/conftest.py

This better emulates how things run in SQLMesh by having all model evaluations run with a begin session first.

fix: run integration tests in session

---

sqlmesh/cli/example_project.py

#3733 made the `config.yml` file generated by `sqlmesh init [dialect]` specific to each engine. All of an engine's supported config fields are listed in the file, with the optional fields commented out.
For DuckDB, the `database` field is optional. However, the SQLMesh quickstart project cannot use an in-memory DuckDB instance and requires a value for `database`.
This PR makes `sqlmesh init duckdb` generate a config file that uses the `db.db` database.

Fix: specify init duckdb database so quickstart works

---

sqlmesh/core/constants.py
sqlmesh/core/model/decorator.py
sqlmesh/core/model/definition.py
tests/core/test_context.py
tests/core/test_model.py

This update enables macros to be passed in the properties for Python models, aside from `audits`, `signals`, `merge filter` and `physical_properties` which are rendered at evaluation time (the latter will be addressed on a subsequent pr). This allows to dynamically control for example the `enabled` flag based on the gateway:
```python
@model(
...,
enabled="@IF(@gateway = 'local', True, False)",
)
```

Feat: Allow macros in python model properties

---

sqlmesh/core/console.py

This fix ensures the sample of table_diff command displays, by comparing the lowercase table names, because the source and target names might have been uppercased before based on the aliases:
https://github.com/TobikoData/sqlmesh/blob/e6dff9b7e0042fb5c567e8d46233f2bc1765fbe3/sqlmesh/core/console.py#L1208-L1213

Fix: Ensure diff sample displays when table names have been uppercased

---

docs/concepts/macros/sqlmesh_macros.md
docs/integrations/engines/trino.md
sqlmesh/core/macros.py
sqlmesh/core/model/definition.py
sqlmesh/core/snapshot/evaluator.py
tests/core/engine_adapter/integration/test_integration_trino.py
tests/core/test_macros.py
tests/core/test_model.py
tests/core/test_test.py

This PR:
- Moves evaluation of `physical_properties` to run time instead of load time
- This enables the usage of things that only exist at run time, such as `@this_model`
- Adds a macro called `@physical_location` that allows a user to create arbitrary `exp.Literal` or `exp.Table` objects in the AST based on the *parts* of the physical table name
The motivation is twofold:
- Right now, there is no way to set custom locations for tables on engines that separate storage and compute (Athena, Trino, Spark etc). This is true even if you write a custom macro and reference it from `physical_properties`, because `physical_properties` is currently rendered at load time which means no snapshot info is available
- Right now, `@this_model` [returns a fully rendered FQN …

Feat!: Adjust physical_properties evaluation and add macro to resolve physical table names

---

docs/examples/incremental_time_full_walkthrough.md
sqlmesh/core/snapshot/definition.py
sqlmesh/core/state_sync/engine_adapter.py
sqlmesh/migrations/v0069_update_dev_table_suffix.py
tests/conftest.py
tests/core/engine_adapter/integration/test_integration.py
tests/core/test_plan.py
tests/core/test_snapshot.py
tests/core/test_snapshot_evaluator.py
tests/core/test_state_sync.py
tests/schedulers/airflow/test_client.py
tests/schedulers/airflow/test_plan.py

This PR ensures consistent terminology in the codebase for referring to non-deployable physical tables. The non-deployable physical tables are going to be called as "dev" tables going forward.
Additionally, this updates changes the suffix for non-deployable table names from `__temp` to `__dev` for the following reasons:
* These tables are not truly temporary; their lifespan matches that of the snapshots they are associated with. As long as a snapshot exists, its corresponding dev table persists
* The existing suffix confuses users who don't like seeing something that looks like a temporary table in their warehouse
* `__temp` is used elsewhere in the codebase to denote actual temporary tables, whose lifespan does not extend beyond the duration of the user session
At the same time, this …

Chore: Use 'dev' suffix instead of 'temp' for non-deployable physical tables

---

docs/cloud/features/scheduler/dagster.md

This updates the installation instructions in the Dagster facade docs to actually work.
Previously they said to update `setup.py` which is ignored by pip in the presence of `pyproject.toml`. The correct file to update is `pyproject.toml`.

Docs(dagster): Fix installation instructions

---

sqlmesh/core/engine_adapter/base.py
sqlmesh/core/engine_adapter/bigquery.py
sqlmesh/core/engine_adapter/clickhouse.py
sqlmesh/core/engine_adapter/databricks.py
sqlmesh/core/engine_adapter/mixins.py
sqlmesh/core/engine_adapter/snowflake.py
tests/core/engine_adapter/test_base.py

Inconsistency in the engine adapter API that this fixes. 
Slack context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1739304449424019

fix: add kwargs to build_table_properties_exp

---

sqlmesh/core/console.py
sqlmesh/core/plan/builder.py
sqlmesh/core/plan/evaluator.py
sqlmesh/core/snapshot/evaluator.py
sqlmesh/utils/errors.py
tests/core/test_plan.py
tests/core/test_snapshot_evaluator.py

When someone gets the destructive change error message, they want to understand more about the problem than just the name of the affected column(s).
SQLMesh has not actually run any ALTER statements when this error occurs, so the statements are not printed to the log. That makes it difficult to figure out what SQLMesh "wanted to do" that it decided it shouldn't.
This PR adds those ALTER statements to the destructive error/warning message.

Feat: include alter statements in destructive change error message

---

sqlmesh/core/config/connection.py
tests/core/test_connection_config.py

Fix(postgres): Quote role names if required when running SET ROLE on cursor init

---

sqlmesh/core/config/connection.py

Fixes #3783
I could get the example project to get until evaluation stage given these changes. The reason it failed was billing:
```
Skipped models
"foo--bar"."sqlmesh_example"."full_model"
Failed models
"foo--bar"."sqlmesh_example"."incremental_model"
```
Note that the config needs to wrap the project name with quotes:
```yaml
project: '"foo--bar"'
```

Fix: handle quoted projects properly in bigquery adapter

---

tests/core/test_context.py

After #3818 was merged there appears to be a timing issue in `test_context::test_plan_runs_audits_on_dev_previews`.
In particular, the error switches between `22` and `10` rows. The actual number of rows doesn't matter to this test, it just checks that the usually blocking audit ran at all and was automatically switched to non-blocking.
This PR relaxes the string matching on the output

Chore: Fix flaky test

---

sqlmesh/core/config/connection.py
tests/core/test_connection_config.py

Reverts TobikoData/sqlmesh#3825
Preemptively calling `to_identifier` in the `role` field can result in incorrectly wrapping case-sensitive roles like `"myRole"` with additional quotes: `"""myRole"""` . If any user has the former in their config, that can break them.
User-facing configs / inputs should instead make sure their “unsafe” identifiers are quoted.

Revert "Fix(postgres): Quote role names if required when running SET ROLE on cursor init"

---

sqlmesh/core/plan/builder.py
tests/core/test_integration.py

We always migrate forward-only models when deploying them to prod, so there's no risk here.

Fix: Don't fail because of an unrestorable change if the target model is forward-only

---

sqlmesh/core/plan/definition.py
sqlmesh/core/plan/evaluator.py
tests/core/test_integration.py
tests/schedulers/airflow/test_client.py
tests/schedulers/airflow/test_integration.py
tests/schedulers/airflow/test_plan.py

Prior to this PR, when we removed intervals across environments, introduced in https://github.com/TobikoData/sqlmesh/pull/3511, we would also remove intervals for downstream snapshots even if they had `disable_restatement` enabled. One tricky part is that the model, in most cases, would not be backfilled in that plan and this would not be communicated in console output. A case where it would be shown is if that downstream model was also an upstream model of one of the restated models or it's downstream models. I get that was confusing - lets give this example:
A -> B -> C
If `B` had `disable_restatement`, and `A` was being restated, then `B` would both have it's intervals removed and it would be backfilled in the plan since it is upstream of `C`. But if `C` had `disable_restatement` then …

fix: respect disable_restatement remove intervals across env

---

sqlmesh/core/plan/builder.py
tests/core/test_plan.py

Prior to this PR, the assumption was made that if a model was being restated in dev that it must either be restating a table that has the dev suffix or it is a new snapshot that isn't used in prod. This isn't always the case and a simple example is creating a dev environment with `--include-unmodified`. If you did that then issued a restatement to your dev environment against a model that had `disable_restatement` then it would restate prod. 
This PR addresses that immediate use case by checking if the snapshot is paused along with if it is in dev in order to determine if `disable_restatement` should be respected.

fix: respect disable restate dev unpaused snapshots

---

docs/reference/model_configuration.md
sqlmesh/core/config/model.py
sqlmesh/core/model/definition.py
tests/core/test_model.py

This update extends the model properties that are supported to be enabled across the entire project through the configuration to also include:  `allow_partials`, `enabled`, `interval_unit`.

Feat: Extend support of project wide model properties

---

sqlmesh/core/renderer.py
sqlmesh/core/snapshot/evaluator.py
tests/core/test_snapshot_evaluator.py

Previously we'd only run pre- / post- statements for the non-dev tables, completely ignoring the dev tables. This update makes it so that pre- and post- statements run consistently for **every** table SQLMesh creates.

Fix: Streamline execution of pre- / post- statements when creating a physical table

---

sqlmesh/core/snapshot/definition.py
tests/core/test_snapshot.py

This fixes the test which was not asserting, adds a test to cover this case (which fails) and fixes the actual problem by de-denting a line (the line is skipped when the returned list is empty because it skips the iteration).

fix: signals that return an empty list are considered ready

---

sqlmesh/core/plan/builder.py
tests/core/test_integration.py
tests/core/test_plan.py

Since model snapshots can be shared between environments and some model kinds may have non-idempotent restatements, we need to prevent users from accidentally restating snapshots used in production as part of their development environments.

Fix: Snapshots promoted in prod shouldn't be restated in dev

---

sqlmesh/core/plan/builder.py
tests/core/test_integration.py

Resolves Repro here: https://github.com/TobikoData/sqlmesh/pull/3845
Slack context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1739560750218099
Prior to this PR we would expand the range of a restatement if a model involved in the restatement expanded the range due to it's model properties. For example a full can't restate a subset so it expands the provided start to match it's model start. The problem was that this expansion is needed to maintain correctness of that model but downstream models can respect the provided start as a limit. 
The thinking is that we really only want to expand the restatement range for downstream if an upstream *incremental* model expanded the range. This would make the restatement consistent across incremental while ignoring the models that aren't …

fix: only expand restatement range if incremental

---

docs/integrations/engines/gcp-postgres.md
sqlmesh/core/config/connection.py
tests/core/test_config.py
tests/core/test_connection_config.py

Prior to this PR, it was assumed that customers would be connecting to GCP Postgres using the public IP. This is most likely the case but they could also connect using private if on a VPN. 
Also noticed that `timeout` was an argument that could be passed into the GCP Postgres connector class but we didn't include it and just passed into the resulting connection class. Also noticed some config options weren't documented or tested which was also fixed.

feat: improve gcp postgres connection config options

---

setup.py

PyGithub 2.6.0 just got released, which caused our cicd bot tests to start failing.
It looks like theyve changed a bunch of stuff. I spent some time trying to make the tests compatible but was ultimately unsuccessful because I dont have enough context of how its meant to work.
I've pinned the older version 2.5.0 so at least the build can continue working in the short term

Fix: Pin PyGithub to 2.5.0 so tests can run

---

sqlmesh/core/snapshot/definition.py
tests/core/test_snapshot.py

Prior to this change, if you tried to restate eg 1 day of a model that is [full_history_restatement_only](https://github.com/TobikoData/sqlmesh/blob/ab6b2502549d12d2a23d4af2d976c180ca6ef1f7/sqlmesh/core/model/kind.py#L131), for example an `INCREMENTAL_BY_UNIQUE_KEY` model:
```
$ sqlmesh plan --restate-model sqlmesh_example.unique_key_model --start 2020-01-01 --end 2020-01-02
No changes to plan: project files match the `prod` environment
Models needing backfill:
└── sqlmesh_example.unique_key_model: [2020-01-01 - 2020-01-10]
```
SQLMesh would automatically adjust the backfill intervals to cover the entire model without making it obvious to the user.
Even if the user notices that the end date in this example was changed to `2020-01-10` they may be confused as to _why_ SQLMesh ignored their …

Fix: Warn when SQLMesh automatically adjusts a restatement range to cover the whole model

---

sqlmesh/core/snapshot/definition.py
sqlmesh/core/state_sync/common.py
tests/core/test_snapshot.py

Prior to this PR, if you were using Snowflake and the `environment_catalog_mapping` config it would result in lowercase catalog names. 
This PR updates the config to normalize according to the dialect. Tested against Snowflake and confirmed to be working as expected. 
Note: The PR doesn't attempt to address a potential issue if someone wanted to quote their catalog name. I think we are missing a `to_identifier` or `parse_identifier` somewhere but it is not the problem I fixing here.

fix!: normalize catalog override name

---

sqlmesh/core/console.py
sqlmesh/core/scheduler.py
tests/core/test_context.py

Currently, the same warning message is print both to file and console. However, we sometimes have more information for the user than is sensible to print to the console. 
This PR adds the ability to print separate messages to file and console. If separate messages are passed, the console message will automatically include a link to the log file.

Feat: allow different warning messages for logger and console

---

docs/concepts/audits.md
sqlmesh/core/audit/builtin.py

We do `foo_audit = ModelAudit("foo", ...)` in `builtin.py`, so my guess is the variable name was copied over inadvertently.

Chore: fix audit doc typos

---

docs/concepts/models/python_models.md
docs/concepts/models/sql_models.md
sqlmesh/core/dialect.py
sqlmesh/core/loader.py
sqlmesh/core/model/__init__.py
sqlmesh/core/model/cache.py
sqlmesh/core/model/decorator.py
sqlmesh/core/model/definition.py
sqlmesh/dbt/loader.py
tests/core/test_model.py

This PR adds a new feature: the ability to implement model blueprints based on a single template.
This feature is useful when multiple models need to share the same logic, but parameterized differently. Today, this is generally possible by either duplicating model definitions, thus violating the [DRY principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself), or creating a custom loader, which involves knowing the inner workings of the codebase.
A simple example that demonstrates the syntax to achieve model blueprinting is shown below:
```sql
MODEL (
name @blueprint.some_table,
blueprints (
(blueprint := customer1),
(blueprint := customer2),
(blueprint := customer3),
),
);
SELECT
*
FROM @blueprint.some_source
```
This definition essentially expands into three different models, each …

Feat!: add model blueprinting

---

sqlmesh/core/state_sync/engine_adapter.py
tests/core/test_state_sync.py

"With multiple snapshots per version, the compaction process may end up recording compacted intervals with different timestamps, which leads to the recording of pending restatement interval records with earlier timestamps than regular interval records that were supposed to precede them. As a result, the order gets messed up the next time we merge the intervals, leading to incorrect auto-restatement behavior.

Fix: Make sure that pending restatement intervals are always recorded last during compaction

---

sqlmesh/core/macros.py
sqlmesh/utils/metaprogramming.py
tests/core/test_model.py

Fixes #3864
The validations we do in `date_spine` today are too strict. This PR relaxes them a bit so that users can supply arbitrary expressions as arguments, besides just string literals– take a look at the new test to see why that makes sense.

Feat: make date_spine macro less strict to allow dynamic behavior

---

sqlmesh/core/snapshot/definition.py
tests/core/test_integration.py
tests/core/test_snapshot.py

In this case, the plan start is set to a value that is greater than the parent's max interval end, which leads to SQLMesh picking up missing intervals for the unchanged parent if the time for the parent to run has already arrived but it hasn't run yet.

Fix: Unexpected backfill of a parent of a changed forward-only child when the child runs before the parent

---

Makefile
docs/guides/custom_materializations.md
examples/custom_materializations/custom_materializations/custom_kind.py
examples/custom_materializations/setup.py
examples/sushi/models/latest_order.sql
sqlmesh/__init__.py
sqlmesh/core/model/kind.py
sqlmesh/core/snapshot/evaluator.py
tests/core/analytics/test_collector.py
tests/core/test_context.py
tests/core/test_integration.py
tests/core/test_snapshot_evaluator.py
tests/integrations/jupyter/test_magics.py

The motivation behind this pull request is to allow custom materializations to fill a role of "behaves similar to an existing materialization - except with some requirements relaxed or changed".
Right now this is either difficult / requires copy+pasting a bunch of code or is just not possible (eg if your custom materialization needs to leverage the project level `time_column_format` config property).
The current custom materializations also dont play nicely with the builtin audits because there is no way of exposing `model.kind.time_column` (which this PR addresses)

Feat: Allow CustomKind subclasses for custom materializations

---

.circleci/test_migration.sh
sqlmesh/core/macros.py
sqlmesh/core/model/definition.py
sqlmesh/core/snapshot/definition.py
tests/core/test_snapshot.py

fix: render signals properly for variables

---

sqlmesh/core/model/definition.py
tests/core/engine_adapter/integration/test_integration_clickhouse.py

Fixes #3876
The cause of the issue here is that we parse these parameterized aggregate functions in ClickHouse into an AST that contains a `"parts"` node, whose value can't be generated by the base class because it's a tuple (see [here](https://github.com/tobymao/sqlglot/blob/ec4e97c31c16a1c8b5eb1acfba0ef77f064505b4/sqlglot/dialects/clickhouse.py#L732-L735)). It works when using the ClickHouse generator, because it skips it in the `func` call (see [here](https://github.com/tobymao/sqlglot/blob/ec4e97c31c16a1c8b5eb1acfba0ef77f064505b4/sqlglot/dialects/clickhouse.py#L1216-L1217)).
I will fix this upstream by moving the generation logic in the base class, but I think the change in this PR is useful regardless. Passing the dialect to the differ means we'll actually use the SQL generated for …

Fix: pass model dialect to sqlglot.diff to avoid possible generation issues

---

sqlmesh/core/config/connection.py
tests/core/test_connection_config.py

Mask the MotherDuck connection token in logs, displaying it as asterisks (`md:db?motherduck_token=************`) instead of revealing the actual value.

Fix: Mask MotherDuck connection token in the logs

---

.circleci/test_migration.sh

When the migration script detects a diff and fails, we no longer see it because of these flags:

Chore: remove debug flags from migration testing script

---

docs/development.md

This morning I cloned the repo, after spending some time thrashing around whilst trying to install the dev dependencies I realised that Apache Airflow does not support Python 3.13. I've added a line to the `development.md` doc to (hopefully) mitigate this issue for other people looking to get started with the repository.

Add supported Python versions into development.md

---

setup.py

The changes in #3842 are not compatible with `cloud-sql-python-connector` versions below `1.8.0`.

Fix: Put a lower bound on the cloud-sql-python-connector dependency

---

sqlmesh/core/engine_adapter/shared.py
tests/core/engine_adapter/integration/test_integration.py
tests/core/engine_adapter/test_postgres.py

For engines that are single catalog only, like Redshift and Postgres, currently we will warn if we detect they seem to be doing a cross-catalog operation. This code is old and hasn't been an issue, but we hit a scenario where a user ran janitor and the janitor deleted something unexpectedly due to this being a warning.
Therefore changing this to raise instead.

fix!: raise instead of warn on catalog mismatch

---

docs/guides/custom_materializations.md
examples/custom_materializations/custom_materializations/custom_kind.py
examples/sushi/models/latest_order.sql
pytest.ini
sqlmesh/core/model/definition.py
sqlmesh/core/model/kind.py
sqlmesh/core/snapshot/evaluator.py
tests/core/test_integration.py
tests/core/test_model.py
tests/core/test_snapshot.py
tests/core/test_snapshot_evaluator.py
tests/integrations/github/cicd/fixtures.py

Allow deserialization of models using custom materializations _without the custom materialization classes being present_.
This essentially moves the `kind` validation for custom materializations into `Model.validate_definition()`, which gets called after everything is loaded.
This means that components that just need to coerce Snapshots into JSON and back without doing anything special can continue to do so without needing the custom materialization classes loaded (since these would typically exist in an external library).
Only the components that evaluate the snapshots will need the custom materialization classes available in the Python environment.
This PR also rolls back the ability for CustomKind subclasses to define persistent properties outside of `materialization_properties`. The …

Fix: Allow deserialization of models using custom materializations 

---

sqlmesh/core/plan/builder.py
sqlmesh/core/snapshot/definition.py
sqlmesh/core/state_sync/base.py
sqlmesh/core/state_sync/engine_adapter.py
tests/core/test_integration.py
tests/core/test_plan.py
tests/core/test_snapshot.py

if your partial restate a daily model -> monthly, (2024-02-15, 2024-02-20), get_removal_interval returned an interval where start > end. this ensures get_removal_interval only returns valid intervals.

fix: prevent get_removal_interval from returning invalid interval

---

sqlmesh/core/context.py

If the auto categorization was disabled via CLI, it's user's intent to enter change categories manually. In this case no_prompts can be enabled.

Fix: Enable prompts if the auto categorization was disabled in CLI

---

sqlmesh/core/config/gateway.py
sqlmesh/core/config/root.py
sqlmesh/core/context.py
tests/core/test_config.py
tests/core/test_context.py

Users can employ different gateways on the same project:
```YAML
gateways:
redshift:
connection:
type: redshift
...
snowflake:
connection:
type: snowflake
...
default_gateway: snowflake
dialect: snowflake
start: 2025-02-05
```
However, the models will be normalized at the `model_defaults.dialect` even if the `default_gateway` is set to a different engine, which can lead to issues / inefficiencies e.g Redshift's `INFORMATION_SCHEMA` stores the tables as lower-case, so with Snowflake's upper-case normalization we'll fail to find the tables/views. 
This PR adds support for `model_defaults` under gateways which override the global dialect, e.g:
```YAML
gateways:
redshift:
connection:
type: redshift
...
dialect: snowflake, normalization_strategy=case_insensitive …
```

Feat: Add model defaults support per gateway configuration

---

sqlmesh/core/dialect.py
tests/core/test_model.py

This update fixes an issue in `when_matched` and `merge_filter` when dealing with multi-part fqns (e.g. `source.second_part.column` ), where the aliases for source and target weren't replaced. The `replace_merge_table_aliases` function now is checking for the first part of the column instead of the column's table and replaces that. This allows for cases like BigQuery's nested fields, which can have arbitrary lengths of parts, by resolving the first part of the name.
Related slack thread: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1740423499786879

Fix: Merge source and target aliases resolution for multi part fqns

---

sqlmesh/core/snapshot/definition.py
tests/core/test_snapshot.py

partial intervals were getting lumped into the previous interval expanding the range, this makes it so that the previous complete interval is isolated and the partial is new. for example
missing_interval('2023-01-01', '2023-01-02 12:00:00') should result in 2 intervals, [2023-01-01, 2023-01-02], [2023-01-02, 2023-01-02 12:00:00], but before this fix you only got one [2023-01-01, 2023-01-02 12:00:00]
closes #3859

fix: allow_partial interval batching

---

docs/concepts/audits.md
docs/concepts/models/managed_models.md
docs/concepts/models/model_kinds.md
docs/concepts/models/python_models.md
docs/concepts/models/seed_models.md
sqlmesh/core/model/definition.py
sqlmesh/core/model/kind.py
tests/core/test_model.py

- Add SEED kind property `supports_python_models=False`
- Clarify in docs which model kinds are/aren't supported for Py models

Fix: error if python model has SEED kind

---

.pre-commit-config.yaml
setup.cfg
setup.py
sqlmesh/core/model/common.py
sqlmesh/utils/metaprogramming.py
tests/core/metaprogramming_test_helper.py
tests/core/test_model.py
tests/utils/test_metaprogramming.py

The motivation behind this change is that the `astor` package has a very slow release cadence, so the latest deployed version tends to be quite behind in its Python support. An example is the `match` statement, which fails to be parsed by [astor v0.8.1](https://pypi.org/project/astor/#history), even though it _is_ supported in the main branch of the project:
```python
import pandas as pd
from sqlmesh import model
@model("test_model", columns={"id": "int"})
def entrypoint(*args, **kwargs):
match 'foo':
case 'foo':
pass
return pd.DataFrame({"id": [1, 2, 3]})
```
The above model fails to be loaded:
```
File "sqlmesh/.venv/lib/python3.12/site-packages/astor/node_util.py", line 137, in abort_visit
raise AttributeError(msg % node.__class__.__name__)
AttributeError: No defined handler for node …
```

Fix!: use inspect.getsource in favor of custom parsing, stop relying on astor

---

sqlmesh/cli/main.py

Loaded project is not necessary to invalidate an environment and adds to runtime unnecessarily.

Fix: Skip project loading when running the 'invalidate' CLI command

---

.circleci/continue_config.yml
sqlmesh/core/engine_adapter/base.py
sqlmesh/core/engine_adapter/bigquery.py
sqlmesh/core/model/meta.py
tests/core/engine_adapter/test_bigquery.py

This PR introduces support for column descriptions in nested types in BigQuery, closes #3854 
The syntax follows BigQuery's conventions for nested and repeated columns, using dots to indicate the appropriate level of nesting:
```sql
MODEL (
name schema.record_model,
column_descriptions(
id = "Unique identifier for the event",
repeated_record.sub_repeated_record.sub_field = "Sub-field within nested repeated record",
record.nested_record.field = "Field within nested record",
record.nested_record.array = "Array of integers",
repeated_record.sub_repeated_record = "Nested repeated record",
record.nested_record = "Nested record"
)
);
SELECT
id,
[STRUCT([STRUCT(sub_field AS sub_field)] AS sub_repeated_record)] AS repeated_record,
STRUCT(
STRUCT([2, 3] AS array, field AS field) AS nested_record
) …
```

Feat(BigQuery): Add support for column descriptions in nested fields

---

sqlmesh/core/dialect.py
tests/core/test_model.py

Fixes #3916
The new regex says: "If I see a `dialect`, ensure there's at least one whitespace, then [a-zA-Z]*, optionally wrapped in single quotes to allow stuff like `'duckdb'` (we have some tests for this ...).

Fix: make dialect regex more robust

---

.circleci/continue_config.yml
sqlmesh/schedulers/airflow/state_sync.py

Fix failing test by warning instead of raising in airflow.

Fix: Airflow warn instead of raise in get environment statements method

---

sqlmesh/core/model/kind.py
sqlmesh/core/plan/builder.py
sqlmesh/migrations/v0073_remove_symbolic_disable_restatement.py
tests/core/test_plan.py

fix!: allow restatement of external models

---

sqlmesh/core/model/meta.py
tests/core/test_model.py

The current UX when a column type is missing in the `columns` key is not great:
```
$ pytest tests/core/test_model.py::test_missing_column_data_in_columns_key
...
>               expr = column.args["kind"]
E               KeyError: 'kind'
sqlmesh/core/model/meta.py:208: KeyError
...
```

Chore: improve error message when data type missing from column

---

sqlmesh/core/console.py
sqlmesh/core/context.py
tests/core/test_table_diff.py
tests/integrations/jupyter/test_magics.py

Prior to this PR, `table_diff` queries where not being written to the log file which made debugging table diff issues a lot harder.
Also, when a model was specified (instead of an explicit source / target table), the following issues occurred:
- Only a single `grain` column was being resolved for the join key even if there were multiple columns
- If the model was in a dev environment and the snapshot backing it was a dev preview, SQLMesh would generate the wrong table name and diff against the wrong table
This PR fixes the bugs and introduces the following changes:
- Output a summary of exactly what is being compared / what SQLMesh resolved the model to so that the user can reason about the results
- Resolve models to the virtual layer instead of the physical layer in order to run diffs …

Fix: Fix logging, grain resolution and source/target object names in table_diff

---

.readthedocs.yaml

API docs were not built correctly for pages importing uninstalled modules.
This PR includes all non-dev extras in the module installation before building the API docs.

Chore: install extras modules before building API docs

---

sqlmesh/core/console.py
tests/integrations/jupyter/test_magics.py

When a model is both directly-modified and has a metadata update, we want to display only the former. On the other hand, if it's an indirectly-modified model with a metadata update, we want to show both because the model may not be rebuilt (e.g. if it's an indirectly-non-breaking change), but we still want to show the metadata update status ([example](https://github.com/user-attachments/assets/dcaa31cb-e238-4630-bfa1-59da4eee8ca7)).

Chore: show only one of direct/indirect/metadata update in console summary

---

web/server/api/endpoints/directories.py
web/server/api/endpoints/files.py
web/server/main.py
web/server/settings.py
web/server/utils.py
web/server/watcher.py

**Problem**
In enterprise, we are seeing the above error with tasks. 
**Solution**
Move the work out of the separate executor which solves the above conflict. 
The problem with that change alone is that it make the call slower because in async await context it's now blocking. To avoid that I've made the dependency injection sync which means FastAPI runs it in itsthreadpool, which means it doesn't slow other calls down. Once thing that needed to be done is to then move the lock protecting the work into a thread.

fix: stop from get loaded context in async

---

sqlmesh/core/state_sync/db/facade.py
sqlmesh/core/state_sync/db/interval.py

The interval start shouldn't really concern itself with the removal of partial intervals and just store the given intervals instead.

Chore: Move removal of partial intervals out of the interval state and into the facade

---

sqlmesh/core/loader.py
tests/core/test_context.py

Include the dialect when parsing the statements to ensure that dialect-specific statements, such as the one below in bigquery, are handled correctly when constructing the python_env:
```
EXPORT DATA OPTIONS (URI='gs://path*.csv.gz', FORMAT='CSV') AS SELECT * FROM all_rows
```
thanks for catching this @georgesittas

Fix: Use the dialect when parsing the environment statements for the python_env

---

web/server/api/endpoints/models.py

We're having an issue with the UI where our model paths are relative, and the relative_to function fails. Not sure whether our venv is the issue, but calling absolute() first fixes the issue.
```
raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: '.' is not in the subpath of '/path/to/sqlmesh/repo' OR one path is relative and the other is absolute.
```

make relative paths absolute first in the models endpoint

---

docs/concepts/models/model_kinds.md
sqlmesh/core/dialect.py
tests/core/test_model.py

This PR exposes the `INCREMENTAL_UNMANAGED` model kind that was previously hidden from native projects because it was built to align with DBT's limited notion of incremental models and lacks a bunch of features such as being able to load data in batches.
However, it turns out it's the only model type we have currently that supports append-only tables

Feat: Enable INCREMENTAL_UNMANAGED models in native projects

---

docs/concepts/models/model_kinds.md
sqlmesh/core/model/definition.py
sqlmesh/core/model/kind.py
sqlmesh/migrations/v0074_add_partition_by_time_column_property.py
tests/core/test_model.py
tests/core/test_snapshot.py
tests/integrations/github/cicd/test_integration.py
tests/schedulers/airflow/test_client.py

Currently, if you have a model something like:
```
kind INCREMENTAL_BY_TIME_RANGE (
time_column ds
)
```
Then the `ds` column would be automatically added to the `partitioned_by` columns whether you wanted it to or not.
This PR allows you to opt-out with the following syntax:
```
kind INCREMENTAL_BY_TIME_RANGE (
time_column ds,
partition_by_time_column false
)
```
(the default is `true` to keep the existing behaviour)

Feat!: Allow opting out of the time_column being automatically added to the partitioned_by columns

---

docs/integrations/engines/bigquery.md
sqlmesh/core/config/connection.py

Authenticating a user's credentials and impersonating a service account are two separate actions that the initial implementation incorrectly bundled

Feat: separate BQ user auth from account impersonation

---

setup.py
sqlmesh/core/model/definition.py
tests/core/test_macros.py

The generation for brackets in DuckDB [changed](https://github.com/tobymao/sqlglot/commit/466c839c2cfc94b398dd619b738df165f2876cdb) after v26.6.0, in order to support the latest semantics, [introduced in v1.2.0](https://duckdb.org/2025/02/05/announcing-duckdb-120.html#breaking-changes).
In order to allow folks to use both the old and the new semantics, we introduced a new dialect setting that controls the version of the dialect, e.g. `dialect="duckdb, version=1.1.0"`.
Dialect settings aren't properly supported in SQLMesh right now, because we hard code dialect strings in various places, but most importantly in the engine adapters:
https://github.com/TobikoData/sqlmesh/blob/5fb2c818a720a823d3f8ef45d047bb33f92376fc/sqlmesh/core/engine_adapter/bigquery.py#L62
This means that even if someone …

Chore!: bump sqlglot[rs] to v26.8.0

---

sqlmesh/core/snapshot/definition.py

Unlike the previous implementation this also ensures that each node is visited exactly once.

Fix: Simplify the deployability index creation

---

.circleci/continue_config.yml
sqlmesh/core/state_sync/db/snapshot.py
sqlmesh/migrations/v0055_add_updated_ts_unpaused_ts_ttl_ms_unrestorable_to_snapshot.py
tests/core/engine_adapter/integration/test_integration.py

PR #3903 introduced a subtle bug where the snapshot count queries stopped being quoted. This meant that on engines like Snowflake, `_snapshots` was interpreted as `_SNAPSHOTS` which caused migration to fail.
This PR fixes the issue and adds a test to detect this in future

Fix: State sync snapshot count() quoting

---

sqlmesh/core/scheduler.py
tests/core/test_scheduler.py

Previously, we were batching intervals in an arbitrary order, which could randomly result in child intervals running even when the same interval was unavailable in its parent due to the signal condition not being met.
This fix ensures that batches are computed in DAG order.
Huge kudos to @plaflamme for providing a test case which reproduces the issue (#3951)

Fix: Batch intervals in DAG order to make sure that parent snapshot signals are respected by their children

---

sqlmesh/core/state_sync/db/facade.py

This is no longer needed in cloud implementation.

chore: remove private push snapshots on state sync

---

sqlmesh/core/context.py
tests/core/test_context.py
tests/core/test_plan.py

To prevent unexpected behavior and confusing errors we should fail the plan immediately if we discover that the selector expressions provided by the user don't return any models.

Fix: Fail the plan command if the selector expression doesn't return any models

---

docs/concepts/macros/macro_variables.md
docs/reference/model_configuration.md
sqlmesh/core/config/model.py
sqlmesh/core/model/decorator.py
sqlmesh/core/model/definition.py
sqlmesh/core/renderer.py
sqlmesh/core/snapshot/evaluator.py
tests/core/test_model.py

This update adds: 
- Macro support in `model_defaults` attributes.
- The ability to conditionally enable these, as well as for `physical_properties`, `session_properties`, `virtual_properties`.  
- For `session_properties`, `virtual_properties` rendering is now moved to runtime to align with `physical_properties`. 
- Introduces the `model_kind_name` macro variable, which holds the name of the current model kind.
This macro is intended for example to disable from `physical_properties` the `creatable_type` for your project's VIEW-type models and set it to `TRANSIENT` for the rest of the model kinds, by having in `model_defaults`:
```yaml
dialect: snowflake
start: 2022-01-01
physical_properties:
creatable_type: "@IF(@model_kind_name != 'VIEW', 'TRANSIENT', NULL)"
```

Feat: Adds support for macros in model_defaults and conditional properties

---

sqlmesh/core/plan/builder.py
tests/core/test_integration.py
tests/core/test_plan.py

In a DAG that looks like `A -> B -> C`, if the user makes a `Breaking` change to `A` and a `Non-breaking` change to `B`, then `C` should be categorized as `Indirect Non-Breaking` rather than `Indirect Breaking`, as it was before this change.
At the same time, if `A` was categorized as `Forward-Only` and `B` as `Non-Breaking`, SQLMesh should prefer the `Forward-only` category for `C` over the `Indirect Non-Breaking` one.

Fix: Direct breaking category should only impact direct children snapshot

---

sqlmesh/core/snapshot/definition.py
tests/core/test_snapshot.py

The view promotion logic determines what snapshots have been added based on equality between `SnapshotTableInfo` objects. 
In some cases, two snapshots' table infos may be functionally identical but have their parent node lists ordered differently. When this occurs, we incorrectly determine that they are not the same snapshot.
This PR overrides the `SnapshotTableInfo` `__eq__` method to determine equality based solely on the snapshot fingerprint. All other similar comparisons in the code already use fingerprint.

Fix: determine SnapshotTableInfo equality with fingerprint only

---

sqlmesh/core/model/definition.py
sqlmesh/core/renderer.py
sqlmesh/core/snapshot/evaluator.py
tests/core/test_context.py
tests/core/test_model.py
tests/core/test_snapshot_evaluator.py

This update fixes an issue in `on_virtual_update` statements, ensuring `this_model` resolves to the environment-specific name, when used within `macro` functions. It does this by passing environment naming info to `table_for_environment` instead of using the `fully_qualified_table` from the model, which defaults to the production view.

Fix: Resolution of this_model within macros of on_virtual_update

---

sqlmesh/core/engine_adapter/bigquery.py
tests/core/engine_adapter/integration/test_integration_bigquery.py

Fixes https://github.com/TobikoData/sqlmesh/issues/3978
In the BigQuery engine adapter, type inference for the fields happens through `to_standard_sql()`; However, it seems like the types that do not belong to stanard SQL are not handled properly (e.g RANGE or JSON, see https://github.com/TobikoData/sqlmesh/commit/4951ff9b539c42242050617869127764d120cf6d) and are instead marked as `TYPE_KIND_UNSPECIFIED`. 
This PR adds a fallback for these types and instead uses `field.field_type`, as was used [before](https://github.com/TobikoData/sqlmesh/pull/1089/files):
```SQL
MODEL (name vaggelis.test);
SELECT 
RANGE('01-01-1900'::DATE, '01-01-1902'::DATE) AS my_range, 
JSON '{"id": 10}' AS foo;
```
```Python3
>>> bq_adapter.columns("vaggelis.test");
{'my_range': DataType(
this=Type.RANGE, …
```

Fix!: Type inference for BQ engine adapter

---

docs/integrations/dlt.md
sqlmesh/cli/example_project.py
sqlmesh/cli/main.py
sqlmesh/integrations/dlt.py
sqlmesh/magics.py
tests/cli/test_cli.py

This update adds support to provide an explicit folder for the dlt pipelines. The default location for the pipelines folders is in the user's home directory: `~/.dlt/pipelines/<pipeline_name>`, but in cases where you use a different directory, this allows to provide a specific one using the `dlt-path` argument for the `sqlmesh init` command:
```bash
$ sqlmesh init -t dlt --dlt-pipeline <pipeline-name> --dlt-path <pipelines_directory> dialect
```
as well as the `sqlmesh dlt_refresh` command:
```bash
$ sqlmesh dlt_refresh <pipeline-name> --dlt-path <pipelines_directory>
```
DLT reference: https://dlthub.com/docs/general-usage/pipeline#separate-working-environments-with-pipelines_dir
Slack thread: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1741767926216659

Feat(dlt): Add support to override the dlt pipelines directory

---

.circleci/continue_config.yml

should fix https://github.com/TobikoData/sqlmesh/issues/3983
minor change in test name in circleci
> style_and_slow_tests -> style_and_cicd_tests
> 
> Run slow tests -> Run cicd tests

fix: rename slow -> cicd tests in circleci

---

pyproject.toml

This should fix the CI, temporarily reverted the DuckDB timestamp/datetime parsing changes.

Chore: bump sqlglot to v26.10.1

---

sqlmesh/core/model/definition.py
tests/core/test_model.py

Small change that allows users to extract out the blueprint list into a macro, instead of inlining it in the model itself.

Feat: support dynamic blueprinting

---

sqlmesh/core/dialect.py
tests/core/test_dialect.py

This update addresses the issue with formatting models containing ON_VIRTUAL_UPDATE statements when running `sqlmesh format`, fixes: #3996

Fix: Support on-virtual-update statements in sqlmesh format

---

sqlmesh/core/engine_adapter/mixins.py
sqlmesh/core/engine_adapter/redshift.py
tests/core/engine_adapter/test_redshift.py

We should always include NO SCHEMA BINDING when creating views in Redshift. Otherwise view creation fails when used with something like external tables.
At the same, views with NO SCHEMA BINDING can't be created for models that rely on recursive CTEs in their queries. This update makes it so that NO SCHEMA BINDING is omitted only when recursive CTES are used.

Fix: Enable schema binding when creating views for queries with recursive CTEs in redshift

---

sqlmesh/core/engine_adapter/redshift.py
sqlmesh/core/schema_diff.py
tests/core/engine_adapter/test_redshift.py
tests/core/test_schema_diff.py

Fix: Only allow to increase precision of VARCHAR for redshift

---

sqlmesh/core/plan/evaluator.py
sqlmesh/core/snapshot/evaluator.py
tests/core/test_integration.py
tests/core/test_snapshot_evaluator.py

This ensures that deployable physical views are available for non-breaking snapshots when migrating downstream indirect non-breaking child view.

Fix: Migration of indirect non-breaking views

---

sqlmesh/core/environment.py
tests/core/test_context.py
tests/core/test_integration.py

This update  passes the  `runtime_stage` and `engine_adapter` in the `before_all` and `after_all` statements so that they can be used in macros called in these statements.

Fix: Pass runtime_stage and engine_adapter in environment_statements

---

sqlmesh/core/model/definition.py
tests/core/test_model.py

Previously, whether the `start_*` / `end_*` macros were supported in pre- or post-statements depended on the model kind. For example, they were not supported if the model was of kind VIEW or FULL. This change ensures that these macros are always available in pre- and post-statements

Fix: Always support start_* / end_* macros in pre- / post- statements

---

sqlmesh/core/model/decorator.py
sqlmesh/core/model/definition.py

Loading blueprints is suboptimal today, because the `blueprints (...)` property is needlessly preserved in the `Model` expression until very late in the loading stage (`_create_model`).
This leads to performance issues when rendering the `MODEL (...)` block to resolve macro calls, because we're traversing very big ASTs that unnecessarily carry the whole blueprint list with them.
We only need to extract the blueprints variables from `blueprints`, so it can be dropped earlier. This PR makes this change.

Feat: improve blueprint loading performance

---

sqlmesh/cli/example_project.py
sqlmesh/integrations/dlt.py
tests/cli/test_cli.py

This update adds support for generating projects for DLT pipelines using the [filesystem destination](https://dlthub.com/docs/dlt-ecosystem/destinations/filesystem), by generating incremental models as usual and using the default [dialect's connection configs](https://github.com/TobikoData/sqlmesh/pull/3733) for the user to add the appropriate credentials based on their engine.
relevant slack thread: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1742201363993729

Feat(dlt): Add support for project generation in filesystem pipelines

---

web/Dockerfile.api

It seems like `make ui-up` has been broken since #3953. I've updated `web/Dockerfile.api` to reflect migrating from `setup.py` to `pyproject.toml`.
The command is currently failing for me with:
```
=> ERROR [generate-openapi-spec 3/5] COPY setup.py setup.py                                                                                   0.0s
=> ERROR [api 3/5] COPY setup.py setup.py                                                                                                     0.0s
```

fix make ui commands

---

sqlmesh/core/context.py
tests/core/test_format.py

Fixes #3976
This is what the new output looks like (messaging is similar to `black`):
EDIT: messaging updated.

Feat: improve format --check output

---

sqlmesh/core/context.py
tests/core/test_integration.py

There was a recent regression that caused the --run flag passed into the plan command to be ignored. This fixes the issue and adds a test to prevent this regression from happening in future.

Fix: Support run flag in the plan command

---

pyproject.toml
sqlmesh/core/dialect.py

Regarding the duckdb change, see https://github.com/tobymao/sqlglot/commit/c0b3448e7a4ec46485dd65b7498855ab57e029ef.

Chore!: bump sqlglot to v26.12.0

---

sqlmesh/core/config/connection.py
tests/core/test_config.py

Prior to this change the model is referenced before it is defined which seems to cause issues in 2.11+ pydantic versions.

fix: fix pydantic import but moving duckdb attach earlier

---

sqlmesh/core/engine_adapter/mixins.py
tests/core/engine_adapter/test_mssql.py

Fixes https://github.com/TobikoData/sqlmesh/issues/4048
The issue here was that we dropped `LIMIT` clauses even if the expression wasn't 0, but MSSQL requires it when an `ORDER` clause is present.
```
2025-03-28 01:32:52,704 - ThreadPoolExecutor-1_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE VIEW [__temp_ctas_r5u2t2m9] AS SELECT [a].[id] AS [id], [c].[test_value] AS [test_value] FROM [master].[dbo].[test_table] AS [a] OUTER APPLY (SELECT [b].[test_value] FROM [master].[dbo].[test_table_two] AS [b] ORDER BY [b].[test_value]) AS [c]; (base.py:2113)
2025-03-28 01:32:52,714 - MainThread - sqlmesh.core.plan.evaluator - INFO - Execution failed for node SnapshotId<"master"."dbo"."test_model": 3980861674> (evaluator.py:289)
File …
```

Fix: only drop LIMIT 0 in VarcharSizeWorkaroundMixin table creation

---

sqlmesh/core/macros.py
tests/core/test_macros.py

this could break existing macro usage with variables that have spaces

fix!: fix macros with spaces to make them more consistent

---

docs/concepts/macros/macro_variables.md
docs/integrations/dbt.md
examples/multi_dbt/bronze/dbt_project.yml
examples/multi_dbt/silver/dbt_project.yml
examples/multi_dbt/silver/macros/store_schemas.sql
sqlmesh/core/environment.py
sqlmesh/core/renderer.py
sqlmesh/dbt/loader.py
sqlmesh/dbt/manifest.py
tests/core/test_context.py
tests/core/test_integration.py
tests/dbt/test_adapter.py
tests/dbt/test_transformation.py
tests/fixtures/dbt/sushi_test/dbt_project.yml
tests/fixtures/dbt/sushi_test/macros/create_tables.sql

This update adds support for dbt's [`on-run-start` and `on-run-end` hooks](https://docs.getdbt.com/reference/project-configs/on-run-start-on-run-end) which are defined in `dbt_project.yml`:
```yaml
on-run-start: sql-statement | [sql-statement]  
on-run-end: sql-statement | [sql-statement]  
```  
Internally, these are mapped to SQLMesh's [`before_all` and `after_all` statements](https://sqlmesh.readthedocs.io/en/stable/guides/configuration/?h=before#before_all-and-after_all-statements) 
---
As part of this update, the [`schemas`](https://docs.getdbt.com/reference/dbt-jinja-functions/schemas) variable is also supported, enabling to grant privileges as you would in dbt with a macro:  
```jinja
{% macro grant_usage_to_schemas(schemas, user) %}
{% for schema in schemas %}
GRANT USAGE ON …
```

Feat(dbt): Add support for on-run-start and on-run-end hooks

---

docs/guides/linter.md

- Linting now happens at plan creation time, not load time
- Document the new `sqlmesh lint` command for faster dev iterations

Chore: Fix linter docs for new command

---

.circleci/continue_config.yml

The airflow tests are currently failing on main because the ancient version of pip was having trouble resolving dependencies and hanging.
Simply upgrading pip prior to setting up the python env seems to fix the issue

Chore: Fix airflow tests

---

sqlmesh/core/model/definition.py
sqlmesh/migrations/v0077_fix_column_type_hash_calculation.py
tests/core/test_model.py

Otherwise, there can be a mismatch between the hash computed using the original instance of a model and the deserialized one when the type is constructed using the default dialect. (eg. `exp.DataType.build("int")`).
Example:
```
In [6]: exp.DataType.build("int").sql("bigquery")
Out[6]: 'INT64'
In [7]: exp.DataType.build("int64", dialect="bigquery")
Out[7]: DataType(this=Type.BIGINT, nested=False)
```

Fix!: Pass the model dialect when computing a hash for the column types

---

docs/integrations/dbt.md

sqlmesh version: 0.170.1
engine: snowflake
When following the documentation [here](https://sqlmesh.readthedocs.io/en/stable/integrations/dbt/#reading-a-dbt-project) and running the command `sqlmesh init -t dbt`, keeps getting error like below:
```
File "/home/venvs/sqlmesh_env/bin/sqlmesh", line 8, in <module>
sys.exit(cli())
^^^^^
File "/home/venvs/sqlmesh_env/lib/python3.11/site-packages/click/core.py", line 1161, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/venvs/sqlmesh_env/lib/python3.11/site-packages/click/core.py", line 1082, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/home/venvs/sqlmesh_env/lib/python3.11/site-packages/click/core.py", line 1697, in invoke
return …
```

Update dbt integration doc sqlmesh init command to avoid init error

---

sqlmesh/core/model/definition.py
tests/core/test_model.py

This model fails in main currently:
```sql
MODEL (
name @foo.some_table,
kind FULL,
blueprints ((
foo := bar
))
);
SELECT
1 AS c
```
With the following error:
```
Error: Failed to load model definition at 'playground/models/test.sql'.
Expected a key-value mapping for the blueprint value, got 'foo := bar' instead at 'playground/models/test.sql'
```
This PR addresses this.

Fix: single blueprint edge case

---

sqlmesh/core/environment.py
sqlmesh/core/renderer.py
tests/core/test_integration.py

Make jinja_macros optional for environment statements to ensure they don't cause extra diffs when running plan in latest versions of pydantic ( > 2.10 ).

Fix: Make jinja_macros optional for environment statements

---

sqlmesh/core/dialect.py
tests/core/test_dialect.py

Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1743582978860569

Fix!: dont wrap macro vars and str replacements in intervals

---

sqlmesh/utils/metaprogramming.py
tests/utils/test_metaprogramming.py

This PR addresses a bug in the Python code serialization logic. When walking objects and looking up function globals, we only add them to the environment if the fetched objects are not falsey, which leads to excluding falsey primitives such as `0`, `False` and `None`. A minimally-reproducible example for this is shown below:
```python
import pandas as pd
from sqlmesh import model
Z = 0
@model(name="foo", columns={"id": "int"})
def entrypoint(context, *args, **kwargs):
return pd.DataFrame({"id": [Z]})
#
#
```
No additional context here. I was simply playing around locally and came across this issue, so figured I'd fix it.

Fix: python serialization edge case

---

sqlmesh/core/console.py
sqlmesh/core/table_diff.py
tests/core/test_table_diff.py

This update improves the filtering approach in table diff when displaying the diff samples for a column, which failed to properly handle array types before.
As part of this also decimal values are now correctly aligned by propagating the decimal precision in row diff to properly display them in the sample. Also added helper methods (`capture_console_output` and `create_test_console`) so we can verify in tests the exact output of console methods from now on.

Fix: Account for array types when showing sample in table diff

---

sqlmesh/core/constants.py
sqlmesh/core/context.py
sqlmesh/core/macros.py
sqlmesh/core/model/common.py
sqlmesh/core/model/decorator.py
sqlmesh/core/model/definition.py
sqlmesh/core/test/context.py
sqlmesh/utils/metaprogramming.py
tests/core/test_model.py

Fixes #4017
Given a model like this:
```sql
MODEL (
name m.@{foo},
blueprints (
(foo := "s p a c e s"),
(foo := 'c'),
),
);
SELECT
@foo AS col
```
The blueprint variables that contain quotes are incorrectly rendered today:
```python
from sqlmesh import Context
ctx = Context()
for fqn, model in ctx.models.items():
print(f"Fully-qualified name: {fqn}, name: {model.name}, query: {model.render_query().sql()}")
```
This PR addresses this bug with the help of [this commit](https://github.com/TobikoData/sqlmesh/commit/d0154902e646d3ef8bc758660018afc233108578), by changing the representation of the blueprint values: their values are now the parsed ASTs, and not the corresponding SQL strings. This behavior is more intuitive, because for example quoted identifiers will be correctly interpolated in …

Fix!: serialize blueprint variables separately to leverage AST

---

docs/concepts/macros/sqlmesh_macros.md
docs/concepts/models/python_models.md
docs/concepts/models/sql_models.md

See also https://github.com/TobikoData/sqlmesh/pull/4061

Chore: update blueprint docs

---

docs/integrations/dbt.md
sqlmesh/cli/example_project.py
tests/cli/test_cli.py

This fixes a regression with the init command for dbt projects which didn't work without a dialect.

Fix: Make dialect in dbt init noncompulsory again

---

sqlmesh/core/state_sync/db/interval.py
tests/core/engine_adapter/integration/config.yaml

Fix: Refreshing snapshot intervals for uncategorized snapshots when state is stored in databricks

---

sqlmesh/core/console.py
tests/cli/test_cli.py

The CLI "Models needing backfill" section displays inclusive interval ranges. Currently, the evaluation progress bar prints exclusive ranges, so they display conflicting information.
This PR makes the progress bar print inclusive intervals as well.

Fix: display inclusive intervals in eval progress bar

---

sqlmesh/core/model/kind.py
tests/core/test_model.py

`ModelKindName.SCD_TYPE_2` is a legacy model kind name that represents an SCD Type 2 by time model. So the prior logic said that only legacy SCD Type 2 by time models had full history restatements when the intention was for all of them to have it.

fix: correctly have scd models depend on past

---

sqlmesh/core/engine_adapter/databricks.py

Databricks currently uses its superclass Spark's `_get_data_objects()` method, which requires special handling to ensure the right catalog is being used when the query is executed.
Databricks now provides a standard `INFORMATION_SCHEMA` system table that contains information about objects in all catalogs. This PR changes the DBX implementation to use that system table.
NOTE: only objects registered with Unity Catalog will be included in this system table. SQLMesh requires Unity Catalog, so this is not an additional requirement.

Chore: use information_schema in dbx _get_data_objects

---

sqlmesh/core/audit/definition.py
sqlmesh/core/console.py
sqlmesh/core/context_diff.py
sqlmesh/core/model/common.py
sqlmesh/core/model/definition.py
tests/core/test_plan.py

This update adds the Python dependencies to the `before all` / `after all` diff and aims to improve the formatting using the Syntax library for consistency with the rest of the diffs. This adds syntax highlighting for Python code in the dependencies section and accordingly for SQL in the statements.

Feat: Improve the cli before all after all diff and include python env

---

sqlmesh/core/console.py
sqlmesh/core/plan/evaluator.py
sqlmesh/core/scheduler.py
sqlmesh/core/snapshot/evaluator.py
sqlmesh/utils/__init__.py
tests/cli/test_cli.py

When a plan only performs a virtual update, no physical layer updates or model evaluations occur.
Currently, there is no CLI output indicating that the physical layer updates and model evaluations were skipped on purpose (the progress bars just don't appear).
This PR adds messages indicating that the physical layer updates and/or model evaluations were skipped:
- Physical: `SKIP: No physical layer updates to perform`
- Models: `SKIP: No model batches to execute`

Feat: print CLI messages when no physical layer or model evals occurred

---

sqlmesh/core/snapshot/definition.py
sqlmesh/utils/errors.py
tests/core/test_snapshot.py

Signal evaluation errors are user errors that we want to properly catch

feat: add custom exception for signal eval errors

---

sqlmesh/core/console.py
sqlmesh/core/state_sync/common.py
sqlmesh/core/state_sync/db/facade.py
sqlmesh/core/state_sync/export_import.py

Prior to this PR, the `StateStream` interface as a whole didn't lend itself well to streaming. The properties it exposed were streams but it itself was not a stream. This made it difficult to send over a HTTP boundary and reassemble on the other side.
This PR changes the `StateStream` interface to be an iterator over its components instead. This makes it much easier to send over HTTP as the sender controls the order in which the components are emitted, not the caller.
The caller just iterates over the stream and uses `isinstance` checks to identify which component its dealing with. I chose `isinstance` checks over checking a "type" property because they play nicely with MyPy

Chore: Refactor the state stream interface

---

sqlmesh/core/snapshot/definition.py
sqlmesh/utils/errors.py
sqlmesh/utils/metaprogramming.py
tests/core/test_snapshot.py

Use the `format_evaluated_code_exception` to properly format the exception for the python env.

fix: include stacktrace in signal eval error message

---

sqlmesh/core/context.py
sqlmesh/core/loader.py
sqlmesh/core/test/__init__.py
sqlmesh/core/test/discovery.py
sqlmesh/core/test/result.py
sqlmesh/core/test/runner.py
sqlmesh/magics.py
sqlmesh/utils/yaml.py
tests/core/test_test.py

Fixes https://github.com/TobikoData/sqlmesh/issues/4068
This PR addresses the following items:
- [Fix] https://github.com/TobikoData/sqlmesh/pull/4047 did not properly handle cases where the model doesn't exist, the errors should be caught
- [Fix] The testing module only takes `config.variables` into account; This is now extended to also use the selected gateway's variables
- [Refactor] The APIs for loading & running tests are fragmented into multiple points e.g `run_model_tests` and `run_tests`. To address that, this PR attempts to unify the test loading+running logic.

Fix!: Propagate gateway variables to model tests

---

sqlmesh/core/dialect.py
tests/core/test_dialect.py

This fixes an issue in formatting [model meta properties that have macro functions](https://github.com/TobikoData/sqlmesh/pull/2574) by handling them in `_props_sql` to account for macro funcs. 
Relevant slack thread: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1744698810151999?thread_ts=1741243847.726999&cid=C044BRE5W4S

Fix: Handle macros in model properties when formatting

---

Makefile
tooling/README.md
tooling/vscode/extensions.json
tooling/vscode/launch.json
tooling/vscode/settings.json
tooling/vscode/tasks.json
vscode/extension/.gitignore
vscode/extension/.vscode-test.mjs
vscode/extension/.vscodeignore
vscode/extension/CHANGELOG.md
vscode/extension/README.md
vscode/extension/esbuild.js
vscode/extension/eslint.config.mjs
vscode/extension/package-lock.json
vscode/extension/package.json
vscode/extension/src/commands/format.ts
vscode/extension/src/extension.ts
vscode/extension/src/lsp/lsp.ts
vscode/extension/src/test/extension.test.ts
vscode/extension/src/utilities/common/constants.ts
vscode/extension/src/utilities/common/log.ts
vscode/extension/src/utilities/common/python.ts
vscode/extension/src/utilities/common/settings.ts
vscode/extension/src/utilities/common/setup.ts
vscode/extension/src/utilities/common/utilities.ts
vscode/extension/src/utilities/common/vscodeapi.ts
vscode/extension/src/utilities/functional/result.ts
vscode/extension/src/utilities/sqlmesh/sqlmesh.ts
vscode/extension/tsconfig.json

firt pass of the vscode extension that includes three features: 
1. lsp which can be used for formatting files
2. command to format whole project
3. ability to restart servers/react to interpreters being changed
open branch
run the following to set up your vscode environment with right settings (be mindful this might override yours)
```bash
make vscode_settings
```
launch the debugger task 'Run extension'
open a SQL file and in the command palette run `Format document` to document single file
run `Format SQLMesh project` to format whole project

feat: introduce minimal extension

---

docs/reference/configuration.md
sqlmesh/core/config/janitor.py
sqlmesh/core/config/root.py
sqlmesh/core/context.py
sqlmesh/core/state_sync/common.py
tests/core/state_sync/test_state_sync.py

This allows users to restore the janitor's previous behavior.

Feat: Add a janitor configuration that allows to warn instead of failing if it fails to delete an expired environment schema / view 

---

.circleci/continue_config.yml
sqlmesh/core/engine_adapter/databricks.py

Prior to this PR, if a Databricks engine adapter was created as multithreaded then the spark engine adapter created internally was single threaded. Therefore the threads would potentially collide and attempt to share common resources. The main issue was `_last_df` which stores the last result which could then be shared across the threads. Also went ahead and reviewed the other kwargs that seems to make sense to pass into the spark engine adapter.

fix: properly share engine adapter config to spark engine adapter

---

sqlmesh/core/plan/evaluator.py
tests/core/test_integration.py

This prevents empty intervals from being recorded for unrelated snapshots.

Fix: Apply empty backfill only to snapshots that have been selected for backfill within a plan

---

sqlmesh/core/linter/definition.py
sqlmesh/core/linter/rule.py
sqlmesh/core/linter/rules/builtin.py
sqlmesh/core/loader.py

This moves the ruleset into the linter definition file. The `RuleSet` is essentially a helper object for the Linter and as such we've put it together with it.
The real reason, though, for this is that we want to make the interface/cognitive load that the customer has to understand to implement a lint rule as small as possible, and essentially just be the `rule.py` file. This makes that file smaller and the load smaller.

refactor: move ruleset into linter definition

---

sqlmesh/core/console.py
sqlmesh/core/context.py
sqlmesh/core/context_diff.py
sqlmesh/integrations/github/cicd/controller.py
tests/core/test_context.py
tests/core/test_plan.py

This update revises the cli output of `before_all` `after_all` statements to 
- not include the python env differences on first plan
- use unidiff for it so that is in line with models instead of ndiff
- account for `--no-diff` flag and don't display the differences when its provided
- as part of this also decoupled `show_model_difference_summary`

Chore: Refine environment statements cli output

---

sqlmesh/core/engine_adapter/base.py
sqlmesh/core/engine_adapter/databricks.py

This fix was needed: https://github.com/TobikoData/sqlmesh/pull/4162
The problem is if a `with_log_level` call happened then it would not include the `multithreaded` argument and therefore the spark session class would be created as single threaded which is not expected.

fix: pass multithreaded with log level

---

sqlmesh/core/model/definition.py
sqlmesh/core/snapshot/evaluator.py
tests/core/test_context.py

Fixes https://github.com/TobikoData/sqlmesh/issues/3966
Internally, `start` & `end` dates are converted to exclusive range to accommodate the interval logic and are transformed back to inclusive during render / evaluation.
The issue is apparent during plan because:
- When running `sqlmesh plan --start <date> --end <date>`, we apply the missing interval logic and propagate the **exclusive** range to `render_audit_query`; We then create the `BETWEEN` filter manually without converting the range back to inclusive, as is the case in all other render calls
- When running `sqlmesh audit --start <date> --end <date>`, the dates are propagated as-is

Fix: Make date range inclusive for audits ran in `sqlmesh plan`

---

docs/integrations/engines/motherduck.md
sqlmesh/core/config/connection.py
tests/core/test_connection_config.py

This update addresses an issue in failing to attach multiple catalogs in MotherDuck by not raising an error internally when the path contains a name and by using `IF EXISTS` for attach. Also corrects minor error in docs.

Fix(motherduck): Attach multiple catalogs in MotherDuck

---

sqlmesh/core/console.py
sqlmesh/core/plan/builder.py
tests/core/test_plan.py

The user should not be able to categorize forward-only into BREAKING or NON-BREAKING. There are a few important invariants that rely on the fact that forward-only models are always categorized as forward-only.

Fix: Forward-only models can't be categorized manually

---

docs/quickstart/cli.md

This PR updates the CLI documentation output descriptions to align with the current SQLMesh CLI output.
Changes include:
- Fixed line number references in output explanations
- Updated descriptions of model execution behaviors
- Clarified the explanation of virtual updates vs. backfills
- Ensured all descriptions match the visual output shown in screenshots
These updates help users better understand what's happening when they run CLI commands.

Update CLI documentation descriptions to match current output format

---

vscode/extension/package.json
vscode/extension/src/auth/auth.ts
vscode/extension/src/commands/signin.ts
vscode/extension/src/commands/signinSpecifyFlow.ts
vscode/extension/src/extension.ts
vscode/extension/src/utilities/isCodespaces.ts

- little improvements to the removing and labelling of sessions

feat: add device flow to vscode extension

---

vscode/extension/src/lsp/lsp.ts

- makes the name that the lsp output is recorded much nicer from a demo name to something logical.
From 
To 
`sqlmesh-lsp`

fix(vscode): improve naming of lsp channel

---

vscode/extension/package.json

Best source of info is here: https://code.visualstudio.com/api/advanced-topics/remote-extensions#installing-a-development-version-of-your-extension
Essentially when you run an extension and you are in an environment where you are connecting vscode to a remote host, the extension can either run on vscode or on the remote host. Currently, in the above example, the extension would run on the host connected rather the one being connect to, this flag changes that.

fix(vscode): force extension to run on host

---

vscode/extension/package.json

when depending on the microsoft python extension to manage python environments as we do, as outlined here, you need to add the Microsoft python extension as an explicit dependency as explained here https://www.npmjs.com/package/@vscode/python-extension
without it you get weird start up bug where the extension doesn't fire off until the ms python extension starts

fix(vscode): specify python requirement

---

vscode/extension/README.md

Fix small typo in extension readme (explicitely). the others minor changes from auto-formatting

Chore(vscode): Fix typo in readme of extension

---

sqlmesh/core/engine_adapter/bigquery.py
tests/core/engine_adapter/test_bigquery.py

The temporary table may include additional columns returned by the query that are not present in the target table. Sourcing column-to-types from the temporary table may make the schema inconsistent with the actual table into which the data is inserted.

Fix: Columns should be sourced from the target table and not the temporary merge table

---

sqlmesh/core/config/connection.py
sqlmesh/core/config/scheduler.py
sqlmesh/core/context.py
tests/core/test_config.py

This update addresses an issue when the configured default gateway's concurrency (e.g. Athena with concurrent_tasks=4) differs from a model-specific gateway (e.g. BigQuery with concurrent_tasks=1) which is explicitly set in some of the models. In these cases, it leads to BigQuery not running in a multithreaded mode and failing to run concurrent jobs. 
The issue is that concurrent_tasks is passed to the snapshot evaluator, but the connection uses the gateway specific or default. This fix ensures that concurrent_tasks is passed to the connection as well to align all gateways for multithreaded use when applied.

Fix: When initialising multiple connections pass concurrent tasks

---

sqlmesh/core/config/root.py
tests/integrations/github/cicd/test_config.py

Prior to this a user could enter a value like `1 week` and it would set the ttl in the past making all of their environments or snapshots immediately expire.

fix: prevent past ttl values for environment and snapshot

---

sqlmesh/core/config/root.py
tests/core/test_config.py

Resolves: https://github.com/TobikoData/sqlmesh/pull/4207
Reverting the typed approach used here since it was causing strange behavior and I didn't want to debug it further: https://github.com/TobikoData/sqlmesh/pull/4158

fix: allow subclassing of config again

---

docs/guides/multi_engine.md

Update the indentation to ensure MkDocs renders the configurations' code blocks under separate tabs. Since we use the [content.tabs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/) extension in `mkdocs.yml`, tab indentation is required to group code blocks under different labels properly on the website.

Chore(docs): Adjust indentation for MkDocs tabs to group content

---

sqlmesh/core/audit/definition.py

The `AuditMixing` class is not a pydantic model so `formatting` being a `Field` can yield a warning on certain Python versions.
This PR solves the warning by replicating the flag across `ModelAudit` and `StandaloneAudit`, similar to how we do it for `expressions_` or `JinjaMacros`.

Fix: Replicate `formatting` to pydantic classes

---

sqlmesh/core/dialect.py
tests/core/test_model.py

The behavior today in main is as follows:
```sql
MODEL (
name test_schema.@{table_name},
kind FULL,
blueprints (
(table_name := "test_table", stage_path := 'foo'),
)
);
SELECT * FROM @stage_path (file_format => 'bar') LIMIT 100
```
```
(.venv) ➜  sqlmesh render test_schema.test_table
Error: Failed to resolve macros for
SELECT
*
FROM @stage_path(file_format => 'bar')
LIMIT 100
Macro 'stage_path' does not exist. at '.../playground/models/test_model.sql'
```
This is because the parsing is off:
```python
>>> from sqlmesh.core.dialect import parse_one
>>> parse_one("""
... SELECT
...   *
... FROM @stage_path (FILE_FORMAT => 'foo')
... LIMIT 100
... """, dialect="snowflake")
Select(
expressions=[
Star()],
limit=Limit(
expression=Literal(this=100, is_string=False)),
from=From(
this=Table( …
```

Fix: address staged file path edge case in snowflake parsing

---

sqlmesh/core/context.py
sqlmesh/core/model/definition.py
sqlmesh/core/snapshot/cache.py
sqlmesh/core/state_sync/cache.py
tests/core/test_integration.py

Otherwise, it's impossible to repair the target environment after upgrade which caused the existing snapshots to be unrenderable.

Fix: Plan application should succeeed even when the snapshot query in state is unrenderable

---

sqlmesh/core/console.py
tests/cli/test_cli.py

The CLI execution progress bar prints an annotation for each model after it is executed.
Currently, the annotation column width includes unnecessary space due to how it is calculated. This PR removes that space.
Column width calculations (`max` is over snapshots):
- Old: `max(len(annotation)) + max(len(audits))`
- Corrected: `max(len(annotation) + len(audits))`

Fix: remove extraneous spacing between CLI annotation and runtime

---

sqlmesh/core/plan/builder.py
sqlmesh/core/snapshot/definition.py
tests/core/test_context.py
tests/core/test_integration.py
tests/core/test_snapshot.py

Scenario:
1. DAG: A -> B (forward-only) -> C
2. User makes a metadata change to A
3. Plan shows that C needs backfilling
The issue occurred because B got categorized as `FORWARD_ONLY` instead of `METADATA` which lead to C being treated as non-deployable. Provide its dev intervals were empty (since it itself wasnt forward-only and therefore didn't inherit production intervals), the planner concluded that backfill was necessray.
This fix ensures that B in the example above is categorized as `METADATA` (which is more accurate anyway) and so C subsequently is treated as both deployable and representative.

Fix: Make sure backfill is not triggered for models downstream of met…adata changes

---

sqlmesh/core/plan/evaluator.py

A long time ago, we created physical tables eagerly and assumed that if a snapshot record existed, a corresponding physical table must also exist. That’s why the order of operations mattered a lot - the record could only be created after the physical table was successfully created.
This is no longer necessary, as physical tables are now created lazily, on demand, if they’re missing

Fix: Create snapshot records before creating physical tables

---

.circleci/continue_config.yml
sqlmesh/core/dialect.py
sqlmesh/core/model/meta.py
sqlmesh/migrations/v0081_update_partitioned_by.py
tests/core/engine_adapter/test_athena.py
tests/core/test_context.py
tests/core/test_model.py
tests/core/test_snapshot.py

This addresses issue #4090 
Prior to this PR, a partition expression in a `MODEL` block like:
```
MODEL (
...,
partitioned_by (bucket(4, a), colb)
);
```
would be parsed into an `exp.Anonymous` node. SQLGlot gained support for `exp.PartitionedByBucket` (and `exp.PartitionedByTruncate`) in order to handle Iceberg transforms in a first class manner.
This is important because Athena inexplicably expects the arguments on the partition transforms to be in a different order depending on if the query is a `CREATE TABLE` or a `CTAS`.
This PR changes the `partitioned_by` property to be parsed with the SQLGlot `_parse_partitioned_by` parser instead of the fallback `_parse_bracket(_parse_field)` parser so that the correct AST nodes are created.
This has the effect of standardizing the parsing of …

Fix!: Change how `partitioned_by` is parsed so that partition expressions with specialized AST nodes are captured

---

sqlmesh/core/context.py
sqlmesh/core/engine_adapter/base.py
sqlmesh/core/renderer.py
sqlmesh/core/snapshot/definition.py
tests/core/test_context.py
tests/core/test_integration.py

The uncategorized parent won’t have a physical table available, so if the user runs `evaluate` on a downstream child that relies on uncategorized upstream changes, the command will fail.
This update makes it so that uncategorized parents are inlined into the target model's query automatically during rendering.

Fix: Expand the parent's model query during query rendering if the parent is not categorized

---

.circleci/config.yml
.circleci/continue_config.yml
docs/integrations/engines/snowflake.md
sqlmesh/core/engine_adapter/snowflake.py
sqlmesh/core/snapshot/evaluator.py
tests/core/engine_adapter/integration/test_integration_snowflake.py
tests/core/engine_adapter/test_snowflake.py
tests/core/test_snapshot_evaluator.py

Addresses issue #3829 
Prior to this, `table_format iceberg` was ignored by the Snowflake adapter.
It now checks for this property and uses it to trigger `CREATE ICEBERG TABLE` statements instead of normal `CREATE TABLE` statements

Feat: Enable Iceberg support for Snowflake

---

sqlmesh/core/engine_adapter/base.py
tests/core/engine_adapter/test_base.py

Values may contain sensitive information and unnecessarily bloat the logs, making them incomprehensible..

Fix: Don't log SQL in the engine adapter if the statement contains values

---

pyproject.toml

The `Databricks` adapter's `_fetch_native_df` method [relies on pyarrow's API](https://github.com/TobikoData/sqlmesh/blob/e2adfe3714b8c794cf348123e022304fd37119f9/sqlmesh/core/engine_adapter/databricks.py#L194). If `pyarrow` is missing, `fetchdf` breaks:
```python
>>> from sqlmesh import Context
>>> ctx = Context()
>>> ctx.fetchdf("select * from foo.bar")
[WARN] pyarrow is not installed by default since databricks-sql-connector 4.0.0,any arrow specific api (e.g. fetchmany_arrow) and cloud fetch will be disabled.If you need these features, please run pip install pyarrow or pip install databricks-sql-connector[pyarrow] to install
[WARN] Parameter '_user_agent_entry' is deprecated; use 'user_agent_entry' instead. This parameter will be removed in the upcoming releases.
Traceback (most recent …
```

Chore: add pyarrow as a dependency for the databricks target

---

sqlmesh/core/macros.py
sqlmesh/core/renderer.py
sqlmesh/utils/metaprogramming.py
tests/core/test_macros.py

Handle MacroEval errors similar to pythonmodel and signal evaluation errors that we want to catch.

Fix: Add custom exception for macro evaluation errors

---

vscode/extension/eslint.config.mjs
vscode/extension/src/commands/format.ts
vscode/extension/src/extension.ts
vscode/extension/src/utilities/errors.ts
vscode/extension/src/utilities/sqlmesh/sqlmesh.ts

Handle the cases where 
- `sqlmesh_lsp` is not present 
- `pygls` and `lsprotocol` are not present, recommend installing `sqlmesh[lsp]`

feat(vscode): better errors for missing sqlmesh_lsp

---

sqlmesh/core/context.py
sqlmesh/core/state_sync/base.py
sqlmesh/core/state_sync/cache.py
sqlmesh/core/state_sync/db/environment.py
sqlmesh/core/state_sync/db/facade.py
sqlmesh/core/state_sync/db/snapshot.py
tests/core/state_sync/test_state_sync.py
tests/core/test_context.py
tests/core/test_integration.py

Fixes https://github.com/TobikoData/sqlmesh/issues/4055
This PR changes the order of deletions so that the actual views & physical tables are deleted **before** their state sync entries; This ensures that if the former fails, the state sync is not modified and a future `sqlmesh janitor` can pick up again the expired snapshots & environments on a later invocation.

Fix: Enviroment & snapshot cleanup order

---

sqlmesh/core/test/definition.py
sqlmesh/core/test/result.py
sqlmesh/core/test/runner.py
tests/core/test_test.py

To [freeze time](https://sqlmesh.readthedocs.io/en/latest/concepts/tests/#freezing-time) through `execution_time` in unit tests we essentially patch the SQLGlot dialects globally to generate any `CURRENT_<date/time>()` reference as a cast at the specified time & type.
This works fine if tests are run sequentially but runs into race conditions in concurrent execution. This PR:
- Replaces the global patching for SQL models by instead transforming the corresponding AST nodes before generation
- Locks the global patching for Python models using the runner's `lock`; This is required because Python models can execute any SQL statement, so the patching is indeed necessary to cover that globally.

Fix: Avoid concurrent dialect patching in model testing

---

docs/guides/table_migration.md
docs/reference/cli.md
sqlmesh/cli/main.py
sqlmesh/core/context.py
sqlmesh/magics.py
tests/core/test_integration.py

The previous interface was very confusing: the user had to determine whether they needed the dev or prod version of the table without having any context about which version they actually needed.
Additionally, the command always returned the physical table name of the locally defined model version, which caused a problem when that version hadn’t been applied yet - in which case the command would fail.
The new interface takes the environment name as an argument with default being `prod` (or whatever default was defined in the project config). The returned physical table name is the one that was promoted in the target environment at the time the command was executed.

Fix!: Improve the table_name command

---

Makefile
sqlmesh/lsp/context.py
sqlmesh/lsp/main.py
sqlmesh/lsp/reference.py
tests/lsp/test_context.py
tests/lsp/test_reference.py
vscode/extension/src/lsp/lsp.ts

- refactors out lsp context
- adds reference code, e.g. the ability to pull out references
- For the time being only works for SQLModels that refer to models that have a _path
- adds test

feat: add go to definition to lsp

---

sqlmesh/core/test/context.py
tests/core/test_test.py

This update allows Python models to be unit tested when they contain non-SQLMesh models, fixes:  #3891 
Given the following test with `ext_table` an upstream table:
```yaml
test_python_model:
model: test_model
inputs:
ext_table:
- id: 1
- id: 2
outputs:
query:
- id: 1
- id: 2
```
and this python_model which uses `ext_table`:
```python
@model(
"test_model",
columns={"id": "int"},
)
def entrypoint(context, *args, **kwargs):
table_ref = context.resolve_table("ext_table")
return context.fetchdf(f"SELECT id FROM {table_ref}")
```
Previously resolving the table in the test would return the actual table name, preventing fixture-based mocking. This instead extends the testing table mapping to map not only sqlmesh models, but upstream references as well, instead of the actual table to the …

Fix: Enable unit testing in Python models with upstream tables

---

sqlmesh/core/console.py
tests/core/test_table_diff.py

Prior to this, running table_diff on tables with a boolean column that contained nulls would produce the following error:
```
TypeError: boolean value of NA is ambiguous
```
This error is thrown when `pd.NA` is attempted to be converted to a Python boolean, eg `bool(pd.NA)`.
This PR converts the `pd.NA` to a Python `None` before determining if cells match to avoid this error

Fix: table_diff - correctly handle nulls in boolean columns when displaying the row diff

---

tests/core/engine_adapter/integration/test_integration_bigquery.py

Fixes CI in main, seems like BigQuery's information schema has been updated since I added the test.

Chore: update bigquery integration test related to info. schema

---

docs/concepts/macros/macro_variables.md
docs/guides/configuration.md
sqlmesh/core/macros.py
sqlmesh/core/renderer.py
tests/core/test_context.py

This update adds the `this_env` variable in the macros for before all after all statements as well as `views` which provides all the views of the virtual layer to be able to easily for example grant rights on the views:
```python
@macro()
def grant_select_privileges(evaluator):
if evaluator.views:
return [
f"GRANT SELECT ON VIEW {view_name} /* sqlglot.meta replace=false */ TO ROLE admin_role;"
for view_name in evaluator.views
]
```
By including the comment `/* sqlglot.meta replace=false */`, you ensure that the evaluator does not replace the view name with the physical table name.

Feat: Make this_env and views available in macros of before after all

---

docs/guides/model_selection.md
docs/guides/tablediff.md
docs/reference/cli.md
docs/reference/notebook.md
sqlmesh/cli/main.py
sqlmesh/core/console.py
sqlmesh/core/context.py
sqlmesh/core/model/meta.py
sqlmesh/magics.py
sqlmesh/utils/git.py
tests/core/test_table_diff.py
tests/integrations/jupyter/test_magics.py
tests/web/test_main.py
web/server/api/endpoints/table_diff.py

This update extends using the table_diff command with `--select-model` to diff a subset or selection of SQLMesh models, fixes: #4198 
https://github.com/user-attachments/assets/7a2c817d-8743-4ddb-abda-cb9db04fbe26
For example with the downstream + to diff `items` and all models downstream of it:
`sqlmesh table_diff prod:dev sushi.items+`  
With the * wildcard to diff all models of a schema:
`sqlmesh table_diff prod:dev 'sushi.*'`  
Similarly with all the selectors: https://sqlmesh.readthedocs.io/en/latest/guides/model_selection/
- If the --show-sample flag is included, the output also includes sample rows. 
- If the engine supports it, it runs all the table diff concurrently.

Feat!: Add support for concurrent table diff of multiple models

---

sqlmesh/core/model/common.py
sqlmesh/migrations/v0082_warn_if_incorrectly_duplicated_statements.py
tests/core/test_model.py

Fixes #4252
I reproduced the issue locally by following the steps outlined in the above issue:
```python
>>> ctx.models['"db"."sqlmesh_example"."incremental_model"'].json()
'{"name":"sqlmesh_example.incremental_model","project":"","start":"2020-01-01","cron":"@daily","tags":[],"dialect":"duckdb","kind":{"name":"INCREMENTAL_BY_TIME_RANGE","on_destructive_change":"ERROR","dialect":"duckdb","forward_only":false,"disable_restatement":false,"time_column":{"column":"\\"event_date\\"","format":"%Y-%m-%d"},"partition_by_time_column":true},"partitioned_by":[],"clustered_by":[],"default_catalog":"db","audits":[],"grains":["(id, event_date)"],"references":[],"allow_partials":false,"signals":[],"enabled":true,"python_env":{},"jinja_macros":{"packages":{},"root_macros":{},"global_objs":{},"create_built …
```

Fix!: exclude Semicolon expressions from model state

---

sqlmesh/core/model/definition.py
tests/core/test_model.py

This PR fixes a small Python model bug related to how we parse the `depends_on` values. Other than that, it also adds a test that demonstrates how one can manually specify blueprint models as dependencies in Python model definitions.

Fix: use maybe_parse for python model depends_on instead of parse_one

---

sqlmesh/core/model/definition.py
tests/core/test_model.py

This is a UX improvement. If a model references an undefined model today, we crash with a `KeyError` after loading, in the metadata hash computation logic:
```
File "sqlmesh/core/model/definition.py", line 1112, in metadata_hash
audit = self.audit_definitions[audit_name]
~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'not_nulll'
```
This PR gracefully handles invalid references and raises early to avoid this:
```
Error: Failed to load model definition at '.../playground/models/test.sql'.
Audit 'not_nulll' is undefined at '.../playground/models/test.sql'
```

Chore: detect invalid audit refs and raise early

---

sqlmesh/cli/main.py

This fixes a bug in the `table_diff` command when used without the `select-model` to ensure backwards compatibility:
```bash
> sqlmesh table_diff dev:prod model
```
which would raise a keyword argument error as the select model would be passed in the kwargs. This fixes it by popping the select model from the kwargs beforehand regardless similarly to the handling in other commands.

Fix: Pop select model in tablediff to ensure backwards compatibility

---

sqlmesh/dbt/builtin.py
tests/core/test_integration.py
tests/core/test_model.py
tests/fixtures/dbt/sushi_test/config.py

Support dialects defined as `bigquery,normalization_strategy=UPPERCASE`

Fix: Support dialects with normalization strategies for dbt projects

---

docs/reference/configuration.md
sqlmesh/__init__.py
sqlmesh/core/console.py
tests/cli/test_cli.py
tests/integrations/github/cicd/test_github_commands.py
tests/integrations/github/cicd/test_integration.py
tests/integrations/jupyter/test_magics.py

Some terminals do not support unicode emoji like those used in the standard CLI output (e.g., running SQLMesh with Powershell.exe in Github Actions). Using the `MarkdownConsole` instead of standard `TerminalConsole` addresses this problem.
There is not a universal way to determine whether a given terminal supports Unicode, so we instead assume that unicode is not needed in any non-interactive context (typically a CI platform).
This PR:
- Automatically detects if we're in a non-interactive context and uses `MarkdownConsole` if so
- Non-interactive contexts include CI (detected via env vars commonly set by CI systems) or anywhere stdout and stdin are not both tty
- Brings the MarkdownConsole output into alignment with recent CLI updates
- Allows the user to force terminal output of any …

Fix: use MarkdownConsole in non-interactive contexts

---

sqlmesh/core/model/kind.py
sqlmesh/migrations/v0083_use_sql_for_scd_time_data_type_data_hash.py
tests/core/test_model.py

This aims to fix an issue where `sqlmesh plan` would show an unexpected diff for the `time_data_type` after a migration was applied for Databricks.
The diff was due to the fact that the local model had the default `time_data_type` which is `Type.TIMESTAMP`, but the deserialized model would parse the `"TIMESTAMP"` according to the databricks dialect, resulting in `Type.TIMESTAMPTZ`. The two types produce a different value when generated with `gen()`, leading to a difference in the data hash.
Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1745437282778639

Fix!: use sql() instead of gen() for time data type data hash computation

---

sqlmesh/core/engine_adapter/bigquery.py

[Documentation](https://cloud.google.com/bigquery/docs/querying-partitioned-tables#query_an_ingestion-time_partitioned_table) states that the `_PARTITIONTIME`'s pseudo-column type is `TIMESTAMP` (which is `TIMESTAMPTZ`)

fix: pseudo-column type is BQ `TIMESTAMP` which maps to `TIMESTAMPTZ`

---

sqlmesh/core/environment.py
tests/core/test_integration.py
tests/integrations/jupyter/test_magics.py

Catch and raise only the relevant error messages for `before all` and `after all` statements  (or dbt's `on_run_start` , `on_run_end` respectively) when an exception during their execution occurs

Fix: Gracefully handle execution errors in before after all

---

sqlmesh/lsp/main.py
vscode/extension/package.json

- starts the vscode extension when a python file gets opened as well
- starts the lsp and now if the workspace that is opnened is a valid
sqlmesh project, loads it directly
- stops the 'bug' of the project not getting activated when you are looking at 
python models

feat(vscode): initialize on python as well

---

examples/sushi/models/marketing.sql
pyproject.toml
tests/core/engine_adapter/integration/test_integration.py
tests/core/test_model.py

Changes in the tests were triggered by this [commit](https://github.com/tobymao/sqlglot/commit/807fbbc5a89925fd3c98e823003a9dc929fcaff6) and are expected.
For future reference:
- https://github.com/tobymao/sqlglot/issues/4859
- https://github.com/eakmanrq/sqlframe/issues/326
- https://github.com/tobymao/sqlglot/pull/4878

Chore!: bump sqlglot to v26.17.1

---

sqlmesh/core/context.py
tests/core/test_table_diff.py

This fix adjusts the condition for `table_diff` when used with a selector option to pick up from the selected models the forward only as well in the tables to compare.

Fix: Adjust condition in table diff to filter in forward only models

---

sqlmesh/lsp/completions.py
sqlmesh/lsp/main.py
sqlmesh/lsp/reference.py
tests/lsp/test_reference.py

- before we were returning the references for a whole file
- now we filter by the position of the request

fix(vscode): filter go to definitions by position

---

docs/reference/cli.md
docs/reference/notebook.md
sqlmesh/cli/main.py
sqlmesh/core/console.py
sqlmesh/core/context.py
sqlmesh/core/state_sync/base.py
sqlmesh/core/state_sync/db/environment.py
sqlmesh/core/state_sync/db/facade.py
sqlmesh/magics.py
tests/core/test_integration.py
tests/integrations/github/cicd/test_github_controller.py
tests/integrations/jupyter/test_magics.py

This update introduces the `sqlmesh destroy` command, which permanently deletes all engine-managed objects, including warehouse data, the associated state tables and cached SQLMesh assets, effectively resetting the entire project, fixes: #3684 
**Usage:** `sqlmesh destroy`
This might be useful for cleaning up development projects, proof-of-concept work or pre-production phases with temporary setups.
> ⚠️ This is destructive and irreversible, and it removes both development and the production environment, so it should only be used when a full removal is necessary.

Feat: Add destroy command to remove entire project resources

---

sqlmesh/__init__.py
sqlmesh/cli/main.py
sqlmesh/magics.py
tests/cli/test_cli.py

Currently, some warnings are printed to console even if `--ignore-warnings` is passed.
This PR fixes that by passing ignore_warnings into `configure_logging()`.

Fix: make logger respect --ignore-warnings

---

sqlmesh/core/console.py
sqlmesh/core/table_diff.py
tests/core/test_table_diff.py

Fixes #4320 
Prior to this PR, diffing a pair of empty tables that had schema changes resulted in a Pydantic error at the row diff step:
This PR accounts for this:

Fix(table_diff): Allow diffing of empty tables

---

.circleci/continue_config.yml
pyproject.toml
sqlmesh/core/engine_adapter/base.py
sqlmesh/core/engine_adapter/mssql.py
sqlmesh/core/engine_adapter/snowflake.py
sqlmesh/core/engine_adapter/spark.py
tests/core/engine_adapter/integration/__init__.py
tests/core/engine_adapter/integration/test_integration.py
tests/core/engine_adapter/integration/test_integration_bigquery.py
tests/core/engine_adapter/integration/test_integration_snowflake.py
tests/core/engine_adapter/test_base.py
tests/core/engine_adapter/test_snowflake.py

... than what is declared in `@model`. Addresses #3915 and #4232 
Prior to this PR, on many adapters the column order in the `DataFrame` emitted by a Python model had to match what was defined for `columns`.
This is because when we convert the `DataFrame` into a `VALUES(...)` list to insert it into the table, the values were in `DataFrame` order but the columns list was in `columns_to_types` order. If these didnt match, then we tried to insert the wrong value into the wrong column.
This PR adjusts the DataFrame to match `columns_to_types` before converting it to a `VALUES(...)` list.
**This PR fixes broken behaviour and thus may have unintended consequences**
Previously, if you had something like:
```
@model (
"foo",
"columns": { "a": "int", "b": "int" }
)
def execute(context: …
```

Fix!: Allow python models to emit DataFrame's with a different column order 

---

docs/guides/multi_engine.md

Add legends for clarity in multiengine docs to provide information of what they represent

Chore: Add legends for clarity in multiengine docs

---

docs/concepts/macros/sqlmesh_macros.md
sqlmesh/core/macros.py
tests/core/test_model.py

This update extends the `@UNION` macro  with a condition that is statically evaluatable and if it is false it short-circuits and it only keeps the first table, otherwise unions all tables, fixes: #4202 
Example:
```sql
MODEL (
name sushi.table_4
);
@UNION(@get_date() > '1996-02-10', 'distinct', sushi.table_1, sushi.table_2, sushi.table_3)
```
the previous behaviour when the first argument can't be interpreted as a conditional True or False remains with the first argument being the union type and then the table names.

Feat: Add condition in the union macro for conditional union of tables

---

sqlmesh/core/state_sync/base.py
sqlmesh/core/state_sync/cache.py
sqlmesh/core/state_sync/db/facade.py
sqlmesh/core/state_sync/db/snapshot.py

[Internal discussion](https://tobikodata.slack.com/archives/C04DTU8RF4J/p1746464244824879)
The `StateSync` API allows `snapshot_ids` to be optional (this used to return all snapshots) but `SnapshotState` will raise an error if `None` is passed in which is counter intuitive.
Note 1: I had initially transformed the check to `if not snapshot_ids` to check for empty iterables but this breaks a few tests. An example of that is if we do `get_snapshots(snapshot.previous_versions)` which might be an empty list (instead of `None`). That is fine, right?
Note 2: The `lock_for_update` arg of `SnapshotState::_get_snapshots()` and `SnapshotState::_get_snapshots_expressions()` seems unused, it's always initialized to `False` and `SnapshotState::get_snapshot()` does not bubble it up. Do we want to remove …

Chore: Remove `t.Optional` from get_snapshots() API

---

vscode/extension/src/auth/auth.ts

The output from tcloud is 
{ "is_logged_in": true, "id_token": { ... } }
{ "is_logged_in": false, "id_token": {} }
and so this makes the zod definition match that.

chore(vscode): make auth status output match

---

docs/concepts/models/python_models.md
sqlmesh/core/model/common.py
sqlmesh/core/model/definition.py
tests/core/test_model.py

Until now, calls in Python macros and models like `resolve_table(f"...{context.blueprint_var('some_var')}...")` would fail (unless `depends_on` was specified), because the Python dependency extraction logic could only handle string literal arguments in these calls.
This PR extends it so that it can also resolve global / blueprint variables, e.g., when interpolated in an f-string.

Feat: resolve (blueprint) variables when parsing python deps

---

tests/core/engine_adapter/integration/test_integration_bigquery.py

This test started failing recently because BQ added the managed table type column... now it's removed. Go figure :)

Chore: fix bigquery information schema integration test

---

sqlmesh/core/snapshot/evaluator.py
tests/core/test_integration.py

If I have model A and a downstream view model B, and I make a `Non-Breaking` change to A, then B is categorized as `Indirect Non-Breaking`. In this case, A gets a new physical table assigned to it, while B continues using the previous physical table by design.
This is generally an acceptable strategy when the physical tables represent materialized tables, but it presents a problem if B's physical table represents a view - in that case, the model query itself is part of the physical table definition and needs to be updated.
If not updated, the view will continue referencing the old physical table of A. This means that when querying B, the user will either get outdated data or encounter a query failure if the old snapshot is deleted by the janitor.
This update ensures that views are always …

Fix: Recreate views even if the change was categorized as indirect non-breaking to update table references

---

sqlmesh/core/console.py
sqlmesh/core/model/definition.py
sqlmesh/core/plan/evaluator.py
sqlmesh/core/scheduler.py
tests/core/test_context.py
tests/core/test_integration.py
web/server/console.py

Feat!: Ensure metadata snapshots with modified audits are still audited 

---

sqlmesh/core/audit/definition.py
sqlmesh/core/loader.py
tests/core/test_model.py

Fix: setting project on standalone audits

---

vscode/extension/src/extension.ts

- by starting the lsp at the end, the extension registers the
expressions faster and makes it more likely to register in the case
where the lsp could fail

fix(vscode): handle lsp failures more gracefully

---

.circleci/continue_config.yml
Makefile
pytest.ini
sqlmesh/core/engine_adapter/base.py
sqlmesh/core/engine_adapter/bigquery.py
sqlmesh/core/engine_adapter/snowflake.py
sqlmesh/core/engine_adapter/spark.py
sqlmesh/utils/pandas.py
tests/core/engine_adapter/integration/__init__.py
tests/core/engine_adapter/integration/config.yaml
tests/core/engine_adapter/integration/conftest.py
tests/core/engine_adapter/integration/test_integration.py
tests/core/engine_adapter/integration/test_integration_athena.py
tests/core/engine_adapter/integration/test_integration_bigquery.py
tests/core/engine_adapter/integration/test_integration_clickhouse.py
tests/core/engine_adapter/integration/test_integration_postgres.py
tests/core/engine_adapter/integration/test_integration_redshift.py
tests/core/engine_adapter/integration/test_integration_snowflake.py
tests/core/engine_adapter/integration/test_integration_trino.py
tests/core/engine_adapter/test_trino.py
tests/core/test_integration.py
tests/core/test_rule.py

In implementing #4348 I noticed a gap in our engine adapter integration tests.
Currently:
- For each engine adapter integration test, we parameterize it by engine (so it gets called at least once per engine)
- Many engine adapter methods take a `QueryOrDF`, that is - a SQL Query or some kind of DataFrame. So we also parameterize each test by `query` and `df`
- However, `df` really only refers to a Pandas DataFrame. At the time the tests were originally written, there was only one other DataFrame implementation - `pyspark`.
- So we also parameterize each test by `pyspark` as well even though this is only relevant for two engines - Spark and Databricks
- The net result is, we have parameterized each test 3 times _per engine adapter_ - once for `query`, `df` and `pyspark`. In many cases this …

Chore: Enable tests for native DataFrame implementations

---

sqlmesh/core/macros.py

Chore: do not warn if non-literal is used in then/else_value of PIVOT macro

---

.circleci/continue_config.yml

This introduces basic testing over `tests/lsp`, it is a start of working tests on Windows. It's not yet checking mypy and all the other tests but it's a start and proves:
1. That sushi loads successfully on Windows
2. That the LSP features especially those around path issues work correctly.
Future improvements should include:
- running mypy
- running full test suite

ci: testing in windows

---

sqlmesh/core/config/connection.py
sqlmesh/core/config/loader.py
sqlmesh/core/config/scheduler.py
sqlmesh/core/loader.py
sqlmesh/core/model/common.py
sqlmesh/core/model/definition.py
sqlmesh/core/model/kind.py
sqlmesh/core/model/meta.py
sqlmesh/utils/pydantic.py
tests/core/test_connection_config.py
tests/core/test_loader.py
tests/core/test_model.py
tests/integrations/github/cicd/test_config.py

This update improves the project validation error messages and changes them from the default pydantic format that looks like:
```
Error: Failed to load model definition at '/Users/izeigerman/github/sqlmesh/examples/tmp/models/incremental_model.sql'.
1 validation error for SqlModel
cron
Value error, Invalid cron expression '123' [type=value_error, input_value=Literal(this=123, is_string=False), input_type=Literal]
For further information visit https://errors.pydantic.dev/2.11/v/value_error at '/Users/izeigerman/github/sqlmesh/examples/tmp/models/incremental_model.sql'
```
To something more digestible. Below is a few examples:
```
Error: Invalid 'duckdb' connection config:
Invalid field 'database':
Input should be a valid string
Verify your config.yaml and environment variables.
```
``` …
```

Chore: Improve error messages returned by pydantic

---

sqlmesh/core/config/connection.py
tests/core/engine_adapter/integration/config.yaml
tests/core/test_config.py
tests/core/test_connection_config.py

Example of the new error message that will be printed if the required engine import is not found:
```
Failed to import the 'bigquery' engine library. Please run `pip install "sqlmesh[bigquery]"`.
```

Fix: Improve error message for missing engine imports

---

docs/guides/tablediff.md
docs/reference/cli.md
docs/reference/notebook.md
sqlmesh/cli/main.py
sqlmesh/core/context.py
sqlmesh/magics.py
tests/core/test_table_diff.py

This update introduces a new `--warn-grain-check` flag to the `table diff` command, providing a more lenient alternative to the current grain enforcement behavioru, closes: #4422
```bash
❯ sqlmesh table_diff dev:prod "*" --warn-grain-check
```
By default, missing grain for a couple of models when selecting multiple models to diff will cause the diff operation to fail. With the `--warn-grain-check` flag, this strict requirement is relaxed:
* Models without a valid grain will trigger a warning and be listed instead of an error.
* Diffs will be computed for the remaining models that do have valid grains.
This allows users to proceed with partial diffs if they desire while still being informed of models that require attention.

Feat(table_diff): Add flag to warn when models lack grain and diff the remaining

---

.circleci/continue_config.yml
sqlmesh/core/engine_adapter/snowflake.py
tests/core/engine_adapter/integration/__init__.py
tests/core/engine_adapter/integration/test_integration_snowflake.py

Addresses #4397 
Prior to this PR, a Snowpark session would get shared across threads.
This lead to strange errors like `Object does not exist or not authorized` as threads would all try to start a transaction, upload a DataFrame and return a pointer to a table which eventually lead to an error as they clobbered each others state.
This PR makes each Snowpark session thread-local and adds a test to ensure concurrent execution works

Fix(snowflake): Allow models that utilize Snowpark to execute concurrently

---

.circleci/continue_config.yml
Makefile
examples/sushi/linter/__init__.py
sqlmesh/core/engine_adapter/athena.py
sqlmesh/core/model/cache.py
sqlmesh/utils/cache.py
sqlmesh/utils/windows.py
tests/conftest.py
tests/core/test_format.py
tests/core/test_model.py
tests/core/test_table_diff.py
tests/integrations/jupyter/test_magics.py
tests/utils/test_metaprogramming.py
web/server/api/endpoints/commands.py
web/server/api/endpoints/files.py
web/server/api/endpoints/models.py
web/server/models.py
web/server/utils.py

This extends the Windows tests to include `make fast-test` instead of just the LSP tests.
There is still more work to do in order to get `make cicd-test` fully working on Windows so that can be addressed in followup PR's as bandwidth allows

Chore: Get fast-test working on Windows

---

sqlmesh/core/macros.py

Public slack thread for context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1747732180271059.
I mistakenly used `SQL()` for some of the arguments in a recent [PR](https://github.com/TobikoData/sqlmesh/pull/4423), which resulted in interpolating the wrong values in the strings that are later parsed. For example, if a string was given for the `prefix` argument, `SQL` means we'll get back the generated value, including the quotes, like `'prefix'foo`.
This PR should address this, I added another doc test for it.

Fix: regression related to string arguments in `@PIVOT` macro

---

sqlmesh/core/console.py
sqlmesh/core/plan/evaluator.py
sqlmesh/integrations/github/cicd/controller.py
tests/cli/test_cli.py

The CLI output for restatement plans has a number of issues:
1. The virtual update progress bar is created even though no virtual updates will occur
2. The physical layer SKIP message appears when no physical layer updates occur even though the user does not expect physical layer updates
3. The "no changes to plan" message is always produced even though the user knows there aren't changes
This PR fixes the first two issues and replaces the "no changes" message with `Restating models`.

Fix: CLI output for restatement plans

---

sqlmesh/core/engine_adapter/base.py
sqlmesh/core/engine_adapter/mysql.py
sqlmesh/core/engine_adapter/postgres.py
sqlmesh/core/engine_adapter/risingwave.py
tests/core/engine_adapter/integration/test_integration.py

Fixes https://github.com/TobikoData/sqlmesh/issues/4082
This PR introduces an identifier limit check right before SQL execution in the engine adapter and enables this check for Postgres & MySQL; These 2 dialects are the only ones with <100 char limits afaict, but we can always go ahead and fill in the rest of the engines too.
In my opinion, the main consideration of this PR is to not cause this issue on our end which should mostly happen during physical table creation; This is the reason that we'll walk the AST only if (1) the engine adapter has set its limit and (2) if the expression is a DDL. 
We can also enable this check for _any_ query expression but we'll introduce a perf hit; This might help unsuspecting users catch some nasty bugs in _their_ SQL, but I wasn't sure if it's worth …

Feat: Introduce runtime check for identifier limits per engine

---

sqlmesh/core/test/definition.py
sqlmesh/core/test/result.py
sqlmesh/core/test/runner.py
tests/core/test_test.py

Before:
```
$ sqlmesh test     
E
======================================================================
ERROR: Traceback (most recent call last):
File "/Users/izeigerman/github/sqlmesh/sqlmesh/core/test/definition.py", line 193, in setUp
self.engine_adapter.create_view(
File "/Users/izeigerman/github/sqlmesh/sqlmesh/core/engine_adapter/shared.py", line 302, in internal_wrapper
return func(*list_args, **kwargs)
File "/Users/izeigerman/github/sqlmesh/sqlmesh/core/engine_adapter/base.py", line 1103, in create_view
self.execute(
File "/Users/izeigerman/github/sqlmesh/sqlmesh/core/engine_adapter/base.py", line 2154, in execute
self._execute(sql, **kwargs)
File "/Users/izeigerman/github/sqlmesh/sqlmesh/core/engine_adapter/base.py", line 2175, in _execute
self.cursor.execute(sql, **kwargs) …
```

Fix: Don't show stacktraces when tests fail

---

sqlmesh/cli/main.py

previously, these flags had default value of False. now, set to None to track what gets explicitly set in `sqlmesh plan` command to later display in UI.

fix: set flag defaults to None in CLI

---

sqlmesh/core/state_sync/db/environment.py
sqlmesh/core/state_sync/db/facade.py
tests/core/state_sync/test_state_sync.py

Before:
```
Plan 'stale_new_plan_id' is no longer valid for the target environment 'prod'. Expected previous plan ID: 'test_plan_id', actual previous plan ID: 'new_plan_id'. Please recreate the plan and try again
```
After:
```
Another plan (new_plan_id) was applied to the target environment 'prod' while the current plan (stale_new_plan_id) was still in progress. Please re-apply your plan to resolve this error.
```

Fix: Improve error messages around concurrent plan application

---

sqlmesh/core/snapshot/evaluator.py
tests/core/test_model.py

The issue is that `snapshots` in the `SnapshotEvaluator._promote_snapshot` method was a `SnapshotId -> Snapshot` dict instead of a `str -> Snapshot`, which is expected by the rendering methods. Since this dict flows into the macro evaluator, `columns_to_types` lookup using string keys would always fail and we'd fail.
I also updated the `_statement_renderer` and `_create_renderer` to pass the `mapping_schema` for consistency, since we do this for the query renderer as well. This is unrelated to the above issue, so happy to revert if we're unsure if it's safe.

Fix: propagate correct snapshot dict to renderer for virtual statements

---

pyproject.toml
tests/core/test_model.py
tests/lsp/test_completions.py

Regarding the changes in the test suite:
- The pretty-printing logic for `Merge` [recently changed](https://github.com/tobymao/sqlglot/commit/2b928e238cba63e5e043207dae1bfe2f140a1c2b).
- In `test_completions.py` there were a couple of assertions that were tighter than needed.

Chore!: bump sqlglot to v26.19.0

---

examples/custom_materializations/pyproject.toml

Quick fix to silence the warning shown below:
```bash
$ make install-dev
...
Building wheels for collected packages: custom_materializations, sqlmesh
DEPRECATION: Building 'custom_materializations' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'custom_materializations'. Discussion can be found at https://github.com/pypa/pip/issues/6334
```
References:
- https://packaging.python.org/en/latest/discussions/setup-py-deprecated/#is-pyproject-toml-mandatory
- …

Chore: add pyproject.toml in examples/custom_materializations

---

sqlmesh/core/context.py
tests/core/test_context.py

See the added test for reference. The issue that we saw in the wild looked something like this:
```
-  event_date
+  event_date,
+  1 AS z
FROM sqlmesh_example.seed_model
WHERE
event_date BETWEEN @start_date AND @end_date
Directly Modified: sqlmesh_example.incremental_model
└── Indirectly Modified Children:
└── sqlmesh_example.full_model
Models needing backfill:
└── sqlmesh_example.incremental_model: [2020-01-01 - 2025-05-20]
Apply - Backfill Tables [y/n]: y
Error: Can't apply a plan with uncategorized changes.
```
This happened after running `sqlmesh plan` with a config that switches off auto-categorization:
```python
PlanConfig(
auto_categorize_changes=CategorizerConfig(
external=AutoCategorizationMode.OFF,
python=AutoCategorizationMode.OFF,
sql=AutoCategorizationMode.OFF, …
```

Fix: prompt if there are any uncategorized snapshots in a plan

---

sqlmesh/__init__.py
sqlmesh/cli/main.py
sqlmesh/core/config/connection.py
sqlmesh/core/context.py
sqlmesh/magics.py
tests/core/test_connection_config.py

This [commit](https://github.com/TobikoData/sqlmesh/commit/cc3e4931ed4ef361f90e340b4bc18793009935c5) introduced new error handling logic for connection configs: if sqlmesh fails to import an engine driver, then it suggests running `pip install` as a possible solution to the issue.
However, problems can arise at import time even if a driver _is_ installed. For example, `pymssql` is known to have [compatibility issues](https://github.com/pymssql/pymssql/issues/769) with M-series Mac systems. This leads to confusing error messages as shown below:
```
((.venv) ) ➜  sqlmesh info
Error: Failed to import the 'mssql' engine library. Please run `pip install "sqlmesh[mssql]"`.
((.venv) ) ➜  playground pip show pymssql  # The above message is misleading, pymssql is already installed
Name: pymssql …
```

Chore!: configure logging before loading config to log errors properly

---

sqlmesh/core/plan/evaluator.py

This is to align this step more with normal evaluations which always take place after physical table creation.

Chore: Run audits for metadata snaphots after creating snapshots and their tables

---

sqlmesh/core/config/connection.py
sqlmesh/utils/pydantic.py
tests/core/test_config.py
tests/core/test_connection_config.py
tests/utils/test_pydantic.py

Prior to this PR, there was no clear way to use an environment variable to set a "complex" field on a connection, such as the `scopes` property on a BigQuery connection which takes a list of strings, or the `keyfile_json` property which takes a dict.
Attempting to do so would just throw a Pydantic error:
```sh
$ SQLMESH__GATEWAYS__BIGQUERY__CONNECTION__SCOPES='["http://..."]' sqlmesh info
Error: Invalid 'bigquery' connection config:
Invalid field 'scopes':
Input should be a valid list
Verify your config.yaml and environment variables.
```
This PR adds a generic `mode=before` validator onto the `ConnectionConfig` base class to check if any "complex type" fields are being set as a string. If they are, and the string contains JSON, it parses the JSON string to a Python value before …

Feat: Allow supplying complex connection config fields as JSON strings

---

sqlmesh/lsp/main.py
vscode/extension/package.json
vscode/extension/src/lsp/lsp.ts
vscode/extension/src/utilities/config.ts
vscode/extension/src/utilities/sqlmesh/sqlmesh.ts
vscode/extension/tests/lineage.spec.ts

- allows context loading in the API if not yet done if it's needed
- tests with e2e tests 
- adds configuration to the vscode extension that allows the absolute/relative path to be configured

feat(vscode): add ability to specify project path

---

sqlmesh/core/macros.py
sqlmesh/core/renderer.py
tests/core/test_model.py

There's no easy way to access the unresolved name of a model within a macro that it calls– `this_model` is usually the resolved version, corresponding to either a physical table, or a view if we're in the promoting stage.
This PR adds a new property in the macro evaluator that can be used to access the model's fully-qualified name. One example where the unresolved name is helpful can be seen in the added test.

Feat: expose model fqn in the macro evaluator

---

sqlmesh/lsp/description.py
sqlmesh/lsp/main.py
sqlmesh/lsp/reference.py
tests/lsp/test_reference.py

feat(vscode): add info to hover

---

sqlmesh/core/config/root.py
tests/__init__.py
tests/conftest.py
tests/core/test_integration.py

Up until now the config's `default_connection` was default initialized to DuckDB for less setup friction.
However, if the gateway connection was not configured properly, this could lead to us silently replacing it with DuckDB.
Our tests largely depended on that fact so as to reduce boilerplate code, and by making it optional there were many failures introduced. For that matter, I went ahead and solved it by monkey-patching `Config.get_connection()`.

Chore!: Make `default_connection` optional

---

sqlmesh/core/context.py
tests/core/test_integration.py

It is often that users try to render a model as `sqlmesh render <path>` instead of `sqlmesh render <model_name>`, which is followed by the cryptic error:
```Python3
❯ sqlmesh render models/test_model.sql
Error: Failed to parse 'models/test_model.sql' into <class 'sqlglot.expressions.Table'>
```
This PR makes it so that `GenericContext::get_model()` fails gracefully, which will then lead to a clearer error:
```
❯ sqlmesh render models/test_model.sql
Resolving models by path is not supported, please pass in the model name instead.
```

Chore: Ensure model search fails gracefully

---

sqlmesh/utils/metaprogramming.py
tests/core/test_model.py

Added test failed with the following error prior to this fix:
```
E       sqlmesh.utils.errors.ConfigError: Failed to load model definition at '/private/var/folders/d9/8x4drv4j38j2y2qxm_3bvp_80000gn/T/pytest-of-georgesittas/pytest-147/test_model_relies_on_os_getenv0/models/model.sql':
E         lineno is out of bounds
```
The issue is that `inspect.getfile` returns `'<frozen os>'` for `getenv`, which is incorrectly treated as relative to the project:
```
(Pdb) path.absolute()
PosixPath('/private/var/folders/d9/8x4drv4j38j2y2qxm_3bvp_80000gn/T/pytest-of-georgesittas/pytest-147/test_model_relies_on_os_getenv0/macros/getenv_macro.py')
(Pdb) other.absolute()
PosixPath('/private/var/folders/d9/8x4drv4j38j2y2qxm_3bvp_80000gn/T/pytest-of-georgesittas/pytest-147/test_model_relies_on_os_getenv0') …
```

Fix: ensure paths exist before treating them as relative (metaprogramming)

---

sqlmesh/core/model/definition.py
tests/core/test_model.py

Behavior in main today (note that we need `JINJA_QUERY_BEGIN`):
```sql
MODEL (name test);
JINJA_STATEMENT_BEGIN;
SELECT 1 AS c
JINJA_END;
```
Fails with a `KeyError: kind` due to this [line](https://github.com/TobikoData/sqlmesh/blob/68def3041e7ae2dad72e2bb3732736157635e4f1/sqlmesh/core/model/definition.py#L2192), which is reported... poorly :)
```
$ sqlmesh --debug info
Error: Failed to load model definition at '.../playground/models/test.sql':
'kind'
```
If I set the model kind explicitly:
```sql
MODEL (name test, kind FULL);
JINJA_STATEMENT_BEGIN;
SELECT 1 AS c
JINJA_END;
```
I see an error that the `path` attribute is missing, even though that's only relevant to `SEED` models:
```
$ sqlmesh --debug info
Error: Failed to load model definition at '.../playground/models/test.sql': …
```

Fix: improve error handling when SQL model query is invalid

---

examples/sushi/config.py
sqlmesh/lsp/main.py

- filters out identical diagnostics which is very possible in blueprints

fix(vscode): duplicate returned diagnostics

---

sqlmesh/core/model/cache.py
tests/cli/test_integration_cli.py

Addresses #4493 
I was able to produce an `ModuleNotFoundError` on `sqlmesh plan` by:
- Creating a module in `site-packages` that exposes a macro
- Importing that macro in `macros/__init__.py`
- Referencing that macro in a model
- `sqlmesh plan` - applied successfully
- Deleting the module from `site-packages`
- Updating `macros/__init__.py` to include the macro definition inline instead of importing it
- **clearing the cache**
- `sqlmesh plan` - `ModuleNotFoundError: no module named <site-packages module>`
When debugging the `ModuleNotFoundError`, I noticed that it was triggered when putting values into the `OptimizedQueryCache` by the `model.render_query()` call that produces the value to be cached.
I also noticed that in `SnapshotCache`, we catch rendering errors, [log the …

Fix: Catch errors caching optimized model queries so that SQLMesh can still load

---

sqlmesh/core/selector.py
tests/core/test_selector.py

This addresses an issue where if you add a tag to a local model that has previously been run / committed to state and run `sqlmesh plan --select-model 'tag:<new tag>'`, the model doesnt get included.

Fix: expand the 'tag:' selector based on local models and not remote ones

---

tests/core/engine_adapter/integration/test_integration_bigquery.py

This test [keeps failing](https://app.circleci.com/pipelines/github/TobikoData/sqlmesh/21207/workflows/3c3d46d8-35cf-407b-87ad-d4932b9134c3/jobs/216297) whenever the schema of `INFORMATION_SCHEMA.TABLES` changes, so I figured I'd simplify it a bit to avoid CI breaking under our feet. The purpose here was to simply demonstrate we can successfully query these schemas, so no substantial difference here.

Chore: clean up bigquery info. schema integration test

---

sqlmesh/dbt/manifest.py
tests/dbt/test_manifest.py
tests/fixtures/dbt/sushi_test/models/schema.yml

With 1.9.5, dbt-core added a `freshness` parameter to model and source configs (in addition to the existing top-level properties).
We pass all contents of both a source's top-level keys and config into our `SourceConfig` constructor, so we get a duplicate `freshness` key error.
This PR uses the dbt.parser.sources `merge_freshness` function to merge the two freshnesses before passing to `SourceConfig`.
closes #4574

Fix: dbt-core 1.9.5 freshness error

---

sqlmesh/lsp/custom.py
vscode/extension/src/commands/renderModel.ts
vscode/extension/src/lsp/custom.ts
vscode/extension/tests/render.spec.ts
vscode/extension/tests/utils.ts

There was a weird reasoon why `mypy` didn't catch mapping t.Optional[str] into str which caused an unexpected runtime error when the pydantic model was validated and the description was None

fix(vscode): render models without descriptions

---

docs/integrations/engines/duckdb.md
sqlmesh/core/config/connection.py
tests/core/test_connection_config.py

This pull request introduces support for the `ducklake` catalog type in DuckDB, including the ability to specify a `DATA_PATH` and activate encryption of the parquet files. The changes span documentation updates, configuration enhancements, SQL generation modifications, and new test cases to ensure functionality.
* Added a new section in `docs/integrations/engines/duckdb.md` demonstrating how to configure the `ducklake` catalog type in both YAML and Python formats, including the use of `DATA_PATH` & `ENCRYPTED`.
* Updated the `DuckDBAttachOptions` class in `sqlmesh/core/config/connection.py` to include a new `data_path` attribute for specifying the `DATA_PATH` option in `ducklake` catalogs. In addition to that, this also adds the `ENCRYPTED` option to activate the parquet encryption.
* …

Add data path and encrypted to duckdb catalog

---

sqlmesh/core/loader.py
sqlmesh/core/model/definition.py
tests/core/test_loader.py
tests/core/test_model.py

Old
```
The MODEL statement is required as the first statement in the definition, unless model name inference is enabled.
```
New
```
Please add a MODEL block at the top of the file. Example:
MODEL (
name sqlmesh_example.full_model, --model name
kind VIEW, --materialization
cron '@daily', --schedule
);
Learn more at https://sqlmesh.readthedocs.io/en/stable/concepts/models/overview
```

Chore: improve error message when no MODEL block

---

sqlmesh/core/context.py
sqlmesh/core/selector.py
tests/cli/test_integration_cli.py

This relates to #4493 
When `--select-model` is used with `sqlmesh plan`, the following occurs:
- We identify which models are selected and use the local versions of those
- For all other models, we fetch the latest version from state
- We also identify dependencies by calling `model.depends_on` and fetch them either locally or from state depending on if they were part of `--select-model`
- the ultimate goal of replacing local versions with remote versions for unselected models is to trick `ContextDiff` into only showing changes for the selected models
The problem is that `model.depends_on` has side effects. It causes a `render_query()` call so it can pull out all the table references, and this can fail if there is a macro reference that contains a python import that *used* to be valid …

Chore: Improve plan error handling when --select-model is used and the remote snapshot can't be rendered

---

tests/cli/test_integration_cli.py

This PR fixes failing CLI integration tests on macOS that were caused by fork safety issues with Objective-C runtime.
The test `test_load_snapshots_that_reference_nonexistent_python_libraries` was failing on macOS with the following error:
```
objc[12949]: +[NSMutableString initialize] may have been in progress in another thread when fork() was called.
objc[12949]: +[NSMutableString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process.
Crashing instead.
```
This is a known issue on macOS when using multiprocessing with `fork()` context, which SQLMesh uses for parallel model loading. The issue is related to this [commit](https://github.com/TobikoData/sqlmeshcommit/67428f0efedce7875e6bbd04099cc5a2b13 …

fix: Set `OBJC_DISABLE_INITIALIZE_FORK_SAFETY` for macOS in CLI integration tests

---

sqlmesh/core/engine_adapter/trino.py
sqlmesh/core/model/meta.py
tests/core/engine_adapter/test_trino.py
tests/core/test_model.py

This adds first-class support for Trino's `SET SESSION AUTHORIZATION` ([docs](https://trino.io/docs/current/sql/set-session-authorization.html)), using the existing `session_properties` mapping. One can now do the following:
```sql
MODEL (
name <model_name>,
...,
session_properties (
authorization = 'foo'
)
);
```
which will result in the following statement:
```sql
SET SESSION AUTHORIZATION 'foo';
```
to be run **before** anything relevant to this model is executed, and then the following statement:
```sql
RESET SESSION AUTHORIZATION;
```
will run **after** all statements relevant to this model have been executed.

Feat: add support for Trino's authorization session property

---

sqlmesh/integrations/github/cicd/command.py
sqlmesh/integrations/github/cicd/controller.py
tests/integrations/github/cicd/test_github_commands.py

Prior to this PR, plan errors would not be surfaced back to the user and would give a confusing `action_required` check title. Now the title communicates a plan error and then the plan error is shown in the summary.

fix: cicd bot correctly surface plan errors

---

pyproject.toml
sqlmesh/__init__.py
sqlmesh/core/console.py
sqlmesh/integrations/github/cicd/command.py
sqlmesh/integrations/github/cicd/controller.py
tests/integrations/github/cicd/conftest.py
tests/integrations/github/cicd/test_github_commands.py
tests/integrations/github/cicd/test_github_controller.py
tests/integrations/github/cicd/test_github_event.py
tests/integrations/github/cicd/test_integration.py

CICD Bot housekeeping:
- Refactor tests to use `conftest.py` instead of registering the fixtures as a pytest plugin (to align with the rest of our test suite)
- Unpin `PyGithub` dependency (which was previously pinned due to an incompatibility in how our mocks were set up) and update test code
This PR introduces the following:
- Parity with the CLI around model failure messages and unhandled exceptions
- The ability to run `sqlmesh_cicd github run-all` locally instead of within GitHub Actions. The intention is to help speed up CICD bot development by being able to launch it in a debugger on an actual project and inspect what it does
Here are some examples of how errors are better handled:
CLI
CICD Bot - Before
CICD Bot - After
CLI
CICD Bot - Before
CICD Bot - After

Fix(cicd): Better handle model failures in GitHub check output

---

docs/guides/tablediff.md
sqlmesh/core/context.py

Behavior in main:
```
((.venv) ) ➜  sqlmesh table_diff 'mssql|sales.fact_sales:databricks|george.sales.fact_sales' --on fact_id --show-sample
Error: Failed to parse 'mssql|sales.fact_sales' into <class 'sqlglot.expressions.Table'>
```
Behavior in this PR:
```
((.venv) ) ➜  sqlmesh table_diff 'mssql|sales.fact_sales:databricks|george.sales.fact_sales' --on fact_id --show-sample
Error: Cross-database table diffing is available in Tobiko Cloud. Read more here: https://sqlmesh.readthedocs.io/en/stable/guides/tablediff/#diffing-tables-or-views-across-gateways
```
Additionally, I've updated the [docs](https://sqlmesh.readthedocs.io/en/stable/guides/tablediff/#configuration-and-syntax) so that `tcloud sqlmesh` is used instead of `sqlmesh`, as the latter does not route to the correct xdb diffing …

Chore: detect xdb diff syntax and raise early

---

pyproject.toml
sqlmesh/core/engine_adapter/duckdb.py
tests/conftest.py
tests/core/state_sync/test_state_sync.py

Similar PRs: 
https://github.com/TobikoData/sqlmesh/pull/4653
https://github.com/TobikoData/sqlmesh/pull/4631
Removed support for <0.10.0 release of DuckDB since 0.10.0 was released Feb 2024 therefore I think we are safe to deprecate.

feat: lazy import duckdb

---

sqlmesh/core/plan/explainer.py

Add extra backslash to prevent raising syntax error in python versions [3.12 or earlier](https://docs.python.org/3/whatsnew/3.12.html#other-language-changes)

Fix: Escape backslash to prevent syntax error in string

---

sqlmesh/core/config/connection.py

Fixes #4589 following @erindru 's supportive comment for adding azuresql to the set.

Fix: add azuresql to state sync engines

---

sqlmesh/dbt/model.py
tests/dbt/test_transformation.py

Chore: Remove obsolete warning when converting a dbt project

---

examples/sushi/models/customers.sql
sqlmesh/lsp/reference.py
tests/integrations/github/cicd/test_integration.py
tests/lsp/test_reference_macro_find_all.py
tests/test_forking.py
tests/web/test_lineage.py
vscode/extension/tests/find_references.spec.ts

Building on #4652  and #4680, this update adds "Find All References" and "Go to References" support for macros in the SQLMesh VSCode extension.

Feat(lsp): Add find all and go to references support for Macros

---

sqlmesh/cli/main.py

`sqlmesh clean` failed, while debugging a dbt project in the wild, due to a model that wasn't able to be loaded. Verified that manually running `rm -r .cache` and re-loading the project fixed the issue.

Fix: skip project loading for clean, destroy and janitor commands

---

sqlmesh/core/table_diff.py
tests/core/engine_adapter/integration/test_integration.py
tests/core/test_table_diff.py

Prior to this PR, when fetching samples, the sample data was fetched in a single query and then client-side separated out into "source_only", "target_only" and "common".
The `--limit` was being applied to the overall query which meant that common rows with mismatches could be pushed out by target only rows.
This lead to output like (note that screenshot uses `--limit 2` to illustrate the problem):
Notice the partial match but then the sample claims that all joined rows match and no source only rows are shown
This PR changes how the sample data is fetched by applying the `--limit` on a per-sample basis ("source_only", "target_only", "common") and not on an overall basis.
This updates the above output with `--limit 2` to look like:

Fix(table_diff): Make `--limit` per-sample and not across all samples

---

docs/integrations/engines/azuresql.md
docs/integrations/engines/mssql.md
pyproject.toml
sqlmesh/core/config/connection.py
sqlmesh/core/engine_adapter/mssql.py
tests/core/test_connection_config.py

Adds support for `pyodbc` as an alternative driver for MSSQL connections, providing users with more flexibility and authentication options.
- Introduces a `driver` option to choose between `pymssql` and `pyodbc`.
- Implements connection string generation for `pyodbc` based on connection parameters.
- Includes validation for different authentication methods when using `pyodbc`.
- Updates dependencies to include `pyodbc`.
>**NOTE** Had to create a new PR, the merge conflicts was gnarly, easier to just restart.
> Replaces PR #4335

Enhances MSSQL connection with pyodbc support v2

---

sqlmesh/core/context.py
sqlmesh/core/plan/builder.py
sqlmesh/core/plan/definition.py
sqlmesh/core/snapshot/definition.py
sqlmesh/utils/date.py
tests/core/test_context.py
tests/core/test_plan.py
tests/integrations/github/cicd/test_github_controller.py
tests/utils/test_date.py

This addresses some issues with setting `--execution-time` on a plan, which is intended to run a plan "as at" a certain time.
Currently, if you specify a relative start date like `--start '2 days ago'` and then you specify a fixed `--execution-time`, eg `--execution-time '2020-01-05'`, SQLMesh will make the start date relative to the current time and not the execution time.
This gets confusing because it makes the plan start / end and any relative dates show no relation to the execution time.
This is also causes problems when `--execution-time` is set to a value older than the latest prod interval for a model, eg:
```
$ sqlmesh plan dev --execution-time 2020-01-05 --start '2 days ago'
...SNIP
Error: Start date / time (2 days ago) can't be greater than end date / time (1749168000000)
``` …

Fix: Make plan dates relative to `--execution-time`

---

tooling/vscode/settings.json
vscode/extension/tests/utils.ts

sets up the playwright extension correctly in vscode so that playwright tests called from the vscode extension work correctly
To set up 
```sh
make vscode_settings
```

chore: allow debugging vscode tests

---

sqlmesh/lsp/main.py
tooling/vscode/extensions.json
vscode/extension/src/utilities/sqlmesh/sqlmesh.ts
vscode/extension/tests/tcloud.spec.ts
vscode/extension/tests/tcloud/README.md
vscode/extension/tests/tcloud/mock_tcloud/__init__.py
vscode/extension/tests/tcloud/mock_tcloud/cli.py
vscode/extension/tests/tcloud/pyproject.toml
vscode/extension/tests/utils.ts

- add mock tcloud for testing tcloud flows
- improved installing enterprise messaging
- added lock around the tcloud install process to make more stable
- removed unneedded lsp function that was causing issues
- fix path finding 
- add prettier to recommended extensions

fix(vscode): improve the tcloud stability

---

sqlmesh/core/plan/__init__.py
sqlmesh/core/plan/evaluator.py
sqlmesh/core/plan/explainer.py
sqlmesh/core/plan/stages.py
sqlmesh/core/scheduler.py
sqlmesh/core/state_sync/base.py
sqlmesh/utils/__init__.py
tests/conftest.py
tests/core/test_context.py
tests/core/test_plan_evaluator.py
tests/core/test_plan_stages.py

This update unifies plan evaluation and explanation by utilizing a common intermediate step: building the list of plan stages first.
The plan stages now contain a fully precomputed set of evaluation steps, removing dynamic behavior from the evaluation process. As a result, the following evaluation details are known ahead of time, before evaluation begins, and without producing any side effects:
- A set of snapshots for which physical tables will be checked and created if missing
- All missing intervals that will be backfilled
- A set of snapshots for which views will be created / deleted in the virtual layer
- A set of snapshots for which the schema will be migrated
- The order of operations
The only remaining dynamic step is the creation of physical tables, as it requires querying the …

Chore: Update the plan evaluator to use stages

---

sqlmesh/core/plan/explainer.py
sqlmesh/core/plan/stages.py

The explainer was incorrectly printing
```
Validate SQL and create physical layer tables and views if they do not exist
```
with an empty list of models if there were no physical updates to perform. This fix makes it so that 
```
SKIP: No physical layer updates to perform
```
is printed instead.

Fix: Reporting the absence of physical layer updates when explaining a plan

---

sqlmesh/core/console.py
sqlmesh/core/test/runner.py
tests/core/test_test.py
tests/integrations/github/cicd/test_github_commands.py
tests/integrations/github/cicd/test_integration.py

This PR mostly cleans up some of the output, e.g:
- Failure before
<br />
<br />
<br />
- Success before
<br />
<br />
<br />
- Failure after
<br />
<br />
<br />
- Success after

Chore: Minor refactors in `sqlmesh test` output

---

vscode/extension/src/auth/auth.ts
vscode/extension/src/utilities/sqlmesh/sqlmesh.ts

- sets up environment where tcloud is called so can run `uv`

fix(vscode): allow uv pip executable called through tcloud

---

examples/sushi/models/customers.sql
sqlmesh/lsp/reference.py
tests/lsp/test_reference_cte_find_all.py
tests/lsp/test_reference_model_column_prefix.py
tests/lsp/test_reference_model_find_all.py
tests/test_forking.py
tests/web/test_lineage.py

This adds support to detect table references in column expressions for models and ctes (e.g. **sushi.orders**.customer_id). (needed for: https://github.com/TobikoData/sqlmesh/pull/4718)

Fix(lsp): Extend support for table references with columns

---

vscode/extension/src/commands/format.ts
vscode/extension/src/commands/signin.ts
vscode/extension/src/commands/signinSpecifyFlow.ts
vscode/extension/src/extension.ts
vscode/extension/src/utilities/errors.ts
vscode/extension/tests/tcloud.spec.ts

When starting the extension and not being signed in, you would before sign in and the lsp would not restart. You would have to manually reload vscode to trigger the lsp. This now triggers the lsp on sign in.

fix(vscode): on sign in, restart lsp

---

sqlmesh/core/engine_adapter/mssql.py
tests/core/engine_adapter/test_mssql.py

This update fixes quoting in mssql's `drop_schema` to correctly handle table and view names containing spaces or special characters. closes #4633 
While this won't be an issue in recent sqlglot versions, the change fool proofs by adding proper square bracket quoting for schema and object names. Also since `_drop_object` does not account for dialect when using `to_table` it is addressed in `drop_schema` and it is passed as a table there.

Fix(mssql): Properly quote table and views when dropping in mssql

---

sqlmesh/dbt/manifest.py

CircleCI started resolving dbt 1.10 which includes a [rename](https://github.com/dbt-labs/dbt-core/commit/14fc39a76ff4830cdf2fcbe73f57ca27db500018#diff-1f09db95588f46879a83378c2a86d6b16b7cdfcaddbfe46afc5d919ee5e9a4d9R430) of the `merge_freshness` function to `merge_source_freshness`.
This is causing `make py-style` to fail with a mypy error:
```
sqlmesh/dbt/manifest.py:24: error: Module "dbt.parser.sources" has no attribute "merge_freshness"; maybe "merge_source_freshness"?  [attr-defined]
```
[(example failed job)](https://app.circleci.com/pipelines/github/TobikoData/sqlmesh/21845/workflows/4b478685-1865-4235-90ff-4a3b36d20ce7/jobs/229341)
This PR updates the import to try importing `merge_source_freshness` if importing `merge_freshness` results in an `ImportError`

Chore: Fix dbt import to prevent cicd failures

---

sqlmesh/lsp/main.py
sqlmesh/lsp/rename.py
tests/lsp/test_document_highlight.py
tests/lsp/test_rename_cte.py
vscode/extension/tests/rename_cte.spec.ts

This update adds CTE renaming (F2) to the SQLMesh LSP server, letting users rename CTEs and their references with proper scope handling. Still to do:

Feat(lsp): Add rename functionality for CTEs in vscode

---

sqlmesh/core/console.py
tests/core/test_test.py

Relevant Slack thread: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1750567588080039
Before:
After:

Chore: do not log test results if there are no tests

---

sqlmesh/core/model/common.py
tests/core/test_model.py

Addresses the bug reported in this Slack thread: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1750228449327769.
T-SQL generates `Boolean` values like `TRUE` into `(1 = 1)`, which causes issues when it is used in the context of a `MODEL` property, such as `enabled`.
For example, if a macro is used and the meta block is rendered, the resulting `Model` expression is generated and re-parsed in the macro evaluator, resulting in a new `Paren(Eq(Literal(1), Literal(1))` expression for the `enabled` field, which resulted in a falsey value with the old logic.

Fix: simplify complex expressions when validating boolean pydantic fields

---

sqlmesh/integrations/github/cicd/command.py
sqlmesh/integrations/github/cicd/controller.py
tests/integrations/github/cicd/test_github_commands.py
tests/integrations/github/cicd/test_integration.py

Prior to this PR, if you had `enable_deploy_command: true` in your `cicd_bot` config and no `users` configured in `required_approver` roles, you'd still get GitHub output like:
The problem with the message `Skipped Deploying to Production because a required approver has not approved` is that it's incorrect because it shows even when there are no required approvers configured.
This PR updates the output to the following:

Fix(cicd_bot): When enable_deploy_command: true, dont show message about required approvers

---

sqlmesh/core/snapshot/evaluator.py
tests/core/test_snapshot_evaluator.py

The statements that run as part of the migration needs to be a part of the same transaction + session.

Fix: Create a transaction and a session when migrating a snapshot

---

sqlmesh/core/engine_adapter/mssql.py
tests/core/engine_adapter/test_mssql.py

This pull request updates SQL queries in the MSSQL engine adapter and its corresponding tests to use uppercase identifiers for schema objects (`INFORMATION_SCHEMA`, `TABLES`, `COLUMNS`, etc.) to align with SQL standards and improve consistency. The changes span both the core implementation and the test suite.
>**NOTE:** This is done to enable the fabric engine adaptor without having to override functions from the MSSQL engine adaptor.
* Updated `columns` method in `sqlmesh/core/engine_adapter/mssql.py` to use uppercase identifiers for schema objects (`COLUMN_NAME`, `DATA_TYPE`, etc.) and table-related keywords (`TABLE_NAME`, `TABLE_SCHEMA`).
* Updated `table_exists` method in `sqlmesh/core/engine_adapter/mssql.py` to use uppercase identifiers for `INFORMATION_SCHEMA.TABLES` and …

fix(mssql): update SQL keywords to uppercase for consistency

---

sqlmesh/core/plan/stages.py
tests/core/test_plan_stages.py

This can sometimes cause a misleading output in the plan explainer. The `snapshots_with_missing_intervals` should only reflect snapshots selected for backfill.

Fix: Propagation of snapshots with missing intervals into the physical layer update stage

---

.circleci/config.yml

- this is so that any other tags like the one to launch vscode does not get picked up

ci: make regex for circle ci stricter

---

sqlmesh/core/snapshot/definition.py
tests/core/test_snapshot.py

Prior to this, when using `environment_suffix_target: catalog` against a model in the default catalog, the CLI would give output like:
```
$ sqlmesh plan erin
...SNIP...
Models needing backfill:
└── none__erin.sqlmesh_example.incremental_model: [2020-01-01 - 2025-04-07]
Apply - Backfill Tables [y/n]: y
```
This was due to an output optimisation where we hid the catalog as unnecessary information if it matched the default catalog.
However, `environment_suffix_target: catalog` relies on the default catalog being present because it needs it to generate the catalog name for the virtual environment.
This PR fixes the output:
```
$ sqlmesh plan erin
...SNIP...
Models needing backfill:
└── tobiko-1__erin.sqlmesh_example.incremental_model: [2020-01-01 - 2025-04-07]
Apply - Backfill Tables [y/n]: …
```

Fix: display_name should not exclude the default catalog when environment_suffix_target is set to CATALOG

---

sqlmesh/integrations/github/cicd/command.py
tests/integrations/github/cicd/test_github_commands.py
tests/integrations/github/cicd/test_integration.py

Breaking since this is a behavior change of the bot. This would impact Github CI/CD bot users if they had logic in their workflows that relied on the neutral output. 
Prior to this change, if a user had branch protection rules in-place the neutral status would allow merging. This would not be expected by users since they want to see this check pass before merging. Therefore this PR changes the status to failure instead of neutral to better support this pattern.

fix!: failure instead of neutral missing req approval

---

sqlmesh/core/snapshot/definition.py

The warning isn't really helpful outside the incremental setting.

Chore: Warn user about interval expansion only if the model is incremental

---

sqlmesh/core/plan/explainer.py

Fix: Include the preview disclaimer in the backfill section of the plan explanation when appropriate

---

sqlmesh/core/context.py

Fixes a bug where the `execution_time` default floored the time component of the returned value
Closes #4848

Fix: execution_time should default to now()

---

pyproject.toml
tests/dbt/test_config.py

This dependency is problematic because it enforces constraints on the `dbt-core` and `pyodbc` packages, making it difficult to efficiently support Python 3.13. Whatever value it provides isn’t worth the trouble.

Chore: Remove dbt-sqlserver dependencies

---

sqlmesh/core/console.py
sqlmesh/core/scheduler.py
sqlmesh/core/snapshot/definition.py
tests/cli/test_cli.py
tests/core/test_scheduler.py
web/server/api/endpoints/plan.py

Current state of the CLI UX for signals on this branch:

Feat!: improve signal CLI UX

---

vscode/extension/tests/global-setup.ts

- when running the tests one by one in vscode for example
- this skips the step of installation if already installed making the
tests run faster

chore: speed up tests when running locally

---

vscode/extension/tests/broken_project.spec.ts

- starts testing the contents of the lineage view

chore(vscode): starts testing the actual contents of the lineage view

---

sqlmesh/core/dialect.py
sqlmesh/core/macros.py
sqlmesh/core/snapshot/definition.py
sqlmesh/utils/cron.py

In situations where SQLMesh is long running (like in a service) the memory can grow indefinitely with the current caching approach. Therefore we are now setting a limit. The value of 500 is picked arbitrarily.

fix: put limit on lru cache

---

docs/guides/projects.md
docs/guides/ui.md
docs/installation.md
docs/quickstart/cli.md
docs/quickstart/notebook.md
docs/quickstart/ui.md

Avoid confusion between `.env` for environment variables and `.venv` for python virtual environments.

docs: move all vens to use .venv

---

vscode/extension/tests/python_env.spec.ts

- gives a little more time for these tests, where a whole python environment has to be created a little more time to be work

chore: make vscode tests less flaky

---

vscode/react/src/components/graph/ModelColumns.tsx
vscode/react/src/components/graph/ModelNode.tsx
vscode/react/src/components/graph/context.tsx
vscode/react/src/domain/column.ts

- when you click a column in the lineage it allows it to show that
columns lineage
- this fixes a bug where unclicking it didn't work
- introduces Column domain type to start shoring up things

fix(vscode): allow undoing clicking of lineage columns

---

docs/integrations/engines/mssql.md
sqlmesh/core/engine_adapter/base.py
sqlmesh/core/engine_adapter/mixins.py
sqlmesh/core/engine_adapter/mssql.py
sqlmesh/core/engine_adapter/postgres.py
sqlmesh/core/engine_adapter/redshift.py
sqlmesh/core/snapshot/evaluator.py
tests/core/engine_adapter/test_mssql.py
tests/core/test_snapshot_evaluator.py

We [recently updated](https://github.com/TobikoData/sqlmesh/pull/4811) the MSSQL `MERGE` implementation to use the `EXISTS` operator for performance improvement. 
The updated implementation [does not always improve performance and is incompatible with some column data types](https://github.com/TobikoData/sqlmesh/issues/4864) (e.g., `GEOMETRY`). 
This PR makes the newer implementation opt-in via the `mssql_merge_exists` flag in the `MODEL` `physical_properties` section.
Original feature request: #4568

Fix: make MSSQL merge exists implementation opt-in

---

docs/guides/configuration.md
docs/reference/configuration.md
sqlmesh/core/config/root.py
sqlmesh/core/config/scheduler.py
sqlmesh/core/context.py
sqlmesh/core/loader.py
sqlmesh/core/model/schema.py
sqlmesh/core/selector.py
sqlmesh/core/state_sync/db/facade.py
sqlmesh/core/state_sync/db/snapshot.py
sqlmesh/dbt/loader.py
sqlmesh/dbt/manifest.py
sqlmesh/dbt/project.py
tests/core/state_sync/test_export_import.py
tests/core/state_sync/test_state_sync.py
tests/core/test_context.py
web/server/watcher.py

By default SQLMesh stores its cache in a `.cache` folder inside the project directory. This introduces a configuration option to specify a custom cache location, either as a relative path or an absolute path. Fixes: #4307 
```yaml
cache_dir: .my_custom_cache
cache_dir: /tmp/sqlmesh_cache
```

Feat: Add support for configurable cache directory

---

sqlmesh/core/console.py
sqlmesh/integrations/github/cicd/command.py
sqlmesh/integrations/github/cicd/controller.py
tests/integrations/github/cicd/test_github_controller.py
tests/integrations/github/cicd/test_integration.py

Addresses #4120 
I've updated this step to more closely align with the CLI by showing the change category as well as any indirectly modified children. I've also added an intro text explaining what it's trying to show.
I've updated this step to switch from a tabular view to a list view so that it can more selectively show certain bits of info and more closely align with the CLI. It now shows:
- A warning about what's causing the PR environment to not contain the full set of data (and thus why a prod deploy wouldnt be a virtual update)
- More information about the work being done (eg `[full refresh]` / `[recreate view]`)
- For incremental models, more information about intervals. We show intervals that were loaded as part of the PR environment but also intervals that were *not* loaded, to …

Feat(cicd_bot): Improve output of 'PR Environment Synced' and 'Prod Plan Preview' steps

---

vscode/react/src/components/graph/SettingsControl.tsx

- makes the button not be wrapped with unncessary html blocks
- gets rid of deprecated headless ui code

chore(vscode): make buttons neater html

---

sqlmesh/core/state_sync/base.py
tests/core/state_sync/test_state_sync.py

Prior to this PR, if a user was running a version that didn't match the remote SQLMesh version, they would likely see a schema or sqlglot version mismatched error before SQLMesh. Erroring on SQLMesh is more useful since it makes it more clear what the issue is - version/SQLGLot should just be backup checks.

fix: check sqlmesh version before sqlglot/schema

---

docs/integrations/engines/duckdb.md
sqlmesh/core/config/connection.py
tests/core/test_connection_config.py

Prior to this PR, users were forced to use the default secret name when creating secrets. Now they can still do that or create secrets with a specific name. This is required to support a use case where users want to define multiple secrets for a single type (ex: multiple secrets for S3) since before they would get an error saying the default name was already defined.

feat: add named secret support DuckDB

---

sqlmesh/core/config/connection.py

Prior to this PR, would get the following error (confirmed in two different environments):
```
duckdb.duckdb.NotImplementedException: Not implemented Error: Failed to initialize DuckLake:PRIMARY KEY/UNIQUE constraints are not supported in DuckLake
```
Confirmed that if I remove this type then the error goes away and Ducklake works as expected. I don't see anywhere in Ducklake docs that it says to include TYPE when using ducklake. Tested using Ducklake with DuckDB and Postgres.

fix: don't include type when using ducklake

---

sqlmesh/core/context.py
sqlmesh/core/macros.py
sqlmesh/core/model/definition.py
sqlmesh/core/node.py
sqlmesh/core/renderer.py
sqlmesh/core/snapshot/definition.py
sqlmesh/dbt/converter/convert.py
sqlmesh/lsp/reference.py
sqlmesh/magics.py
tests/core/test_model.py
tests/integrations/github/cicd/conftest.py
vscode/openapi.json
vscode/react/src/api/client.ts
vscode/react/src/pages/lineage.tsx
web/server/api/endpoints/models.py
web/server/models.py
web/server/settings.py

At the moment, the path type is slightly confusing. Models can exist without a Path. Rather than mark the `_path` property as `None` we call `Path()` which is equivalent to calling `Path(".")` which is not particularly indicative it just returns your path to `cwd`. Optional is a much better representation.

chore: make _path optional and more representative

---

sqlmesh/core/console.py
sqlmesh/integrations/github/cicd/command.py
sqlmesh/integrations/github/cicd/controller.py
tests/integrations/github/cicd/test_github_controller.py
tests/integrations/github/cicd/test_integration.py

Related to #4120 
Currently, if there are lots of models to backfill, we "helpfully" truncate the list in the `Prod Plan Preview` step:
However, this is undesirable in the CI/CD bot because there is no equivalent of the `-vv` option to set the output verbosity. This means anyone reviewing the bot output has no way of actually knowing the full extent of the models to be backfilled.
This PR updates the CI/CD bot to always show the full list of models affected:

Fix(cicd_bot): Don't truncate backfill model list

---

.circleci/continue_config.yml
sqlmesh/core/engine_adapter/athena.py
sqlmesh/core/engine_adapter/base.py

Athena does not seem to deal with comments well, e.g:
```Python3
>>> self._execute('/* test */ DESCRIBE foo')
pyathena.error.OperationalError: FAILED: ParseException line 1:0 cannot recognize input near '/' '*' 'test'
```
This can cause `base.py::table_exists()` to fail silently (due to the try/catch) and thus not drop tables when needed.

Fix: Do not attach `correlation_id` for Athena queries

---

sqlmesh/migrations/v0085_deterministic_repr.py
sqlmesh/utils/metaprogramming.py
tests/utils/test_metaprogramming.py

Prior to this PR, models could show changes to `__sqlmesh__vars__` even though there is not an actual change to the model. Looking at the code and it appears that the dictionary is not deterministic so this PR aims to address that shortcoming.

fix!: make repr deterministic for fingerprinting

---

sqlmesh/core/loader.py
sqlmesh/core/model/common.py
sqlmesh/core/model/definition.py
sqlmesh/lsp/context.py
sqlmesh/lsp/errors.py
sqlmesh/lsp/main.py
sqlmesh/utils/errors.py

- adds path in places to make this as possible with
- refreshes well on typing

feat(lsp): return load time errors as diagnostics

---

sqlmesh/core/config/connection.py
tests/core/test_connection_config.py

Follow up to https://github.com/TobikoData/sqlmesh/pull/4913
Documentation consistently shows including `'ducklake` in the path: https://ducklake.select/docs/stable/duckdb/usage/choosing_a_catalog_database
It seems like if you exclude it from the path but included the type then it would also work. If you include both though you would get an error. Therefore since the last PR excluded it from TYPE we had some users not include it in the path and had an error.
This PR ensures the `'ducklake` prefix is always there if the type of "ducklake" is provided.

fix: add `'ducklake` prefix if not present

---

sqlmesh/core/test/definition.py
tests/core/test_test.py

Fix to convert nan and nat values to none so tests can be generated from upstream dependencies with null columns in them without errors, fixes: #4881

Fix: Convert to none nan values for test generation

---

pnpm-lock.yaml
sqlmesh/core/config/loader.py
sqlmesh/lsp/main.py
vscode/extension/package.json
vscode/extension/tests/broken_project.spec.ts

- return error
- filter diagnostics so it doesn't show in wrong place

feat(vscode): diagnostic for bad config.yaml error

---

sqlmesh/core/console.py
tests/core/test_table_diff.py

Prior to this, showing the row_diff sample on a table where Pandas had coerced a value to an `ndarray` would return the following error:
```
[ValueError: The truth value of an array with more than one element is ambiguous.
```
The cause is that the current code assumed `pd.isnull()` would always return a `bool`, when actually it returns an `array[bool]` if it gets passed an array.
This PR updates the code to handle arrays and say "arrays are considered null (python None) if all their items are null"

Fix(table_diff): Properly handle null check for array types in data sample

---

sqlmesh/utils/rich.py
tests/core/test_test.py

This fixes a bug where unit test output displayed row numbers starting from 0 instead of the actual DataFrame index, making it harder to trace the source of test mismatches. To preserve them moved away from the use of enumerate in `df_to_table` which ignored the original index to zip with df.index. The updated tests show the expected behaviour.

Fix: Preserve actual dataframe indices in unit test output

---

sqlmesh/core/engine_adapter/bigquery.py
tests/core/engine_adapter/integration/test_integration_bigquery.py

Follow up of https://github.com/TobikoData/sqlmesh/pull/4832 to also add the `correlation_id` as a BigQuery label at each query (i.e job) executed.
Docs
-------
[BQ Labels](https://cloud.google.com/bigquery/docs/adding-labels#python_2)

Feat: Tag BigQuery queries with their correlation ID as label

---

sqlmesh/core/engine_adapter/base.py
sqlmesh/core/engine_adapter/trino.py
sqlmesh/core/plan/evaluator.py
sqlmesh/core/scheduler.py
sqlmesh/core/snapshot/evaluator.py
tests/core/engine_adapter/test_base.py
tests/core/test_integration.py
tests/core/test_snapshot_evaluator.py

This update introduces an `is_restatement` flag and logic in `run_merged_intervals` to distinguish between restatements (which should clean up historical data from the restatement start date onwards) and regular runs (which should only append new changes). currently SCD Type 2 models with offset  cron greater than the interval start incorrectly used restatement cleanup logic during regular scheduled runs, which can be demonstrated from the added `test_scd_type_2_regular_run_with_offset` test.

Fix: Don't use SCD type 2 restatement logic in regular runs

---

sqlmesh/cli/options.py
tests/cli/test_cli.py

Fix: respect env. var for leading comma & normalize format settings

---

sqlmesh/core/model/common.py
sqlmesh/migrations/v0085_deterministic_repr.py
sqlmesh/migrations/v0086_check_deterministic_bug.py
sqlmesh/utils/metaprogramming.py
tests/core/test_model.py
tests/utils/test_metaprogramming.py

Fixing a mistake in this PR: https://github.com/TobikoData/sqlmesh/pull/4925
The issue is that the user could have defined a variable in the global namespace and this PR would sort the dictionary which would cause an issue for the user if they rely on the dictionary order. Therefore this PR makes the sorting logic focused just on the known dictionaries that we control: sqlmesh vars and sqlmesh blueprint vars. It also changes the sorting to only sort on the root level dict instead of doing a recursive sort. This is because a user could define a dict as a value in variable/blueprint variables and we don't want to change that. 
The previous 85 migration is updated to do the correct thing. 86 migration was added to try to detect if the user may have been impacted by this bug and if so it will …

fix!: correctly identify keys to make deterministic

---

docs/guides/signals.md

Chore: use paren syntax in signals docs

---

sqlmesh/integrations/github/cicd/controller.py

This helps make `GithubController` more testable in environments where the SQLMesh context is provided as a test fixture

Chore: Allow supplying a Context to GithubController

---

docs/concepts/models/python_models.md
sqlmesh/core/model/definition.py
tests/core/test_model.py

This update adds support for resolving variables in cron for python models. The updated existing tests show the use for macro variables and the newly added tests for blueprint python models.

Chore: Add cron in the fields to render for python models

---

pyproject.toml

- was doing a refactor for a listing rule and ended up importing lsp into other modules which we don't want to happen, this configures the linter to avoid this.

chore: prevent bad imports from lsp module elsewhere

---

vscode/extension/tests/quickfix.spec.ts

- also refactored the openProblemsView

chore(vscode): add test for quickfix

---

vscode/extension/package.json
vscode/extension/src/lsp/lsp.ts
vscode/extension/tests/external_models.spec.ts

- before if you were to open vscode and an external models file, the extension would not start automatically

feat(vscode): startup extension on external models files

---

sqlmesh/core/plan/evaluator.py
tests/core/test_integration.py

Example scenario: 
1. The kind of a model changed from `INCREMENTAL_UNMANAGED` to `INCREMENTAL_BY_TIME_RANGE` while the physical version remained the same
2. The kind changed is deployed to prod. At the same time a snapshot of this model with the old kind is still promoted in one or more dev environments
3. The model snapshot with the new kind is restated in prod
4. Because there's an old snapshot with previous kind deployed to some dev environment, the original restatement interval gets expanded and applied to the shared physical version
5. The user ends up restating full history instead of just the specified interval

Fix: Prevent snapshots with shared versions in dev environments from expanding restatement intervals for prod snapshots

---

sqlmesh/core/state_sync/db/snapshot.py

This PR prevents a race condition that can occur when two runs update auto restatements at the same time. Although the delete + insert happens in a transaction, certain databases and transaction isolation levels can result in duplicate rows being inserted and violate the primary key constraint on the auto restatements table.
For example, the default transaction isolation level for Postgres is READ COMMITTED, and at that level, [if the first updater commits, the second updater will ignore the row if the first updater deleted it](https://www.postgresql.org/docs/17/transaction-iso.html#XACT-READ-COMMITTED). In this case, the second updater will be blocked when deleting auto restatements until the first updater commits, but then will not delete any rows even though the first updater has …

Fix: Use merge when updating auto restatements

---

sqlmesh/core/plan/builder.py
sqlmesh/dbt/model.py
tests/core/test_plan.py
tests/dbt/test_transformation.py

For the kind change to be non-breaking / forward-only the following conditions must be met:
* Both the old model kind and the new one are incremental kinds
* The partitioning of the model hasn't changed
Additional non-breaking conditions can be added later.

Fix!: Suppor forward-only changes of model kinds under certain circumstances

---

sqlmesh/core/console.py
sqlmesh/core/linter/definition.py
sqlmesh/core/linter/rule.py
tests/core/test_context.py

- also printed the line numbers
```
❯ sqlmesh lint
Linter errors for /Users/benjaminking/Developer/sqlmesh/examples/sushi/models/customers.sql:
- nomissingaudits at line 1: Model `audits` must be configured to test data quality.
Linter errors for /Users/benjaminking/Developer/sqlmesh/examples/sushi/models/marketing.sql:
- nomissingaudits at line 1: Model `audits` must be configured to test data quality.
Linter errors for /Users/benjaminking/Developer/sqlmesh/examples/sushi/models/active_customers.sql:
- nomissingaudits at line 1: Model `audits` must be configured to test data quality.
Linter errors for /Users/benjaminking/Developer/sqlmesh/examples/sushi/models/customer_revenue_lifetime.sql:
- nomissingaudits at line 6: Model `audits` must be configured to test data quality.
Linter errors …
```

feat: allow linter to return multiple violations

---

sqlmesh/core/renderer.py
tests/core/test_model.py

There have been quite a few occasions in the wild where the parser fails to process a rendered Jinja string, while at the same time displaying a limited query context in the exception, making debugging difficult. This PR debug-logs the rendered Jinja string right before it is parsed.

Chore: log rendered jinja right before parsing it to improve debugging

---

sqlmesh/core/engine_adapter/duckdb.py
tests/core/engine_adapter/test_duckdb.py

DuckDB does not natively support partitioning, but the ducklake extension does. 
The extension requires partitioning to be set via `ALTER` after table creation.
This PR updates the DuckDB adapter to execute that `ALTER` if the table is in a ducklake catalog. For other catalog types, partitioned_by is ignored.

Feat: add partitioning for ducklake databases

---

vscode/extension/src/commands/stop.ts
vscode/extension/src/extension.ts
vscode/extension/src/lsp/lsp.ts
vscode/extension/tests/stop.spec.ts

- stopped server would just restart if something needed it
- this adds explicit flag which indicates that it was stopped by a user

fix: stopped server would just restart

---

vscode/extension/tests/bad_setup.spec.ts
vscode/extension/tests/broken_project.spec.ts
vscode/extension/tests/diagnostics.spec.ts
vscode/extension/tests/external_models.spec.ts
vscode/extension/tests/find_references.spec.ts
vscode/extension/tests/fixtures.ts
vscode/extension/tests/format.spec.ts
vscode/extension/tests/go_to_definition.spec.ts
vscode/extension/tests/hints.spec.ts
vscode/extension/tests/lineage.spec.ts
vscode/extension/tests/lineage_settings.spec.ts
vscode/extension/tests/python_env.spec.ts
vscode/extension/tests/quickfix.spec.ts
vscode/extension/tests/rename_cte.spec.ts
vscode/extension/tests/render.spec.ts
vscode/extension/tests/stop.spec.ts
vscode/extension/tests/tcloud.spec.ts
vscode/extension/tests/tests.spec.ts
vscode/extension/tests/venv_naming.spec.ts

- cleans up tem dir after every test

chore(vscode): move tests to central temp dir creation

---

docs/examples/incremental_time_full_walkthrough.md

See description in issue #5047.

chore(docs): fix-broken-link-to-example-file

---

sqlmesh/core/loader.py

- before you would get an error saying None is non-iterable
- was just slightly confusing when you first create the file
in vscode and we show a confusing error

feat: allow empty external models file

---

sqlmesh/core/snapshot/definition.py
tests/core/test_snapshot.py

Prior to this, `SnapshotTableInfo.data_version` was not inheriting the `table_naming_convention` property, causing unexpected behaviour

Fix: table_naming_convention not passed in all cases

---

sqlmesh/core/linter/rules/builtin.py
tests/core/linter/test_builtin.py
vscode/extension/tests/quickfix.spec.ts

- Note that at the moment it does not work when there is no `external_models.yaml` file. In this case it doesn't suggest the fix.

feat: no missing external model provides fix

---

vscode/extension/tests/bad_setup.spec.ts
vscode/extension/tests/utils.ts

- some of these were flaky but this should fix them and make them more reliable
- as working on pieces that affect this bit of the codebase we want these tests working

chore(vscode): reenabling tests

---

vscode/extension/tests/lineage.spec.ts

- working on enabling configuration tests 
- wanting them working before we play with multi project

chore(vscode): enabling more tests

---

.circleci/continue_config.yml
sqlmesh/core/dialect.py
tests/core/test_dialect.py

Closes #5065 
I think Athena has been broken since SQLMesh `v0.198.0` were we [upgraded](https://github.com/TobikoData/sqlmesh/commit/4a44d8952f1ed7a2192dbbceceab4927adffc2ba) SQLGlot to `v26.32.0`.
With that upgrade:
- Athena stopped extending Trino and became its own top-level Dialect
- It also defined some extra top-level Parser/Tokenizer/Generator classes that could not be reached directly from `<dialect>.Parser`, `<dialect>.Tokenizer` etc
This PR includes the extra set of top-level classes when extending the Athena dialect and adds a test that checks `MODEL (...)` can be roundtripped across every dialect

Fix(athena): Properly extend Athena dialect

---

sqlmesh/core/loader.py

Signals for a given project are registered explicitly by importing files in `./signals`.  In macros, the global registry of "standard macros" is copied out at the beginning of load, and user defined macros are loaded, then registry is set back to its old state. We do the same here now.
the issue is when you copy paste a signal from project A to project B
https://github.com/z3z1ma/sqlmesh/blob/6ed83334ef95cc23146eef6ff76731d1252e6665/sqlmesh/utils/__init__.py#L135-L140
this code will not raise a ValueError in the unique key dict subtly masking the fact that the signal that will persist is from project A. this mean project B in metaprogramming will not share subpath with __module__ and will be registered as an import payload

Fix: clean signal registry before loading signals for the given project

---

sqlmesh/core/state_sync/db/snapshot.py

This reverts commit 089ba465b4764f9beb53c1836d295318e6e642d0.

Fix: Revert "Fix: Use merge when updating auto restatements (#5016)"

---

sqlmesh/core/dialect.py
sqlmesh/core/loader.py
sqlmesh/core/model/definition.py
sqlmesh/core/model/meta.py
sqlmesh/migrations/v0088_include_default_audits_in_model.py
tests/core/test_audit.py
tests/core/test_integration.py
tests/core/test_model.py

This update ensures that audit arguments from default_audits are no longer dropped when model audits are present.
Previously, if a model defined its own audits, only those were retained and the arguments from default_audits were silently dropped (since we used the audit_definitions with empty args). This adds both in the model's audits, preserving them along with their arguments.

Fix!: Add model default audits in the model preserving their args

---

sqlmesh/core/model/definition.py

Use info in the logs instead of warning for cases where a property is conditionally assigned.

Chore: Info instead of warn for conditional properties assignment

---

sqlmesh/core/engine_adapter/postgres.py
sqlmesh/core/state_sync/db/snapshot.py
tests/core/engine_adapter/integration/test_integration_postgres.py
tests/core/engine_adapter/test_postgres.py

#5016 was reverted with #5108 because we didn't properly handle fetching server version with pg8000. This PR re-introduces merge for updating auto restatements but with added support for pg8000.

Feat: Re-introduce merge for updating auto restatements

---

sqlmesh/core/engine_adapter/bigquery.py
sqlmesh/utils/connection_pool.py
tests/core/engine_adapter/test_bigquery.py

This PR aims to address the following problem: suppose a plan is submitted, resulting in a BigQuery job submission to evaluate a model, followed by a keyboard interrupt issued by the user (e.g., CTRL-C / SIGINT is sent from the terminal).
Today we don't cancel the job, meaning that long-running jobs will be left orphaned to run in BigQuery, despite the plan being cancelled. This may result in needless computation (i.e., cost), and so in this PR we ~intercept the keyboard interrupt~ keep track of pending jobs and send a cancellation request upon closing the adapter, unless the jobs are already completed by that point.

Feat!: cancel submitted BigQuery jobs on keyboard interrupts

---

sqlmesh/core/context.py
sqlmesh/core/plan/builder.py
tests/core/test_context.py

Update to validate start is less than end date/time early during plan build time in the event that the user hasn't provided a start date in the config or in all models explicitly, fixes: #4916

Chore: Validate start and end dates during plan build time

---

pyproject.toml
sqlmesh/core/engine_adapter/bigquery.py
sqlmesh/dbt/adapter.py
tests/core/engine_adapter/integration/test_integration_bigquery.py
tests/dbt/test_adapter.py

returns columns in the proper Column subclass type.
fixes #1874

Fix!: sqlmesh.dbt.adapter.RuntimeAdapter.get_columns_in_relation()

---

sqlmesh/core/engine_adapter/bigquery.py

This follows the same logic from [BigQueryEngineAdapter.columns()](https://github.com/TobikoData/sqlmesh/blob/main/sqlmesh/core/engine_adapter/bigquery.py#L351-L357) to ensure `query_job` is not None before using it.

fix: BigQueryEngineAdapter.get_table_schema() mypy error

---

sqlmesh/core/state_sync/db/facade.py
sqlmesh/core/state_sync/db/migrator.py
sqlmesh/core/state_sync/db/snapshot.py
sqlmesh/core/state_sync/db/utils.py
sqlmesh/migrations/v0090_add_forward_only_column.py
tests/core/state_sync/test_state_sync.py

With introduction of the dev-only VDE mode, all snapshots that share the name also share the version. This means that fetching all snapshots with the same version may no longer be feasible, as it could result in retrieving the entire state in extreme cases.
This update optimizes the snapshot unpausing operation eliminating the need to fetch snapshots with shared versions. There were a few changes in the past that allow us to simplify the current implementation substantially:
- Deprecation of the Airflow support means that we no longer need to align the unpaused timestamp by the interval unit
- Interval compaction for garbage-collected snapshots means we no longer track intervals for individual snapshots, so there is no need to accurately reflect the effective-from timestamp in the state. …

Chore!: Optimize snapshot unpausing

---

sqlmesh/dbt/builtin.py
tests/dbt/test_transformation.py

Previously when using in dbt `log` the info parameter was ignored and we only logged in the logs if the debug mode was enabled. This updates the log builtin to use the info flag to control the levelling level to match dbt's handling ( https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/context/base.py#L570)

Fix(dbt): Use the info to control logging for dbt log builtin

---

pyproject.toml
sqlmesh/dbt/builtin.py

This adds support for dbt's [debug macro](https://docs.getdbt.com/reference/dbt-jinja-functions/debug-method) in a dbt project which opens an iPython debugger in the context of a macro
```python
{% macro my_macro() %}
{% set something_complex = my_complicated_macro() %}
{{ debug() }}
{% endmacro %}
```
This is enabled both by using the dbt `DBT_MACRO_DEBUGGING` environment variable or the sqlmesh native: `SQLMESH_DEBUG` or running with `--debug` flag.

Feat(dbt): Add dbt debug macro

---

sqlmesh/core/linter/helpers.py
tests/core/linter/test_helpers.py

- **refactor: refactor dialect parsing code to be reused**
- **feat: add the ability to return range for key and value**
- improved the parsing logic and made it more robust
- added the ability to return the value for the value range as well

feat: function to get range of key/value in model block

---

docs/integrations/dbt.md

This is the docs updates for the changes introduced in https://github.com/TobikoData/sqlmesh/pull/5156
In particular, `sqlmesh init -t dbt` now produces yaml config by default, so this updates the docs on how to work with that instead of python config

Docs(dbt): update for yaml config

---

sqlmesh/dbt/adapter.py
sqlmesh/dbt/builtin.py
sqlmesh/dbt/context.py
sqlmesh/dbt/manifest.py
sqlmesh/utils/conversions.py
sqlmesh/utils/jinja.py
tests/dbt/test_transformation.py
tests/fixtures/dbt/sushi_test/dbt_project.yml
tests/fixtures/dbt/sushi_test/macros/graph_usage.sql

This adds support for the dbt `graph` context variable which contains information about the nodes in a dbt project. 
Docs: https://docs.getdbt.com/reference/dbt-jinja-functions/graph

Feat(dbt): Add dbt graph context variable support

---

sqlmesh/core/plan/builder.py

Fix: Remove leftover forward-only category usage when categorizing orphaned snapshots

---

.github/workflows/private-repo-test.yaml

Following this: https://dvc.org/blog/testing-external-contributions-using-github-actions-secrets
Changed repo to require approval for all external contributions.

chore: allow forks run private repo tests

---

.circleci/continue_config.yml
.circleci/install-prerequisites.sh
.circleci/manage-test-db.sh
docs/integrations/engines/fabric.md
packages-microsoft-prod.deb
tests/core/engine_adapter/integration/config.yaml

- fix cloud tests on main that are currently failing due to the import check
- enable Fabric integration tests
- add community support banner to docs (similar to risingwave)

Chore(fabric): Enable integration tests

---

sqlmesh/dbt/manifest.py

This ensures that we format the error message appropriately before presenting the error to the user.

Fix: Intercept errors when loading the dbt manifest

---

sqlmesh/dbt/basemodel.py
sqlmesh/dbt/context.py
sqlmesh/dbt/loader.py
sqlmesh/utils/errors.py
tests/dbt/test_model.py

Dbt ignores with a warning tests that have refs to models that don't exist. This mimics that behavior. 
dbt function that explicitly does not fail if test: https://github.com/dbt-labs/dbt-core/blob/0836095a572532fc22b1c0981346eebe56f7d1fb/core/dbt/parser/manifest.py#L1324-L1332
I noticed in testing that constraints that make invalid refs also do not affect execution so I included that in the test although I didn't have to make any code changes at this time to support it.

feat: dbt adapter allow invalid ref for tests

---

sqlmesh/core/snapshot/evaluator.py
tests/core/test_snapshot_evaluator.py

Fix: Cleanup of materialized view snapshots

---

sqlmesh/core/model/definition.py
sqlmesh/dbt/seed.py
tests/core/test_model.py
tests/dbt/test_transformation.py

This update contains 3 super small fixes:
- Better error message when the seed model's `columns` has values that are missing in the produced dataframe
- Make pandas date parsing more lax and avoid failing when the conversion fails
- Treat a single whitespace as NA value for dbt seeds

Fix: Small fixes for seed models

---

sqlmesh/core/config/connection.py
sqlmesh/core/engine_adapter/duckdb.py
sqlmesh/core/state_sync/common.py
tests/core/engine_adapter/test_duckdb.py

MotherDuck has full support for database creation / deletion so we should use that.

Fix: Catalog creation / deletion for motherduck

---

.github/workflows/pr.yaml
Makefile
examples/sushi_dbt/profiles.yml
pyproject.toml
sqlmesh/dbt/loader.py
sqlmesh/dbt/manifest.py
sqlmesh/dbt/relation.py
sqlmesh/dbt/seed.py
sqlmesh/dbt/util.py
tests/dbt/conftest.py
tests/dbt/test_adapter.py
tests/dbt/test_config.py
tests/dbt/test_integration.py
tests/dbt/test_manifest.py
tests/dbt/test_model.py
tests/dbt/test_transformation.py

Widens the core compatibility range by addresses a few gaps where we weren't currently compatible and then adding CI checks to run fast tests and load dbt-sushi across the latest bugfix release of each dbt version.
One key part of this change is making sure that any fast dbt test we have doesn't require a sushi context or more generally DuckDB adapter information. This is because the DuckDB dbt-adapter for old dbt releases changed how catalogs are determined that affects these tests. Therefore we currently just run this slow tests on later versions. In tests where we needed some adapter to do things like loading with the Manifest, I used a Postgres connection instead since that is stable across the dbt releases.

feat: widen dbt-core compatibility range

---

examples/sushi_dbt/models/schema.yml
examples/sushi_dbt/tests/generic/greater_than_amount.sql
sqlmesh/dbt/manifest.py
tests/dbt/test_manifest.py

We don't handle **whitespace trimming** in the `{% test foo %} -> {% macro test_foo %}` conversion today, which results in this error: `Encountered unknown tag 'test'`. This PR address this. An example of such a test in the wild can be found [here](https://github.com/metaplane/dbt-expectations/blob/77d385655ce3318685cf6930b46d077f61de5f55/macros/schema_tests/column_values_basic/expect_column_values_to_be_in_type_list.sql).

Fix: handle whitespace trimming in dbt test-to-macro jinja normalization

---

examples/sushi/models/customer_revenue_by_day.sql
examples/sushi/models/waiter_as_customer_by_day.sql
sqlmesh/core/macros.py
sqlmesh/core/renderer.py
tests/core/test_model.py

Docs for reference: https://jinja.palletsprojects.com/en/stable/templates/#escaping

Fix!: render `{% raw %}...{% endraw %}` correctly

---

sqlmesh_dbt/cli.py
sqlmesh_dbt/error.py
tests/dbt/cli/test_global_flags.py

Currently the traceback is printed for the sqlmesh_dbt subcommands, this introduces a custom click group subclass that automatically wraps all subcommand callbacks with `cli_global_error_handler` ensuring error handling across the cli commands like `run`, `list` and in case more are added in the future.

Fix(dbt_cli): Add global error handling group for dbt subcommands

---

sqlmesh/dbt/project.py
tests/dbt/test_config.py

The added test fails without this fix:
```
>       all_project_variables = {**project_yaml.get("vars", {}), **(variable_overrides or {})}
E       TypeError: 'NoneType' object is not a mapping
```

Fix: properly handle empty `vars` mapping in dbt_project.yml

---

sqlmesh/dbt/context.py
tests/dbt/test_config.py
tests/dbt/test_manifest.py
tests/fixtures/dbt/sushi_test/dbt_project.yml
tests/fixtures/dbt/sushi_test/macros/top_waiters_limit.sql

Prior to this PR, the dbt adapter didn't support references to custom macros in the project variables. This adds that support.

feat: support custom macros in dbt vars

---

sqlmesh/dbt/basemodel.py
sqlmesh/dbt/context.py
sqlmesh/dbt/loader.py
sqlmesh/utils/errors.py
tests/dbt/test_model.py

Expands on previous PR to also include source references (which dbt handles in the same way): https://github.com/TobikoData/sqlmesh/pull/5207

feat: dbt adapter allow invalid source ref for tests

---

.circleci/continue_config.yml
.circleci/manage-test-db.sh
sqlmesh/core/engine_adapter/fabric.py
tests/conftest.py

This addresses:
- An oversight in tearing down the database for Redshift that caused [this failure](https://app.circleci.com/pipelines/github/TobikoData/sqlmesh/23761/workflows/3630bb10-cb60-4a40-8a46-ceac25108e44/jobs/270112)
- The failures caused by `teardown failed on attempt N! Exiting immediately!` when there is a `StashKey` error
- eg [here for trino](https://app.circleci.com/pipelines/github/TobikoData/sqlmesh/23774/workflows/da3cc0fb-02fc-41d7-8bcd-0d89309731bf/jobs/270410)
- and [here for fabric](https://app.circleci.com/pipelines/github/TobikoData/sqlmesh/23756/workflows/541b8d2c-da3d-4f18-94db-43871d1dec05/jobs/270034)
I had a handler for capturing the `StashKey` errors and it worked - if `pytest-retry` wasnt in the mix. So it was working for `style_and_cicd_tests` but not the …

Chore: Address more integration test flakiness

---

sqlmesh/dbt/basemodel.py
tests/dbt/test_model.py

Currently we raise an exception when a circular test reference is discovered. Our exception suggests moving the circular reference test in the upstream model to the downstream model. This PR takes it a step further and automatically does that for you.

Fix: Automatically repair dbt test circular references by moving upstream test to downstream model

---

sqlmesh/core/engine_adapter/spark.py
sqlmesh/core/snapshot/evaluator.py
tests/core/engine_adapter/test_spark.py
tests/core/test_snapshot_evaluator.py

A regression has been introduced to WAP support in #5189. The updated table name returned by the WAP prepare step wasn't being used for actual insert.
This update mitigates the issue and address the gaps in our test coverage to prevent this issue from happening in future.

Fix: Regression in WAP support

---

sqlmesh/dbt/manifest.py
tests/dbt/test_model.py

If a user incorrectly put `tests` in their model config dbt would ignore this and load/run fine. Our adapter would error. This change has our passed kwargs always override what is in the user's model config to match dbt behavior.

fix: ignore extra keys in node config

---

sqlmesh/dbt/common.py
sqlmesh/dbt/model.py
tests/dbt/test_model.py

This PR does not add runtime support for microbatch - it just allows the dbt adapter to load microbatch models. Follow up PR(s) will be adding runtime support so it matches dbt behavior.

chore: add dbt microbatch interface

---

sqlmesh/core/audit/definition.py
sqlmesh/core/context_diff.py
sqlmesh/core/model/common.py
sqlmesh/core/model/definition.py
sqlmesh/core/node.py
sqlmesh/core/snapshot/categorizer.py
sqlmesh/core/snapshot/definition.py
sqlmesh/migrations/v0093_use_raw_sql_in_fingerprint.py
sqlmesh/migrations/v0093_use_unrendered_query_in_fingerprint.py
tests/core/state_sync/test_export_import.py
tests/core/test_audit.py
tests/core/test_context.py
tests/core/test_integration.py
tests/core/test_model.py
tests/core/test_selector.py
tests/core/test_snapshot.py
tests/core/test_snapshot_evaluator.py
tests/core/test_table_diff.py
tests/core/test_test.py
tests/integrations/github/cicd/test_integration.py

This update eliminates the need for a rendered query when computing the model’s data hash. This means that the categorizer can now decide that the snapshot represents a metadata change even though the data hash has changed.
Doing this has the following benefits:
- Faster fingerprint calculation
- Eliminates the dependency on SQLGlot optimizer when calculating fingerprints which brings us one step closer to eliminating snapshot record migration as a result of the product upgrade

Fix!: Avoid using rendered query when computing the data hash

---

sqlmesh/core/model/meta.py
tests/core/test_model.py
tests/core/test_snapshot.py

Fix: complete lookback support for custom materializations

---

sqlmesh/dbt/model.py
tests/dbt/test_transformation.py

dbt disregards cluster_by config when creating tables for view models.

Fix: Match dbt handling of cluster_by config for view materializations

---

sqlmesh/dbt/model.py
tests/dbt/test_transformation.py

dbt ignores bigquery partition_by config when not using the bigquery plugin. Have sqlmesh mimic this behavior.

Fix: Ignore bigquery partition_by config when the target isn't bigquery

---

sqlmesh/utils/jinja.py
tests/fixtures/dbt/sushi_test/dbt_packages/my_macros/dbt_project.yml
tests/fixtures/dbt/sushi_test/dbt_packages/my_macros/macros/log_value_alt.sql
tests/fixtures/dbt/sushi_test/dbt_packages/my_package/dbt_project.yml
tests/fixtures/dbt/sushi_test/dbt_packages/my_package/models/dummy_model.sql
tests/fixtures/dbt/sushi_test/dbt_project.yml

The added test demonstrates what this PR aims to support. Basically:
- The root project specifies a `macros` directory in `dbt_project.yml` that lives within `dbt_packages/`
- Another package in that directory references said macro without qualifying it with its package name
The above works in dbt, but SQLMesh didn't support it until now because an assumption was made that each package could only see the contents defined within it, not outside of it. So, the package in the 2nd bullet above would fail to see the aforementioned macro and fail at render time, since the symbol wasn't present in `jinja_env.globals`.

Fix: ensure root package is treated top-level in dbt

---

sqlmesh/dbt/builtin.py
tests/dbt/test_transformation.py
tests/fixtures/dbt/sushi_test/models/top_waiters.sql

SQLMesh's dbt integration only supported keyword argument syntax for the `config()` function:
```sql
{{ config(materialized='table', alias='my_table') }}
```
However dbt also supports dictionary syntax:
```
{{ config({"materialized": "table", "alias": "my_table"}) }}
```
and since this: https://github.com/TobikoData/sqlmesh/pull/5269 would make us actually render this jinja config block it would fail without supporting the args

Fix: Add support for args syntax in dbt config

---

sqlmesh/core/snapshot/evaluator.py
tests/core/test_snapshot_evaluator.py

This update improves the performance of the schema migration plan stage by checking for the existence of snapshot tables in bulk instead of one by one.
The impact is particularly noticeable when deploying many changes to production or when initializing a project with existing models from scratch.

Fix: Prefetch all relevant data objects during snapshot migration

---

sqlmesh/dbt/model.py
tests/dbt/test_model.py

Fixes two misunderstanding of the dbt microbatch:
* SQLMesh `batch_size` is always 1 for dbt microbatch. In other words, they never issue a query that spans multiple intervals.
* `concurrent_batches` really determines, in SQLMesh terms, if a model depends on self which ultimately determine if the snapshot depends on past. Like SQLMesh, dbt determines this automatically by looking for self-referenes but users can force this with the `concurrent_batches` flag. Therefore if we see is `False`, meaning it should run sequentially, then we add the model to the `depends_on`.

fix: dbt microbatch parameter conversion

---

sqlmesh/dbt/model.py
tests/dbt/test_config.py
tests/dbt/test_transformation.py

There's no point in omitting view and incremental by time range models.

Fix: Allow partials by default for all models converted from a dbt project

---

docs/integrations/dbt.md
examples/sushi_dbt/models/customer_revenue_by_day.sql
examples/sushi_dbt/models/waiter_as_customer_by_day.sql
examples/sushi_dbt/models/waiter_revenue_by_day.sql
examples/sushi_dbt/models/waiter_revenue_by_day_v1.sql
sqlmesh/dbt/model.py
tests/dbt/test_manifest.py
tests/dbt/test_model.py

Prior to this PR, users could opt-in to using the incremental by time range SQLMesh behavior by adding a `time_column` property to their incremental config and then setting `{% if sqlmesh_incremental is defined %}` jinja block. 
This PR deprecates this behavior (but still supports it for now) and add a new incremental strategy called `incremental_by_time_range`. This gives SQLMesh it's own API for defining it's specific fields and removes the need for defining a jinja code block to activate it.

feat: add dedicated `incremental_by_time_range` strategy

---

pyproject.toml

- ~6hrs ago, a new version of `dbt-snowflake` (1.10.1) got released
- it declares it's compatible with `dbt-adapters>=1.16`
- pip dutifully resolves `dbt-adapters==1.16.4` because that's the one that's compatible with all the dbt packages we install (mainly, `dbt-databricks` has a constraint for `<1.16.5`)
- trying to use this combination results in `ImportError: cannot import name 'InvalidCatalogIntegrationConfigError' from 'dbt.adapters.catalogs'` because that class was not introduced until `dbt-adapters==1.16.6`
so this PR excludes this specific version `1.10.1` of `dbt-snowflake` with the assumption that upstream will either yank the release or fix the issue in the next version

Fix: exclude bugged version of dbt-snowflake so pip resolves compatible version of dbt-adapters

---

sqlmesh/core/snapshot/__init__.py
sqlmesh/core/snapshot/definition.py
sqlmesh/core/state_sync/base.py
sqlmesh/core/state_sync/db/facade.py
sqlmesh/core/state_sync/db/snapshot.py
tests/core/state_sync/test_state_sync.py
tests/core/test_snapshot.py

This is the first in a series of PR's looking at adjusting and clarifying how **restatements** work.
Currently, when a model is restated in `prod`, the following occurs:
1. Intervals are cleared from state for that model
2. Intervals are cleared from state for all versions of that model present in dev environments
The purpose of that last step is to prevent stale / old data from getting promoted to `prod` if someone decides to deploy a dev environment containing a version of the model that got built before the prod restatement occurred.
However, the current implementation has a gap. It only clears intervals for snapshots that are *promoted* in dev environments, because it's limited by what `StateSync` methods are available and it currently iterates over all environments from …

Feat(state_sync): Add the ability to fetch all versions of a snapshot by name

---

sqlmesh/dbt/builtin.py
tests/dbt/test_transformation.py

No explicit documentation of this usage, but seen in the wild
Ref: https://github.com/dbt-labs/dbt-core/blob/a9dae5cac16607558d318dd20e0aab383a58d1e2/core/dbt/context/base.py#L217

Fix: make sure builtin dbt macros can be referenced with the 'context.' prefix

---

sqlmesh/core/renderer.py
sqlmesh/dbt/__init__.py
sqlmesh/dbt/basemodel.py
sqlmesh/dbt/source.py
sqlmesh/utils/date.py
tests/core/test_snapshot.py
tests/dbt/test_model.py

One behavior difference between dbt microbatch and SQLMesh incremental by time range is that dbt microbatch, by default, includes the date filter for you. You can opt-out of this by adding a `.render()` after the ref. This PR adds that functionality.
Some tricky parts of this:
* To add the filter we need to know the event column and the start/end dates. All of that is known at load time for dbt but we only know event column at load time in SQLMesh. Therefore preparing the `EventTimeFilter` happens in two stages on SQLMesh - one when we load to record the event column and then at execution we add the start/end
* dbt uses end as exclusive and therefore doesn't use `BETWEEN` in the expression. Therefore the end is made exclusive. An alternative approach is to patch the filter render method …

feat: dbt microbatch ref filter support

---

sqlmesh/dbt/model.py
tests/dbt/test_manifest.py
tests/dbt/test_model.py
tests/fixtures/dbt/sushi_test/models/waiter_as_customer_by_day.sql
tests/fixtures/dbt/sushi_test/models/waiter_revenue_by_day.sql
tests/fixtures/dbt/sushi_test/models/waiter_revenue_by_day_v1.sql

Fixes error saying that column expression can't be serialzied.

fix: dbt time column serialization

---

sqlmesh/core/snapshot/definition.py
tests/core/test_integration.py

A snapshot should never be considered deployable if its parent is not representative.

Fix: Deployability of a child snapshot when its parent snapshot is indirect non-breaking without intervals

---

sqlmesh/core/engine_adapter/base.py
sqlmesh/core/engine_adapter/bigquery.py
sqlmesh/core/engine_adapter/fabric.py
sqlmesh/core/engine_adapter/mixins.py
sqlmesh/core/engine_adapter/mssql.py
sqlmesh/core/engine_adapter/shared.py
tests/core/engine_adapter/test_base.py
tests/core/engine_adapter/test_mssql.py

Deprecating `InsertOverwriteWithMergeMixin` and instead rely solely on `INSERT_OVERWRITE_STRATEGY`. Basically before we had two ways of doing the same thing so this consolidates into a single way.

chore: refactor to remove merge mixin

---

sqlmesh/core/console.py
sqlmesh/core/plan/builder.py
sqlmesh/core/plan/definition.py
sqlmesh/core/plan/explainer.py
tests/cli/test_cli.py
tests/core/test_plan_stages.py

This PR builds on #5285 to make it easier to reason about what's going on with restatements, which are a critical part of seamless dbt compatibility.
Currently, "restatements" has some nuance:
- Many things assume a plan is a restatement plan if `plan.restatements` is set. However, `plan.restatements` gets set for dev previews, leading to confusion when SQLMesh outputs "Restating models" when no restatements were specified
- We don't show how the selector for `--restate-model` maps to the backfill item list, leading to "why do I suddenly have 100 models to backfill when I only specified 3"-type questions
- In `--explain`, we currently just say "some intervals might cleared", instead of specifically listing the affected snapshots and what environments theyre promoted in
- notice that it …

Feat: Improve CLI and --explain output for restatements

---

pyproject.toml
sqlmesh/core/plan/stages.py
sqlmesh/core/snapshot/definition.py
sqlmesh/core/snapshot/evaluator.py
tests/core/test_context.py
tests/core/test_integration.py
tests/core/test_plan_stages.py
tests/core/test_snapshot_evaluator.py
tests/fixtures/dbt/sushi_test/models/model_with_raw_code.sql

Previously, we were incorrectly skipping the migration stage for view snapshots.

Fix: Regression that caused view snapshos not to be migrated

---

sqlmesh/core/snapshot/evaluator.py
tests/core/test_integration.py

This fixes a regression introduced by the refactor that coupled model table creation with evaluation.
Self-referential models required `columns` to be specified in the definition despite having fully annotated queries.

Fix: Create empty physical tables for fully annotated self-referential models

---

sqlmesh/core/plan/builder.py
sqlmesh/core/plan/common.py
tests/core/test_integration.py
tests/core/test_plan.py

Prior to this, a simple metadata change on a seed would trigger it to be recreated / data reloaded:
This PR updates `should_force_rebuild` to return `False` on a seed snapshot if only its metadata changed. This works because snapshots with metadata changes share the physical table with the previous snapshot, meaning:
- intervals are inherited from the previous snapshot
- this causes `missing_intervals()` to return no missing intervals
- causing no backfill!

Fix: Dont backfill seeds if the seed data didnt actually change

---

pyproject.toml

- removes an old pin for uvicorn for the lsp
- was copied as depends on web but uvicorn is not an actual python dep

fix: remove need for uvicorn

---

.circleci/continue_config.yml
pyproject.toml

Pin cryptography due to this change in 46.0.1: https://github.com/pyca/cryptography/commit/2726efdb6d67f1c90cf9c6062d9fe051965586f8 which leads to conflict on cffi since snowflake requires <2.0.0.

Chore: Pin cryptography instead of leaving it to the resolver

---

sqlmesh/core/model/definition.py
tests/core/test_model.py

For python models we currently attempt to render `auto_restatement_cron`, which incorrectly treats values like `@hourly` as SQLMesh macro variables.

Fix: support auto_restatement_cron in python models

---

sqlmesh/dbt/adapter.py
tests/dbt/test_adapter.py

This aligns the parameter names to ensure compatibility when using adapter.dispatch() with keyword arguments. The dispatch method in dbt uses `macro_namespace` and `macro_name` as parameters for example:
```jinja
{% macro my_macro(arg1, arg2) -%}
{{ return(adapter.dispatch(macro_name='my_macro', macro_namespace='package_1')(arg1, arg2)) }}
{%- endmacro %}
```
Dbt docs: https://docs.getdbt.com/reference/dbt-jinja-functions/dispatch

Fix(dbt): Update dispatch signature to match dbt method

---

sqlmesh/core/config/connection.py
sqlmesh/core/engine_adapter/base.py
sqlmesh/core/engine_adapter/spark.py
sqlmesh/core/snapshot/evaluator.py
tests/core/engine_adapter/test_spark.py

After deprecate Airflow integration and removing the corresponding test suite we lost our only avenue for testing Spark + Iceberg combination. As a result, the Iceberg-specifc WAP support fell behind and deteriorated as the recent wave of Spark + Iceberg issues suggests.
This update disables WAP by default with the option to enable it in future. This should buy us time to introduce back continuous testing for the Spark + Iceberg combo and address all issues.

Fix: Disable WAP support by default for Spark and Iceberg

---

sqlmesh/dbt/adapter.py
tests/dbt/test_adapter.py
tests/fixtures/dbt/sushi_test/macros/distinct.sql

dbt package macros can be overridden in the root package. This PR includes the root package when searching  packages during macro dispatch resolution.

Fix: Include root package in search candidates when resolving dbt macros

---

sqlmesh/core/console.py
tests/integrations/github/cicd/test_github_controller.py

Linter warnings currently appear in the error output section

Fix: route linter warnings correctly in github output

---

sqlmesh/dbt/target.py
tests/dbt/test_transformation.py

Expands the set of fields accessible via the `{{ target.[field] }}` syntax in a dbt model.
https://docs.getdbt.com/reference/dbt-jinja-functions/target

Chore: add fields to dbt jinja target variable

---

sqlmesh/dbt/model.py

Sometimes a model-level config will be microbatch and specify `begin`, but a higher-level config overrides the materialization to non-incremental.
In this situation, we currently pass `begin` through to sqlmesh and error - this PR removes that behavior.

Fix: pop 'begin' model config for all model kinds

---

sqlmesh/core/model/kind.py
sqlmesh/core/snapshot/evaluator.py
sqlmesh/dbt/adapter.py
sqlmesh/dbt/basemodel.py
sqlmesh/dbt/builtin.py
sqlmesh/dbt/manifest.py
sqlmesh/dbt/model.py
sqlmesh/dbt/package.py
sqlmesh/utils/jinja.py
tests/dbt/test_custom_materializations.py
tests/dbt/test_manifest.py
tests/dbt/test_model.py
tests/dbt/test_transformation.py
tests/fixtures/dbt/sushi_test/macros/materializations/custom_incremental.sql
tests/fixtures/dbt/sushi_test/models/custom_incremental_model.sql
tests/fixtures/dbt/sushi_test/models/custom_incremental_with_filter.sql
tests/fixtures/dbt/sushi_test/profiles.yml

This update adds support for dbt custom materializations which allows users to define their own strategies via jinja macros. 
Docs:  https://docs.getdbt.com/guides/create-new-materializations?step=2

Feat(dbt): Add support for dbt custom materializations

---

Makefile

Small fixup– I meant this to be "clear", not "clean". The latter doesn't seem right.

Chore: rename clean-caches to clear-caches

---

sqlmesh/core/engine_adapter/base.py
sqlmesh/core/engine_adapter/base_postgres.py
sqlmesh/core/engine_adapter/bigquery.py
sqlmesh/core/engine_adapter/clickhouse.py
sqlmesh/core/engine_adapter/mssql.py
sqlmesh/core/engine_adapter/mysql.py
sqlmesh/core/engine_adapter/postgres.py
sqlmesh/core/engine_adapter/spark.py
sqlmesh/core/snapshot/evaluator.py
tests/core/engine_adapter/test_athena.py
tests/core/engine_adapter/test_base.py
tests/core/engine_adapter/test_snowflake.py
tests/core/test_snapshot_evaluator.py
tests/dbt/test_transformation.py

This reduces the number of INFORMATION_SCHEMA queries from 28 down to 6 on the fresh `sushi` project. I anticipate equally dramatic improvements in other scenarios.

Chore: Cache results of get_data_objects

---

docs/guides/configuration.md
sqlmesh/core/constants.py
tests/core/engine_adapter/integration/conftest.py
tests/core/engine_adapter/test_trino.py
tests/dbt/test_adapter.py

Just a small improvement to allow users to relocate the `.sqlmesh` home folder.

Chore: make `.sqlmesh` location configurable

---

tests/cli/test_cli.py
tests/utils/test_helpers.py

I tried running `pytest -n auto tests/cli/test_cli.py` from a different system, locally, and started seeing assertion errors related to line break positioning:
```
FAILED tests/cli/test_cli.py::test_plan_dev_longnames - AssertionError: assert 'sqlmesh_example__dev_butamuchlongerenvironmentname.seed_cccccccccccccccccccccccc\ncccccccccccccccccccccccccccccccccccccccccccccccccccccccc_model          [ins...
FAILED tests/cli/test_cli.py::test_plan_nonbreaking_noautocategorization - AssertionError: assert '[1] [Breaking] Backfill sqlmesh_example.incremental_model and indirectly \nmodified children' in '.\n=========================================================...
FAILED tests/cli/test_cli.py::test_run_cron_not_elapsed - AssertionError: assert 'No models are ready to run. Please wait until a …
```

Chore: make console width deterministic in tests

---

tests/dbt/cli/test_run.py

This aims to fix the flaky test `test_run_with_changes_and_full_refresh`. This fails intermittently because when the test modifies model_b.sql, dbt's change detection mechanism doesn't always register the update due to the limited granularity of filesystem timestamps. So dbt may rely on a stale cached model definition, which doesn't include the updated schema with the new column c. The fix is to explicitly unlink the partial parse cache file after modifying the model, which forces dbt to perform a full parse and register the changes.

Chore: Fix flaky test by unliking dbt msgpack for deterministic behaviour

---

sqlmesh/dbt/basemodel.py
sqlmesh/dbt/context.py
sqlmesh/dbt/source.py
tests/dbt/test_transformation.py

An idiom used in dbt projects is to define a model as both a model and a source to circumvent circular dependencies. 
For example:
- Model A is a cache of load times from an external source
- Model B is the loaded values form the external source
Model A uses model B to figure out the previous load time by the max timestamp
Model B uses Model A to know what timestamp it needs to fetch from without having to redo that expensive calculation
In this idiom, Model B can be defined also as a source. Model A can then call it using the `source()` method, circumventing the circular dependency. 
However, it does also mean the developer has to make sure the table for Model B is created before Model A is called. Putting the `source()` call in an `is_incremental()` block is one way to solve that. There …

Fix: Add workaround to ignore source dependency if fqn matches model

---

sqlmesh/core/model/common.py
sqlmesh/core/model/definition.py
sqlmesh/core/snapshot/evaluator.py
sqlmesh/dbt/basemodel.py
tests/core/test_snapshot_evaluator.py
tests/dbt/test_transformation.py
tests/fixtures/dbt/sushi_test/macros/insert_hook.sql
tests/fixtures/dbt/sushi_test/models/model_with_transaction_hooks.sql

This adds support for `transaction` in dbt pre and post hooks. By default hooks are executed inside of the same transaction as the model being created. Hooks that need to run outside a transaction are for example when executing a VACUUM in Redshift or inserting into an audit table at the start of a run where the insert should persist even if the model fails. Running the hook outside a transaction ensures it won’t be rolled back.
These are set in a dbt project either with the `before_begin` and `after_commit` macro:
```
{{
config(
pre_hook=before_begin("SQL-statement"),
post_hook=after_commit("SQL-statement")
)
}}
```
or by setting the `transaction` flag in a dict:
```
{{
config(
pre_hook={
"sql": "SQL-statement",
"transaction": False
},
post_hook={
"sql": "SQL-statement",
"transaction": …
```

Feat(dbt): Add support for transaction in dbt pre and post hooks
