web/client/src/library/components/button/Button.tsx, web/client/src/library/components/editor/Editor.tsx, web/client/src/library/components/ide/IDE.tsx, web/client/src/library/components/ide/RunPlan.tsx, web/client/src/library/components/modal/ModalDrawer.tsx, web/client/src/library/components/plan/Plan.tsx, web/client/src/library/components/plan/PlanActions.tsx, web/client/src/library/components/plan/PlanChangePreview.tsx, web/client/src/library/components/plan/PlanHeader.tsx, web/client/src/library/components/plan/PlanWizard.tsx, web/client/src/library/components/plan/PlanWizardStepOptions.tsx, web/client/src/library/components/tasksProgress/TasksProgress.tsx, web/client/src/library/components/toggle/Toggle.tsx, web/client/tailwind.config.js
https://user-images.githubusercontent.com/5644753/227601341-eb5f11f1-90eb-42db-b099-0049bdf1754e.mov
=> [UI] Display plan in drawer instead of modal

docs/concepts/overview.md, docs/guides/connections.md, docs/guides/models.md, docs/guides/scheduling.md, docs/integrations/engines.md, docs/integrations/github.md, docs/integrations/overview.md, docs/quick_start.md, docs/reference/cli.md, docs/reference/configuration.md, docs/reference/notebook.md, docs/reference/overview.md, mkdocs.yml
- Reorder guides/ and add integrations/engines.md to mkdocs.yml
- Edits
- guides/connections.md
- guides/scheduling.md
- guides/models.md    
- integrations/github.md
- Fix links in concepts/overview.md and quick_start.md
- Minor word edits to reference/ docs
=> Edits to documentation

docs/integrations/dbt.md
=> Edit integrations/dbt

docs/concepts/glossary.md
We need these out by launch so links work on website.
=> Add website terms

README.md
Resolves: https://github.com/TobikoData/sqlmesh/issues/637
=> [Other] Fix slack link

sqlmesh/core/config/connection.py, sqlmesh/dbt/profile.py, tests/core/test_connection_config.py
Resolves: https://github.com/TobikoData/sqlmesh/issues/643
I can't test this myself but it looks like this should solve it based on the documentation.
=> Add support for Snowflake authenticator

docs/guides/connections.md, docs/integrations/engines.md
Add Snowflake `authenticator` details to docs (from #644)
=> Add Snowflake authenticator param to docs

setup.py
=> Fix: require >= v.1.9.1 for pydantic

web/client/src/library/components/plan/Plan.tsx, web/server/api/endpoints/plan.py
Fixing UI issue:
Create a dev environment that is just a mirror of prod. Then make a change to an incremental model and load a subset of data. Once that is done run plan again but this time select all dates. The UI will say "No Change" and not allow the user to fill in the missing gaps.
=> [UI] Check for missing backfills

web/client/src/library/components/banner/Banner.tsx, web/client/src/library/components/plan/PlanHeader.tsx, web/client/src/library/components/plan/PlanWizard.tsx, web/client/src/library/components/plan/hooks.ts
Just  a text message about all  ran tests
=> Feat: Display Tests Report when running plan 

examples/airflow/Makefile
If you have never run package before then plugin won't load when running Airflow locally.
=> Fix: Add package to init so plugins work

web/client/src/library/components/editor/Editor.tsx, web/client/src/library/components/editor/EditorFooter.tsx, web/client/src/library/components/editor/extensions/SqlMeshDialect.ts, web/client/src/library/components/editor/extensions/index.ts, web/client/src/library/components/fileTree/FileTree.tsx, web/client/src/library/components/plan/PlanChangePreview.tsx, web/client/src/library/components/plan/PlanWizard.tsx, web/client/src/models/file.ts, web/client/src/utils/index.ts, web/client/src/workers/sqlglot/sqlglot.py
=> Fix: styling bugs and incorrect spelling

sqlmesh/core/plan/definition.py, tests/core/test_plan.py
If a removed model(s) is referenced in any downstream models the following error will be displayed as a result of this change:
```
$ sqlmesh plan
Error: Removed models {'sqlmesh_example.example_incremental_model'} are referenced in model 'sqlmesh_example.example_full_model'. Please remove broken references before proceeding.
```
Fixes #706
=> Fix: Ensure that removed models are not referenced downstream during plan creation (#706)

sqlmesh/dbt/basemodel.py, sqlmesh/dbt/loader.py, sqlmesh/dbt/model.py, sqlmesh/dbt/project.py, sqlmesh/dbt/target.py, tests/dbt/test_transformation.py
=> Fix: [dbt] materialized can be jinja and allow, but warn, on extra profile fields

docs/integrations/engines.md, setup.cfg, setup.py, sqlmesh/core/config/__init__.py, sqlmesh/core/config/connection.py, sqlmesh/core/engine_adapter/__init__.py, sqlmesh/core/engine_adapter/base.py, sqlmesh/core/engine_adapter/base_postgres.py, sqlmesh/core/engine_adapter/postgres.py, sqlmesh/core/engine_adapter/redshift.py, sqlmesh/core/engine_adapter/spark.py, sqlmesh/core/snapshot/evaluator.py, sqlmesh/dbt/target.py, sqlmesh/schedulers/airflow/operators/postgres.py, sqlmesh/schedulers/airflow/util.py, tests/core/engine_adapter/test_base.py, tests/core/engine_adapter/test_base_postgres.py, tests/core/engine_adapter/test_postgres.py, tests/core/engine_adapter/test_redshift.py, tests/core/test_snapshot_evaluator.py, tests/dbt/test_adapter.py
Also includes some refactoring. With Postgres complete it is a good time to go in and harden everything: https://github.com/TobikoData/sqlmesh/issues/676
Resolves: https://github.com/TobikoData/sqlmesh/issues/125
=> Feat: Add Postgres Support (built-in, Airflow, dbt)

docs/reference/notebook.md
- Changed the argument name of Context class from "path" to "paths" and edited the path name for better clarity.
- Added instructions on how to initialize example project in Databricks and configure the connection details.
=> Updated notebook.md

web/client/src/api/channels.ts, web/client/src/library/components/banner/Banner.tsx, web/client/src/library/components/plan/Plan.tsx, web/client/src/library/components/plan/PlanHeader.tsx, web/client/src/library/components/plan/PlanWizard.tsx, web/client/src/library/components/plan/context.tsx, web/client/src/library/components/plan/hooks.ts, web/client/src/library/components/report/ReportTestsErrors.tsx, web/server/console.py
Display details breakdown of failed tests or occurred errors when running plan with tests
=> Feat: Display tests report

docs/concepts/models/model_kinds.md, docs/integrations/dbt.md, sqlmesh/dbt/model.py, tests/dbt/test_transformation.py
Also improve dbt incremental documentation
=> Feat: [dbt] Support incremental_by_unique_key when unique_key defined with no incremental_strategy

sqlmesh/cli/main.py
Fixes https://github.com/TobikoData/sqlmesh/issues/737
=> Fixed typo

sqlmesh/dbt/context.py, sqlmesh/dbt/loader.py, sqlmesh/dbt/model.py, sqlmesh/dbt/package.py, sqlmesh/dbt/profile.py, sqlmesh/dbt/target.py, tests/dbt/test_config.py, tests/dbt/test_transformation.py
=> Fix: Clean-up target defaults

web/client/src/index.css, web/client/src/library/components/editor/Editor.css, web/client/src/library/components/editor/EditorCode.tsx, web/client/src/library/components/editor/extensions/SqlMeshDialect.ts, web/client/src/library/components/editor/extensions/index.ts, web/client/tailwind.config.js
=> Feat: Highlight know columns in editor

docs/concepts/plans.md
Based on [this Slack conversation](https://tobiko-data.slack.com/archives/C0550PZQM0U/p1682614970776169?thread_ts=1682550452.715839&cid=C0550PZQM0U) with @eakmanrq
=> Clarify definition of "backfill" in docs

web/client/src/context/editor.ts, web/client/src/context/lineage.tsx, web/client/src/library/components/editor/Editor.tsx, web/client/src/library/components/editor/EditorPreview.tsx, web/client/src/library/components/graph/Graph.css, web/client/src/library/components/graph/Graph.tsx, web/client/src/library/components/graph/help.ts, web/client/src/utils/index.ts
=> Fix: display nodes more condensed, update connection on column name change

sqlmesh/core/model/definition.py
Prior to the fix dates would be represented as `'2023-01-01'` instead of `2023-01-01`
=> Fix: DataFrame Where Clause Quoting

web/server/watcher.py
A typo in a model, audit, etc. shouldn't cause the IDE's file watcher to stop watching.
=> Fix: Continue watching even if context.load() fails

sqlmesh/cli/main.py
Wrapped quotes around sql[mesh]
#798
=> Fix: format code

examples/sushi/models/order_items.py, sqlmesh/core/engine_adapter/snowflake.py, tests/core/test_context.py
=> Fix: In Snowflake adapter return the DataFrame as is without modifying its column names. 

examples/sushi/config.py, setup.py, sqlmesh/core/context.py, sqlmesh/integrations/github/cicd/command.py, sqlmesh/integrations/github/cicd/controller.py, tests/fixtures/github/pull_request_closed.json, tests/fixtures/github/pull_request_comment.json, tests/fixtures/github/pull_request_review_submit.json, tests/fixtures/github/pull_request_synchronized.json, tests/integrations/github/cicd/fixtures.py, tests/integrations/github/cicd/test_github_commands.py, tests/integrations/github/cicd/test_github_controller.py, tests/integrations/github/cicd/test_github_event.py
I would like to write some more but getting what I have for now added and will add some more over time.
Also bumped mypy version while trying to fix bug and it works fine so including it in the release.
=> Add Tests to Github Action CI/CD Bot

sqlmesh/core/model/seed.py, sqlmesh/core/state_sync/engine_adapter.py, sqlmesh/migrations/v0006_change_seed_hash.py, tests/core/test_seed.py, tests/core/test_snapshot.py
=> Fix: duplicates on migrations

sqlmesh/core/console.py
Sometimes Databricks freezes up while applying a plan. Removing the rich terminal progress updating removed all freezing while testing locally. There could still be some issues remaining but this at least fixes one of the sources of freezing. Unfortunately this makes the notebook UI even less appealing but in the short term stability is certainly worth it over presentation.
=> Fix: Reduce or Fix Databricks Notebook Freezing

sqlmesh/cli/main.py, sqlmesh/core/context.py, sqlmesh/core/loader.py, sqlmesh/dbt/loader.py
Also support external models in dbt formatted projects.
=> Fix: Allow create_external_models to run for projects with star projections

sqlmesh/core/engine_adapter/base.py, sqlmesh/core/engine_adapter/spark.py, tests/core/engine_adapter/test_base.py
Depends on: https://github.com/TobikoData/sqlmesh/pull/890
=> Fix: Use SUPPORTS_INSERT_OVERWRITE and cleanup

sqlmesh/core/model/meta.py
=> Fix: use dialect in column_to_types_ validator

sqlmesh/core/test/definition.py, tests/core/test_test.py
=> Include a model's CTEs when testing one of its CTEs

tests/web/test_main.py, web/client/openapi.json, web/client/src/api/instance.ts, web/client/src/index.css, web/client/src/library/components/documentation/Documentation.tsx, web/client/src/library/components/editor/Editor.css, web/client/src/library/components/editor/EditorCode.tsx, web/client/src/library/components/editor/extensions/index.ts, web/client/src/library/components/graph/Graph.tsx, web/client/src/library/components/graph/ModelLineage.tsx, web/client/src/library/components/graph/context.tsx, web/client/src/library/components/graph/help.ts, web/client/src/library/pages/ide/IDE.tsx, web/client/src/routes.tsx, web/server/api/endpoints/lineage.py, web/server/models.py
When requesting column lineage display CTE nodes + source in case model has CTEs
=> Feat: display node for CTE

docs/integrations/airflow.md
We mean config.yaml probably, right?
=> Docs: Update airflow.md

docs/integrations/engines.md, examples/sushi/config.py, sqlmesh/__init__.py, sqlmesh/core/config/__init__.py, sqlmesh/core/config/connection.py, sqlmesh/utils/__init__.py, tests/conftest.py, tests/schedulers/airflow/conftest.py, tests/schedulers/airflow/test_end_to_end.py
Resolves: https://github.com/TobikoData/sqlmesh/issues/576
=> Feat: Add spark connection config

docs/comparisons.md
The Python models and data contracts sections likely need more work. Please provide input for those sections here or take another pass after the PR is merged.
=> Chore: Updated dbt comparison documentation to include new SQLMesh features.

setup.py, sqlmesh/core/dialect.py, sqlmesh/core/model/definition.py, sqlmesh/core/model/kind.py, web/client/src/workers/sqlglot/sqlglot.py
This will resolve the issues caused by https://github.com/tobymao/sqlglot/pull/1750, when we bump SQLGlot.
TODO:
=> Chore: bump sqlglot version

sqlmesh/core/constants.py, web/client/src/context/context.ts, web/client/src/library/components/editor/extensions/SqlMeshDialect.ts, web/client/src/library/components/graph/Graph.tsx, web/client/src/library/components/graph/context.tsx, web/client/src/library/components/graph/help.ts, web/client/src/library/components/plan/PlanWizardStepOptions.tsx, web/client/src/library/components/report/ReportErrors.tsx, web/client/src/library/pages/ide/ActivePlan.tsx, web/client/src/library/pages/ide/IDE.tsx, web/client/src/library/pages/ide/RunPlan.tsx, web/client/src/models/environment.ts, web/client/src/types/enum.ts, web/client/src/workers/sqlglot/worker.ts, web/server/api/endpoints/lineage.py, web/server/console.py, web/server/settings.py, web/server/watcher.py
1. Environments not getting updated after plan applied
2. Delay plan call after plan apply
3. Display nodes for CTEs when SQL has multiple `WITH`
4. Refetch environments, after plan promote step happened
=> Fix: various bugs

.circleci/config.yml, .circleci/continue_config.yml
This PR also renames the `ide-build` job to `ui-build`.
=> Chore: Only run UI tests when UI files have changed.

web/server/api/endpoints/table_diff.py
Nan is not json encodable so replace it with None.
=> Fix: Replace nan with None in table diff sample

sqlmesh/core/macros.py, tests/core/test_macros.py
=> Fix(macros): ensure @FILTER condition is evaluated

sqlmesh/core/engine_adapter/spark.py
On Databricks we had an issue where Spark was returning an error when trying to reference the temporary views where it couldn't identify the object. This is after upgrading to Unity and Spark 3.4 (Spark 3.1 contains some changes to how temp view works). Global temp view works just as well since we are using globally unique names and it appears to resolve this issue.
=> Fix: Use global temp view for Spark

sqlmesh/core/model/definition.py, tests/core/test_model.py
Only print the warning when it may directly impact the functionality and user experience (like column-level lineage). We check whether the query contains star projection before printing out the warning.
=> Fix: Make the missing schema warning less noisy

sqlmesh/core/test/definition.py, tests/core/test_test.py
=> Fix: Disregard column order when comparing DataFrames in tests

sqlmesh/core/dialect.py, sqlmesh/core/model/common.py, sqlmesh/core/model/definition.py, sqlmesh/migrations/v0013_serde_using_model_dialects.py, sqlmesh/utils/pydantic.py, tests/core/test_model.py
=> Feat!: use dialect when (de)serializing model expressions

sqlmesh/dbt/target.py
=> Feat: Add Snowflake authenticator connection config for dbt projects

sqlmesh/core/audit/builtin.py, tests/core/test_audit.py
Make chi test a nice example of the power of sqlmesh tests and polish it to make it more stats-ey and less long-form relational
=> Chore: polish up chi square test and allow auditing for dependence OR independence

sqlmesh/core/context.py, sqlmesh/core/plan/definition.py, sqlmesh/core/snapshot/definition.py, sqlmesh/core/state_sync/__init__.py, sqlmesh/core/state_sync/cache.py, tests/core/test_state_sync.py
This reverts commit c8308bfe190185d32bce63d669987f2aa7a39620.
=> Revert "Revert "Feat: add a state sync cache for performance""

examples/sushi_dbt/config.py, setup.py, sqlmesh/core/config/__init__.py, sqlmesh/core/config/connection.py
GCP has a special connector that integrates their gcloud auth with their postgres managed service.
=> Feature: Add connection config for GCP managed Postgres

web/client/openapi.json, web/client/src/library/components/plan/Plan.tsx, web/client/src/library/components/plan/PlanActions.tsx, web/client/src/library/components/plan/PlanWizardStepOptions.tsx, web/client/src/library/components/plan/context.tsx, web/client/src/library/components/plan/hooks.ts, web/client/src/library/pages/ide/IDE.tsx, web/client/src/library/pages/ide/RunPlan.tsx, web/server/api/endpoints/commands.py, web/server/api/endpoints/plan.py, web/server/models.py
When apply to `new` env without changes
but if set to FALSE
=> Feat: add promote_all option to UI

sqlmesh/core/console.py, sqlmesh/core/context.py, sqlmesh/core/plan/evaluator.py, sqlmesh/core/scheduler.py, sqlmesh/core/snapshot/evaluator.py, tests/core/test_integration.py, web/server/console.py
Fixes second half of https://github.com/TobikoData/sqlmesh/issues/1050.
Demo:
=> Feat: add progress bar for snapshot creation

docs/comparisons.md
Reverts TobikoData/sqlmesh#1182
=> Revert "Docs: Remove extra check mark from dbt comparison"

sqlmesh/core/context.py, sqlmesh/core/state_sync/engine_adapter.py, sqlmesh/engines/commands.py, tests/core/test_integration.py, tests/schedulers/airflow/operators/test_targets.py
Resolves: https://github.com/TobikoData/sqlmesh/issues/1175
=> Feat: Drop schemas for expired environments

sqlmesh/core/console.py, sqlmesh/core/plan/evaluator.py, sqlmesh/core/scheduler.py, tests/core/test_integration.py, web/server/console.py
https://github.com/TobikoData/sqlmesh/assets/7747479/696c7c09-6d85-494a-a127-282162b8f105
=> Fix: Make sure the evaluation progress bar looks good when evaluating a large number of models

docs/concepts/models/overview.md, sqlmesh/core/engine_adapter/base.py, sqlmesh/core/engine_adapter/bigquery.py, sqlmesh/core/engine_adapter/spark.py, sqlmesh/core/model/definition.py, sqlmesh/core/model/meta.py, sqlmesh/core/snapshot/evaluator.py, sqlmesh/dbt/model.py, tests/core/engine_adapter/test_bigquery.py, tests/core/engine_adapter/test_spark.py, tests/core/test_model.py, tests/core/test_snapshot_evaluator.py, tests/dbt/test_transformation.py
=> Feat: Allow specifying of arbitrary table properties as part of the model definition

.gitignore, web/client/openapi.json, web/client/src/index.css, web/client/src/library/components/graph/Graph.tsx, web/client/src/library/components/graph/ModelLineage.tsx, web/client/src/library/components/graph/context.tsx, web/client/src/library/components/graph/help.ts, web/client/src/library/components/input/InputToggle.tsx, web/client/src/library/components/plan/PlanChangePreview.tsx, web/client/src/library/pages/ide/RunPlan.tsx
Column type display
Long name lineage node
Add options to hide columns for all nodes in lineage
Add option to toggle background for lineage
=> Fix:  Few styling bugs around lineage 

docs/reference/configuration.md
Document this feature: https://github.com/TobikoData/sqlmesh/pull/1171
=> Docs: Document state schema feature

web/client/package.json, web/client/src/api/index.ts, web/client/src/context/editor.ts, web/client/src/context/project.ts, web/client/src/library/components/button/Button.tsx, web/client/src/library/components/container/Container.tsx, web/client/src/library/components/documentation/Documentation.tsx, web/client/src/library/components/editor/Editor.tsx, web/client/src/library/components/editor/EditorCode.tsx, web/client/src/library/components/editor/EditorPreview.tsx, web/client/src/library/components/editor/EditorTabs.tsx, web/client/src/library/components/editor/hooks.ts, web/client/src/library/components/fileExplorer/Directory.tsx, web/client/src/library/components/fileExplorer/DragLayer.tsx, web/client/src/library/components/fileExplorer/File.tsx, web/client/src/library/components/fileExplorer/FileExplorer.tsx, web/client/src/library/components/fileExplorer/context.tsx, web/client/src/library/components/fileExplorer/help.ts, web/client/src/library/components/graph/Graph.tsx, web/client/src/library/components/search/SearchList.tsx, web/client/src/library/pages/ide/IDE.tsx, web/client/src/library/pages/ide/context.tsx, web/client/src/models/artifact.spec.ts, web/client/src/models/directory.spec.ts, web/client/src/models/directory.ts, web/client/src/models/file.ts, web/client/src/utils/index.ts, web/server/api/endpoints/files.py, web/server/models.py, web/server/watcher.py
=> Feat: sync file system via sse

sqlmesh/core/macros.py, tests/core/test_model.py
=> Fix(macros): incrementally resolve macro var definitions

docs/faq/faq.md
- How do I run SQLMesh models on a schedule?
- How do I use SQLMesh with Airflow?
=> Docs: Add scheduling questions to FAQ

mkdocs.yml
This is a very minor change to make it easier to access the various sqlmesh resources from any page on your docs website
=> Add repo and social links mkdocs.yml

setup.py, sqlmesh/core/model/meta.py, tests/core/test_model.py
Depends on: https://github.com/tobymao/sqlglot/pull/2010
=> Chore: bump sqlglot to v17.10.2

sqlmesh/core/macros.py, tests/core/test_macros.py
=> Feat: allow macro lambdas with expansion on tuples

docs/integrations/dbt.md
=> Docs: update dbt docs with full list of unsupported jinja methods

setup.py
The latest version of pandas, 2.1.0, has some breaking changes.
=> Chore: Pin pandas version

tests/web/test_main.py, web/client/openapi.json, web/client/src/api/index.ts, web/client/src/context/context.ts, web/client/src/library/pages/ide/IDE.tsx, web/client/src/library/pages/ide/RunPlan.tsx, web/client/src/models/environment.ts, web/server/api/endpoints/environments.py, web/server/models.py
=> Feat: Add pinned_environments/default_target_environment + ability to delete env

setup.py, sqlmesh/core/macros.py, tests/core/engine_adapter/test_mssql.py, tests/core/test_macros.py
Fixes a couple of incompatibilities caused by https://github.com/tobymao/sqlglot/commit/85ef892f7770a693ee3240e0697f3c4191d964a8
cc @treysp
=>  Chore: bump sqlglot, fix mssql tests and a couple of type hints 

docs/concepts/models/model_kinds.md
Without the newline the asterisks the bullets would not be created.
=> Docs: Fix SCD Type 2 Formatting

sqlmesh/integrations/github/cicd/controller.py, tests/integrations/github/cicd/test_github_controller.py
The CI/CD bot uses merge commits in order to both create it's PR environments and to do the deployments. These merge commits are a representation of both of what is currently in the PR and what is in main. This doesn't work though if there is currently a merge conflict between the branches. In order for sometime to hit this bug they would need to issue a `/deploy` command or provide a required approval while having a branch that has a merge conflict.
This change makes it so that we will detect a merge conflict and raise when attempting to do a deployment. 
I also put in a fix where users would see output from prior steps in their plan previews. This was because this output was captured and not cleared before generating the preview.
=> Fix: Github CI/CD bot and merge conflicts

sqlmesh/core/snapshot/definition.py, sqlmesh/schedulers/airflow/dag_generator.py, sqlmesh/utils/__init__.py
=> Fix: Sanitize model names before using them as part of Airflow task IDs

examples/sushi/audits/assert_item_price_above_zero.sql, sqlmesh/core/audit/__init__.py, sqlmesh/core/audit/definition.py, sqlmesh/core/console.py, sqlmesh/core/loader.py, sqlmesh/core/model/definition.py, sqlmesh/core/state_sync/common.py, sqlmesh/dbt/basemodel.py, sqlmesh/dbt/common.py, sqlmesh/dbt/loader.py, sqlmesh/dbt/manifest.py, sqlmesh/dbt/model.py, sqlmesh/dbt/test.py, sqlmesh/utils/jinja.py, tests/core/test_audit.py, tests/core/test_context.py, tests/core/test_integration.py, tests/dbt/test_config.py
Also allow configuration of sqlmesh specific fields (start, cron, stamp, etc.) for dbt singular tests
=> Feat: Add standalone audits to sqlmesh format

examples/sushi/tests/test_customer_revenue_by_day.yaml, examples/sushi/tests/test_order_items.yaml, examples/wursthall/tests/test_order_item_f.yaml, sqlmesh/core/test/definition.py, tests/core/test_integration.py
Had to also fix some of our tests because data were wrong types.
=> Fix: Use model's columns_to_types if available in tests

setup.cfg, setup.py, sqlmesh/core/config/scheduler.py, sqlmesh/core/plan/__init__.py, sqlmesh/core/plan/evaluator.py, sqlmesh/schedulers/airflow/client.py, sqlmesh/schedulers/airflow/mwaa_client.py, tests/core/test_plan_evaluator.py, tests/schedulers/airflow/test_mwaa_client.py
Going to update documentation in a follow-up PR.
=> Feat: Support plan applications with MWAA

sqlmesh/core/engine_adapter/base_postgres.py, sqlmesh/core/model/meta.py
=> Fix: allow udt DataType.building for dialects that support UDTs

sqlmesh/core/model/common.py, sqlmesh/core/model/definition.py, sqlmesh/core/model/kind.py, sqlmesh/core/model/meta.py, sqlmesh/core/model/seed.py, sqlmesh/migrations/v0026_fix_view_kind_data_hash.py, sqlmesh/migrations/v0026_remove_dialect_from_seed.py, tests/core/test_model.py, tests/core/test_seed.py
=> Feat!: Support CSV parser settings for seed models

sqlmesh/core/engine_adapter/bigquery.py, sqlmesh/core/node.py, sqlmesh/core/plan/definition.py, sqlmesh/core/snapshot/definition.py, sqlmesh/migrations/v0027_minute_interval_to_five.py, sqlmesh/utils/cron.py, sqlmesh/utils/date.py, tests/core/engine_adapter/test_bigquery.py, tests/core/test_model.py, tests/core/test_snapshot.py, tests/dbt/test_config.py
additional performance boosts
still need to add some tests and validate that this doesn't break existing minute level models
=> Feat!: add more interval units and make the smallest 5 minutes

sqlmesh/core/context.py, sqlmesh/core/plan/definition.py, sqlmesh/core/state_sync/base.py, sqlmesh/core/state_sync/engine_adapter.py, sqlmesh/schedulers/airflow/api.py, sqlmesh/schedulers/airflow/client.py, sqlmesh/schedulers/airflow/common.py, sqlmesh/schedulers/airflow/state_sync.py, tests/core/test_state_sync.py, tests/schedulers/airflow/test_client.py
=> Feat: Use the latest prod interval as an end date for dev plans

web/server/main.py
Ensure the correct content type for static files in the UI.
=> Chore: Specify MIME types for javascript and css files

sqlmesh/schedulers/airflow/api.py
this will allow users to use flask v1
=> Feat: support flask v1 via using route

setup.py, sqlmesh/core/dialect.py, tests/core/test_macros.py
In anticipation of https://github.com/tobymao/sqlglot/pull/2359...
=> Fix: update snowflake staged file code to match sqlglot

sqlmesh/cli/main.py, web/server/settings.py
Pass CLI parameters like config and gateway to the UI when launching the UI.
=> Chore: Pass CLI parameters to UI

sqlmesh/core/dialect.py, sqlmesh/core/engine_adapter/base.py, sqlmesh/core/engine_adapter/mixins.py, sqlmesh/core/model/common.py, sqlmesh/core/model/definition.py, sqlmesh/core/model/kind.py, sqlmesh/core/model/meta.py, tests/core/engine_adapter/test_base.py, tests/core/engine_adapter/test_bigquery.py, tests/core/engine_adapter/test_integration.py, tests/core/engine_adapter/test_mssql.py, tests/core/test_integration.py, tests/core/test_model.py, tests/core/test_snapshot_evaluator.py
=> Feat: accept expressions in unique key

sqlmesh/utils/cron.py, sqlmesh/utils/date.py, tests/utils/test_date.py
this solves an issue where dates between 1970 and 1972 are ambiguous.
=> Fix!: to_datetime now only accepts millis and not epoch seconds

sqlmesh/cli/main.py, web/server/settings.py
=> Fix: the way arguments are passed from CLI to UI

sqlmesh/core/engine_adapter/base.py, sqlmesh/core/engine_adapter/bigquery.py, sqlmesh/core/engine_adapter/snowflake.py, sqlmesh/core/engine_adapter/spark.py, tests/core/engine_adapter/test_integration.py
This fixes some of the integration test errors. Trey is looking into a MSSQL issue getting the current database.
=> Fix: empty schema and schema name parsing

tests/core/engine_adapter/test_integration.py
Thanks @treysp for pointing this out.
=> chore: fix debugging comment

sqlmesh/core/macros.py, sqlmesh/core/renderer.py, sqlmesh/core/snapshot/evaluator.py, tests/core/test_snapshot_evaluator.py
This is the first step towards adding support for the following pattern (it's still a WIP - will finish in a followup PR):
```sql
MODEL (...);
@IF(@runtime_stage = 'evaluating', <statement>);  -- only execute <statement> @ snapshot evaluation time
...
```
=> Feat: expose a macro var to check if we're evaluating snapshots

sqlmesh/core/console.py, sqlmesh/core/plan/evaluator.py, sqlmesh/core/scheduler.py, tests/core/test_scheduler.py, web/server/console.py
=> Chore: Report duration for each finished snapshot batch during evaluation

sqlmesh/core/model/definition.py, sqlmesh/core/model/meta.py, sqlmesh/schedulers/airflow/dag_generator.py, sqlmesh/schedulers/airflow/integration.py, sqlmesh/schedulers/airflow/operators/hwm_sensor.py, sqlmesh/utils/date.py, tests/core/test_model.py, tests/core/test_snapshot.py, tests/schedulers/airflow/operators/test_hwm_sensor.py, tests/schedulers/airflow/test_client.py
Docs will be updated in a follow-up PR.
=> Feat: Support sensors for external tables in Airflow

sqlmesh/integrations/github/cicd/controller.py
The check run API support both a `summary` and `text` and they both have a limit of `65535` characters. Therefore I try to put text into both of these and then truncate whatever might be left.
This does a naive split of the text therefore if the summary provided contained markdown we will likely not be outputted correctly. Depending on how common this is, we should consider having callers check their payload size and have a compacted output option.
=> fix: bot properly deal with truncated output

sqlmesh/utils/dag.py
This is just a sanity check that helps detecting infinite loops.
=> Chore: raise if we can't make progress when topo-sorting a DAG

docs/integrations/engines/duckdb.md, sqlmesh/core/config/connection.py, sqlmesh/core/engine_adapter/duckdb.py, tests/core/engine_adapter/config.yaml, tests/core/engine_adapter/test_integration.py, tests/dbt/test_adapter.py
Thanks for pointing this out @crericha!
=> feat: Add DuckDB Catalog Support

web/client/src/index.css, web/client/src/library/components/editor/Editor.css, web/client/src/library/components/editor/EditorFooter.tsx, web/client/src/library/components/editor/extensions/SQLMeshDialect.ts, web/client/src/library/components/graph/Graph.tsx
https://github.com/TobikoData/sqlmesh/assets/5644753/0138634c-e3f8-465f-8ee6-26f8db2ef868
it can not recognize alias and provide list of exact columns for a particular model instead it shows list of all columns. But it can be improved further with sqlglot
=> Feat: Add better autocomplete for models and columns

sqlmesh/dbt/basemodel.py, sqlmesh/dbt/common.py, sqlmesh/dbt/manifest.py, sqlmesh/dbt/source.py, sqlmesh/dbt/test.py, tests/dbt/test_config.py
Also remove residual QuotingConfig from before the switch to using the manifest.
=> Chore: Refactor to remove legacy QuotingConfig class

docs/concepts/models/sql_models.md
=> Chore: add a reference to the runtime stage in pre/post statement docs

docs/faq/faq.md, sqlmesh/core/model/definition.py, sqlmesh/core/renderer.py, tests/core/test_model.py
=> Fix!: allow partial schemas to display accurate missing schema warnings

web/client/src/library/components/graph/Graph.tsx, web/client/src/library/components/graph/context.tsx, web/client/src/library/components/graph/help.ts, web/client/src/library/components/search/SearchList.tsx, web/client/src/library/components/search/help.ts
=> Feat: Add filter for up/downstream models  in lineage

docs/reference/configuration.md, sqlmesh/core/config/scheduler.py, sqlmesh/schedulers/airflow/client.py, tests/schedulers/airflow/test_client.py
Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1700478613060759
=> Fix: Batch up snapshot IDs when sending them to the Airflow Webserver as part of a GET request

sqlmesh/schedulers/airflow/integration.py
For scenarios when users want to manually update data through plans or want to run `sqlmesh run` themselves elsewhere.
=> Feat: Add ability to disable generation of cadence DAGs in Airflow

examples/sushi/models/raw_marketing.py, setup.py, sqlmesh/core/engine_adapter/redshift.py, tests/core/engine_adapter/config.yaml, tests/core/engine_adapter/spark/conf/spark-defaults.conf, tests/core/engine_adapter/test_integration.py, tests/core/engine_adapter/test_redshift.py
I also updated the new project integration test (thanks again @treysp!) to also do a run dag to expose issues like this one.
Edit: Removed the adding of dag since it caused weird fatal errors when running locally. Will look to add it back later.
=> fix: make redshift late binding again

Makefile
UI artifacts need to be built first to get picked up by the wheel.
=> Fix: Build UI before wheel

web/client/src/library/components/editor/Editor.tsx, web/client/src/library/components/editor/EditorFooter.tsx, web/client/src/library/components/input/Selector.tsx, web/client/src/library/pages/ide/RunPlan.tsx, web/server/api/endpoints/plan.py
Dropdown bug
display error if user `uncheck` include_unmodified option
=> Fix: Dialect dropdown + include_unmodified

sqlmesh/core/macros.py, tests/core/test_macros.py
=> fix: macros resolution inside lambdas

sqlmesh/cicd/bot.py, sqlmesh/cli/main.py
These might have been used for debugging while in development.
=> Chore: Remove the ability to run CLI files as scripts

sqlmesh/core/engine_adapter/trino.py, tests/core/engine_adapter/test_trino.py
=> Fix: Trino Set Catalog Typo

sqlmesh/core/context.py, sqlmesh/core/loader.py
I expect this to significantly help with performance.
=> fix: cache default catalog

sqlmesh/core/dialect.py, sqlmesh/core/engine_adapter/base.py, sqlmesh/utils/pandas.py
Mostly stolen from @treysp's PR in order to fix build: https://github.com/TobikoData/sqlmesh/pull/1878
=> chore: fix typing latest pandas-stub

sqlmesh/core/engine_adapter/base.py, sqlmesh/core/engine_adapter/base_postgres.py, sqlmesh/core/engine_adapter/bigquery.py, sqlmesh/core/engine_adapter/databricks.py, sqlmesh/core/engine_adapter/duckdb.py, sqlmesh/core/engine_adapter/mixins.py, sqlmesh/core/engine_adapter/mssql.py, sqlmesh/core/engine_adapter/redshift.py, sqlmesh/core/engine_adapter/shared.py, sqlmesh/core/engine_adapter/snowflake.py, sqlmesh/core/engine_adapter/spark.py, sqlmesh/core/engine_adapter/trino.py, sqlmesh/core/snapshot/evaluator.py, tests/core/engine_adapter/test_base.py, tests/core/engine_adapter/test_mssql.py, tests/core/test_snapshot_evaluator.py
No logic changes just moving classes around
=> chore: move shared objects to shared.py

docs/concepts/glossary.md, docs/guides/configuration.md, examples/sushi/config.py, sqlmesh/core/config/root.py, sqlmesh/core/context.py, sqlmesh/core/engine_adapter/shared.py, sqlmesh/core/environment.py, sqlmesh/core/plan/definition.py, sqlmesh/core/snapshot/definition.py, sqlmesh/core/state_sync/common.py, sqlmesh/core/state_sync/engine_adapter.py, sqlmesh/migrations/v0035_add_catalog_name_override.py, sqlmesh/schedulers/airflow/dag_generator.py, tests/core/test_config.py, tests/core/test_environment.py, tests/core/test_integration.py, tests/core/test_snapshot.py, tests/core/test_state_sync.py, tests/schedulers/airflow/test_plan.py
Adds support for changing the catalog used for an environment schema based on a regex pattern.
=> feat!: Add config for view catalog

sqlmesh/core/context.py, sqlmesh/core/plan/evaluator.py, tests/web/test_main.py, web/server/api/endpoints/commands.py, web/server/api/endpoints/plan.py, web/server/main.py
This PR uses circuit breaker to halt a backfill in the UI.
=> Fix: Cancel apply in UI

web/client/src/context/context.ts, web/client/src/index.css, web/client/src/library/components/banner/Banner.tsx, web/client/src/library/components/input/Selector.tsx, web/client/src/library/components/plan/Plan.tsx, web/client/src/library/components/plan/PlanActions.tsx, web/client/src/library/components/plan/PlanActionsDescription.tsx, web/client/src/library/components/plan/PlanApplyStageTracker.tsx, web/client/src/library/components/plan/PlanBackfillDates.tsx, web/client/src/library/components/plan/PlanChangePreview.tsx, web/client/src/library/components/plan/PlanHeader.tsx, web/client/src/library/components/plan/PlanOptions.tsx, web/client/src/library/components/plan/context.tsx, web/client/src/library/components/report/ReportErrors.tsx, web/client/src/library/components/tasksOverview/TasksOverview.tsx, web/client/src/library/pages/ide/IDE.tsx, web/client/src/library/pages/ide/RunPlan.tsx, web/client/src/library/pages/ide/context.tsx, web/client/src/models/plan-action.ts, web/client/src/models/sqlmesh-model.ts, web/client/src/models/tracker-plan-apply.ts, web/client/tailwind.config.js
simplifies Plan Interface a bit 
https://github.com/TobikoData/sqlmesh/assets/5644753/8f3ddfa4-90a8-4355-9ca6-1f350b1a0491
=> Fix:  Update overview stage

sqlmesh/migrations/v0034_add_default_catalog.py
BQ requires a where expression when doing updates
=> fix: catalog migration BigQuery

sqlmesh/core/console.py, sqlmesh/core/context.py, sqlmesh/core/snapshot/evaluator.py, sqlmesh/core/state_sync/common.py
Basic implementation which reports the name of each deleted object.
=> Chore: Report the progress of the janitor process

tests/web/test_main.py, web/server/api/endpoints/models.py, web/server/watcher.py
Also make query rendering optional.
=> Feat: Add get model endpoint.

sqlmesh/__init__.py, sqlmesh/core/console.py
Debugging in the terminal using something like pdb is a nightmare. Lets make it nicer. 
Setting `SQLMESH_DEBUG=1 sqlmesh ...` will make our lives much easier!
=> Feat: add a debugger friendly console mode

tests/web/test_main.py, web/server/api/endpoints/lineage.py
- Missing schema for external models.
- Missing dialect for parsing table names.
- Handle models with managed columns.
=> Fix: Various UI lineage issues

web/server/api/endpoints/files.py, web/server/watcher.py
Fixing: https://github.com/TobikoData/sqlmesh/issues/2006
=> Fix: Set warning when getting file content results in error

sqlmesh/core/engine_adapter/databricks.py
Looks like Unity and some Databricks cluster configurations can throw exceptions on get current catalog in addition to set current catalog. So now we will check for exceptions on both and fallback to SQL.
=> fix: databricks get catalog unity exception

tests/core/engine_adapter/test_integration.py
The `customer_revenue_by_day` sushi model contains a column name with a space, and Databricks errors unless the table property `delta.columnMapping.mode = 'name'` is set.
Other engines error if that table property is in the model DDL, so this PR conditionally sets it for Databricks in the sushi integration test.
Closes #2026
=> Chore: allow spaces in column names for databricks sushi test

web/client/src/library/components/editor/Editor.tsx, web/client/src/library/components/editor/EditorInspector.tsx, web/client/src/library/components/tableDiff/TableDiff.tsx
Show all values for deleted rows
=> Fix: Show all value for deleted rows (table-diff)

web/client/src/App.tsx, web/client/src/library/components/graph/ModelLineage.tsx, web/client/src/library/components/graph/ModelLineageSearch.tsx, web/client/src/library/components/graph/help.ts, web/client/src/library/components/search/SearchList.tsx, web/client/src/workers/lineage.ts
when selecting model, lineage component displays model search bar with list of models already pre-loaded. It slows things down and actually not needed before user starts typing
=> Fix: Improve perf by lazily loading list of models for lineage

sqlmesh/schedulers/airflow/dag_generator.py
In order to help reduce the change of character limits when sending stats in Airflow for tasks, we are switching to model name instead of snapshot name for the task ids. We also truncate the tag model name to the max characters to ensure users don't get an error when defining this non-functional tag.
=> fix: airflow use model name instead of snapshot name

sqlmesh/schedulers/airflow/dag_generator.py
This is what I get for not running the Airflow tests 🤦
=> chore: use node for name instead of model

web/client/src/context/editor.ts, web/client/src/library/components/editor/Editor.tsx, web/client/src/library/components/editor/EditorCode.tsx, web/client/src/library/components/editor/EditorFooter.tsx, web/client/src/library/components/editor/extensions/SQLMeshDialect.ts
Disable default settings for autocompletion package for codemirror and define it manually.
=> Fix: Control autocompletion manually

web/client/src/library/components/button/Button.tsx, web/client/src/library/components/plan/Plan.tsx, web/client/src/library/components/plan/PlanActions.tsx, web/client/src/library/pages/docs/Content.tsx, web/client/src/library/pages/plan/Plan.tsx, web/client/src/library/pages/root/Page.tsx
=> Feat: Use sidebar for module navigation icons

web/client/src/index.css, web/client/src/library/components/graph/Graph.tsx, web/client/src/library/components/graph/ModelLineage.tsx, web/client/src/library/components/graph/ModelLineageDetails.tsx, web/client/src/library/components/graph/ModelNode.tsx, web/client/src/library/components/graph/context.tsx, web/client/src/library/components/graph/help.ts, web/client/src/library/components/logo/Spinner.tsx, web/client/src/library/components/search/SearchList.tsx, web/client/tailwind.config.js
- Rename lineage details
- Handle duplicates 
- Add reset for current model lineage
- Center `selected model node` on clicking model name
=> Fix: Improve lineage flow

web/client/src/App.tsx, web/client/src/context/context.ts
https://github.com/TobikoData/sqlmesh/assets/5644753/19b9143f-ac96-4fb9-8537-3ff7cdc5b62d
=> Fix: Synchronize selected environment in all tabs

tests/web/conftest.py, tests/web/test_lineage.py, tests/web/test_main.py, web/server/api/endpoints/lineage.py, web/server/models.py
This PR
- Normalizes table names so the UI can correctly match them with their model's fqn.
- Handles the cases where a lineage node's expression are unions and CTEs.
=> Fix: Lineage 

sqlmesh/core/dialect.py, tests/core/test_dialect.py
Related Slack thread: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1708432374934119
=> Fix: restrict scope of sqlmesh statement parsers

docs/quickstart/cli.md, docs/quickstart/notebook.md, docs/quickstart/ui.md, sqlmesh/cli/example_project.py, tests/cli/test_cli.py, tests/core/engine_adapter/test_integration.py
=> Feat: update init example project to run on all engines

sqlmesh/dbt/builtin.py, tests/dbt/test_transformation.py
=> Fix: Add support for the dbt's 'var.has_var()' expression

sqlmesh/dbt/model.py, tests/dbt/test_transformation.py
Support for https://docs.getdbt.com/reference/resource-configs/snowflake-configs#configuring-virtual-warehouses
=> Feat: Support the Snowflake Warehouse model config for dbt projects

web/client/src/index.css, web/client/src/library/components/editor/Editor.css, web/client/src/library/components/editor/EditorPreview.tsx, web/client/src/library/components/graph/Graph.css, web/client/src/library/components/graph/Graph.tsx, web/client/src/library/components/graph/ModelLineage.tsx, web/client/src/library/components/graph/ModelNode.tsx, web/client/src/library/components/graph/context.tsx, web/client/src/library/components/graph/help.ts, web/client/src/library/components/plan/PlanChangePreview.tsx, web/client/tailwind.config.js
fixing colors and other styling for lineage nodes, to maintain visual consistency
=> Fix: Clean up lineage styling

sqlmesh/core/state_sync/common.py, tests/core/test_state_sync.py
In the case when a BREAKING snapshot has been superseded by an INDIRECT_NON_BREAKING snapshot which in turn has been subsequently replaced by a FORWARD_ONLY snapshot, we end up in a situation when the original snapshot has already been paused (because of the INDIRECT_NON_BREAKING update) but the `unrestorable` flag is not set for it despite the newest update being `FORWARD_ONLY`.
=> Fix: Set the 'unrestorable' flag even when the snapshot has already been paused

sqlmesh/core/test/definition.py, tests/core/test_test.py
Partially addresses of the fourth item in https://github.com/TobikoData/sqlmesh/issues/1637
=> Feat: add support for arrays in unit tests

docs/reference/model_configuration.md
And expand seed model properties
=> Docs: clarify which general properties apply to which kinds in model configuration reference

sqlmesh/core/engine_adapter/redshift.py
When a query involves window functions, Redshift would extend the plan with additional projections for the exclusive purpose of helping it compute the return value.
In this case the name of the projection is set to `<>`. This update makes sure that we skip these columns.
=> Fix: Support syntethic projections added to the plan by redshift

sqlmesh/core/test/definition.py, tests/core/test_test.py
Addresses the fifth item in #1637 and improves the way SQLMesh handles invalid columns in expected outputs. The name `partial` may change - some alternatives we're considering are `partial_columns` and `col_subset`.
Will update the documentation to add this, unit test descriptions & nested data type support soon.
=> Feat: allow partial unit test expected column sets, improve error handling

setup.cfg, setup.py
Dependency is no longer needed after https://github.com/TobikoData/sqlmesh/pull/2254
=> chore: remove fsspec dependency

docs/integrations/engines/mssql.md, sqlmesh/core/config/connection.py
By making user and password fields optional for MSSQL connection config
Closes #2258
=> Feat: support MSSQL Windows Authentication 

.circleci/continue_config.yml
Decided to leave other tests as-is for now but testing out scaling up our slow tests which take up most of the time.
=> chore: scale up slow tests

.circleci/config.yml
Missed this step in this PR: https://github.com/TobikoData/sqlmesh/pull/2270
=> chore: add pypirc command

tests/core/test_context.py
Can create flakiness in tests with these tests sharing cache without proper isolation.
=> chore: isolate context in context tests

sqlmesh/core/model/definition.py
This way users can manually include "self" as part of the `depends_on` attribute which would signal the desire to opt into the `depends_on_past` behavior.
=> Fix: Consider the depends_on property provided by a user when determining whether a model depends on the past

web/client/src/context/project.ts, web/client/src/library/components/documentation/Documentation.tsx, web/client/src/library/components/fileExplorer/context.tsx, web/client/src/library/components/plan/help.spec.ts, web/client/src/models/artifact.posix.spec.ts, web/client/src/models/artifact.ts, web/client/src/models/artifact.win.spec.ts, web/client/src/models/directory.posix.spec.ts, web/client/src/models/directory.ts, web/client/src/models/directory.win.spec.ts, web/client/src/utils/index.ts
Fixing [this](https://github.com/TobikoData/sqlmesh/issues/2309) issue
- file content not loading (on windows)
=> Fix: Do not modify file/model path on UI

sqlmesh/core/dialect.py, sqlmesh/core/engine_adapter/base.py, sqlmesh/core/test/definition.py, tests/core/engine_adapter/test_base.py, tests/core/engine_adapter/test_databricks.py, tests/core/engine_adapter/test_redshift.py, tests/core/test_test.py
Still a WIP, a refactor is under way for this. Expecting to have an MVP soon.
=> Feat: add support for YAML dictionaries in unit tests

sqlmesh/core/model/kind.py
Minor cleanup to store dialect in a variable instead of getting it twice.
=> chore: cleanup dialect variable reuse

docs/concepts/macros/sqlmesh_macros.md
=> Fix typo in sqlmesh_macros.md

docs/reference/cli.md, sqlmesh/cli/main.py, sqlmesh/core/context.py, sqlmesh/magics.py, tests/cli/test_cli.py, tests/integrations/jupyter/test_magics.py
Adding a new CLI command to help figure out the name of the physical table given a model name. The local model snapshot is used for this purpose.
=> Feat: A CLI command to print the name of the physical table for a model

docs/reference/cli.md, docs/reference/notebook.md
Updated to match the current `--help` output.
=> Chore: update CLI command reference

docs/concepts/models/overview.md, docs/concepts/models/python_models.md, docs/quickstart/cli.md, docs/quickstart/ui.md
=> Docs: add model DDL columns example 

setup.py, sqlmesh/core/test/definition.py, tests/core/test_test.py
This PR depends on https://github.com/tobymao/sqlglot/pull/3241.
=> Fix!: Handle maps during test generation

sqlmesh/core/state_sync/engine_adapter.py
Sometimes migrated snapshots map to other snapshots that already exist in the state. If we don't check the existence of rows first, we'd violate the primary key constraint.
=> Fix: Only insert new seed rows during migration

docs/guides/incremental_time.md, docs/guides/table_migration.md, mkdocs.yml
=> Docs: add table migration guide

sqlmesh/core/model/definition.py, tests/core/test_model.py
https://github.com/TobikoData/sqlmesh/issues/2413
=> chore: add error message for untyped self references

sqlmesh/migrations/v0045_move_gateway_variable.py
This migration script should've been a part of #2391
=> Fix!: Add the missing migration script for the gateway variable

.circleci/continue_config.yml, .circleci/test_migration.sh, sqlmesh/cli/main.py, sqlmesh/core/context.py
Test steps:
1. Check out the previous release.
2. Initialize the SQLMesh state by running the `plan` command against the prod environment.
3. Switch back to the original state of the git repo.
4. Migrate
5. Make sure there are no differences when comparing the local project state with prod.
=> Chore: Add a script for testing the migration

sqlmesh/core/test/definition.py, tests/core/test_config.py, tests/core/test_test.py
=> Fix: convert NaN and NaT to None for test generation

sqlmesh/core/context.py, tests/core/test_context.py
=> Fix!: generate table name using default dialect

setup.py
=> Chore: Bump FastAPI version

setup.py, sqlmesh/core/dialect.py, tests/core/test_dialect.py
=> fix!: improve sqlmesh format closes #2469

docs/concepts/glossary.md, docs/concepts/plans.md
Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1713544991466839
=> chore: update docs summarize change behavior

sqlmesh/core/model/definition.py, sqlmesh/core/renderer.py, tests/core/test_model.py
additionally only cache queries with no arguments since it's getting complicated caching everything
=> feat: add this_model var to model statements

sqlmesh/schedulers/airflow/client.py, sqlmesh/schedulers/airflow/common.py, sqlmesh/schedulers/airflow/plan.py, tests/schedulers/airflow/test_client.py, tests/schedulers/airflow/test_plan.py
=> Fix: Support for plans with restatements when using the Airflow REST extension

web/server/main.py
FastAPI is deprecating startup and shutdown events in favor of a lifespan function.
=> Chore: Use FastAPI's lifespan function

sqlmesh/core/loader.py, sqlmesh/core/model/seed.py, sqlmesh/integrations/github/cicd/controller.py, sqlmesh/magics.py, sqlmesh/schedulers/airflow/operators/databricks.py, sqlmesh/schedulers/airflow/operators/spark_submit.py, tests/cli/test_cli.py, tests/core/test_config.py, tests/core/test_connection_config.py, tests/core/test_model.py, tests/core/test_schema_loader.py, tests/core/test_snapshot.py, tests/dbt/test_config.py, tests/dbt/test_integration.py, tests/dbt/test_transformation.py, tests/integrations/github/cicd/test_github_commands.py, tests/integrations/github/cicd/test_integration.py
Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1713874907674759
=> Fix: set utf-8 encoding in most open calls

sqlmesh/core/state_sync/engine_adapter.py
Seed records don't need to be migrated
=> Fix: Don't push seed records when migrating snapshot rows

sqlmesh/core/config/connection.py
Standardizing this as a separate property instead of creating it within the create engine adapter call.
=> chore: make connection factory property with kwargs

docs/concepts/models/python_models.md, docs/guides/configuration.md, docs/reference/model_configuration.md, examples/sushi/models/items.py, examples/sushi/models/order_items.py, examples/sushi/models/orders.py, examples/sushi/models/raw_marketing.py, examples/sushi/models/waiters.py, sqlmesh/core/model/decorator.py, tests/core/test_model.py
=> Feat: @model decorator `kind` arg should be passed a dict

docs/integrations/engines/duckdb.md
Docs for this feature: https://github.com/TobikoData/sqlmesh/pull/2565
=> chore: add documentation for new duckdb catalog options

tests/web/test_lineage.py, web/server/api/endpoints/lineage.py
If different models happen to have CTEs or derived tables with the same name, lineage would incorrectly group them into the same node.
=> Fix: Prepend model name to CTE and derived table node names

sqlmesh/core/test/definition.py, tests/core/test_test.py
=> Refactor: clean up some sections in the unit test module

docs/reference/notebook.md, mkdocs.yml
...and add back to top button when users start scrolling back up a page
https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
=> Docs: Add note about vscode widgets and ipywidgets version

sqlmesh/core/config/connection.py
Add user agent to both Databricks Python SQL connector and Databricks Connect.
=> chore: add user agent to databricks connections

setup.py
Context: https://github.com/duckdb/duckdb/issues/12191
=> Chore: Exclude the 0.10.3 duckdb release

sqlmesh/core/state_sync/engine_adapter.py, tests/core/test_state_sync.py
Otherwise the query might get too large due to all interval IDs that get passed into it.
=> Fix: Delete intervals in batches during compaction

sqlmesh/core/engine_adapter/mixins.py, sqlmesh/core/engine_adapter/mssql.py, sqlmesh/core/engine_adapter/redshift.py, tests/core/engine_adapter/test_mssql.py, tests/core/engine_adapter/test_redshift.py
=> Fix: For MSSQL apply the same workaround for the varchar size as we use for Redshift

docs/reference/configuration.md
updating the SQLMesh UI settings in the docs to match the code [here](
https://github.com/TobikoData/sqlmesh/blob/0639bf892ae9218dd7216d2afdda7eb07efedc7e/sqlmesh/core/config/ui.py#L13)
=> Chore: update docs for ui formatter option

sqlmesh/core/macros.py, tests/core/test_macros.py, tests/core/test_state_sync.py
=> Fix: ensure MacroEvaluator.columns_to_types returns types as DataTypes

web/server/models.py
This should resolve the Pydantic deprecation warnings in our tests.
=> Chore: Update UI models to subclass PydanticModel

sqlmesh/core/model/meta.py, tests/core/test_model.py
=> Fix: normalize column names in column_descriptions dict

sqlmesh/core/model/definition.py, tests/core/test_model.py
Previously we didn't extract referenced variables because the `python_env` has already been formed and passed from upstream.
=> Fix: Detection of referenced variables in Python SQL models

setup.py
This should unblock https://github.com/TobikoData/sqlmesh/pull/2749, cc @bobbyiliev
=> Chore: bump sqlglot to v25.0.3

sqlmesh/integrations/github/cicd/controller.py, tests/integrations/github/cicd/test_github_commands.py, tests/integrations/github/cicd/test_integration.py
Just makes the text look more consistent.
=> fix: cicd bold verb like other bullet

setup.py
PR where this was added: https://github.com/TobikoData/sqlmesh/pull/2666
=> chore: remove snowpark dev dependency

docs/guides/scheduling.md, docs/integrations/airflow.md, docs/integrations/engines/mssql.md, sqlmesh/schedulers/airflow/operators/mssql.py, sqlmesh/schedulers/airflow/util.py
adding support for microsoft mssql in the airflow scheduler.
=> add mssql support for airflow

sqlmesh/core/console.py, sqlmesh/core/state_sync/engine_adapter.py
This improvement introduces a separate progress bar in the CLI for environment migration., fixes #2738 
New output message:
```
Migrating snapshots ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.0% • 4/4 • 0:00:00
All snapshots have been migrated successfully.
Migrating environments ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.0% • 1/1 • 0:00:00
All environments have been migrated successfully.
The migration has been completed successfully.
```
=> Feat: Add environment migration progress bar

setup.py, sqlmesh/core/engine_adapter/mixins.py, sqlmesh/core/model/definition.py
Thought I'd post this early, need to deploy sqlglot first. Probably in a few days..
Context: https://github.com/tobymao/sqlglot/commit/468123e4b7612287e128529de62f3a88f4e1d579
=> Chore!: bump sqlglot to v25.2.0

sqlmesh/core/config/scheduler.py, sqlmesh/schedulers/airflow/client.py, tests/schedulers/airflow/test_client.py
This enables support for Airflow cloud providers like Astronomer.
=> Feat: Support token authentication for Airflow REST API

sqlmesh/core/model/kind.py, tests/core/test_model.py, tests/integrations/github/cicd/test_integration.py
This greatly impacts the quality of the diffs that SQLMesh prints out when presenting a plan.
=> Fix: Make sure to render all model kind attributes

sqlmesh/core/snapshot/evaluator.py, tests/core/test_snapshot_evaluator.py
In the managed strategy, the dev preview table is always a normal table, so drop it using a normal DROP TABLE command.
=> Fix: Drop dev previews of managed tables correctly

examples/sushi_dbt/models/schema.yml, examples/sushi_dbt/models/top_waiters.sql, examples/sushi_dbt/models/waiter_revenue_by_day_v1.sql, sqlmesh/dbt/basemodel.py, sqlmesh/dbt/builtin.py, sqlmesh/dbt/context.py, sqlmesh/dbt/manifest.py, tests/dbt/test_manifest.py, tests/fixtures/dbt/sushi_test/models/schema.yml, tests/fixtures/dbt/sushi_test/models/waiter_revenue_by_day_v1.sql
Introduces support for the dbt model versioning feature as described here: https://docs.getdbt.com/docs/collaborate/govern/model-versions
=> Feat: Support dbt model versioning

docs/concepts/tests.md, sqlmesh/core/context.py, sqlmesh/core/test/__init__.py, sqlmesh/core/test/discovery.py, sqlmesh/utils/yaml.py, tests/core/test_test.py
=> Feat: add support for parameterization of model names in unit tests

sqlmesh/core/macros.py, tests/core/test_macros.py
Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1720460653564549?thread_ts=1720454069.814999&cid=C044BRE5W4S
=> Fix: normalize excluded columns in STAR macro, fix except_ logging

docs/concepts/models/python_models.md
Context: https://github.com/TobikoData/sqlmesh/issues/2885
=> Chore: update python model docs to include audit example

sqlmesh/core/dialect.py, tests/core/test_macros.py
=> Fix: Using macros with IGNORE NULLS

docs/concepts/models/managed_models.md
Clarify the downside of using normal tables for dev previews of managed tables
=> Chore!: Update managed table docs

docs/concepts/macros/sqlmesh_macros.md
=> Docs: fix lists in sqlmesh macros concepts

sqlmesh/core/snapshot/evaluator.py, tests/core/test_snapshot_evaluator.py
Prior to this change we always did a check on the table's database against the physical schema as a safety check to avoid deleting tables outside of where we expect to delete tables. This logic though assumes the following `evaluation_strategy.delete` call actually does a delete. This isn't true for symbolic evaluations. Therefore we had a bug where users could get errors when their symbolic models would expire and it would say it was going to delete outside of the scope of the physical db but that wasn't really the case since the actual delete was a no-op. 
Since the Evaluation Strategy is responsible for determining what deletes are actually happening, I push this check down to the strategy implementation layer. Now for deletes that do nothing there will not be a check and therefore …
=> fix: remove error when deleting expired external model snapshots

sqlmesh/core/renderer.py, tests/core/test_model.py
Addresses one of the items mentioned in https://tobiko-data.slack.com/archives/C044BRE5W4S/p1723562831081849
=> Feat: allow returning >1 statements using macros

docs/concepts/models/python_models.md
Update docs with the added functionality of pre/post statements for python models
=> Docs: Update python pre/post statements example

sqlmesh/core/state_sync/engine_adapter.py, tests/core/test_state_sync.py
=> Fix: Exponentially multiplying removed interval records

sqlmesh/core/model/cache.py, sqlmesh/core/snapshot/cache.py, sqlmesh/core/snapshot/definition.py, sqlmesh/core/state_sync/engine_adapter.py, sqlmesh/utils/cache.py, tests/core/test_integration.py, tests/core/test_snapshot.py, tests/core/test_state_sync.py
This update introduces a file cache for snapshots fetched from the state, which should significantly speed up plan generation time.
=> Chore!: Introduce the snapshot cache to the state sync

setup.py, sqlmesh/core/engine_adapter/base.py, sqlmesh/core/schema_diff.py, sqlmesh/core/snapshot/evaluator.py, sqlmesh/migrations/v0004_environmnent_add_finalized_at.py, sqlmesh/migrations/v0011_add_model_kind_name.py, sqlmesh/migrations/v0015_environment_add_promoted_snapshot_ids.py, sqlmesh/migrations/v0019_add_env_suffix_target.py, sqlmesh/migrations/v0032_add_sqlmesh_version.py, sqlmesh/migrations/v0033_mysql_fix_blob_text_type.py, sqlmesh/migrations/v0035_add_catalog_name_override.py, sqlmesh/migrations/v0038_add_expiration_ts_to_snapshot.py, sqlmesh/migrations/v0040_add_previous_finalized_snapshots.py, sqlmesh/migrations/v0052_add_normalize_name_in_environment_naming_info.py, sqlmesh/migrations/v0055_add_updated_ts_unpaused_ts_ttl_ms_unrestorable_to_snapshot.py
Context around `exp.AlterTable -> exp.Alter`: https://github.com/tobymao/sqlglot/commit/0428c37e11f42be8eba352e69c1d2e7425824d38
=> Chore!: bump sqlglot to v25.14.0

docs/concepts/macros/sqlmesh_macros.md
Context: https://github.com/TobikoData/sqlmesh/issues/2900
=> Docs: document unavailable schema placeholder for sqlmesh macros

sqlmesh/utils/metaprogramming.py, tests/utils/test_metaprogramming.py
=> Fix: handle metaprogramming inspect.getfile TypeError

docs/reference/cli.md, docs/reference/notebook.md, sqlmesh/cli/main.py, sqlmesh/magics.py, tests/cli/test_cli.py
=> Feat: dry run flag alias

docs/reference/cli.md, docs/reference/notebook.md, sqlmesh/cli/main.py, sqlmesh/core/context.py, sqlmesh/magics.py, tests/core/test_format.py
Adds a `--check` flag to `sqlmesh format`
=> feat: format check

sqlmesh/core/dialect.py, tests/core/test_macros.py
=> fix: Allow macros in set operations

sqlmesh/cli/main.py, web/docker-compose.yml, web/server/app.py
Missed in this PR since they are dynamically referenced: https://github.com/TobikoData/sqlmesh/pull/3126
=> fix: have ui be loadable again

docs/concepts/audits.md
https://github.com/TobikoData/sqlmesh/blob/36e9ebbce74cbb2fa757669056f5484e8c61504c/sqlmesh/core/constants.py#L60
=> docs: fix folder name

setup.py, sqlmesh/core/dialect.py, sqlmesh/core/test/definition.py, sqlmesh/dbt/target.py, tests/core/test_test.py
=> Fix!: recursively transform dataframe values when converting to a query

sqlmesh/core/renderer.py
=> fix: catch optimize errors and log path

sqlmesh/core/constants.py
Reverts TobikoData/sqlmesh#3140
=> Revert "Fixed daemon detection to determine forking behavior"

docs/integrations/engines/bigquery.md, sqlmesh/core/config/connection.py, tests/core/test_connection_config.py
=> Support for BigQuery quota project

sqlmesh/core/engine_adapter/bigquery.py, tests/core/engine_adapter/test_bigquery.py
=> Fix(bigquery): fix BQ materialized view column comments

sqlmesh/core/dialect.py, sqlmesh/core/macros.py, sqlmesh/core/model/definition.py, sqlmesh/core/renderer.py, tests/core/test_model.py
We don't currently support parameterized python models, i.e. whose names contain variables. This PR adds support for them.
=> Feat: add support for parameterized python model names

sqlmesh/core/loader.py
=> fix: web reloading caused iteration error

.circleci/continue_config.yml, setup.py, sqlmesh/core/engine_adapter/athena.py, sqlmesh/dbt/target.py, tests/core/engine_adapter/integration/test_integration_athena.py, tests/dbt/test_config.py
Initial support for [dbt-athena](https://github.com/dbt-labs/dbt-athena)
ref issue #1315
=> Feat: Support DBT Athena adapter

web/server/settings.py
When the SQLMesh UI is running in multiple browser windows/tabs, concurrent access to the SQLMesh context could cause errors. There was previously a lock on context creation, but that was not enough. This PR locks the SQLMesh context for the duration of the request for endpoints that use it.
=> Fix: Prevent loaded context from being used concurrently

sqlmesh/core/config/gateway.py, sqlmesh/core/config/root.py, sqlmesh/core/config/scheduler.py, tests/core/test_config.py
This makes it easier to add support for new schedulers with custom configurations.
=> Chore: Make the scheduler config extendable

web/client/package-lock.json, web/client/package.json, web/client/src/library/components/documentation/Documentation.tsx
This feature adds markdown capabilities to the description field enabling among other things:
* Multiline
* Code blocks and code (triple and single backtick enclosing)
* Bolding
Markdown features that are not currently working with this:
* Headers
* Ordered and unordered lists
* Italicizing
=> Adding markdown feature to model description

sqlmesh/core/engine_adapter/mixins.py, sqlmesh/core/engine_adapter/postgres.py, tests/core/engine_adapter/test_postgres.py
Support for Merge statement has only been introduced in Postgres 15.
=> Fix: Support merging for Postgres version < 15

sqlmesh/core/context.py
Custom materializations break `migrate` unless you load them for `Snapshot.parse_obj` which calls `_validate_materialization`.
```
2024-10-24 18:32:34,076 - MainThread - sqlmesh.cli - ERROR - Unhandled exception (__init__.py:57)
File "<redacted>/lib/python3.12/site-packages/sqlmesh/core/state_sync/engine_adapter.py", line 1223, in migrate
self._migrate_rows(promoted_snapshots_only)
File "<redacted>/lib/python3.12/site-packages/sqlmesh/core/state_sync/engine_adapter.py", line 1321, in _migrate_rows
snapshot_mapping = self._migrate_snapshot_rows(snapshots_to_migrate)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<redacted>/lib/python3.12/site-packages/sqlmesh/core/state_sync/engine_adapter.py", line 1473, in _migrate_snapshot_rows …
```
=> Fix: correctly handle snapshot serde during migrate

.circleci/continue_config.yml, .circleci/get_scm_version.py
Also updated logic to use setuptools_scm for the version instead of manually calculating it.
=> chore: fix missing comma in private test trigger

sqlmesh/core/console.py
- make the tables plural as can be creating many
=> fix: small typo in output

sqlmesh/core/model/definition.py, tests/core/test_model.py
=> Fix: Support passing variables into python models as kw-only arguments

docs/reference/cli.md, docs/reference/notebook.md, sqlmesh/cli/main.py, sqlmesh/core/test/definition.py, sqlmesh/magics.py, tests/core/test_test.py
=> Feat: add support for recursive CTEs in unit tests

docs/concepts/models/model_kinds.md
Make it easy for people to take advantage of this powerful model kind. Should be an easy copy and paste template to then iterate from.
=> clear incremental by partition example

sqlmesh/core/lineage.py, web/server/api/endpoints/models.py
=> Fix: quote columns before fetching their descriptions in the UI

sqlmesh/core/dialect.py, tests/core/test_model.py
Context: https://tobiko-data.slack.com/archives/C07HJH22U9Z/p1732102445585029
=> Feat: allow parameterizing model kinds using macros

sqlmesh/core/scheduler.py
Missed this when doing this refactor: https://github.com/TobikoData/sqlmesh/pull/3405
=> fix: ensure execution time is set

docs/examples/incremental_time_full_walkthrough.md
This video is resonating with people, so let's make it part of the official docs to easily discover.
=> Add Video Example

sqlmesh/core/engine_adapter/bigquery.py, sqlmesh/core/engine_adapter/mixins.py, sqlmesh/core/table_diff.py, tests/core/engine_adapter/integration/test_integration_bigquery.py
=> Feat: add support for comparing nested BigQuery values (structs, arrays)

sqlmesh/core/renderer.py, tests/core/test_model.py
=> Fix!: store a Table in @this_model var instead of its str representation

web/client/package-lock.json, web/client/package.json, web/client/src/api/channels.ts, web/client/src/api/instance.ts, web/client/src/library/components/graph/help.ts, web/client/src/routes.tsx, web/client/src/types/index.d.ts, web/client/src/workers/index.ts, web/client/src/workers/sqlglot/sqlglot.ts, web/client/vite.config.ts
Fixing case where urls has `//` and breaking import
include css files and workers into js output instead of having separate files
=> Fix: import for workers

sqlmesh/core/dialect.py, tests/core/test_dialect.py
Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1733307762741739
=> Fix: apply cast-to-dcolon rule for every model statement

web/client/src/library/components/plan/PlanApplyStageTracker.tsx
=> Fix: UI task position

docs/reference/configuration.md, sqlmesh/core/config/connection.py, sqlmesh/core/engine_adapter/base.py, tests/core/test_config.py, tests/core/test_test.py, tests/integrations/jupyter/test_magics.py
=> feat: add an option to pretty sql

README.md, docs/concepts/models/model_kinds.md
Missing word "record" from model kinds md.
Also being explicit that the way to contribute is to fork.
=> Some tiny docs fixes as I find them

sqlmesh/cli/main.py
Small update to allow us to change this easier in the future.
=> chore: move list of non-context commands to constant

sqlmesh/core/state_sync/common.py
=> Chore: Fix logger warning small typo

tests/core/test_schema_loader.py
The test in question was relying on manipulating internal state of `Context`, which got modified recently to have the concept of `selected_gateway` as well as `gateway`.
This updates the test to create a new Context instead
=> Chore: fix faulty test

sqlmesh/core/loader.py, tests/utils/test_jinja.py
Fixes https://github.com/tobymao/sqlglot/issues/4521
=> Fix: propagate dialect to extract call for script loading

sqlmesh/core/dialect.py, tests/core/test_model.py
=> Feat: allow macro functions in when_matched property

setup.py, sqlmesh/core/model/cache.py, tests/core/test_model.py
=> Fix: include column descriptions in optimized query cache key

setup.py, sqlmesh/core/test/definition.py, tests/core/test_test.py
=> Refactor: remove freezegun dependency in favor of time-machine

tests/core/engine_adapter/integration/test_integration_bigquery.py
[This](https://github.com/TobikoData/sqlmesh/commit/ca109fbfb633fff5174c31339e006e28261bc001) broke CI in main.
=> Chore: fix bigquery integration test

sqlmesh/utils/date.py
=> Fix: remove os-specific strftime format character

sqlmesh/core/engine_adapter/base.py
Fixes #3606
This reflects what we [used to do](https://github.com/TobikoData/sqlmesh/pull/3497/files#diff-1e99ae31d7c58d170f7ec858973e8398edf9042c0e000176cf5570098a3a4688L1823-R1851) prior to the recent `when_matched` refactor.
=> Fix: stop mutating model.when_matched in merge strategy

web/Dockerfile.app, web/client/src/library/components/editor/Editor.tsx, web/client/src/library/components/editor/EditorFooter.tsx, web/client/src/library/components/editor/EditorInspector.tsx, web/client/src/workers/sqlglot/sqlglot.ts
fixing https://github.com/TobikoData/sqlmesh/issues/3588
=> Fix: Properly include dialect when formatting

sqlmesh/schedulers/airflow/dag_generator.py
This pull request enhances the Airflow integration with SQLMesh by adding support for model tags in Airflow UI.
=> Feat: pass model tags to the airflow ui

sqlmesh/core/dialect.py
Hopefully this fixes the CI issue.
=> Fix: make sqlglot generator overriding more robust

docs/concepts/models/python_models.md, sqlmesh/core/model/common.py, sqlmesh/core/model/definition.py, tests/core/test_model.py
=> Feat: make strict dependency resolution optional in python models

docs/integrations/dbt.md, sqlmesh/dbt/common.py, sqlmesh/dbt/model.py, tests/dbt/test_transformation.py
This is more in line with expectations of dbt users.
=> Feat dbt incremental allow partials

setup.py, tests/core/engine_adapter/test_athena.py
Also add a test to show issue #3683 is fixed
=> Chore!: bump sqlglot to v26.3.8

docs/requirements.txt
Addresses https://github.com/TobikoData/sqlmesh/security/dependabot/27
=> Chore: bump pdoc to 14.5.1 to address gh security alert

sqlmesh/cli/example_project.py
Quick styling fix. It seems that the indentation was inadvertently changed at some point? It looks like this in the main branch:
=> Chore: fix example project indentation

docs/integrations/airflow.md
Fixes the Google Cloud Composer docs link.
=> fix: Update airflow.md

docs/concepts/plans.md
=> fix tag docs

docs/integrations/engines/databricks.md, sqlmesh/__init__.py, sqlmesh/core/config/connection.py, sqlmesh/core/engine_adapter/base.py, sqlmesh/core/engine_adapter/databricks.py, sqlmesh/utils/errors.py
Reverts TobikoData/sqlmesh#3781
=> Revert "feat: don't force db connect if using serverless"

sqlmesh/core/engine_adapter/base.py, sqlmesh/core/engine_adapter/databricks.py
This didn't fully address the issue: https://github.com/TobikoData/sqlmesh/pull/3799
Found out another case when testing within a Databricks notebook.
=> fix: databricks with_log_level

sqlmesh/core/console.py, sqlmesh/core/model/definition.py, sqlmesh/core/scheduler.py, sqlmesh/core/snapshot/evaluator.py, sqlmesh/engines/commands.py, sqlmesh/utils/errors.py, tests/core/test_context.py, tests/core/test_scheduler.py
**Old audit error**
**New audit error**
**Old audit warning**
**New audit warning**
=> Feat: improve audit error message formatting

sqlmesh/core/console.py, tests/integrations/jupyter/test_magics.py
[Before](https://github.com/user-attachments/assets/ce471cc2-00e9-4173-9ef3-6b94c02055af) vs [after](https://github.com/user-attachments/assets/5cead242-c4b6-4603-9bba-39b6c9ec6bfd).
=> Chore: improve metadata update console printing

sqlmesh/core/model/decorator.py, tests/core/test_model.py
The issue is that when name inference is enabled, all Python models receive the same name in the model registry, causing only one model to be picked up. The solution is to infer the name before registering the model in the registry.
=> Fix: Inference of python model names from the file system

sqlmesh/magics.py
=> fix: correctly check completion status in run_dag magic

sqlmesh/core/plan/evaluator.py, tests/core/test_integration.py
Prior to this PR, if you had something like `A [incremental_by_time_range] <- B[incremental_by_unique_key]` and tried to restate a part of A, B would only be fully restated if it was in `prod`.
If B was in a dev environment, then it would be partially restated even though it's a model type that doesn't support partial restatement. If B was later promoted to `prod`, then this could lead to incorrect data in `prod`.
This PR adjusts the logic to, when calculating restatement intervals based on `SnapshotTableInfo`, if any of the affected snapshots are "full restatement only" then the full snapshot records are fetched from state so that the restatement intervals can be widened correctly.
=> Fix: Selectively widen restatement intervals if they affect a downstream model that cannot be partially restated

sqlmesh/core/snapshot/evaluator.py
=> Fix: Using empty set as a default argument value

sqlmesh/core/context.py
- slight improvement that is then a launch pad to 'multi proces'
formatting of docs to make it faster
=> chore: refactor out targets as early as possible

sqlmesh/core/config/connection.py, sqlmesh/core/engine_adapter/base.py, sqlmesh/core/engine_adapter/bigquery.py, sqlmesh/core/engine_adapter/clickhouse.py, sqlmesh/core/engine_adapter/snowflake.py, sqlmesh/core/engine_adapter/trino.py, sqlmesh/core/environment.py, sqlmesh/core/model/definition.py, sqlmesh/core/model/kind.py, sqlmesh/core/plan/evaluator.py, sqlmesh/core/renderer.py, sqlmesh/core/snapshot/evaluator.py, sqlmesh/core/state_sync/db/environment.py, tests/core/test_model.py
=> Fix: Propagation of boolean model fields in Python models

sqlmesh/core/console.py, sqlmesh/core/plan/evaluator.py, sqlmesh/core/scheduler.py, sqlmesh/core/snapshot/evaluator.py, sqlmesh/utils/__init__.py, tests/cli/test_cli.py, web/server/console.py
Currently, the eval progress bar has static column widths.
With this PR, column widths will be based on the maximum length of information to display.
=> Feat: fit eval progress bar column widths to content

sqlmesh/core/console.py
If a standalone audit had the longest annotation of all models in an execution, the annotation column width was not calculated correctly
=> Fix: column width for execution progress bar with standalone audit

docs/guides/multi_repo.md
Based on this feedback: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1742485307057849
=> chore: document multi-repo migrations

vscode/extension/eslint.config.mjs, vscode/extension/src/auth/auth.ts, vscode/extension/src/commands/format.ts, vscode/extension/src/extension.ts, vscode/extension/src/lsp/lsp.ts, vscode/extension/src/utilities/errors.ts, vscode/extension/src/utilities/sqlmesh/sqlmesh.ts
- when someone runs a command that requires a user to be signed in
rather than fail, this nudges a user to sign in before hand
=> feat(vscode): before running commands check if signed in

sqlmesh/core/macros.py, sqlmesh/core/model/definition.py, sqlmesh/core/renderer.py, tests/core/test_model.py
This allows users to write Python macros and then easily call them from Jinja, including Jinja macros.
=> Feat!: First-class support for calling python macros from jinja context

sqlmesh/integrations/dlt.py
PR with breaking change: https://github.com/dlt-hub/dlt/pull/2519
=> fix: compat with dlt 1.10.0 release

vscode/extension/src/utilities/sqlmesh/sqlmesh.ts
Adds progress notification when installing sqlmesh enterprise.
=> feat(vscode): add installation progress bar for sqlmesh enterprise

sqlmesh/utils/metaprogramming.py, tests/core/test_model.py
See the added test for [context](https://github.com/TobikoData/sqlmesh/pull/4249/files#diff-f3de4d159300cd3fc7e7073f004c2eac345751fe96c2d1754a0b76a453eb4098R9300-R9312) around this.
=> Fix: 'duplicate definitions' python env bug due to module import order

sqlmesh/cli/main.py, sqlmesh/core/context.py, sqlmesh/magics.py, tests/core/test_context.py
=> Feat: return non-zero code when at least one audit fails in sqlmesh audit

sqlmesh/core/dialect.py, tests/core/test_dialect.py
Seems like this one slipped through the cracks.
=> Fix: address Snowflake table parsing bug

sqlmesh/lsp/main.py
Slightly incorrect initialization meant that we were returning the wrong diagnostics to the wrong model, this fixes that.
=> fix: fix the lsp initialization

package-lock.json, web/client/package.json
- old version of esbuild isn't working in workspace so cleaning up old things that depend on it.
=> chore: update orval in web

docs/concepts/macros/jinja_macros.md, sqlmesh/core/constants.py, sqlmesh/utils/jinja.py, tests/core/test_model.py
Currently blueprint variables are not support when using jinja.
=> Fix: Support blueprint variables in jinja macros

sqlmesh/core/model/definition.py, tests/core/test_context.py, tests/core/test_model.py
Casting virtual update expressions as VirtualUpdateStatement
=> Fix of render definition method for virtual update statements

sqlmesh/core/plan/evaluator.py, sqlmesh/core/snapshot/__init__.py, sqlmesh/core/snapshot/evaluator.py
=> Fix: Iterate through the whole DAG before raising an error when creating physical tables

sqlmesh/lsp/completions.py, sqlmesh/lsp/custom.py, sqlmesh/lsp/main.py, tests/lsp/test_completions.py, vscode/extension/src/completion/completion.ts, vscode/extension/src/extension.ts, vscode/extension/src/lsp/custom.ts, vscode/extension/src/lsp/lsp.ts
- adds keywords from tokenizer
- adds models in project minus the model that the file constructs.
=> feat(vscode): add completion provider

sqlmesh/core/plan/builder.py, tests/core/test_integration.py
A typical scenario that this fix addresses:
DAG: A -> C, B -> C
1. Make a NON_BREAKING change to A and deploy it to `dev_a`
2. Make a NON_BREAKING change to B and deploy it to `dev_b`
3. Deploy the 1st change to `prod`.
4. Rebase the 2nd change against the 1st one and try to deploy it `prod.` It results in a new snapshot for model `C`, created as a result combining the 2 changes to `A` and `B`. The new indirectly modified snapshot is created without any direct changes as part of the same plan.
This update improves the heuristics applied to determine the correct change category for such an "orphaned" snapshot.
=> Fix: Correctly categorize an orphaned indirectly modified snapshot created as a result of a merge of 2 or more directly modified parents

sqlmesh/core/context.py, sqlmesh/core/plan/builder.py, sqlmesh/core/plan/definition.py, tests/core/test_plan.py
identify and store flags a user sets manually
=> feat: store plan flags

.circleci/continue_config.yml, sqlmesh/core/engine_adapter/spark.py
Fixes CI in main, didn't notice this because I didn't run the databricks test in the sqlglot bump pr
=> Fix: databricks timestampntz handling

vscode/react/src/components/graph/ModelColumns.tsx, vscode/react/src/components/graph/context.tsx, vscode/react/src/domain/model.ts, vscode/react/src/domain/sqlmesh-model.ts
Reverts TobikoData/sqlmesh#4452
=> Revert "chore(vscode): reducing any types"

vscode/extension/src/utilities/common/python.ts, vscode/extension/src/utilities/exec.ts, vscode/extension/src/utilities/sqlmesh/sqlmesh.ts
=> fix(vscode): make work better with venvs

sqlmesh/core/model/definition.py, tests/core/test_model.py
This is very similar to https://github.com/TobikoData/sqlmesh/pull/4323 – signals suffer from the same issue audits did.
=> Chore: detect invalid signal refs and raise early

tests/core/engine_adapter/test_snowflake.py
Addresses issue #4181 
When we create a materialized view on Snowflake, we inject a COPY GRANTS property.
However, this property is required to be in a different location on a `CREATE MATERIALIZED VIEW` statement vs a `CREATE VIEW` statement.
There is a [PR against SQLGlot](https://github.com/tobymao/sqlglot/pull/5109) that fixes this on the SQLGLot side. This PR ensures that the fix is working on the SQLMesh side.
**This PR will fail until the SQLGlot PR makes it into a release**
=> Fix(snowflake): Correctly handle COPY GRANTS property in materialized views

sqlmesh/lsp/context.py, sqlmesh/lsp/custom.py, sqlmesh/lsp/main.py, vscode/extension/package.json, vscode/extension/src/commands/renderModel.ts, vscode/extension/src/extension.ts, vscode/extension/src/lsp/custom.ts, vscode/extension/tests/lineage.spec.ts, vscode/extension/tests/render.spec.ts, vscode/extension/tests/utils.ts
=> feat(vscode): render model

sqlmesh/lsp/main.py, vscode/extension/src/lsp/lsp.ts, vscode/extension/tests/lineage.spec.ts
=> faet(vscode): support multiple workspaces

vscode/extension/src/commands/renderModel.ts, vscode/extension/src/extension.ts, vscode/extension/src/providers/renderedModelProvider.ts
=> feat(vscode): rerender on save model

sqlmesh/lsp/description.py, tests/lsp/test_description.py
=> fix(lsp): generate markdown including None

examples/sushi/models/orders.py, sqlmesh/core/loader.py, sqlmesh/core/model/decorator.py, tests/core/test_context.py, tests/core/test_model.py
Closes #4779 
Kudos to @florianm for the detailed bug report and for sharing a repo to reproduce the issue.
=> Fix: Support signals for Python models

sqlmesh/core/linter/definition.py, sqlmesh/core/linter/rule.py, sqlmesh/core/linter/rules/builtin.py, sqlmesh/lsp/context.py, sqlmesh/lsp/main.py, tests/lsp/test_code_actions.py
- add notifications when to refresh inlays and diagnostics
- add feature to core
- refactor the lsp a little bit
=> feat: add fixes to linting errors

.github/workflows/release_extension.yaml
- also removed redundant steps that slowed the job down
=> ci: publish to open vsx

pyproject.toml, tests/core/engine_adapter/test_mssql.py
Relevant commits:
- https://github.com/TobikoData/sqlmesh/commit/186f0edceb01f68a37a2b03266d6ab0be76bc8a8
- https://github.com/tobymao/sqlglot/commit/db4e0ece950a6a1f543d8ecad48a7d4b1d6872be
=> Chore!: bump sqlglot to v26.31.0

vscode/extension/playwright.config.ts
- keeps traces on errors to help debug
=> chore(vscode): turn on trace to help debug

Makefile
Just a small helper command to make cache cleaning easier. I found my self using this frequently recently.
=> Chore: add Makefile command to recursively clean `.cache` dirs
