TobikoData/sqlmesh

- sqlmesh/core/engine_adapter/base_spark.py
- tests/core/engine_adapter/test_spark.py
@crericha I suddenly realized there was one more place where the order of column alteration was incorrect.
> fix: Drop columns before adding columns when altering table in Spark

- .circleci/config.yml
The filters were removed because I thought they were redundant with requires, but jobs after `gh-release` didn't trigger.
> Add tag filters to release jobs

- examples/wursthall/models/db/item_d.sql
- sqlmesh/core/model/__init__.py
- sqlmesh/core/model/kind.py
- sqlmesh/core/model/meta.py
- sqlmesh/core/snapshot/definition.py
- tests/core/test_integration.py
- tests/core/test_model.py
- tests/core/test_snapshot.py
- tests/dbt/test_config.py
fix: full refresh should respect all intervals to get upstream backfills
> breaking: validate only correct model kinds support batch_size.

- .circleci/config.yml
Attach workspace so the IDE will get picked up by the publish job.
> Attach workspace when publishing Python package

- web/client/src/context/editor.ts
- web/client/src/context/fileTree.ts
- web/client/src/library/components/editor/Editor.tsx
- web/client/src/library/components/editor/EditorCode.tsx
- web/client/src/library/components/editor/EditorTabs.tsx
- web/client/src/library/components/fileTree/Directory.tsx
- web/client/src/library/components/fileTree/File.tsx
- web/client/src/models/directory.ts
> [UI] Fix bugs for file tree

- docs/guides/models.md
- docs/quick_start.md
- sqlmesh/core/console.py
- sqlmesh/core/context.py
- sqlmesh/core/plan/evaluator.py
- sqlmesh/core/scheduler.py
- tests/core/test_scheduler.py
- web/server/console.py
Resolves: https://github.com/TobikoData/sqlmesh/issues/659
> Feat: Use view name for targets in backfill progress

- sqlmesh/core/config/base.py
- sqlmesh/dbt/basemodel.py
- sqlmesh/dbt/builtin.py
- sqlmesh/dbt/common.py
- sqlmesh/dbt/model.py
- sqlmesh/dbt/source.py
- sqlmesh/utils/jinja.py
- tests/dbt/test_config.py
- tests/dbt/test_transformation.py
- Jinja config() calls in the model should not be rendered (to match dbt behavior)
- Have update_with use assignment when modifying fields to trigger validators
- Enable validation on assignment for DbtConfig classes to validate new input and do any necessary type conversion.
- Fix some edge cases in extracting the Jinja config() calls from SqlModel queries
- Implement config jinja method (attribute dict of model's config) https://docs.getdbt.com/reference/dbt-jinja-functions/config
> [DBT] Capture all config fields before rendering them

- Makefile
It looks like our Airflow integration tests run in an Ubuntu container and that container's python defaults to python 2. So we can replace all of the python/pip references to python3/pip3. It looks like that is what we did to get Airflow working in the first place: https://github.com/TobikoData/sqlmesh/blob/main/examples/airflow/Makefile#L12
Error CI job: https://app.circleci.com/pipelines/github/TobikoData/sqlmesh/3111/workflows/bc3d7a7f-01cb-46ee-bbdd-dc9bad76eeac/jobs/19482
> fix: Specify python3 for CI

- sqlmesh/core/console.py
- sqlmesh/core/plan/definition.py
- sqlmesh/core/plan/evaluator.py
Resolves: https://github.com/TobikoData/sqlmesh/issues/686
UI is already displaying this correctly. 
We still show model names in the modified section. I _think_ this separation makes sense. Conceptually it is like "Here is what is changed in terms of the code (model names) and then here is what is being applied in terms of data (the "table" references)."
> Fix: Show view name in models needing backfill

- docs/concepts/audits.md
- sqlmesh/core/audit/builtin.py
- tests/core/test_audit.py
Add a built-in audit that allows arbitrary expressions that must hold for all rows in a model.
> feat: add `forall` audit

- sqlmesh/core/audit/definition.py
- sqlmesh/core/context.py
- sqlmesh/core/snapshot/evaluator.py
Example usage:
```
% sqlmesh --path examples/sushi --config local_config audit --model sushi.items
Found 3 audit(s).
accepted_values PASS.
not_null PASS.
assert_items_price_exceeds_threshold SKIPPED.
Finished with 0 audit errors and 1 audit skipped.
Done.
```
> Fix: Respect audit skip flag

- examples/sushi/models/waiter_as_customer_by_day.sql
- sqlmesh/core/audit/builtin.py
- tests/core/test_audit.py
Apply the `NOT` predicate before `REDUCE` to handle cases where only one criteria is specified.
> fix: forall with only one criteria

- docs/concepts/audits.md
- examples/sushi/models/items.py
- sqlmesh/core/audit/builtin.py
- tests/core/test_audit.py
Since `values` is a SQL keyword, it is not suitable as an audit parameter. This renames it to `is_in` which is close to the `IN` SQL keyword while not being one.
Fixes #702
> fix: rename `values` parameter to `is_in`

- web/client/src/library/components/editor/EditorPreview.tsx
> Fix: table and query tabs for editor Preview are not scrollable 

- setup.py
- sqlmesh/utils/file.py
- tests/core/test_file.py
This pull request introduces support for [fsspec](https://filesystem-spec.readthedocs.io/en/latest/) and transactional operations over files. It aims to introduce a new state adapter, `FileAdapterStateSync`.
Fsspec is a Python library that provides a unified interface to access various filesystems. With this addition, sqlmesh can now interact with different file systems, such as local and cloud-based (GCS, S3, Azure), using a consistent API.
Moreover, the pull request includes the implementation of transactional support over files within the filesystem via a wrapper class. Transactions over files are theoretically at a serializable-level of isolation with built-in rollbacks. 
The current implementation of sqlmesh lacks reliable state storage outside of persistent OLTP services. Currently …
> Feat: File state adapter

- sqlmesh/utils/transactional_file.py
Small fix after integration testing on GCS. The noteworthy callout is that the `protocol` attached to a filesystem can be a str OR sequence so we need to normalize it, we should also support the associated aliases.
This implementation passed all tests against our live GCS too so its really nice 🎉  (obviously changing the test to use some random file path in our bucket instead of a `NamedTemporaryFile`.
> [Fix] Small fix after integration testing on GCS

- web/server/api/endpoints/environments.py
- web/server/api/endpoints/plan.py
- web/server/main.py
This PR fixes a race condition on IDE startup when multiple requests access the state sync concurrently.
> Fix: Run plan in default event loop instead of an executor

- docs/integrations/engines.md
- sqlmesh/core/config/connection.py
- sqlmesh/core/engine_adapter/__init__.py
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/bigquery.py
- sqlmesh/dbt/target.py
- sqlmesh/schedulers/airflow/operators/bigquery.py
- sqlmesh/schedulers/airflow/operators/targets.py
This BigQuery config required changing properties at execution time instead of connection properties that can be set when creating the connector. Therefore I introduced a concept of execution config and then that can be passed into the engine adapter to be available at execution time. 
Airflow only supports the `num_retries` config so that is all that gets passed into Airflow.
I also fixed a bug where BigQuery had it's concurrency set to 4. When using the built-in scheduler this creates a lot of errors trying to concurrently do updates against state table. Best to set to 1 for this case.
> Feat: Add execution config for BigQuery

- setup.py
- sqlmesh/core/constants.py
- sqlmesh/core/context.py
- sqlmesh/core/loader.py
- sqlmesh/core/model/__init__.py
- sqlmesh/core/model/cache.py
- sqlmesh/core/model/definition.py
- sqlmesh/core/renderer.py
- sqlmesh/dbt/builtin.py
- sqlmesh/dbt/loader.py
- sqlmesh/dbt/package.py
- sqlmesh/dbt/project.py
- sqlmesh/utils/cache.py
- tests/core/test_model.py
- tests/dbt/conftest.py
- tests/utils/test_cache.py
There is also an opportunity to cache the `python_env` after it's been compiled by `prepare_env` but this hasn't been addressed in this PR.
> Feat: Introduce the caching layer when loading SQL models

- docs/reference/configuration.md
- sqlmesh/__init__.py
- sqlmesh/cli/__init__.py
Enabling the debug mode ensures that full backtraces are printed in CLI and that the default log level is set to DEBUG.
> Chore: Add ability to enable a debug mode

- sqlmesh/cli/main.py
- sqlmesh/core/context.py
Fixes #696 
Printed output when all connections succeed:
When one connection fails:
> Chore: Add the 'info' command to CLI

- docs/integrations/engines.md
- sqlmesh/core/config/connection.py
Resolves: https://github.com/TobikoData/sqlmesh/issues/750
> Fix: Remove Postgres `keepalives_idle` default

- setup.py
- sqlmesh/core/loader.py
- web/client/src/library/components/editor/EditorPreview.tsx
- web/client/src/library/components/ide/IDE.tsx
- web/client/src/models/file.ts
- web/server/api/endpoints/files.py
- web/server/api/endpoints/plan.py
- web/server/main.py
- web/server/watcher.py
Currently if user tries to add new file to `model's` folder it immediately crushing and sending Error, even before user even have a chance to create a valid model.
> Fix: Allow empty files in models folder and refetch lineage on model file change

- sqlmesh/core/context.py
- sqlmesh/core/context_diff.py
- sqlmesh/core/environment.py
- sqlmesh/core/plan/evaluator.py
- sqlmesh/core/state_sync/base.py
- sqlmesh/core/state_sync/common.py
- sqlmesh/core/state_sync/engine_adapter.py
- sqlmesh/migrations/v0004_environmnent_add_finalized_at.py
- sqlmesh/schedulers/airflow/dag_generator.py
- tests/core/test_state_sync.py
- tests/web/test_main.py
The environment record in the state is updated before virtual layer operations are applied to the data warehouse. This leads to scenarios in which SQLMesh ends up in an incorrect state due to the partially applied transition without any ability to repair it.
This PR introduces a new state operation called `finalize` which is applied to the target environment *at the very end* of the plan application process. Thanks to this finalization, SQLMesh can now determine whether the previous environment update was successful and then reapply the plan if it wasn't, even if there's no meaningful difference between the local state and the remote environment otherwise.
> Fix: Introduce environment finalization

- docs/quick_start.md
- sqlmesh/cli/example_project.py
Makes some changes to increase the accessibility & readability of the [quick start project](https://sqlmesh.readthedocs.io/en/stable/quick_start/) (what you get when you do `sqlmesh init`): 
- Removed leading `example_` from all model names 
- Added `/seeds` dir, `seed_data.csv`, and `seed_model.sql` model
- Updated `incremental_model.sql` to be downstream of `seed_model.sql` 
- Renamed audit from `example_full_model.sql` to `assert_positive_order_ids.sql` (it tends to be convention to give the audit/macro filename the same name as the audit/macro itself.  
- Updated quick start doc to reflect all of the above, fixed typo with new_columns having `1` not `z`, and added ASCII art of the DAG it builds (could be replaced by an IDE screenshot later). 
I've tested it locally by running `sqlmesh …
> Modify quickstart project and add seed file

- sqlmesh/dbt/target.py
> Fix: redshift config port can be a string in profiles.yml

- sqlmesh/core/plan/evaluator.py
- sqlmesh/schedulers/airflow/dag_generator.py
I forgot that it's ok to backfill before promoting when applying a forward-only plan in dev, since all forward-only snapshots target temp tables and no schema migration takes place.
> Fix: When applying a forward-only plan in dev the backfill should precede the promotion

- sqlmesh/cli/main.py
Added a print statement to print the rendered dag filename in the terminal when `sqlmesh dag` is ran
[#306](https://github.com/TobikoData/sqlmesh/issues/306)
> refactor: print rendered dag location in terminal

- docker-compose.yml
- setup.py
- Less server reloading by only watching `sqlmesh` and `web/server` directories for changes.
- Set a graceful shutdown timeout to force reloading since SSE connections were blocking the server from reloading.
> Chore: Update uvicorn configs for a better developer experience

- examples/wursthall/config.yaml
- setup.py
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/bigquery.py
- tests/core/engine_adapter/test_bigquery.py
Previously we only loaded Pandas DataFrames using the native loader when loading for insert overwrite models. Now we also use it when creating a table from a DataFrame. 
Also fixed a bug with the new temp table logic that would modify the table object passed in to also have the new table table name.
> Improve BigQuery Pandas Implementation

- web/server/console.py
- web/server/main.py
- web/server/utils.py
This PR has the API send stack traces in SSEs so exceptions from executor tasks, e.g. plan/apply, don't get lost and the app can react to the errors.
> Feat: Log exception stack traces from executor tasks to API console

- web/server/watcher.py
An API model used to be simpler so `json.dumps()` was good enough. However, a model now has datetime fields and other fields the standard Python `json` library can't encode out of the box.
> Fix: JSON encoding for models

- setup.py
- sqlmesh/core/schema_diff.py
This PR resolves the regression that would be caused due to `StructKwarg` being removed in https://github.com/tobymao/sqlglot/commit/7b09bffd7820748df5e9f1ce21f74883a7041ca8 once we bump SQLGlot.
This depends on releasing a new SQLGlot version because it's still in v12.1.0; once that's done I'll bump its version here too.
> Fix: replace exp.StructKwarg with exp.ColumnDef in schema diff

- web/server/main.py
When serving IDE we need to always give control back to Browser so it can use router properly, otherwise something like `/docs/models/custom-model_1`  would be resolved as 404 by the server, because that path only exists in SPA
> always redirect back to index.html

- setup.py
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/base_spark.py
- sqlmesh/core/engine_adapter/duckdb.py
- sqlmesh/core/engine_adapter/logical_merge.py
Cleaned up some sections where we do `exp.Insert(this=..., expression=..., overwrite=...)`, by using the builder introduced in https://github.com/tobymao/sqlglot/commit/c01edb014b5101eac9913b04404753b324581214.
> Refactor: use sqlglot's exp.insert to simplify Insert building

- web/server/api/endpoints/lineage.py
Models that reference external tables were causing errors when fetching their column-level lineages.
> Fix: Handle external tables when fetching column-level lineage

- web/client/.eslintrc.js
- web/client/src/context/editor.ts
- web/client/src/library/components/graph/Graph.tsx
- web/client/src/library/components/graph/ModelLineage.tsx
- web/client/src/library/components/graph/help.ts
- web/client/src/main.tsx
Displays node on lineage for external tables. In Addition to PR [856](https://github.com/TobikoData/sqlmesh/pull/856)
To be more specific it displays any node that not a `model` but still present in API response when asking for columns lineage
> Feat: Display external table on lineage

- sqlmesh/core/state_sync/engine_adapter.py
- sqlmesh/utils/date.py
- tests/core/test_state_sync.py
> Fix: Make sure start_at / end_at are strings when storing an environment record in state sync

- tests/conftest.py
Prior to this change the tests would detect config in your home directory and it could change the behavior of the test. This change mocks out the home directory in order ensure this local config is ignored.
> Fix: Ignore local config when running tests

- docs/integrations/github.md
- sqlmesh/integrations/github/cicd/command.py
- sqlmesh/integrations/github/cicd/controller.py
- tests/fixtures/github/pull_request_command_deploy.json
- tests/integrations/github/cicd/fixtures.py
- tests/integrations/github/cicd/helper.py
- tests/integrations/github/cicd/test_github_commands.py
- tests/integrations/github/cicd/test_github_controller.py
- tests/integrations/github/cicd/test_github_event.py
Breaking Change: The bot now has a behavior change where before if you had a SQLMesh project where no required approvers were defined in your config then a PR would automatically be deployed to prod if tests passed and PR environment was updated. Now the bot skips the prod deploy in this case. To do the deploy you need to issue the `/deploy` command.
> Feat!: Add Github Action Bot Deploy Command

- setup.py
4.6.0 is causing issues for us on Python 3.8 and 3.9. So forcing the last known good release for now.
> Chore: Don't use bugged typing-extensions release

- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/spark.py
- sqlmesh/core/snapshot/evaluator.py
- tests/core/test_snapshot_evaluator.py
A follow up PR will make use of the `SUPPORTS_INSERT_OVERWRITE` property within the engine adapter to cleanup implementation. This PR is just focused on resolving yielding dataframes into an insert/overwrite.
> Fix: Concat Dataframes if insert overwrite

- setup.py
- sqlmesh/core/dialect.py
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/renderer.py
- tests/core/test_macros.py
This will resolve mypy issues created due to the latest sqlglot [changes](https://github.com/tobymao/sqlglot/pull/1689/).
When we bump sqlglot to v14.1.0, I'll bump its version here too and the CI will be fixed.
> Chore!: fix mypy issues, use _parse_table_parts instead of _parse_table

- sqlmesh/core/plan/definition.py
- sqlmesh/core/plan/evaluator.py
- sqlmesh/core/snapshot/__init__.py
- sqlmesh/core/snapshot/definition.py
- sqlmesh/schedulers/airflow/dag_generator.py
- tests/core/test_snapshot.py
@eakmanrq I realized that that we had a problem when trying to promote forward-only changes as part of the CI/CD bot.
The issue is that the order of plan application depended on whether the plan itself was forward-only or not. This is ok when we create **new** forward-only snapshots but doesn't work when we are trying to promote **existing** forward-only snapshots to prod. In other words, the CI / CD bot would require the `--forward-only` flag in order for the application to succeed.
This PR addresses the described issue by introspecting a plan and checking whether there are paused forward-only snapshots that are about to be promoted. If there are, then we need to promote before evaluation, otherwise we follow the normal flow.
> Fix: Evaluate snapshots after pomoting the environment if the plan contains paused forward-only snapshots

- examples/sushi/models/customer_revenue_lifetime.sql
- sqlmesh/core/config/model.py
- sqlmesh/core/dialect.py
- sqlmesh/core/model/definition.py
- sqlmesh/core/model/kind.py
- sqlmesh/core/model/meta.py
- sqlmesh/core/scheduler.py
- sqlmesh/core/snapshot/definition.py
- sqlmesh/core/snapshot/evaluator.py
- sqlmesh/migrations/v0010_seed_hash_batch_size.py
- tests/core/test_integration.py
- tests/core/test_scheduler.py
- tests/core/test_snapshot.py
- tests/utils/test_dag.py
Breaking Change: Bugfix is included in this PR that correctly includes `batch_size` in the model metadata fingerprint for seed models. 
This adds support for the built-in scheduler but without proper restatement support.
TODO:
* Add restatement support for all `depends_on_past` models (so that means incremental by unique key also)
* PR: https://github.com/TobikoData/sqlmesh/pull/921
* Add Airflow support
> Feat!: Add depends_on_past through self-reference check support (Built-in only)

- examples/sushi/models/customer_revenue_by_day.sql
- examples/sushi/models/customer_revenue_lifetime.sql
- examples/sushi/models/customers.sql
- examples/sushi/models/top_waiters.sql
- examples/sushi/models/waiter_names.sql
- examples/sushi/models/waiter_revenue_by_day.sql
- sqlmesh/core/model/definition.py
- sqlmesh/core/model/meta.py
- sqlmesh/core/snapshot/definition.py
- tests/core/test_model.py
- tests/core/test_snapshot.py
- tests/core/test_table_diff.py
- tests/schedulers/airflow/test_client.py
- web/server/api/endpoints/models.py
- web/server/models.py
We should start capturing primary key early as it could seed future interfaces. What is a model without a primary key anyway. 
Given this interface, we can simplify the data-diff interface, use this to do automatic non_null & unique audits, and to communicate outwards in the UI and metadata clearly the key for the model, be it a single or composite value.
> Feat: Add primary key capture to model to seed future interfaces

- sqlmesh/core/model/definition.py
If we don't mind converting the grains to `Identifier`s, the implementation can be simplified (fwiw it can also be simplified if I just do it all inline like it used to be).
> Fix: ensure AST is correct in meta field converter

- setup.py
- sqlmesh/cli/main.py
- sqlmesh/core/context.py
- sqlmesh/core/dialect.py
- sqlmesh/core/loader.py
- sqlmesh/core/model/definition.py
- sqlmesh/core/model/meta.py
- sqlmesh/core/renderer.py
- sqlmesh/magics.py
- tests/core/test_audit.py
- tests/core/test_model.py
- tests/core/test_snapshot.py
- tests/core/test_table_diff.py
- tests/dbt/test_transformation.py
This PR (WIP) aims to improve how we handle case-sensitive identifiers across different dialects, especially in Snowflake. The problem is that Snowflake [resolves identifiers](https://docs.snowflake.com/en/sql-reference/identifiers-syntax) as uppercase, which [used to be](https://github.com/tobymao/sqlglot/commit/dcfe67f5aff6a1f8739c704dfc4f71ad2f2b293e) inconsistent with SQLGlot's optimizer, hence causing problems when expanding star projections (case-sensitivity was not preserved).
There are several outstanding items:
> Fix!: normalize identifiers and model names

- sqlmesh/core/config/connection.py
- sqlmesh/core/dialect.py
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/base_postgres.py
- sqlmesh/core/engine_adapter/bigquery.py
- sqlmesh/core/engine_adapter/redshift.py
- sqlmesh/core/engine_adapter/snowflake.py
- sqlmesh/core/engine_adapter/spark.py
- sqlmesh/core/model/__init__.py
- sqlmesh/core/model/kind.py
- sqlmesh/core/model/meta.py
- sqlmesh/core/snapshot/definition.py
- sqlmesh/core/snapshot/evaluator.py
- sqlmesh/dbt/model.py
- tests/core/engine_adapter/test_base.py
- tests/core/engine_adapter/test_base_postgres.py
- tests/core/test_plan_evaluator.py
- tests/core/test_snapshot_evaluator.py
- tests/dbt/test_transformation.py
This PR introduces support for materialized views. 
The `VIEW` kind has been extended to accommodate the new `materialized` flag. The model definition looks as follows:
```sql
MODEL (
name test_schema.test_model,
kind VIEW (
materialized true
)
);
```
The support for materialized views has been enabled for the following engines:
* Snowflake
* BigQuery
* Redshift
* Postgres
The `materialized` flag is ignored when applied to engines that don't support it. 
During evaluation of a model of this kind, the view will be replaced (or recreated) only if the model's query rendered during evaluation doesn't match the query used during the previous view creation for this model, or if the target view doesn't exist. Thus, views are recreated only when needed in order to realize all the benefits …
> Feat: Add support for materialzied views

- docs/integrations/engines.md
`default_engine_operator_args` is actually: `engine_operator_args`
Also the key `sqlmesh_gcp_conn_id` should be: `bigquery_conn_id`
> Docs: Update engines.md

- docs/concepts/macros/jinja_macros.md
- examples/sushi/models/waiter_as_customer_by_day.sql
- sqlmesh/core/audit/definition.py
- sqlmesh/core/dialect.py
- sqlmesh/core/model/definition.py
- sqlmesh/dbt/basemodel.py
- sqlmesh/dbt/model.py
- sqlmesh/dbt/test.py
- sqlmesh/migrations/v0012_update_jinja_expressions.py
- tests/core/test_audit.py
- tests/core/test_dialect.py
- tests/core/test_model.py
- tests/core/test_state_sync.py
- tests/dbt/test_config.py
This update isolates Jinja expressions into designated blocks to simplify SQL parsing and capture user's intention more precisely. 
Model definition example:
```sql
MODEL (
name sqlmesh_example.full_model
);
JINJA_STATEMENT_BEGIN;
{{ pre_hook() }}
JINJA_END;
JINJA_QUERY_BEGIN;
SELECT {{ 1 + 1 }};
JINJA_END;
JINJA_STATEMENT_BEGIN;
{{ post_hook() }}
JINJA_END;
```
> Feat!: Extend SQL parser with designated blocks for jinja code

- docs/integrations/engines.md
- sqlmesh/schedulers/airflow/operators/redshift.py
Breaking Change: When passing in a override for the default connection ID for Redshift in Airflow you will need to use `redshift_conn_id` instead of `conn_id`.
> Fix!: Update redshift connection id to be consistent

- setup.py
Fixes issue with bigquery project names ending with a number. https://tobiko-data.slack.com/archives/C044BRE5W4S/p1686345066753279?thread_ts=1686173985.623249&cid=C044BRE5W4S
> Fix: Bump sqlglot

- web/client/src/library/components/report/ReportErrors.tsx
- web/client/src/library/components/report/ReportTestsErrors.tsx
- web/client/src/library/pages/ide/IDE.tsx
When re-using `ReportErrors` component it subscribing to `errors` SSE multiple times which causing issue with displaying errors
> Fix: Avoid duplicate subscription on component reuse

- sqlmesh/core/snapshot/evaluator.py
Refactored the flag-driven implementation of the Snapshot Evaluator so that it relies on polymorphism instead.
This should help make subsequent iterations on this module a lot less error-prone. 
While refactoring I noticed a bug which impacted `INCREMENTAL_BY_UNIQUE_KEY` models in case when more than one DataFrame is returned. The first DataFrame was inserted using `merge` strategy while all subsequent inserts where appended. The new implementation made it very clear.
> Chore: Refactor the snapshot evaluator

- sqlmesh/cli/main.py
- sqlmesh/core/console.py
- sqlmesh/core/context.py
- sqlmesh/core/table_diff.py
We need dead-simple diffs. Certain parameters are required so they should be positional arguments, not options. We should leverage the new `grain` metadata (it already leverages it). The invocation should be as concise and self evident as possible without having to remember flags and help text. Please see the examples below to get a feel for the utility and practical approach.
**Notes:**
1. Use pos args, reduce flags
2. Use a new easy-to-grasp syntax for cross env comparison, `<from-env>:<to-env>` as pos arg 1
3. We are diffing a model against itself in another env, so just take the name as pos arg 2
4. We use the `grain` metadata if supplied reducing invocation to just 2 args, total, for full functionality
5. Keep `--on` flag so user has escape hatch to override grain if they want
6. …
> Feat: Greatly simplify table diff CLI invocation

- sqlmesh/core/audit/definition.py
- sqlmesh/core/context.py
- sqlmesh/core/dialect.py
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/logical_merge.py
- sqlmesh/core/engine_adapter/spark.py
- sqlmesh/core/loader.py
- sqlmesh/core/model/cache.py
- sqlmesh/core/model/definition.py
- sqlmesh/core/renderer.py
- sqlmesh/core/snapshot/definition.py
- sqlmesh/core/snapshot/evaluator.py
- sqlmesh/core/test/definition.py
- sqlmesh/dbt/adapter.py
- sqlmesh/dbt/basemodel.py
- sqlmesh/dbt/builtin.py
- sqlmesh/integrations/llm.py
- sqlmesh/utils/errors.py
- tests/core/test_model.py
- tests/dbt/test_config.py
- tests/dbt/test_manifest.py
- tests/dbt/test_transformation.py
- tests/fixtures/dbt/sushi_test/models/waiter_revenue_by_day.sql
- web/server/api/endpoints/lineage.py
- web/server/api/endpoints/models.py
To support model queries with jinja expressions that can only be rendered at runtime (as opposed to parse time) I refactored the model definition and made the rendered query and the columns-to-types mapping optional for sql models.
For context, the jinja expression can't be rendered at parse time if it requires connection to the data warehouse.
> Feat: Optional rendered query and columns-to-types mapping

- tests/core/engine_adapter/test_duckdb.py
The `merge` method expects a `QueryOrDf` but `parse_one` without an `into` arg returns `Expression` which is incompatible. Dunno why this wasn't caught, but we'll get a mypy failure if https://github.com/tobymao/sqlglot/pull/1797 is merged (tested locally).
> Chore: fix mypy type hints in test_duckdb

- sqlmesh/core/dialect.py
- sqlmesh/core/loader.py
- sqlmesh/core/model/definition.py
- sqlmesh/core/renderer.py
- tests/core/test_model.py
Since the column-to-types mapping is now optional there doesn't seem to be much reason to prohibit `SELECT *` queries in models that reference external tables.
With this update we assume that we don't have a mapping available if we identify a `*` projection in the rendered / optimized query.
> Fix: Allow SELECT * in models that reference external tables

- sqlmesh/core/config/connection.py
With intervals now in a separate table the number of updates is significantly reduced and therefore it should be possible to enable concurrent tasks for Delta tables. Still defaulting to one until we can do some testing to verify this isn't an issue.
> Feat: Remove restriction on Databricks concurrent tasks

- sqlmesh/core/context.py
- sqlmesh/core/loader.py
- sqlmesh/core/model/definition.py
- tests/core/test_model.py
Validating definition requires the columns-to-types mapping which in turn relies on the rendered optimized query. The latter cannot be produced correctly without setting the schema first.
> Fix: Validate model definition only after the schema for it is set

- docs/integrations/engines.md
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/databricks.py
- sqlmesh/core/engine_adapter/spark.py
- sqlmesh/core/snapshot/evaluator.py
- sqlmesh/engines/spark/db_api/spark_session.py
- tests/core/engine_adapter/test_base.py
- tests/core/engine_adapter/test_databricks.py
- tests/core/test_snapshot_evaluator.py
Note: This PR has Databricks do a non-transactional delete + insert due to issues with dynamic insert/overwrite on Unity catalog tables. Once a `REPLACE WHERE` bug is fixed we will be switching to that which will make it atomic again. 
The `USE CATALOG` approach from before only worked if SQL was being executed. So if you had a Dataframe then that catalog would not be used. The `setCurrentCatalog` works across both SQL and Dataframe API.
> Fix: Various Databricks related fixes

- sqlmesh/cli/main.py
- sqlmesh/core/config/scheduler.py
- sqlmesh/core/context.py
- sqlmesh/core/state_sync/base.py
- sqlmesh/core/state_sync/engine_adapter.py
- sqlmesh/integrations/github/cicd/controller.py
- sqlmesh/schedulers/airflow/api.py
- sqlmesh/schedulers/airflow/client.py
- sqlmesh/schedulers/airflow/common.py
- sqlmesh/schedulers/airflow/state_sync.py
- tests/core/test_state_sync.py
- tests/integrations/github/cicd/test_github_controller.py
- tests/schedulers/airflow/test_client.py
This update allows user to invalidate the target environment by setting its expiration timestamp to now, forcing it to be garbage collected during a subsequent run of the janitor process.
CC: @z3z1ma
> Feat: Add ability to invalidate the environment

- sqlmesh/core/config/__init__.py
- sqlmesh/core/config/loader.py
- sqlmesh/core/config/root.py
- sqlmesh/core/context.py
- sqlmesh/utils/__init__.py
This PR allows users to set environment variables for their SQLMesh project configs in their `~/.sqlmesh/` config defaults. This is useful for variables like user tokens, keys, passwords, etc.
> Feat: Introduce config env_vars

- sqlmesh/core/engine_adapter/bigquery.py
- sqlmesh/core/renderer.py
- sqlmesh/dbt/adapter.py
- sqlmesh/dbt/builtin.py
- tests/dbt/conftest.py
- tests/dbt/test_adapter.py
Sometimes `ref` are passed into the dbt adapter while constructing a model query. This means that the production table name will be used since jinja rendering happens before we get a chance to resolve table references. 
This update ensures that dbt's `ref` returns resolved table references when using adapter.
> Fix: Map relations to snapshot physical tables in the dbt adapter

- Makefile
- examples/sushi/config.py
- setup.py
- sqlmesh/core/_typing.py
- sqlmesh/core/config/root.py
- sqlmesh/core/config/scheduler.py
- sqlmesh/core/context.py
- sqlmesh/core/notification_target.py
- sqlmesh/core/plan/evaluator.py
- sqlmesh/core/scheduler.py
- sqlmesh/core/user.py
- tests/conftest.py
- tests/core/test_notification_target.py
This PR adds Slack and SMTP notification targets as well as the notion of events that should trigger notifications.
- Notification targets defined in a config but missing fields will be silently ignored. Most common case is probably fields that are taken from environment variables but the environment variables are not available.
- If no username is specified in a config, the config's notification targets are used. Most common use case is probably production environments.
- If a username is specified in a config, only that user gets notified. Most common use case is probably users developing locally. There is currently one exception. See below:
- Audit model owners are notified their audits failed if there is a user with a notification target configured for an `audit_failure` event and the …
> Feat: Enhance notification target functionality

- docs/integrations/engines.md
- sqlmesh/core/config/connection.py
- sqlmesh/core/engine_adapter/databricks.py
- sqlmesh/engines/spark/db_api/spark_session.py
- tests/core/engine_adapter/test_databricks.py
Two key changes:
* With this change all spark connections (either through the SparkSession DBAPI, Databricks Connect Session, or Databricks SQL Connection) will set their partitioning to be dynamic since we assume dynamic partition insert/overwrite in SQLMesh.
* This is still ongoing, but based on what Databricks support is saying is that Unity actually does support dynamic insert/overwrite so we are switching back to that.
I'm leaving the `REPLACE WHERE` stuff because still not sure what the best long term solution is going to be on Databricks.
> Fix: Enforce dynamic INSERT/OVERWRITE and make Databricks INSERT/OVERWRITE

- setup.cfg
- sqlmesh/core/engine_adapter/bigquery.py
- tests/core/engine_adapter/test_bigquery.py
- tests/core/engine_adapter/test_databricks.py
Prior to this change whenever we did client direct calls (which is fairly common in BQ engine adapter) they were not retried and only the SQL execution calls were retried. This retries all db calls.
> Fix: Make all BigQuery db calls retryable

- setup.py
A dependency is missing. `sqlmesh` invocation fails.
```
File "pydantic/networks.py", line 578, in pydantic.networks.import_email_validator
ModuleNotFoundError: No module named 'email_validator'
The above exception was the direct cause of the following exception:
File "/Users/alexanderbutler/Documents/harness/analytics-platform/.venv/bin/cdf", line 5, in <module>
from continuous_data_flow.cli import app
File "/Users/alexanderbutler/Documents/harness/analytics-platform/src/continuous_data_flow/cli.py", line 7, in <module>
import sqlmesh.cli.main as sqlmesh
File "/Users/alexanderbutler/Documents/harness/analytics-platform/.venv/lib/python3.10/site-packages/sqlmesh/__init__.py", line 16, in <module>
from …
```
> Fix: cli failure due to missing package

- sqlmesh/core/_typing.py
- sqlmesh/core/config/root.py
- sqlmesh/core/context.py
- sqlmesh/core/notification_target.py
- sqlmesh/core/plan/evaluator.py
- sqlmesh/core/user.py
- sqlmesh/schedulers/airflow/client.py
- sqlmesh/schedulers/airflow/common.py
- sqlmesh/schedulers/airflow/dag_generator.py
This allows us to properly create target notifications from YAML configs. For example
```yaml
default_gateway: duckdb
gateways:
duckdb:
connection:
type: duckdb
users:
- username: admin
roles:
- required_approver
notification_targets:
- type: slack_api # <-- type
notify_on:
- apply_start
- apply_failure
- apply_end
- audit_failure
token: "{{ env_var('ADMIN_SLACK_API_TOKEN') }}"
channel: UXXXXXXXXX
notification_targets:
- type: slack_webhook # <-- type
notify_on:
- apply_start
- apply_failure
- run_start
url: "{{ env_var('SLACK_WEBHOOK_URL') }}"
- type: smtp # <-- type
notify_on:
- run_failure
host: "{{ env_var('SMTP_HOST') }}"
user: "{{ env_var('SMTP_USER') }}"
password: "{{ env_var('SMTP_PASSWORD') }}"
sender: sushi@example.com
recipients:
- team@example.com
```
> Feat: Add type discriminator to notification targets

- setup.py
- tests/core/engine_adapter/test_spark.py
This fixes a regression that will be caused due to https://github.com/tobymao/sqlglot/commit/bdac905b85330e7c44d2ddcd3a84a6f0babcb08c.
TODO
> Chore: bump sqlglot to v17.3.0

- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/bigquery.py
- tests/core/engine_adapter/test_base.py
- tests/core/engine_adapter/test_bigquery.py
I noticed when answering a Slack question that we didn't properly handle if a DataFrame was passed into the `merge` method.  I made sure to update BigQuery implementation too since it does special handling of Dataframes.
> Fix: Properly support DataFrames when doing INCREMENTAL_BY_UNIQUE_KEY

- web/client/src/utils/index.ts
allows eslint to understand that `value` exists after using `isNotNil(value)`
> Fix: add type so eslint understands when value is exists

- sqlmesh/core/model/definition.py
- sqlmesh/core/renderer.py
- sqlmesh/core/test/definition.py
- sqlmesh/dbt/adapter.py
- sqlmesh/dbt/builtin.py
- tests/core/test_model.py
- dbt models may try to hit the db during rendering, so make sure the db tables are populated before rendering the model.
- Allow unit tests to override table mappings when rendering.
> Fix: Populate unittest inputs before rendering query, which may access the input tables

- sqlmesh/core/config/connection.py
It appears that even though `session_configuration` defaults to dict it doesn't appear with that default in `values` so we need to set it to dict in that case.
> Fix: Databricks session_configuration can be None

- sqlmesh/core/context_diff.py
- sqlmesh/core/model/__init__.py
- sqlmesh/core/model/common.py
- sqlmesh/core/model/definition.py
- sqlmesh/core/plan/definition.py
- sqlmesh/core/snapshot/definition.py
- tests/core/test_plan.py
Prior to this change if you added an external model then it would block being able to apply that change as forward-only. Now we only block if the model is an internal model.
> Fix: Allow forward-only on added external models

- sqlmesh/core/config/loader.py
- sqlmesh/core/context.py
- sqlmesh/utils/__init__.py
- tests/core/test_config.py
- tests/core/test_context.py
- tests/core/test_format.py
- tests/utils/test_filesystem.py
Breaking Change: Personal config files in your home directory now override config defined in a project. 
Prior to this change whenever a config was loaded it was validated as is and therefore it was expected any source of configs be complete and not partial. This made doing things like defining a password in a personal config not possible. This change combines all the config as dicts and then after that validates that combined representation. 
Python config cannot be partial and all the other configs override it if they are defined. I wonder though if we should just have it be that users either use Python or use YAML + Env vars. Open to feedback. 
Also included is some cleanup of tests where I didn't realize we could get `tmp_path` which is a `pathlib.Path` object instead of using …
> Fix!: Allow partials when loading configs + Personal Config Overrides Project

- docs/integrations/engines.md
- sqlmesh/core/config/connection.py
Also adds config validation and documentation for GCPPostgresConnectionConfig.
> Fix: Use unique type for GCPPostgresConnectionConfig

- sqlmesh/dbt/model.py
- tests/dbt/test_transformation.py
We can discern the time column for incremental by time models automatically using the dbt bigquery partition_by config, which specifies the column.
> Feat: Determine time_column from bigquery partition_by config

- sqlmesh/migrations/v0016_fix_windows_path.py
- sqlmesh/utils/metaprogramming.py
Prior to this change if a path was generated using a Windows computer it would generate a different fingerprint than a linux/macos computer. This normalizes them.
> Fix: Fix windows paths for executables

- web/client/src/context/context.ts
- web/client/src/library/components/button/Button.tsx
- web/client/src/library/components/fileExplorer/FileExplorer.tsx
- web/client/src/library/components/fileExplorer/context.tsx
- web/client/src/library/components/modal/ModalConfirmation.tsx
- web/client/src/library/pages/ide/IDE.tsx
- web/client/src/library/pages/ide/RunPlan.tsx
We have Confirmation component in multiple places , moving it to higher scope should help just reuse it from one place
> Feat: re-use ModelConfirmation component from IDE page

- sqlmesh/cli/main.py
- sqlmesh/core/dialect.py
- sqlmesh/core/model/seed.py
- sqlmesh/dbt/seed.py
- sqlmesh/integrations/github/cicd/controller.py
- sqlmesh/migrations/v0017_fix_windows_seed_path.py
- tests/core/test_dialect.py
Two fixes:
1. Windows does not support `faulthandler.register` so I just check if the attribute exists and if so then we error. Docs: https://docs.python.org/3/library/faulthandler.html#faulthandler.register
2. If a user wrote a seed path in windows format then that is how it would be stored in state. Now we ensure that windows paths are converted to linux.
> Fix: Fix Windows faulthandler and seed path

- sqlmesh/core/plan/definition.py
- tests/core/test_plan.py
Prior to this change if someone makes a change and the fingerprint is for a snapshot that already exists then we would throw an error saying that the snapshot already has intervals and that is unexpected. This enables us to do this again.
> Fix: Allow reverting to previous versions

- web/server/api/endpoints/models.py
Projects with un-inferable models, such as models with star projections of external models, would cause the UI to error.
> Fix: UI error when a model has empty columns_to_types

- sqlmesh/dbt/target.py
dbt pgsql profile parsing was treating schema name as database name
> Fix: Make dbt postgresql targeting read database name from profile correctly

- sqlmesh/core/engine_adapter/bigquery.py
It looks like `google.cloud.exceptions` is now an alias to `google.api_core.exceptions` after it was moved. In order to support a wide variety of clients we can support both paths for now and then later consider a minimum version to remove this check.
> Fix: Support dual exception paths for BigQuery

- sqlmesh/core/context.py
- sqlmesh/core/test/__init__.py
- sqlmesh/core/test/definition.py
- tests/web/test_main.py
- web/server/api/endpoints/commands.py
- web/server/models.py
This PR introduces an endpoint for the UI to trigger one or all model tests. The endpoint serializes test error and failures in the response, as well as sends the console output via the sse endpoint.
> Feat: Introduce the model test API endpoint

- sqlmesh/core/model/kind.py
- sqlmesh/dbt/model.py
I've realized that Incremental Unmanaged models should be forward_only by default to err on the side of caution.
> Fix: Set forward_only to true by default for the Incremental Unmanaged model kind

- tests/core/test_integration.py
It seems like `SHOW ALL TABLES` doesn't return views but I'm not sure how this test ever worked (but it did). 🤷
> Chore: Fix invalidating env test

- sqlmesh/core/config/gateway.py
- sqlmesh/core/config/root.py
- sqlmesh/core/config/scheduler.py
- sqlmesh/core/state_sync/engine_adapter.py
- sqlmesh/migrations/v0001_init.py
- sqlmesh/migrations/v0003_move_batch_size.py
- sqlmesh/migrations/v0004_environmnent_add_finalized_at.py
- sqlmesh/migrations/v0005_create_seed_table.py
- sqlmesh/migrations/v0007_env_table_info_to_kind.py
- sqlmesh/migrations/v0008_create_intervals_table.py
- sqlmesh/migrations/v0009_remove_pre_post_hooks.py
- sqlmesh/migrations/v0011_add_model_kind_name.py
- sqlmesh/migrations/v0012_update_jinja_expressions.py
- sqlmesh/migrations/v0013_serde_using_model_dialects.py
- sqlmesh/migrations/v0014_fix_dev_intervals.py
- sqlmesh/migrations/v0015_environment_add_promoted_snapshot_ids.py
- sqlmesh/migrations/v0016_fix_windows_path.py
- sqlmesh/migrations/v0017_fix_windows_seed_path.py
- sqlmesh/schedulers/airflow/util.py
- tests/core/test_state_sync.py
Allow users to customize the schema name for state metadata. If None or empty string is provided then no schema is used and therefore the default schema for the connection/user is used instead.
> Feat: Support custom schema name for state metadata

- docs/integrations/github.md
Prior to this comment on a PR would actually trigger a job based on code in main instead of the merge commit for the PR. This change makes sure we always use the merge commit for checking out the project code.
> Fix: CI/CD bot - Always get merge commit regardless event type

- docs/integrations/github.md
- sqlmesh/integrations/github/cicd/command.py
- sqlmesh/integrations/github/cicd/controller.py
- tests/integrations/github/cicd/test_github_commands.py
- tests/integrations/github/cicd/test_github_controller.py
Prior to this change the CI/CD bot always used the `merge` method when merging a branch (if you enable the feature). Now you can pass in what merge method you want it to use.
> Feat: CI/CD Bot Add Merge Method

- web/client/src/api/index.ts
- web/client/src/library/components/plan/Plan.tsx
- web/client/src/library/pages/ide/IDE.tsx
Before we're only sending request when canceling `apply` command
> Fix: Send cancel plan request when canceling a plan

- sqlmesh/core/console.py
2 nits I have had for awhile. 
1) `render` truncates text longer than the terminal width which makes the output unusable
Since early on, I have replaced the `ctx.obj.show_sql` function with just regular `print` in `cli.py` to fix this issue. But have been meaning to submit something here.
This tiny change fixes it.
Before:
After:
The other nit thats been around, which I couldn't get Pygment to stop doing is inserting a bunch of whitespace, so when you paste it over to bq console, its almost unreadable/unusable.
My suggestion is a `--no-pretty-print` flag.
> Fix: allow render output to wrap instead of cropping

- sqlmesh/core/engine_adapter/spark.py
- tests/conftest.py
- tests/core/engine_adapter/test_base.py
- tests/core/engine_adapter/test_base_postgres.py
- tests/core/engine_adapter/test_bigquery.py
- tests/core/engine_adapter/test_databricks.py
- tests/core/engine_adapter/test_mixins.py
- tests/core/engine_adapter/test_redshift.py
- tests/core/engine_adapter/test_spark.py
Also dry'd up some tests by simplifying mocked engine adapter creation.
> Fix: Spark partition by on state tables

- setup.cfg
- sqlmesh/core/engine_adapter/databricks.py
- sqlmesh/engines/spark/db_api/spark_session.py
I tested in Databricks running this:
```
%sql
USE CATALOG example;
```
And then 
```python
spark.read.table(table)
```
That table only exists in `example` and it worked. So you can set `USE CATALOG` and have it work across both SQL and Dataframe operations. The trick though is that you must be on Unity Catalog for this to work so we initially try `setCurrentCatalog` and then fallback to this.
> Fix: Improve Databricks Catalog setting

- sqlmesh/core/engine_adapter/spark.py
- tests/core/engine_adapter/test_spark.py
When running on latest Databricks I got an error saying it could not infer the schema for a Pandas Dataframe when inserting a new environment record. So this allows us to define the schema when we get a `columns_to_type` and the columns are all non-complex. Otherwise we still pass in None and let it infer.
> Fix: Support inserting dataframes into Environment on Databricks

- sqlmesh/cli/main.py
- sqlmesh/core/context.py
- sqlmesh/magics.py
- tests/core/test_context.py
Currently if you do run dag from magics and CLI it will not raise an exception if there is an error while applying. That means the scheduler will think that it was successful when it failed. In addition notifications would tell you it succeeded when it didn't. This change makes it so that the interfaces are aware of the outcome and can raise accordingly.
> Feat: Raise error if Run DAG Fails

- sqlmesh/core/console.py
Rich has shown to cause Databricks to freeze in the past so removing the rich progress bars to avoid this issue.
> Fix: Implement richless Databricks console for Model Creation

- sqlmesh/core/engine_adapter/bigquery.py
This seems to be a more appropriate use of the `Retry` constructor as per implementation: https://github.com/googleapis/python-api-core/blob/main/google/api_core/retry.py#L308-L324
The sleep generator is later created by the `Retry` instance itself here: https://github.com/googleapis/python-api-core/blob/main/google/api_core/retry.py#L346-L348
> Fix: Pass sleep generator parameters directly into the Retry instance in the BigQuery adapter

- sqlmesh/core/audit/definition.py
- sqlmesh/core/engine_adapter/snowflake.py
These changes ensure that we can successfully run the quickstart example in Snowflake (tested).
The two issues I faced when I tried to run `sqlmesh plan` for it were:
1) Got the error `Failed to cast variant value .... to DATE` when trying to evaluate the seed model. The problem was that the dataframe we pass in `write_pandas` had a column of type `datetime64[ns]`, but the underlying column's type was `DATE` (`ds`'s type). See related SO discussion which I included in a comment [here](https://stackoverflow.com/a/75627721).
2) After fixing the above issue, I got another error when trying to evaluate the full model, specifically when trying to run its `assert_positive_order_ids` audit. The reason was that in `Audit.render_query` we were creating a query with a table whose name is produced …
> Fix(snowflake): extract date from datetime values, quote audit's this_model

- sqlmesh/core/console.py
- sqlmesh/core/table_diff.py
- tests/core/test_table_diff.py
This PR modifies the table diff CLI output by:
- Presenting row stats by row source (both tables, source only, target only)
- Calculating column comparison stats for joined rows only
- Removing "_matches" from column comparison stats labels
- Separating row samples by row source (both tables, source only, target only)
- Reordering sample DFs so join columns are in leftmost position
- Displaying only columns with >0 mismatches in the joined sample comparison
- Interleaving source/target cols for joined sample comparison ([s__col1, t__col1, s__col2, t__col2] instead of [s__col1, s__col2, t__col1, t__col2])
---- Previous CLI output ----
---- New CLI output ----
> Feat: table diff sample by row source

- sqlmesh/core/plan/definition.py
- sqlmesh/core/scheduler.py
- sqlmesh/core/snapshot/evaluator.py
- tests/core/test_plan.py
- tests/core/test_snapshot_evaluator.py
This update ensures that we re-create views for view model snapshots even if the snapshot was categorized as `INDIRECT_NON_BREAKING` (as opposed to `FORWARD_ONLY`).
> Fix: Correctly recreate views for snapshots categorized as indirect non-breaking

- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/databricks.py
- tests/core/engine_adapter/test_base.py
- tests/core/engine_adapter/test_databricks.py
By the end of October Databricks will have a release out that supports listing columns in REPLACE WHERE. Until then we will use Replace Where without the columns listed since that the only option that works with Unity currently (although they will also be fixing that too eventually).
> Fix: Make Databricks use replace where

- sqlmesh/dbt/basemodel.py
- sqlmesh/dbt/common.py
- sqlmesh/dbt/test.py
- sqlmesh/migrations/v0020_remove_redundant_attributes_from_dbt_models.py
Amount of data in the `config` attribute of the `sushi.customer_revenue_by_day` model before the fix: 10KB
After the fix: 1.5KB
> Fix!: Exclude redundant keys from the config attribute in dbt models

- web/server/watcher.py
Currently if local db present in root , changes to db triggers file watcher and that raise an error preventing from saving file after
> Fix: Make file watcher ignore local db updates

- sqlmesh/core/snapshot/evaluator.py
- tests/core/test_snapshot_evaluator.py
Prior to this change we would check if the name started with a physical schema name but that assumes there is no catalog on the name. This makes it so we parse the name and then check if the database matches the physical schema.
> Fix: Correctly check schema names when cleaning up

- web/client/src/api/index.ts
- web/client/src/library/components/graph/ModelLineage.tsx
- web/client/src/utils/index.ts
We are not really have a use case for async debouncing. But,  the way react works in dev mode it will run hooks twice and in our case it results in multiple request sent (and canceled -> screenshot). It should not be a problem in prod build
> Fix: Remove debounce async

- sqlmesh/core/console.py
- sqlmesh/core/table_diff.py
- Change "joined" to "common"
- If diff is across environments, include env name in data comparison sample column names
- Remove s__ and t__ prefixes from s-only and t-only samples
Old styling:
New styling:
> Fix: CLI table-diff styling

- sqlmesh/core/environment.py
- sqlmesh/core/plan/definition.py
- sqlmesh/core/plan/evaluator.py
- sqlmesh/core/scheduler.py
- sqlmesh/core/snapshot/__init__.py
- sqlmesh/core/snapshot/definition.py
- sqlmesh/core/state_sync/base.py
- sqlmesh/core/state_sync/cache.py
- sqlmesh/core/state_sync/common.py
- sqlmesh/core/state_sync/engine_adapter.py
- sqlmesh/schedulers/airflow/client.py
- sqlmesh/schedulers/airflow/common.py
- sqlmesh/schedulers/airflow/plan.py
- sqlmesh/schedulers/airflow/state_sync.py
- sqlmesh/utils/dag.py
- tests/core/test_integration.py
- tests/core/test_plan.py
- tests/core/test_plan_evaluator.py
- tests/core/test_snapshot.py
- tests/core/test_state_sync.py
- tests/schedulers/airflow/test_client.py
- tests/schedulers/airflow/test_plan.py
In main we only remove the intervals that are explicitly passed in for a snapshot. In order to have this work with depends_on_past where the intervals can expand beyond that range we have missing_intervals check if intervals beyond that range should be considered missing.
This change flips that so we now remove intervals beyond the range defined if needed and then missing intervals is now more simple again and just returns what is missing for the given range.
This PR also addresses an issue (thanks for catching @crericha) where if a depends_on_past model removes intervals beyond the range then we need to make sure all downstream snapshots also remove intervals beyond that range.
> Fix: Remove intervals instead missing intervals

- .circleci/config.yml
- Makefile
- docker-compose.build.yml
Dev releases prior to this would not include the latest web code. This now ensures that each build has latest web code.
> Chore: Add dev publish command

- sqlmesh/core/plan/definition.py
- tests/core/test_plan.py
... and the auto categorization mode is set to FULL
> Fix: Fallback to the breaking change category if the model's query can't be rendered at parse time 

- docs/concepts/models/model_kinds.md
- examples/sushi/models/customers.sql
- examples/sushi/models/marketing.sql
- examples/sushi/models/raw_marketing.py
- examples/sushi/schema.yaml
- sqlmesh/core/dialect.py
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/model/__init__.py
- sqlmesh/core/model/definition.py
- sqlmesh/core/model/kind.py
- sqlmesh/core/model/meta.py
- sqlmesh/core/snapshot/evaluator.py
- sqlmesh/utils/date.py
- tests/core/engine_adapter/test_base.py
- tests/core/test_context.py
- tests/core/test_integration.py
- tests/core/test_snapshot_evaluator.py
This PR adds support for SCD Type 2 using `updated_at` timestamps. 
Follow Up PRs:
* Cleanup engine adapter Pandas overrides so it is easy to get the correct pandas implementation per engine
* Add "check column" support (checking values of columns instead of `updated_at`)
* Add dbt adapter support
> Feat: Add SCD Type 2 Support

- sqlmesh/core/engine_adapter/base.py
- tests/core/engine_adapter/test_base.py
The transpilation to spark is invalid. Error:
```
Window function row_number() requires window to be ordered, please add ORDER BY clause. For example SELECT row_number()(value_expr) OVER (PARTITION BY window_partition ORDER BY window_ordering) from table.
```
Going to hotfix by removing this entirely (user should be ensuring that their source is unique on the column they claim it to be) but open to adding it back in later if we think the cost is worth it. This was an undocumented aspect of the code so documentation does not need to be changed.
> Fix: Remove Distinct On from scd type 2

- web/client/openapi.json
- web/client/src/api/index.ts
- web/client/src/library/components/plan/Plan.tsx
- web/client/src/library/pages/ide/RunPlan.tsx
Also increased delay to be 1min. Timeout only should send an error if server is not `500` but request taking longer then `delay` to return response. Mainly when server is unresponsive (an unexpected error occurred on server). Another potential case is when calling `context.load()` from `_get_loaded_context`  triggered  and takes too long.
> Fix: Clear timeoutId and callback to avoid zombie timeouts

- sqlmesh/core/model/definition.py
- tests/core/test_snapshot.py
- tests/core/test_snapshot_evaluator.py
- tests/schedulers/airflow/test_client.py
As it turns out the interval unit may impact a partitioning scheme of the created table and hence should be a part of the data hash and not the metadata hash.
> Fix!: Make interval unit a part of the data hash

- pytest.ini
- setup.py
- sqlmesh/core/dialect.py
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/base_postgres.py
- sqlmesh/core/engine_adapter/bigquery.py
- sqlmesh/core/engine_adapter/duckdb.py
- sqlmesh/core/engine_adapter/mixins.py
- sqlmesh/core/engine_adapter/mssql.py
- sqlmesh/core/engine_adapter/mysql.py
- sqlmesh/core/engine_adapter/redshift.py
- sqlmesh/core/engine_adapter/snowflake.py
- sqlmesh/core/engine_adapter/spark.py
- sqlmesh/core/snapshot/evaluator.py
- tests/conftest.py
- tests/core/engine_adapter/__init__.py
- tests/core/engine_adapter/test_base.py
- tests/core/engine_adapter/test_bigquery.py
- tests/core/engine_adapter/test_databricks.py
- tests/core/engine_adapter/test_duckdb.py
- tests/core/engine_adapter/test_integration.py
- tests/core/engine_adapter/test_mixins.py
- tests/core/engine_adapter/test_mssql.py
- tests/core/engine_adapter/test_redshift.py
- tests/core/engine_adapter/test_spark.py
- tests/core/test_snapshot_evaluator.py
The core change is to create a single method (`_df_to_source_query`) that can be overridden by any engine to take a Dataframe and create a query. They just need to return a generator that creates expressions. Since it is a generator they can also define their own setup/teardown logic around each expression. This covers all known implementations of either converting pandas to SQL, loading pandas to temp table and then reading from the table, or create a tempView out of a PySpark Dataframe. 
One known regression is that for BigQuery and Snowflake we now always load to a temp table from a Pandas Dataframe and then copy those contents into the target table when in some cases we could have loaded the target directly. Since Pandas Dataframes are smaller data I doubt this have much actual impact …
> Chore: Improve Engine Adapter Abstraction for Handling DataFrames

- sqlmesh/core/macros.py
- sqlmesh/utils/metaprogramming.py
- tests/core/test_macros.py
Let's say we have a third-party package `foo`, which contains the following macro definition:
```python
from sqlmesh.core.macros import macro
@macro()
def test_macro(evaluator):
return "test_macro"
```
There's currently a bug where if one tries to expose this macro to their models by importing it in `macros/__init__.py`, it's not correctly resolved and will ultimately result in the following error @ runtime:
```python
SQLMeshError: Macro 'test_macro' does not exist
```
This PR aims to solve this issue by handling `Executable`s that are `IMPORT`s in `MacroEvaluator`'s constructor. Before, we'd just ignore them and nothing would be added to the evaluator's `macros` attribute, whereas now we map the macro's name to the corresponding function object after verifying that the import indeed …
> Fix: ensure external macros are resolved correctly

- sqlmesh/core/config/connection.py
- sqlmesh/core/config/gateway.py
- sqlmesh/core/config/root.py
- tests/core/test_connection_config.py
Instead of relying on Pydantic's union discriminator for connection config deserialization we now use our own custom validator which produces clear validation errors instead of garbage returned previously.
Before:
```
$ sqlmesh info
Error: 25 validation errors for Config
gateways -> local -> connection -> type
unexpected value; permitted: 'bigquery' (type=value_error.const; given=databricks; permitted=('bigquery',))
gateways -> local -> connection -> instance_connection_string
field required (type=value_error.missing)
gateways -> local -> connection -> user
field required (type=value_error.missing)
gateways -> local -> connection -> db
field required (type=value_error.missing)
gateways -> local -> connection -> type
unexpected value; permitted: 'gcp_postgres' (type=value_error.const; …
```
> Fix: Improve error reporting when validating the connection config

- sqlmesh/migrations/v0023_fix_added_models_with_forward_only_parents.py
```
File "/.../sqlmesh/core/state_sync/engine_adapter.py", line 655, in migrate
migration.migrate(self)
File "/.../sqlmesh/migrations/v0023_fix_added_models_with_forward_only_parents.py", line 39, in migrate
parsed_snapshot = snapshot_mapping[snapshot_id]
KeyError: ('analytics.fct_sales__account_module_unit', '2775306648')
```
Its possible for a migration to fail here. Added a check.
> Fix: Add check for key in migration 0023

- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/bigquery.py
- sqlmesh/core/engine_adapter/duckdb.py
- sqlmesh/core/engine_adapter/mssql.py
- sqlmesh/core/engine_adapter/snowflake.py
- sqlmesh/core/engine_adapter/spark.py
- tests/core/engine_adapter/test_spark.py
Currently if a user provides a PySpark DataFrame then we don't infer the `columns_to_types` from that DataFrame and instead rely on them to provide it (or try to process without it). This change makes it so that we will determine the SQLGlot schema from the provided PySpark DataFrame schema. This means that we now know the `columns_to_types` for both Pandas and PySpark DataFrames and therefore we can assume in code where we are explicitly handling DataFrames that we can get the `columns_to_types`. 
Also added the ability to convert a SQLGlot schema to PySpark schema. This is used when creating a DataFrame from Pandas and we want to enforce the provided schema is applied to the resulting PySpark DataFrame.
> Feat: Spark Schema to SQLGlot Schema Support

- setup.py
- sqlmesh/core/engine_adapter/redshift.py
- tests/core/engine_adapter/test_integration.py
Redshift recently added merge support but it has some constraints like no CTE's in the source query that we would need to workaround. As a result I went the easier route and just added merge support by using the Logical Merge Mixin.
> Feat: Add merge support to Redshift

- .circleci/continue_config.yml
- Makefile
- tests/core/engine_adapter/docker-compose.yaml
- tests/core/engine_adapter/test_integration.py
This change makes it so we will run these engine adapter integrations on main similar to Airflow integration tests.
> Chore: Add Automated Engine Adapter Integration Tests

- sqlmesh/core/dialect.py
- tests/core/test_dialect.py
Example:
```python
from sqlmesh.core.dialect import select_from_values_for_batch_range
values = [
(1, '2022-01-01', '{"foo":"bar"}'), 
(2, '2022-01-01', '{"foo":"qaz"}')
]
columns_to_types = {
'id': exp.DataType.build("int"), 
'ds': exp.DataType.build("text"), 
'json_col': exp.DataType.build("json")
}
print(select_from_values_for_batch_range(values, columns_to_types, 0, len(values)).sql(pretty=True))
```
> Chore: Wrap JSON strings with PARSE_JSON() in values

- sqlmesh/core/snapshot/definition.py
- sqlmesh/core/snapshot/evaluator.py
- tests/core/test_snapshot_evaluator.py
Some engines fail or behave unexpectedly when we attempt to create the same schema concurrently. 
Additionally, this update reduces the number of redundant `CREATE SCHEMA` statements.
> Fix: Create schemas sequentially when evaluating or promoting snapshots

- setup.py
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/bigquery.py
- tests/core/engine_adapter/test_bigquery.py
I've previously refactored the insert-overwrite logic for BQ to fetch partitions being overwritten from the INFORMATION_SCHEMA view instead of the actual table. 
What I didn't do, however, is actually partitioning the temporary table so that partition records appear in the aforementioned view. This PR addresses this.
> Fix: Partition a temporary table when insert-overwriting by partition in BQ

- sqlmesh/core/dialect.py
- tests/core/test_model.py
> Fix: ensure overridden parser methods are called with the appropriate args

- .circleci/continue_config.yml
- sqlmesh/core/engine_adapter/base_postgres.py
- sqlmesh/core/engine_adapter/redshift.py
There is some nuance to supporting materialized views on Postgres that the current implementation does not current address. Therefore we are removing materialized view support for Postgres until we can fully implement the required support for the feature.
> Fix!: Remove Postgres Materialized View Support

- web/client/src/library/components/documentation/Documentation.tsx
- web/client/src/library/components/editor/EditorInspector.tsx
> Fix: Move columns and rendered query to separate tabs in Editor inspector

- sqlmesh/core/state_sync/engine_adapter.py
- tests/core/test_state_sync.py
When a project's first migration fails, state tables could be left over depending on when the failure occurs. This causes problems for future migrates. This PR drops all state tables if the first migration fails.
> Fix: Drop state tables during rollback when first migration fails

- sqlmesh/core/engine_adapter/mixins.py
Previously was doing any on an iterator and also applying a transformation. What this meant if that if we got a match and there were further matches then those additional matches didn't get the transform applied to them. This could come up if using SCD Type 2 on certain engines like Postgres.
> Fix: SCD Type 2 Replace Query Mixin

- sqlmesh/core/dialect.py
- sqlmesh/core/macros.py
- tests/core/test_macros.py
This fixes an issue inadvertently introduced in https://github.com/tobymao/sqlglot/commit/8af4054d4e96b62309b1543d51548728bdba520f (later updated [here](https://github.com/tobymao/sqlglot/commit/17e39d04916e3e406307ed8922cb2597b4a6998a)). Snowflake allows `@foo` to appear in `FROM` clauses, which clashes with our macro variable syntax and hence the parsing was off, causing errors in e.g. audits because they reference `@this_model` in the `FROM` clause.
Verified that with this branch I can successfully run `sqlmesh plan` for the example project using the Snowflake dialect.
> Fix: treat Snowflake's staged file paths as MacroVars

- sqlmesh/core/test/definition.py
The expected values for a unit tests are expressed in YAML where it is difficult to express expected data types. This fix casts the types provided in the YAML to the types returned by the engine adapter which would match the actual types returned from the model.
> Fix: Ensure Unit Tests Data Types Match

- sqlmesh/schedulers/airflow/mwaa_client.py
- tests/schedulers/airflow/test_mwaa_client.py
We need to escape quotes and escape sequences within the value of this function so Airflow can recognize the string
Additionally, when we try to quote (and escape) with single quotes, Airflow returns a 500 error. We guess this is because Airflow is using escaped single quotes as part of its internal functioning
> Fix MWAA client's set_variable

- sqlmesh/core/config/connection.py
Repro (Pydantic 2 only) showing the issue:
```
class Parent:
@property
def _test_prop(self) -> str:
return "original_val"
@property
def test_prop(self) -> str:
return self._test_prop
class Child(Parent):
_test_prop = "new_val"
assert Child().test_prop == "new_val"
class ParentPydantic(PydanticModel):
@property
def _test_prop(self) -> str:
return "original_val"
@property
def test_prop(self) -> str:
return self._test_prop
class ChildPydantic(ParentPydantic):
_test_prop = "new_val"
assert ChildPydantic().test_prop == "original_val"
```
> Fix: Property Override Pydantic 2

- sqlmesh/core/plan/evaluator.py
- tests/core/test_plan_evaluator.py
Turns out Airflow CLI also logs warnings into stderr, in which case we don't want to raise an exception.
> Fix: Log MWAA CLI stderr instead of raising an exception

- sqlmesh/core/plan/evaluator.py
- sqlmesh/core/state_sync/engine_adapter.py
- sqlmesh/migrations/v0028_add_plan_dags_table.py
- sqlmesh/schedulers/airflow/api.py
- sqlmesh/schedulers/airflow/common.py
- sqlmesh/schedulers/airflow/integration.py
- sqlmesh/schedulers/airflow/mwaa_client.py
- sqlmesh/schedulers/airflow/operators/hwm_sensor.py
- sqlmesh/schedulers/airflow/plan.py
- tests/core/test_plan_evaluator.py
- tests/schedulers/airflow/test_mwaa_client.py
- tests/schedulers/airflow/test_plan.py
MWAA relies on shell / bash to set variables in Airflow and bash has limit on a number of characters that can be passed in. 
With this update we no longer rely on Airflow to store our Plan Application DAG specs and instead use our own internal state.  The additional `_plan_dags` table is added to our state to support this.
> Feat: Use internal state instead of Airflow Variables to store Plan DAG specs

- sqlmesh/core/engine_adapter/__init__.py
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/base_postgres.py
- sqlmesh/core/engine_adapter/bigquery.py
- sqlmesh/core/engine_adapter/duckdb.py
- sqlmesh/core/engine_adapter/mixins.py
- sqlmesh/core/engine_adapter/mysql.py
- sqlmesh/core/engine_adapter/shared.py
- sqlmesh/core/engine_adapter/spark.py
- sqlmesh/core/snapshot/evaluator.py
- sqlmesh/core/state_sync/common.py
- sqlmesh/core/state_sync/engine_adapter.py
- sqlmesh/dbt/adapter.py
- tests/core/engine_adapter/test_duckdb.py
The pymssql library [always begins transactions](https://github.com/pymssql/pymssql/issues/460) - "pymssql opens transaction on connection start with 'BEGIN TRAN' and after conn.commit() it commits already opened transaction and then open new one again."
In some cases we did not explicitly close them, leading to hung sessions.
The fix wraps calls to `cursor.execute()` in a transaction **in the base engine_adapter**, ensuring they are properly closed. 
Some engines do not support transactions or handle them idiosyncratically, such that this approach does not work. Engine adapters are now given a flag that determines whether their executions occur within transactions. 
At this time, BigQuery, DuckDB, and Spark have the flag set to False.
> Fix(mssql): execute within transactions to prevent hanging

- sqlmesh/cli/main.py
This command has been deprecated for many months. Finally deleting it.
> Chore: Remove ide CLI command

- docs/integrations/github.md
- sqlmesh/integrations/github/cicd/controller.py
Prior to this we were rely on rich console's inference of the environment to not include color in the output text. This now forces that behavior. 
Also includes a documentation fix for the CI/CD bot.
> Fix: force no color when using github markdown console

- sqlmesh/core/macros.py
- sqlmesh/core/model/definition.py
Apparently this part:
```python
if mocked_star.name in (self.columns_to_types or {}):
```
was causing `self.columns_to_types` to render the query in `optimize=True` mode and so we would get a warning pre-evaluation time for the sushi project because the mocked column was unresolved. I think this PR makes it a little bit cleaner, it mimics what we do to detect actual star projections.
> Chore: refactor the detection of SQLMESH_MOCKED_STAR

- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/mssql.py
This PR wraps `fetchone`, `fetchall`, and `fetchdf` in transactions to ensure query results are still available for fetching after we return from `execute`.
> Fix(MSSQL): wrap fetches in transaction

- docs/integrations/engines/bigquery.md
- sqlmesh/schedulers/airflow/hooks/bigquery.py
Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1697020053051689
This results in the Airflow Operator client now having parity with the local client that is created for built-in. 
Note: This is untested in order save time having to actually bring up Airflow and test so I would appreciate extra 👀 on it.
> Fix: Support Setting Location in BigQuery Airflow Operator

- sqlmesh/core/_typing.py
- sqlmesh/core/dialect.py
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/base_postgres.py
- sqlmesh/core/engine_adapter/bigquery.py
- sqlmesh/core/engine_adapter/databricks.py
- sqlmesh/core/engine_adapter/duckdb.py
- sqlmesh/core/engine_adapter/mssql.py
- sqlmesh/core/engine_adapter/mysql.py
- sqlmesh/core/engine_adapter/postgres.py
- sqlmesh/core/engine_adapter/redshift.py
- sqlmesh/core/engine_adapter/shared.py
- sqlmesh/core/engine_adapter/snowflake.py
- sqlmesh/core/engine_adapter/spark.py
- sqlmesh/core/snapshot/evaluator.py
- sqlmesh/core/state_sync/common.py
- sqlmesh/core/test/definition.py
- sqlmesh/dbt/adapter.py
- sqlmesh/utils/errors.py
- tests/core/engine_adapter/test_base.py
- tests/core/engine_adapter/test_bigquery.py
- tests/core/engine_adapter/test_databricks.py
- tests/core/engine_adapter/test_integration.py
- tests/core/engine_adapter/test_mssql.py
- tests/core/engine_adapter/test_postgres.py
- tests/core/test_context.py
- tests/core/test_snapshot_evaluator.py
- tests/core/test_state_sync.py
Controversial change to highlight: Removed the field `catalog_name` and instead let callers provide a `TableName` which means it can either be a string or `exp.Table` object. 
Added engine adapter methods:
* `get_current_catalog`
* `set_current_catalog`
New Property: `CatalogSupport`
This tells the `set_catalog` decorator what level of catalog support the engine adapter has in order to set the catalog properly. 3 levels:
* Unsupported
* Requires Set Catalog
* Full Support
`Requires Set Catalog` means that operations cannot be provided with the catalog but instead they need `set_current_catalog` against the catalog and then they can provide the operation but now with the catalog dropped. This always refers to the target of the operation (ex: if drop schema, the schema being drooped) and we …
> Fix: Add Proper Catalog Support to Engine Adapter

- sqlmesh/core/engine_adapter/bigquery.py
- sqlmesh/core/schema_diff.py
- tests/core/test_schema_diff.py
If types are compatible (i.e: alterable) then that also means for BigQuery that the inverse relationship can be a no-operation for us. We can't alter but we can insert new values without issue. 
This can later be expanded to more engines but just focusing on BigQuery for now.
> Feat: Support BigQuery No-Op Coerce Types

- docs/concepts/models/model_kinds.md
- setup.py
- sqlmesh/core/dialect.py
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/mixins.py
- sqlmesh/core/model/kind.py
- sqlmesh/core/model/meta.py
- sqlmesh/core/snapshot/evaluator.py
- tests/core/engine_adapter/test_base.py
- tests/core/test_snapshot_evaluator.py
Users can now override the when matched logic for `INCREMENTAL_BY_UNQIUE_KEY` model kind. Note that macros are not supported in this PR.
> Feat: Support When Matched Expression for Merge

- sqlmesh/core/dialect.py
- sqlmesh/core/macros.py
- tests/core/test_snapshot_evaluator.py
This PR along with https://github.com/TobikoData/sqlmesh/commit/c637908ab859617b18dafc54335fa38dd6a08dd6 allows SQLMesh users to conditionally execute pre/post-statements based on the current runtime stage, using the good ol' `@IF` macro: `@IF(condition, statement)`.
~The reason I didn't just implement this using the good ol' `@IF(...)` macro, is that we don't account for statements / commands in normal function calls and hence we'd need to override its parser to account for them, thus making the `_parse_if` method more complex.~ Refactored to use `@IF` instead.
> Feat: add support for @IF(cond, statement) macro

- setup.py
Looks like mypy dropped 3.7 support with 1.5+. So just upgrading to 1.4 until we can also drop 3.7.
> chore: upgrade mypy

- .circleci/continue_config.yml
- Makefile
- tests/core/engine_adapter/test_integration.py
Doing this to make CI less flaky on main. We should do two things in order to re-enable remote tests:
* Make sure the remote tests read/write to isolated path (in case someone else is running tests locally)
* Add retry to all adapters in order to deal with network blips (Redshift seems to have the most issues with this)
Until then we need to make sure to run these manually when making engine adapter changes.
> chore: ci only run local engine integration tests

- Makefile
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/utils/__init__.py
- tests/conftest.py
- tests/core/engine_adapter/__init__.py
- tests/core/engine_adapter/test_bigquery.py
- tests/core/engine_adapter/test_mixins.py
- tests/core/engine_adapter/test_mssql.py
MySQL table names must be <=64 characters long. 
Some SQLMesh temp table names exceed that, so this PR changes the length of the random ID embedded in the table name from a 32-character UUID4 to 8 alphanumeric characters.
> Fix(mysql): use 8-character random ID for temp table names

- sqlmesh/dbt/builtin.py
- sqlmesh/dbt/target.py
- tests/dbt/test_config.py
Now that we don't store all target config fields in the snapshot, we need to be able to get the dbt classes (relation, column, and quote_policy) without instantiating the TargetConfig class.
> Fix: Get dbt classes without all config fields present

- sqlmesh/utils/cache.py
For end users this shouldn't matter since the SQLMesh version will change with new migration scripts this does help with local testing where we add a migration script but we still get cached results because no version change has happened.
> chore: include schema version in cache key

- sqlmesh/core/engine_adapter/shared.py
- tests/core/engine_adapter/config.yaml
- tests/core/engine_adapter/docker-compose.yaml
- tests/core/engine_adapter/spark/Dockerfile
- tests/core/engine_adapter/spark/conf/hive-site.xml
- tests/core/engine_adapter/spark/conf/spark-defaults.conf
- tests/core/engine_adapter/test_integration.py
- tests/core/engine_adapter/trino/catalog/datalake.properties
- tests/core/engine_adapter/trino/catalog/testing.properties
Adds Spark to our integration tests and since it is deployed locally it means it will be tested on all merges to main. 
I ended up adding the local config as a checked in YAML so now users just need to have connection config to external services defined locally. 
Note: Iceberg was just included because I needed a way to add a catalog and I was pulling my hair out trying to figure out how to do it when the catalog isn't a Iceberg/Delta catalog. I just eventually gave up and made it an Iceberg catalog. The tests involving creating objects or loading data are all done agains the default catalog and therefore it is reading/writing Parquet files to "S3" (Minio).
> chore: add local spark to integration tests

- sqlmesh/core/node.py
- sqlmesh/core/snapshot/definition.py
- sqlmesh/core/state_sync/common.py
- tests/core/test_integration.py
- tests/core/test_plan.py
- tests/core/test_scheduler.py
- tests/core/test_snapshot.py
- tests/core/test_state_sync.py
- tests/schedulers/airflow/test_plan.py
if a project does not have a start date set, models with monthly cron would never run because the default start date was yesterday.
> Fix: start dates of models are now relative to cron

- examples/sushi/config.py
- sqlmesh/core/config/connection.py
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/databricks.py
- sqlmesh/utils/connection_pool.py
- tests/conftest.py
- tests/core/test_integration.py
Prior approach didn't take into account that a connection could be closed (like after running tests) and once re-opened it wouldn't have the catalogs applied. Originally in another PR I modified the connection factory to init the catalogs but that doesn't work because the cursor object created by DuckDB is unique from the connection object from which it is created (despite them saying it is a duplicate). Therefore we need to make sure that whenever a cursor is created that it gets the catalog initialized.
This is more thoroughly tested in the default catalog PR that actually uses these catalogs and ensures the connection is configured correctly.
> fix: duckdb init catalogs at cursor level

- .circleci/continue_config.yml
Looks like we still aren't waiting long enough: https://app.circleci.com/pipelines/github/TobikoData/sqlmesh/8149/workflows/08276a54-3e95-4329-ae05-ef325d214116/jobs/56809
> chore: increase wait time for ci containers

- sqlmesh/utils/dag.py
- tests/utils/test_dag.py
This is with the changes introduced in this PR:
```
➜  cat models/a.sql
model (name a, kind full);
select id from b
➜ cat models/b.sql
model (name b, kind full);
select id from a
➜  cat models/normal.sql
model (name normal, kind full);
select 1 as a%
➜  sqlmesh info
Error: Detected a cycle in the DAG. Please make sure there are no circular references between models.
Last models added to the DAG: normal
Possible model candidates to check for circular references: b, a
```
If I get rid of the `normal.sql` model, then the error message becomes:
```
➜  sqlmesh info
Error: Detected a cycle in the DAG. Please make sure there are no circular references between models.
Possible model candidates to check for circular references: b, a
```
> Chore: improve error message when cycle is detected in model graph

- sqlmesh/core/config/connection.py
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/base_postgres.py
- sqlmesh/core/engine_adapter/databricks.py
- sqlmesh/core/engine_adapter/shared.py
- tests/core/test_connection_config.py
Postgres engines allow only creating objects within the catalog assigned in the connection itself. Therefore they do support catalogs but only creating objects within the connection catalog. This change will make sure that the catalog being targeted matches the connection catalog and if so it will remove the catalog and perform the operation.
Redshift allows querying across catalogs (not creating objects) but this distinction does not matter for the `set_catalog` decorator since it is focused on the objects actually being created and not the expressions being used.
> feat: Add Single Catalog Support to Postgres Engines

- sqlmesh/core/state_sync/base.py
- sqlmesh/core/state_sync/engine_adapter.py
- sqlmesh/migrations/v0032_add_sqlmesh_version.py
- tests/core/test_state_sync.py
Current behavior:
```
Error: SQLMesh (local) is using version '30' which is behind '31' (remote). Please upgrade SQLMesh ('pip install --upgrade "sqlmesh==31"' command).
```
The suggested command is incorrect because we're interpolating `versions.schema_version` instead of the actual SQLMesh package version. To overcome this issue I added a new column `sqlmesh_version` to the `_versions` state table which is currently only used to improve the UX when an error message is raised.
> Fix!: show proper pip install command when sqlmesh schema version is behind

- sqlmesh/core/state_sync/base.py
- tests/core/test_state_sync.py
> Fix: add validators to handle None values in Versions class

- sqlmesh/core/engine_adapter/mixins.py
- sqlmesh/core/engine_adapter/spark.py
- tests/core/engine_adapter/test_spark.py
It appears when writing local files with spark it does not like a table that starts with double underscore. So I updated temp table for spark to remove it.
Also re-organized things a bit to remove the pattern where we got a query from source query and then made a source query again.
> fix: spark temp tables

- sqlmesh/cli/main.py
**Problem:**
This has bugged me for awhile, but current way `sqlmesh render` works has a lot of issues if your SQL is wider than console length. It automatically wraps and insert new lines which breaks usage in scripts and even copy paste. Furthermore it pads the end of line all the way out to the terminal width. Which is also really annoying. Lastly, and I don't know if this is consistent -- I get truncated text sometimes too. 
**Solution:**
Let people just dump the output as is to stdout, so we can use it in our vimscripts and so on. Or even so its cleaner to yank. 
Add `--no-pretty-print` to render command which just uses simple print stmt
> Feat: Optionally disable formatting of model sql in render

- sqlmesh/cicd/bot.py
- sqlmesh/cli/main.py
- sqlmesh/integrations/github/cicd/controller.py
- sqlmesh/utils/__init__.py
It can be tricky to understand what is going on with the bot so now if a user sets `SQLMESH_DEBUG` to `1` then they will get the normal debug logging and then also bot specific log messages when using the CI/CD bot.
> chore: Add Logging to Github CI/CD Bot

- sqlmesh/integrations/github/cicd/controller.py
Despite what the documentation and error message says, Github limits summary messages based on byte size instead of character length. Therefore prior to this fix if you had a special character in the output that required more than 1 byte you could get an error saying that the message size was too large. This now correctly truncates based on bytes instead of characters.
> fix: github cicd truncate byte length

- docs/concepts/macros/sqlmesh_macros.md
- docs/concepts/models/sql_models.md
> Chore: update docs to include MacroEvaluator.columns_to_types

- sqlmesh/core/plan/definition.py
- sqlmesh/integrations/github/cicd/controller.py
- tests/integrations/github/cicd/test_github_controller.py
I believe the way this happens is if a PR environment is created and then we go to report what was loaded compared to prod and prod has changed. If that is the case then when we diff we could get new snapshots that have not been categorized. This change allows those to flow through and just get reported as uncategorized snapshots.
> fix: github cicd support uncategorized snapshots

- examples/sushi/macros/macros.py
- examples/sushi/macros/utils.py
- sqlmesh/core/loader.py
- sqlmesh/utils/__init__.py
- sqlmesh/utils/metaprogramming.py
This aims to fix the bug demonstrated below:
```
➜  cat models/test.sql
model (name test, kind full);
select @bar()
➜  cat macros/macro_a.py
from sqlmesh.core.macros import macro
@macro()
def foo(evaluator):
return "'foo'"
➜  cat macros/macro_b.py
from macros.macro_a import foo
from sqlmesh.core.macros import macro
@macro()
def bar(evaluator):
return f"{foo(evaluator)} AS foo"
➜  sqlmesh render test
Error: Duplicate key 'foo' found in UniqueKeyDict<macros>. Call dict.update(...) if this is intentional.
```
It also gets rid of a duplicate implementation of the python file importer method defined under `Loader`, which might need to be double-checked to ensure it's equivalent to the definition under `metaprogramming.py` that took its place.
> Fix: be more lenient when registering duplicate functions

- docs/concepts/models/model_kinds.md
- sqlmesh/core/dialect.py
- tests/core/test_model.py
- Updates documentation to get rid of redundant parentheses in coalesced unique key
- Makes the parser more lenient so it can recognize parenthesized coalesced unique keys
> Fix: allow parsing functions as property values in model meta

- sqlmesh/dbt/target.py
Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1699749136590689
> Fix: Return a column type instead of an instance of the type in Redshift dbt target

- sqlmesh/core/renderer.py
- tests/core/test_context.py
- tests/core/test_model.py
prior to this commit, render a model would auto expand any snapshot that did not have a version (uncommitted). this way the render query would always generate a runnable sql query. however, with large projects, expansion is extremely expensive and makes the default render unusable.
> Fix!: remove auto expansion in render of unpushed snapshots

- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/base_postgres.py
- tests/core/engine_adapter/test_base_postgres.py
Steps to recreate:
1. Create a project with `sqlmesh init postgres`
2. Change default gateway to postgres database
3. Delete full_model and its test
4. Change incremental_model to `kind VIEW` and set `allow_partials true`
5. Run `sqlmesh plan` twice
Error:
```
======================================================================
Successfully Ran 0 tests against postgres
----------------------------------------------------------------------
No differences when compared to `prod`
Models needing backfill (missing dates):
└── sqlmesh_example.view_model: 2023-11-15 - 2023-11-15
Apply - Backfill Tables [y/n]: y
Evaluating models ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.0% • 1/1 • 0:00:00
FAILED processing snapshot name='sqlmesh_example.view_model' …
```
> Fix(postgres): view model support

- examples/sushi/models/items.py
- tests/core/test_model.py
Some engines only allow specific table properties
> Chore: test python model table properties inline

- sqlmesh/core/test/definition.py
- tests/core/test_test.py
Implements the first feature in https://github.com/TobikoData/sqlmesh/issues/1637
TL;DR: input columns can now be omitted in unit tests, implicitly giving them `NULL` values.
> Feat: allow omitting columns in unit tests

- sqlmesh/core/dialect.py
- sqlmesh/core/model/common.py
- sqlmesh/core/model/definition.py
before this change, dialect.parse always does a regex to find the model dialect override. this is expensive and not necessary when the dialect is known ahead of time like in serialization.
> fix: don't check for dialects when they are already known

- docs/concepts/tests.md
- sqlmesh/core/test/definition.py
- tests/core/test_test.py
Extends the previous [implementation](https://github.com/TobikoData/sqlmesh/pull/1714) of item 1 in #1637 to also allow omitting output columns.
> Feat: allow omitting output columns in unit tests, add docs

- docs/integrations/overview.md
This PR adds a link to the [Kestra integration](https://kestra.io/).
> docs: add kestra integration link

- docs/concepts/tests.md
- sqlmesh/cli/main.py
- sqlmesh/core/context.py
- sqlmesh/core/test/definition.py
- tests/core/test_test.py
- tests/web/test_main.py
Addresses the second item in https://github.com/TobikoData/sqlmesh/issues/1637. Below I've shared some examples to demonstrate how this looks, both in the CLI and the UI.
TL;DR instead of `difflib.ndiff` the diff will now be produced with `DataFrame.compare`.
EDIT: check out https://github.com/TobikoData/sqlmesh/pull/1741#issuecomment-1821065762 for updated views of the error reporting.
<details>
<summary>A single column in a single row is incorrect (outdated)</summary>
CLI:
```
➜  tests sqlmesh test
F
======================================================================
FAIL: test_example_full_model (tests/test_full_model.yaml)
----------------------------------------------------------------------
AssertionError: Data differs
num_orders
expected actual
0        5.0    2.0 …
```
> Feat: show only relevant columns (as DataFrames) when unit tests fail

- sqlmesh/core/context.py
Just a small change so that configs can be passed already in a dictionary so you do not have to go through the `_load_configs` plumbing and/or be constrained to pass in a `Config` object which is then [applied to all paths](https://github.com/z3z1ma/sqlmesh/blob/4f29e0f94c71a975f846476e38304b651b175a32/sqlmesh/core/context.py#L1436-L1437). Per path config should be doable without hacking at context if it is externally suppliable.
> Feat: allow passing config to context with expected type

- setup.py
Previously, DuckDB 0.8.1 and pandas 2.1.0 weren't compatible.
> Chore: Unpin pandas

- sqlmesh/integrations/github/cicd/controller.py
- tests/integrations/github/cicd/test_github_controller.py
Previously just check run updated were chunked up but now this will chunk up comments too. Note that like before this chunking does not respect markdown formatting so the final output can be messy. Ideally each caller has a way to compact output if needed that still provides a full formatted result but this at least ensures we don't error and captures as much as we can.
> fix: cicd chunk up comments and check runs

- sqlmesh/core/config/connection.py
I double checked and the rest of the ones listed are valid so the bug was just password. 
Resolves: https://github.com/TobikoData/sqlmesh/issues/1753
> Fix: Trino Remove Password from Connection Kwargs

- sqlmesh/core/context.py
- Fix issue when calling `sqlmesh run` without any arguments. Default environment is prod.
- Fix issue with incorrect argument to run_failure notification function.
> Fix: Run notifications

- sqlmesh/dbt/target.py
This now matches what is in dbt: https://github.com/dbt-labs/dbt-redshift/blob/e88a48331f05b7024cadc191d554500de4cad2da/dbt/adapters/redshift/connections.py#L119
It looks like before we implemented it to match Postgres: https://github.com/dbt-labs/dbt-core/blob/5488dfb9926c3f81e6a80bd0d8b01fe7f0ac7a60/plugins/postgres/dbt/adapters/postgres/connections.py#L29
Also removed `keepalives_idle` since that wasn't used/isn't supported (also come over from Postgres).
> fix: redshift dbt connection timeout none

- docs/concepts/tests.md
- docs/reference/cli.md
- sqlmesh/cli/example_project.py
- sqlmesh/cli/main.py
- sqlmesh/core/context.py
- sqlmesh/core/test/__init__.py
- sqlmesh/core/test/definition.py
- tests/core/test_test.py
This PR introduces a way to automate the generation of unit tests for a given model, by specifying how its dependencies should be populated with data. This is achieved through user-supplied queries which are executed against the default warehouse, but the interface can certainly be improved over time.
Currently, the CLI command looks like this:
```
$ sqlmesh create_test model_to_test -q dep1 'SELECT ...' -q dep2 'SELECT ...' ...
```
To be addressed in a future PR:
- Update other interfaces to add support for this command (Notebooks, UI)
- Add an "append" mode which updates an existing test, see https://github.com/TobikoData/sqlmesh/pull/1756#discussion_r1406937195
Notes:
- Updated some type hints for consistency, e.g. `dict[...]` to `t.Dict[...]`
- Updated the example project's `inputs` …
> Feat: automate unit test generation

- sqlmesh/core/dialect.py
- sqlmesh/core/test/definition.py
- tests/core/test_dialect.py
- tests/core/test_test.py
The current implementation of select_from_values_for_batch_range constructs an empty VALUES () clause in case it's passed an empty list for its 'values' argument, which is usually a syntax error.
This commit makes it so we instead return a dummy query that's guaranteed to not return any rows (using a WHERE FALSE filter).
Additionally, it fixes a few bugs in the unit test module related to test cases that contain empty input / output rows.
> Fix: handle empty list in select_from_values_for_batch_range

- sqlmesh/core/audit/definition.py
- sqlmesh/core/dialect.py
- sqlmesh/core/model/definition.py
- tests/core/test_dialect.py
- tests/integrations/github/cicd/test_integration.py
When diffing models/audits, we extract meta, statements, and queries from their rendered definitions and diff them separately. This PR simplifies diffing by just diffing the rendered definitions.
> Chore: Simplify text_diff

- setup.py
The recent release of the pytest-asyncio library, v0.23.0+, breaks one of our unit tests (sqlmesh/tests/core/test_context.py::test_ignore_files). Will investigate further, but pinning pytest-asyncio for now.
> Chore: Pin pytest-asyncio

- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/redshift.py
- tests/core/engine_adapter/test_integration.py
- tests/core/engine_adapter/test_redshift.py
in redshift, CTAS types are not determinstic based on the logical plan of a query. adding limits or where false to an md5(...) will change from the expected varchar(32) into a varchar(1). this pr tries to detect these and then force casts projections to the right types.
> feat: redshift plan parsing to address ctas varchar(1) bug

- sqlmesh/core/config/scheduler.py
- tests/core/test_config.py
The validator used to work in Pydantic v1 since a field's alias defaulted to the field's name if there was no alias specified. In v2, it's None if not specified.
> Fix: Cloud_composer scheduler config supported field validation

- sqlmesh/core/test/definition.py
- tests/core/test_test.py
Fixes #1799
Not quite sure if this change will have unintended side effects, but normalizing "non-existent" values to `np.nan` instead of `None` (previous approach) seemed just as reasonable to me.
@vchan the previous logic was introduced in https://github.com/TobikoData/sqlmesh/pull/1110, just tagging to make sure I'm not missing additional context here.
> Fix!: workaround for weird date dtype bug exposed by duckdb v0.9.2

- web/client/openapi.json
- web/client/src/App.tsx
- web/client/src/api/index.ts
- web/client/src/context/context.ts
- web/client/src/context/plan.ts
- web/client/src/library/components/plan/Plan.tsx
- web/client/src/library/components/plan/PlanActions.tsx
- web/client/src/library/components/plan/PlanActionsDescription.tsx
- web/client/src/library/components/plan/PlanApplyStageTracker.tsx
- web/client/src/library/components/plan/PlanOptions.tsx
- web/client/src/library/components/plan/help.spec.ts
- web/client/src/library/components/plan/help.ts
- web/client/src/library/components/plan/hooks.ts
- web/client/src/library/pages/ide/IDE.tsx
- web/client/src/library/pages/ide/PlanSidebar.tsx
- web/client/src/library/pages/ide/RunPlan.tsx
- web/client/src/models/plan-action.ts
- web/client/src/models/tracker-plan-apply.ts
- web/client/src/models/tracker-plan-cancel.ts
- web/client/src/models/tracker-plan-overview.ts
- web/client/src/models/tracker-plan.ts
- web/client/src/utils/index.ts
Previous update to plan flow has introduced some regression. It inaccurately display stages and messages (Button Labels). Also not showing changes to Model Metadata and when there are some backfills but no changes.
I added class to control current `plan-action` from single source.
> Chore: Add plan action class to control plan flow

- sqlmesh/dbt/basemodel.py
- tests/dbt/test_model.py
In the dbt workflow, tests are run separately from transformation, so it is okay to have circular test references. In SQLMesh, tests (aka audits) are run during transformation to prevent bad data from propagating and thus the test dependencies are included in dag construction. This PR provides a clearer error message on how to fix these circular test references, so that the project can use the SQLMesh workflow.
> Feat: Detect circular references from dbt tests

- setup.py
3.0.0 was recently released which started breaking our builds: https://github.com/sdispater/pendulum/releases/tag/3.0.0
> Chore: Fix pendulum dependency

- sqlmesh/cli/main.py
The context created by the CLI cannot be passed to the uvicorn process so the UI will need to create its own anyway.
> Chore: Do not load a context when starting the UI

- web/server/api/endpoints/plan.py
Very slow, especially if there are lots of models.
> Fix: Do not load environments to get their naming info

- sqlmesh/core/plan/__init__.py
- sqlmesh/core/plan/definition.py
- sqlmesh/integrations/github/cicd/controller.py
- tests/integrations/github/cicd/test_github_controller.py
- tests/integrations/github/cicd/test_integration.py
Prior to this change if a user had changes in a PR that had overlapping subdags then the plan summary would duplicate those entries. Now each model will be represented once. 
In addition, took the opportunity to cleanup old "Loaded" and "Unloaded" snapshots since they did not end up being useful outside of the context of the CI/CD bot.
> Fix: CI/CD Bot Duplicate Model Names in Output

- sqlmesh/__init__.py
- sqlmesh/cicd/bot.py
- sqlmesh/cli/main.py
if i call configure_logging() in the notebook, i expect ignore_warnings to work, with the current it doesn't work because write_to_stdout is set to true make the default log level info.
> fix!: make logging more intuitive to use

- tests/web/test_main.py
- web/client/src/api/instance.ts
- web/server/api/endpoints/commands.py
- web/server/api/endpoints/plan.py
when returning `None` from endpoint with `200` response has `null` in it. So returning 204  is more predictable
> Chore: Return 204 on empty reuqest

- sqlmesh/core/console.py
- sqlmesh/integrations/github/cicd/controller.py
- tests/integrations/github/cicd/test_integration.py
Prior to this change if you had an error during PR plan application you would just get a plan application error in the output and none of the details of the error from the individual node evaluations themselves. This improves that so those errors will be printed.
> feat: CI/CD Capture Console Errors

- sqlmesh/core/dialect.py
- tests/core/test_context.py
This fixes a bug when calling render from the CLI or the UI.
```
File "sqlmesh/core/dialect.py", line 780, in select_from_values
for i in range(0, num_rows, batch_size):
ValueError: range() arg 3 must not be zero
```
> Fix: Handle 0 batch_size in select_from_values

- sqlmesh/cli/main.py
[We don't support](https://sqlmesh.readthedocs.io/en/latest/reference/cli/) a `version` command anymore, so I got rid of a no-op branch in the CLI
> Chore: clean up dead code related to old version CLI command

- sqlmesh/core/loader.py
I originally thought we just needed this potentially for Airflow but realized that it is needed for reason given in the comment.
> fix: add back default catalog in cache entry id

- sqlmesh/core/engine_adapter/redshift.py
This doesn't change any functionality since Redshift is currently being set as only supporting a single catalog. The fact that Redshift doesn't support `USE <catalog>` or something similar is currently preventing us from allowing Redshift to leverage multi-catalog features.
> chore: redshift cleanup incorrect set catalog

- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/base_postgres.py
- sqlmesh/core/engine_adapter/bigquery.py
- sqlmesh/core/engine_adapter/databricks.py
- sqlmesh/core/engine_adapter/duckdb.py
- sqlmesh/core/engine_adapter/mixins.py
- sqlmesh/core/engine_adapter/mssql.py
- sqlmesh/core/engine_adapter/mysql.py
- sqlmesh/core/engine_adapter/postgres.py
- sqlmesh/core/engine_adapter/redshift.py
- sqlmesh/core/engine_adapter/shared.py
- sqlmesh/core/engine_adapter/snowflake.py
- sqlmesh/core/engine_adapter/spark.py
- sqlmesh/core/engine_adapter/trino.py
Instead of having to put a decorate on each class method in order for it to run `set_catalog`, now it is defined at the class level with overrides defined there too. This removes the chance of mistakes when adding new public methods and removes some code redundancy of having to override parent methods just to override `set_catalog`. 
The only logic change is reorganizing the decorator to be a class decorator and checking the attributes of a class to find methods to wrap.
> chore: Make set catalog a class decorator

- tests/web/test_main.py
- web/client/openapi.json
- web/client/src/context/context.ts
- web/client/src/library/components/documentation/Documentation.tsx
- web/client/src/library/components/editor/Editor.tsx
- web/client/src/library/components/editor/EditorFooter.tsx
- web/client/src/library/components/editor/EditorInspector.tsx
- web/client/src/library/components/editor/EditorPreview.tsx
- web/client/src/library/components/fileExplorer/File.tsx
- web/client/src/library/components/graph/Graph.tsx
- web/client/src/library/components/graph/ModelNode.tsx
- web/client/src/library/pages/docs/Content.tsx
- web/client/src/models/file.ts
- web/client/src/models/sqlmesh-model.ts
- web/server/api/endpoints/files.py
- web/server/api/endpoints/meta.py
- web/server/api/endpoints/models.py
- web/server/main.py
- web/server/models.py
- web/server/settings.py
- web/server/watcher.py
Decouple files from models to speed up loading of file system (files don't need loaded_context).
Move checking for whether a file is a model and of which type to Model class
> Fix: Don't send sqlmesh type with files, and handle that independently on ui

- sqlmesh/core/loader.py
Someone would only hit this if doing programatic changes but that did happen to me when writing some new tests. I don't see an issue leaving it as a float since the period will be later sanitized anyways: https://github.com/TobikoData/sqlmesh/blob/19432843d0c09f12aa24fbce4679bc429cfce30c/sqlmesh/utils/cache.py#L122
> fix: caching sub-second accuracy

- sqlmesh/core/context.py
Prior to this if you had a Python model that returned a SQLGlot expression it would try to format it assuming it contained just SQL when it contained Python.
> fix: only SQLGlot format sql files

- docs/concepts/macros/sqlmesh_macros.md
- sqlmesh/core/macros.py
- sqlmesh/core/model/definition.py
- tests/core/test_model.py
An attempt at allowing inline defs to be callables like macros. Works for the simplest case.
```sql
MODEL(...);
-- A macrodef should be able to take a simple lambda and do substitution as a callable
-- Allows for highly specific macros to be colocated with the model
-- Makes models with complex biz logic easier to break down, inline
@DEF(convert_to_int, x -> case when left(x, 1) = 'A' then 1 when left(x, 1) = 'B' then 2 when left(x, 1) = 'C' then 3 end);
SELECT
id,
cust_rank_1, 
cust_rank_2,
cust_rank_3
@convert_to_int(cust_rank_1) as cust_rank_1_int,
@convert_to_int(cust_rank_2) as cust_rank_2_int,
@convert_to_int(cust_rank_3) as cust_rank_3_int
FROM
some.model
```
Can add a test and run this direction if you think its the right way. Otherwise defer to you all 😃
> Feat: Simple inline macro functions

- sqlmesh/migrations/v0036_delete_plan_dags_bug_fix.py
Workaround if you hit an issue using Airflow after migrating to `0.63.0`:
Run `DELETE FROM sqlmesh._plan_dags;` against your state backend.
> fix: include plan_dags in migration

- sqlmesh/cli/main.py
Since these are multiple Click will populate the values as an empty tuple and therefore they will always exist. As a result we would never have these set to None despite expecting None to be provided.
> fix: correctly set missing model selectors to None

- sqlmesh/core/context.py
- sqlmesh/core/state_sync/base.py
- sqlmesh/core/state_sync/engine_adapter.py
- sqlmesh/schedulers/airflow/api.py
- sqlmesh/schedulers/airflow/client.py
- sqlmesh/schedulers/airflow/state_sync.py
- tests/core/test_state_sync.py
- tests/schedulers/airflow/test_client.py
This update ensures that when using model selector the default plan end will be inferred using the last backfilled interval of the selected model on prod.
> Feat: Use max interval end of selected models when picking a default plan end

- sqlmesh/core/config/scheduler.py
Provided we now use FQN for Snapshot names the size of each individual Snapshot ID has grown significantly. Therefore we need to reduce the default batch size to account for the increased snapshot ID payload size.
> Fix: Default value for the max snapshot IDs per request used for Cloud Composer

- .circleci/continue_config.yml
- Makefile
- examples/airflow/docker_compose_decorator.py
- pytest.ini
- setup.py
- tests/conftest.py
- tests/core/test_integration.py
- tests/integrations/jupyter/test_magics.py
Low effort way to improve test performance. Cut times locally in half. Changed Circle from Small to Medium and nearly cut the test time (just test) in half. 
Biggest issue now is that we load balance the tests across the workers by module. This is because some module assume we aren't running in parallel and therefore share resources across tests. This results in a skew across the workers. Fix shouldn't be too bad but taking the easy win for now.
> chore: parallelize tests by module

- .circleci/continue_config.yml
- pytest.ini
- tests/core/engine_adapter/test_integration.py
Combined with the improvements from #1939 it seems like we can now parallelize all tests except for Airflow.
`worksteal` approach means that workers can take work from other workers if they finish their queue early (shared/greedy approach). 
From some simple testing, it seems like assigning 2 workers per code is ideal on CircleCI so updated config to match that. Tests are now 3x faster on CircleCI than prior to these two PRs.
> chore: parallelize by test

- sqlmesh/core/context.py
- tests/core/test_integration.py
- tests/integrations/jupyter/test_magics.py
Thanks @crericha for pointing out the problem and providing a solution.
We used to display in info the system macros + user macros but users likely only care about seeing their own macros listed in info. 
Also updated one test to allow for the existence of other tables in the sqlmesh schema.
> fix: show only user macro count in info

- sqlmesh/core/model/definition.py
- tests/core/test_model.py
External models are written like this:
But they fail when the method render definition is called due to the meta converter lookup not having a dialect argument. 
---
This PR fixes that with what is likely the correct behavior
> Fix: pass dialect to name field value converter

- docs/concepts/models/model_kinds.md
- docs/integrations/dbt.md
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/model/kind.py
- sqlmesh/core/snapshot/evaluator.py
- sqlmesh/dbt/basemodel.py
- sqlmesh/dbt/manifest.py
- sqlmesh/dbt/model.py
- tests/core/engine_adapter/test_integration.py
- tests/core/test_integration.py
- tests/core/test_snapshot_evaluator.py
- tests/dbt/test_integration.py
- tests/dbt/test_manifest.py
- tests/dbt/test_transformation.py
- tests/fixtures/dbt/sushi_test/snapshots/items_check_snapshot.sql
- tests/fixtures/dbt/sushi_test/snapshots/items_no_hard_delete_snapshot.sql
- tests/fixtures/dbt/sushi_test/snapshots/items_snapshot.sql
Adds limited support for dbt snapshots with those limitations/behavioral difference documented.
Previous scd_type_2 test was moved to be a dbt test that compares running dbt runtime, dbt adapter, and sqlmesh to make sure they all return the same result (except for documented behavioral difference). 
Follow up PRs will add full snapshot support.
> feat: add limited dbt snapshot support

- web/server/api/endpoints/plan.py
- web/server/models.py
The node_type attribute is not optional in the ChangeDisplay Pydantic model.
> Fix: Missing node type for removed snapshots in context diff

- tests/web/test_main.py
- web/client/openapi.json
- web/server/api/endpoints/files.py
- web/server/watcher.py
When saving files and file watcher catch error , it should send SSE event and continue collecting changes. And eventually it should send SSE with changes back to update UI.
> Fix: Send sse error if file watcher throws

- examples/wursthall/models/src/menu_item_details.sql
- sqlmesh/core/model/definition.py
- tests/core/test_model.py
Depending on how you organize your sqlmesh project, you may want to declare a seed in some nested directed colocated with a relevant model file. The `../../../../` gets kludgy. Our desire is often to specify a path from the *context root*. This should be straightforward to do. Here I have implemented it via using `~` to be indicative of the module path / context root. If we don't like the overloading we could try something else but to be fair Path.expanduser is never called anyway so it never would have worked and seeds being located in a real user home dir is an anti-pattern to say the least. 
So lets provide something nicer.
EDIT: pivoted to use a special `$root` (case-insensitive) substitution to avoid confusion
> Feat: Allow using $root in seed paths to specify path relative to context path

- sqlmesh/core/config/scheduler.py
- sqlmesh/core/context.py
- tests/conftest.py
- tests/core/test_integration.py
Previously we shared actual engine adapters across the data warehouse connection and state sync connection (if one isn't provided). It seems more proper to have each one have a unique connection but share a common config. That way the two connections can make changes (like changing catalog settings) independent of another.
> fix: share connection config state sync instead of adapters

- docs/concepts/audits.md
- sqlmesh/core/audit/builtin.py
- tests/core/test_audit.py
As per the slack thread. The inclusive argument application is inverted in the handful of audits using the pattern. 
https://tobiko-data.slack.com/archives/C044BRE5W4S/p1705526103351769
> Fix: Correct the inclusive arg audits and docs

- sqlmesh/core/context.py
- sqlmesh/core/state_sync/base.py
- sqlmesh/core/state_sync/engine_adapter.py
- sqlmesh/schedulers/airflow/api.py
- sqlmesh/schedulers/airflow/client.py
- sqlmesh/schedulers/airflow/common.py
- sqlmesh/schedulers/airflow/state_sync.py
- tests/core/test_state_sync.py
- tests/schedulers/airflow/test_client.py
This update ensures that the latest intervals are normalized by snapshot and the minimum value is picked to guarantee that no unexpected backfills get triggered during plan application with explicit model selection.
This also solves the issue of having unexpected backfills when a newly added model is explicitly selected with `--select-model`, in which case there would be no existing intervals to get the max value from and the `now` is used for the plan end as a result, causing unrelated models to be backfilled.
> Fix: Normalize max end interval by snapshot when models are selected explicitly

- sqlmesh/core/macros.py
- sqlmesh/core/renderer.py
EDIT: The original crux of the issue was to fix the below
```sql
MODEL (
name my.model,
kind FULL,
dialect bigquery,
grain id
);
SELECT * FROM upstream.table;
ALTER TABLE my.model ADD PRIMARY KEY (id) NOT ENFORCED; -- this is not mapped to snapshot
```
We have fixed this in sqlglot. Part 2 is making available default catalog. Part 3 would be properly parsing `GRANTs` into dedicated nodes? Otherwise the mapping from name -> snapshot will never work?
> Feat: Add @default_catalog to the macro environment

- web/client/openapi.json
- web/client/src/context/context.ts
- web/client/src/library/components/sourceList/SourceList.tsx
- web/client/src/library/pages/docs/Content.tsx
- web/client/src/library/pages/docs/Docs.tsx
- web/client/src/library/pages/editor/Editor.tsx
Added `globally` shared `lastSelectedModel` to pre-select file or show (previous selection) when returned back to Docs.
It also allows to preserve selected model and in case when user selected `model` file from `File Explorer` to show that model in Docs or vice versa, when user selected `model` in Docs to select that `file` in `File Explorer` and `Tabs`
> Chore: "remember" last selected model from Docs and show on return

- docs/concepts/models/seed_models.md
- sqlmesh/core/model/definition.py
- tests/core/test_model.py
We must "expand" any markers (`$root` is the only one currently) eagerly in the SeedModel constructor. (vs currently just doing it for the sake of the `Seed` container.
Main reason is so the [_track_file](https://github.com/z3z1ma/sqlmesh/blob/284990baa4fe72310f5beeef35f9201cc6e2f107/sqlmesh/core/loader.py#L311-L313) call here does not throw (not that anyone is using this feature just yet), but also looking forward so `SeedModel.seed_path` is correct without any additional work and  the SeedKind path makes sense.
I may slip in a documentation update in this PR too mentioning the marker in the SeedKind section
> Fix: expand seed $root marker in constructor

- web/client/src/api/index.ts
- web/client/src/library/components/documentation/Documentation.tsx
- web/client/src/library/components/editor/EditorInspector.tsx
- web/server/api/endpoints/models.py
- web/server/watcher.py
`Models` API endpoint returns only model's essential details and omits `sql`. In order to get `rendered sql` we need to send another API call to `Model` API endpoint. Also when `model's` file's changed, include `rendered sql` in payload sent via SSE.
> Feat: Fetch model's sql from API on demand

- web/client/openapi.json
- web/client/src/library/components/plan/Plan.tsx
- web/client/src/library/components/plan/PlanActions.tsx
- web/client/src/library/components/plan/PlanApplyStageTracker.tsx
- web/client/src/library/pages/ide/IDE.tsx
Animates transition between different stages when `run plan/apply plan`. Animation is very simple and need some work but makes plan UX less choppy
> Chore: Add animation to plan stages transition

- web/client/src/library/components/documentation/Documentation.tsx
In docs, viewing the SQL for a model, when I change models, the SQL doesn't update until minimize the section and expand it again.
> Fix: SQL for a model freezes in Docs

- tests/core/test_integration.py
The state metadata may contain other tables. Rework the tests to only verify that the expected tables exist, not that they are the only tables.
> Fix: Allow other tables in sqlmesh state schema

- docs/concepts/macros/sqlmesh_macros.md
Small nit to fix callout in macro docs on identifier interpolation. Meaningfully useful to know.
> Docs: fix callout in macro doc

- sqlmesh/core/plan/evaluator.py
- sqlmesh/core/snapshot/definition.py
- sqlmesh/core/snapshot/evaluator.py
- sqlmesh/schedulers/airflow/common.py
- sqlmesh/schedulers/airflow/dag_generator.py
- sqlmesh/schedulers/airflow/plan.py
- tests/core/test_integration.py
- tests/core/test_snapshot_evaluator.py
- tests/schedulers/airflow/test_plan.py
The following chain of events must take place for the issue to materialize:
1. A schema of a forward-only model A have been updated.
2. It was pushed to a dev environment.
3. Changes to model A haven't been deployed to prod yet.
4. A downstream model B have been updated to use schema changes from A.
5. Changes to model B were never pushed to a dev environment.
6. Instead both changes were pushed to prod at the same time.
> Fix: Child snapshot targeting a wrong parent forward-only snapshot table when the parent was created in dev and the child in prod

- sqlmesh/core/scheduler.py
- tests/core/test_scheduler.py
nodes are now connected to a terminal node to avoid many to many edges
before:
after:
104 edges -> 60 edges
> fix: further improve performance of dag by introducing a dummy node

- docs/quickstart/cli.md
- sqlmesh/core/console.py
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/base_postgres.py
- sqlmesh/core/engine_adapter/bigquery.py
- sqlmesh/core/engine_adapter/duckdb.py
- sqlmesh/core/engine_adapter/mssql.py
- sqlmesh/core/engine_adapter/mysql.py
- sqlmesh/core/engine_adapter/redshift.py
- sqlmesh/core/engine_adapter/snowflake.py
- sqlmesh/core/engine_adapter/spark.py
- sqlmesh/core/engine_adapter/trino.py
- sqlmesh/core/plan/evaluator.py
- sqlmesh/core/snapshot/evaluator.py
- sqlmesh/dbt/adapter.py
- sqlmesh/schedulers/airflow/common.py
- sqlmesh/schedulers/airflow/dag_generator.py
- sqlmesh/schedulers/airflow/plan.py
- tests/core/engine_adapter/test_base.py
- tests/core/engine_adapter/test_integration.py
- tests/core/engine_adapter/test_mssql.py
- tests/core/test_integration.py
- tests/core/test_snapshot_evaluator.py
- tests/integrations/github/cicd/test_integration.py
- tests/schedulers/airflow/test_plan.py
This update makes sure that physical tables for snapshots are created lazily when they are actually needed. This is particularly helpful when using the model selector, in which case we create tables for selected models only.
Additionally, this update has a nice side effect of adding self-healing properties to the plan / apply flow by automatically re-creating snapshot tables if they happen to be missing.
> Feat: Create snapshot tables on demand

- sqlmesh/core/snapshot/definition.py
- sqlmesh/core/state_sync/common.py
- sqlmesh/core/state_sync/engine_adapter.py
- sqlmesh/migrations/v0038_add_expiration_ts_to_snapshot.py
- tests/core/test_state_sync.py
Previously,  the janitor process would fetch all snapshot records to figure out what needs to be cleaned up. This led to a large memory footprint for projects with many models and / or changes.
This update ensures that only records that actually expired are fetched from the state DB.
> Fix: When deleting expired snapshots in janitor only fetch relevant snapshot records

- sqlmesh/migrations/v0039_include_environment_in_plan_dag_spec.py
- sqlmesh/schedulers/airflow/common.py
- sqlmesh/schedulers/airflow/dag_generator.py
- sqlmesh/schedulers/airflow/integration.py
- sqlmesh/schedulers/airflow/plan.py
- sqlmesh/schedulers/airflow/util.py
- tests/schedulers/airflow/operators/test_hwm_sensor.py
- tests/schedulers/airflow/operators/test_targets.py
- tests/schedulers/airflow/test_plan.py
Currently we fetch all snapshots on the scheduler side which may lead to high memory consumption there. Additionally we had passed all these snapshots into underlying DAG tasks potentially causing high memory consumption at the execution time which could lead to tasks being SIGKILLed.
> Fix: Fetch snapshot records on demand when generating Airflow dags

- setup.py
Pytest just made a new major release: https://github.com/pytest-dev/pytest/releases/tag/8.0.0
It has a bunch of breaking changes and at a minimum broke compatibility with `pytest-lazy-fixture`. Therefore pinning for now until we can ensure full compatibility.
> chore: pin pytest version

- setup.py
2.6 requires email-validator > 2 and our Airflow testing environment requires Airflow 2.3.3. Pinning <2.6 for now until we get this fixed.
> fix: Pydantic less than 2.6

- sqlmesh/core/config/connection.py
- tests/conftest.py
- tests/core/test_connection_config.py
Part of fix for: https://github.com/TobikoData/sqlmesh/issues/2037
Result of this change: https://github.com/TobikoData/sqlmesh/pull/1975
Prior to this change we would allow multiple adapters to share a common data file for DuckDB. This actually works fine until multiple adapters are created again pointed to the already created file and then the second adapter (typically state sync) will not read any data. This is why testing before of having multiple adapter run a plan and check the result did not show any issues.
The solution is to check when creating a new adapter for DuckDB if the new adapter is going to point to file that overlaps a file already used by another adapter. If so, we just reuse the past adapter. This has a downside that any additional configuration associated with the …
> fix: share duckdb adapter is overlapping data files

- sqlmesh/core/engine_adapter/spark.py
- sqlmesh/core/snapshot/evaluator.py
- tests/core/engine_adapter/test_spark.py
Fix after this PR: https://github.com/TobikoData/sqlmesh/pull/2031
The PR introduced a flow where we would create a table if not exists if the query is a self-referencing query. This doesn't work for Spark WAP since spark doesn't let you create a table with a WAP ID at the end. This makes sense because to have the branch you needed to create the table first and then altered it. Therefore this PR updates Spark's create table to issue the create table on the table itself without the branch. 
While working on that fix I noticed a different issue: If `_create_table` was called with `IF NOT EXISTS` included and was Iceberg and WAP capable then we would do the "Dummy" Insert into call: https://github.com/TobikoData/sqlmesh/blob/f583fcec955e9433f755737ecbab279888643fc0/sqlmesh/core/engine_adapter …
> fix: Spark Create Table DDL WAP

- sqlmesh/cli/__init__.py
- sqlmesh/cli/main.py
Part of the fix for this issue: https://github.com/TobikoData/sqlmesh/issues/2037
It makes sense that we close connections when using CLI prior to exiting. Open question about how we would mimic this in environments with long-running python instances (Notebook/UI) but fixing in CLI for now.
> fix: context close on Create/Update/Delete operations

- sqlmesh/core/snapshot/definition.py
- sqlmesh/utils/pydantic.py
- tests/utils/test_pydantic.py
We have an issue that Pydantic includes private attributes in the equality check:
https://github.com/pydantic/pydantic/blob/b785d5b1db4eccb922dd2bf17faea5fc842e6a57/pydantic/main.py#L880
We use these for caching values. When we do equality checks our intent is to check if the public attributes of the class are the same and not if the cached attributes are equal. 
This PR has a way of solving this problem but involves mutating the actual objects themselves so it would be best if we had a solution that didn't involve that. Are there Pydantic config properties that can help us here? @izeigerman do you have any ideas? I want to find a solution that works for all Pydantic classes instead requiring each one to provide an override if they introduce private attributes.
> fix!: ignore private attributes doing equality pydantic

- sqlmesh/core/state_sync/common.py
- tests/core/test_state_sync.py
Scenario: A user has views being created in a catalog we will call `main` based on the default catalog from the connection (could also come from the model itself). They then add a `environment_catalog_mapping` which maps that models to the same catalog that they were already being mapped to which would mean having the views still be created in `main`. Before this change, we would consider this a catalog change and therefore say that we need to both add and remove those views from the environment. Since add runs before remove this would result in the views being dropped.
We now check the actual view paths and only demote if we see a change. So if the catalog change ends up being no change for the object itself then we won't remove it.
> fix: changing catalog env override existing catalog matches

- sqlmesh/cli/main.py
- sqlmesh/core/context.py
- sqlmesh/core/dialect.py
- sqlmesh/magics.py
Not enough configurability. Expose very nice implementation in Generator to the benefit of all users while preserving existing behavior by default.
> Feat: more configuration for format command

- web/client/src/library/components/graph/ModelLineage.tsx
- web/client/src/library/components/graph/ModelLineageSearch.tsx
- Search overlay is better positioned now (it was a little too high before and now is better aligned with the items it covers up)
- If you open the lineage search at a small size and then increase width, the search overlay will disappear and no longer stay open (with a disappearing close button)
- Light mode background color for search overlay for small screens:
(dark mode comparison)
> fix: minor lineage search visual issues

- sqlmesh/core/snapshot/evaluator.py
- tests/core/test_snapshot_evaluator.py
I've realized that if, for whatever reason, the creation of a dev table succeeds while the subsequent creation of a prod table fails, SQLMesh will end up in an incorrect state. The only way to recover from this is by manually dropping the dev table.
> Fix: Check existence of both dev and prod tables in the snapshot evaluator

- sqlmesh/core/audit/definition.py
- tests/core/test_audit.py
Currently, the audit loader assigns any SQL comments above the audit DDL to the audit's `description` field. That field does not have first-class support, so audits with a comment present errored out.
This PR allows comments to be present by removing the assignment of the comment to the description field.
Closes #2054
> Fix: allow comments in audit file

- setup.py
For dev we still need Pydantic <2.6 due to conflicts with Airflow (see comments) but users can use Pydantic 2.6+ if they want. We won't be testing 2.6+ in our CI/CD pipeline but I did run locally and verified all the slow tests passed. I'm hoping Airflow soon adds support for 2.6 and then we can update our dev install to use that latest Airflow release.
> fix: remove pydantic 2.6 restriction

- docs/concepts/audits.md
- docs/concepts/macros/jinja_macros.md
- docs/concepts/macros/sqlmesh_macros.md
- docs/concepts/tests.md
- docs/guides/notifications.md
- docs/guides/tablediff.md
- docs/quickstart/cli.md
- docs/quickstart/notebook.md
- docs/quickstart/ui.md
- examples/sushi/models/customer_revenue_by_day.sql
- examples/sushi/models/customer_revenue_lifetime.sql
- examples/sushi/models/top_waiters.sql
- examples/sushi/models/waiter_as_customer_by_day.sql
- sqlmesh/cli/example_project.py
- sqlmesh/core/audit/builtin.py
Brackets `[]` are identifiers in tsql as of sqlglot v20.8.0, so models with the tsql dialect cannot parse MODEL DDL that uses brackets to define arrays. 
Arrays defined with parentheses can be parsed by all dialects. This PR changes all examples to use parentheses for array definition in MODEL DDL, including documentation, the SQLMesh example project, and the sushi project.
> Docs: define arrays with parentheses in MODEL DDL

- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/model/definition.py
- sqlmesh/utils/__init__.py
- tests/core/engine_adapter/test_base.py
- tests/core/engine_adapter/test_bigquery.py
- tests/core/engine_adapter/test_databricks.py
- tests/core/engine_adapter/test_spark.py
- tests/utils/test_helpers.py
CTAS calls include a schema definition if column comments are present and columns_to_types are available. Currently, the schema definition could include `UNKNOWN` or `NULL` data types, which cause the CTAS call to error out.
This PR ensures that the schema definition is only included if all column types are known.
Closes #2060
> Fix: do not include a schema def in CTAS unless all column types are known

- docs/reference/cli.md
And remove deprecated `ide` command
> Docs: add invalidate to CLI reference page

- web/client/src/library/components/button/Button.tsx
- web/client/src/library/components/editor/Editor.tsx
- web/client/src/library/components/editor/EditorInspector.tsx
- web/client/src/library/components/editor/EditorPreview.tsx
- web/client/src/library/components/editor/EditorTabs.tsx
- web/client/src/library/components/input/Input.tsx
- web/client/src/library/components/splitPane/SplitPane.tsx
- web/client/src/library/components/tab/Tab.tsx
Add manual trigger (icon) to Editor Inspector, to manually collapse/expend and hide by default
Also make `Inputs` smaller
> Feat: Make editor inspector collapsable on click

- sqlmesh/core/notification_target.py
The command arguments could have sensitive information. Removing the command from notifications for now. Will add it back with the sensitive information redacted in the near future.
> Chore: Remove command from slack notification

- docs/concepts/models/external_models.md
- docs/faq/faq.md
Clarify that:
- They consist solely of the external table's column metadata
- SQLMesh's actions are determined by the model(s) querying the `EXTERNAL` model, not the external model itself
> Docs: expand external model documentation

- sqlmesh/core/engine_adapter/base.py
- tests/core/engine_adapter/test_base.py
- tests/core/engine_adapter/test_bigquery.py
- tests/core/engine_adapter/test_spark.py
Prior to this change if you had a self-referencing query that is full refresh (SCD Type 2 is this) then we would always do a create table if not exists since we need a table to reference if one doesn't exist. If a column was unknown then we would get an error trying to create the table.
Now we check if column types are all known in create table and if they aren't then we raise an error. The exception is if the table already exists and we get IF NOT EXISTS then we just return since we aren't creating the table anyways. This addresses the error case here since even though we have an unknown it is ok since the table is already created.
> fix: replace query unknown self-reference

- sqlmesh/core/selector.py
- sqlmesh/utils/git.py
- tests/core/test_selector.py
This update adds support for intersections to the model selection syntax using the `&` operator. For example, the expression `tag:my_tag & my_model+` selects all models downstream of `my_model` that also have the tag `my_tag`.
Additionally, this pull request introduces a new selector expression, `git:<target_branch>`, which selects models based on files that have been modified when compared to the `<target_branch>` Git branch.
> Feat: Extend selector with ability to select models that are different from the git main branch

- sqlmesh/core/engine_adapter/mssql.py
- sqlmesh/core/model/definition.py
- tests/core/engine_adapter/test_integration.py
If a seed file contained a missing value in a string column, its `NaN` value was coerced to string `"nan"` with pandas `astype(str)`. This PR ensures only non-missing values are coerced to string.
Also:
- Converts `NaN` values to `None` for MSSQL engine pymssql library
- Adds integration test confirming successful `NaN` -> db `NULL` -> `NaN`/`None` roundtrip
> Fix: do not convert missing seed string column values to string

- examples/sushi/macros/macros.py
- sqlmesh/core/macros.py
- tests/core/test_macros.py
This reverts commit 61451e2838f04af016bf695699a793cf94fb0b44. PR: https://github.com/TobikoData/sqlmesh/pull/2041
The issue is that is breaks Airflow tests because the macros are not serialized properly to include type hints.
> Revert "Feat: Macro typing coercion (#2041)"

- web/client/src/library/components/sourceList/SourceList.tsx
- web/client/src/library/pages/audits/Audits.tsx
- web/client/src/library/pages/docs/Docs.tsx
- web/client/src/library/pages/errors/Errors.tsx
- web/client/src/library/pages/plan/Plan.tsx
- web/client/src/library/pages/tests/Tests.tsx
Three main things being added here
- virtualizing the list of items in the docs list using tanstack react virtualizer
- when user refreshes the page, if the active item is not visible in the docs list, list will be scrolled until the active item is visible
- added a button so if you scroll away from the currently active item and want to return to it, it will be easy to do so
==
Video showing page refresh results in active item being visible, and the "scroll to" button when it is scrolled out of frame:
https://github.com/TobikoData/sqlmesh/assets/81378/469b7318-dd77-4d34-9865-9d97a26b8488
> feat: Virtualized docs list, auto scroll to active item on refresh

- sqlmesh/core/config/feature_flag.py
- sqlmesh/core/config/root.py
- sqlmesh/dbt/loader.py
- tests/core/test_config.py
- tests/dbt/test_adapter.py
Adds a feature flag for disabling SCD Type 2 Support (or called "Snapshots" in dbt) using the dbt adapter. This would disable all Snapshot models. The plan is to remove this in a few weeks if we find it is not needed as we continue to rollout full Snapshot support to dbt models.
> feat: add dbt scd type 2 feature flag

- setup.py
- sqlmesh/core/dialect.py
- sqlmesh/core/schema_diff.py
Was super annoying to detect the need for the L458 change in schema_diff.py (triggered by a recent [change](https://github.com/tobymao/sqlglot/commit/b4e886877ecfbafdd64c515c765c3c54764bd987#diff-7857fedd1d1451b1b9a5b8efaa1cc292c02e7ee4f0d04d7e2f9d5bfb9565802cR3837) in sqlglot), may need to refactor this at some point to avoid the mutations if possible.
> Chore!: bump sqlglot to v21.0.0

- docs/reference/cli.md
- sqlmesh/cli/main.py
- sqlmesh/core/context.py
The new mode allows to block the `sqlmesh invalidate` command until the environment record and associated views are actually deleted. 
The mode requires a connection to data warehouse, which means that it's presently not supported when using Airflow unless the data warehouse connection configured separately.
> Feat: Add support for the synchronous mode to the 'invalidate' CLI command

- tests/conftest.py
Handlers are shared globally which was causing an issue where Airflow tests would add handlers and those handlers would then affect the results of other tests (like upcoming CLI tests: https://github.com/TobikoData/sqlmesh/pull/2091)
I initially tried fixing Airflow directly by setting `_AIRFLOW__AS_LIBRARY` within a autouse fixture but that broke some tests and also required that imports for Airflow be within the scope of functions which was annoying. This solution though helps rescope logger to not share state across modules which seems more broadly useful. I decided to scope it to modules instead of functions because I want to make it easy for future tests to configure logging at the module level and not have this override it.
> chore: scope log handlers to modules

- docs/guides/configuration.md
- docs/reference/cli.md
- docs/reference/configuration.md
- examples/sushi/config.py
- sqlmesh/cli/main.py
- sqlmesh/core/config/__init__.py
- sqlmesh/core/config/plan.py
- sqlmesh/core/config/root.py
- sqlmesh/core/console.py
- sqlmesh/core/context.py
- sqlmesh/core/plan/builder.py
- sqlmesh/magics.py
- tests/core/test_integration.py
This introduces the additional `--enable-preview` flag (and a corresponding config option) to the plan command, which enables automatic computation of data previews for changes applied to forward-only models in development environments. 
Previously, to achieve the same outcome (compute previews), users had to run two plan commands: 1) to apply forward-only changes, and 2) to restate affected models in dev so that the portion of data is recomputed to make the preview available.
> Feat!: Automatically compute previews for changed forward-only models in dev

- .circleci/continue_config.yml
- setup.cfg
- sqlmesh/utils/pydantic.py
Recent PR referenced a class that is not part of Pydantic 1 and therefore led to an error in Airflow tests that use Pydantic 1.
The reason why our Pydantic 1 CI test didn't catch it is because we downgrade pydantic 2 to pydantic 1 in CI but then leave pydantic_core behind which allowed the tests to pass. So updated CI too in order to catch this earlier in the future.
> chore: fix pydantic 1 support with new type

- sqlmesh/cli/example_project.py
If you init the example project it won't work because we try to put a string in for the partition column. This makes it so that bigquery uses a date data type.
> fix: init bigquery with correct type

- tests/web/test_main.py
- web/client/openapi.json
- web/server/api/endpoints/commands.py
- web/server/api/endpoints/plan.py
When have `running task` there maybe some API calls to `/plan` endpoint and in case when multiple browser tabs opened, requests are coming form all the  tabes pretty much at the same time. So instead of `error and drop` request, it just `wait and re-tries`
> Fix: When plan running dont error and just wait

- sqlmesh/dbt/package.py
This is to cover an edge case in which the variables are set in the `dbt_project.yaml` config as follows:
```
vars:
```
> Fix: Support a missing value for an explicitly provided 'vars' key

- sqlmesh/core/model/definition.py
- sqlmesh/core/snapshot/definition.py
- sqlmesh/utils/date.py
- tests/core/test_model.py
- tests/core/test_state_sync.py
- tests/utils/test_date.py
Prior to this PR, Trino would error if we provided a timestamp since it expects the format to have a space between date and time instead of a `T`. I tested across all engines and they all accept the space so switching to that instead. 
Note that this PR does not address the issue that `ts` includes timezone but we assign it to a datatype that does not support TIMEZONE. That is being addressed in this PR: https://github.com/TobikoData/sqlmesh/pull/2112
> fix: use space instead of T for timestamp format

- docs/concepts/macros/macro_variables.md
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/utils/date.py
- tests/core/engine_adapter/test_base.py
- tests/core/engine_adapter/test_integration.py
- tests/core/engine_adapter/test_spark.py
- tests/core/test_model.py
- tests/core/test_state_sync.py
- tests/utils/test_date.py
Prior to this change `ts` could contain timezone information if that was passed in and would cause issues for some engines. Now we make sure that `ts` does not contain timezone and `tstz` does. 
Took the opportunity to reduce some extra code in engine adapter and write some tests to ensure we could cast the values correctly across all engines. Also ran the engine adapter integration tests across all engines (including remote) to ensure it works.
> feat!: add tstz support

- sqlmesh/utils/date.py
- tests/utils/test_date.py
After refactoring old PR into two PRs, I forgot the most important part of actually adding `tstz` variable. 🤦 This adds it and then adds a test to make sure all expected variables are being set. 
Breaking since this is incompatible with previous release since someone could use the `_tstz` variable and someone on last release wouldn't recognize it.
> fix!: add missing tstz variable

- sqlmesh/core/model/definition.py
- tests/core/test_model.py
For seed models, SQLMesh currently converts columns from string to all date/time types using `pd.to_datetime()`, which always returns a `pd.Timestamp` type. 
If a user specifies a column as type `DATE` in the model definition, the above approach creates a discrepancy between the Pandas dataframe type (timestamp) and the SQL engine type (date). For DuckDB, this results in an error.
This PR differentiates conversion for date and datetime types, converting the former into `datetime.date` objects instead of pandas timestamps.
> Fix: differentiate seed date and datetime types

- sqlmesh/core/state_sync/base.py
- sqlmesh/core/state_sync/engine_adapter.py
- tests/core/test_state_sync.py
Prior to this change we considered SQLMesh versions "compatible", or that they could be run together, if they shared a common sqlglot minor version and were on the same migration release. Sometimes though we introduce incompatibility that doesn't require a migration and we represent this with a minor version bump. Therefore this change now considers SQLMesh's minor version too when deciding if releases are compatible.
> feat!: include sqlmesh in version check

- sqlmesh/core/config/connection.py
- sqlmesh/core/config/root.py
- sqlmesh/core/context.py
SQLMesh currently assumes the default DuckDB test connection can execute queries containing the main connection's default catalog name, which is not always true due to different identifier quotes across engines. 
This PR transpiles the default catalog name from the main connection dialect to the DuckDB dialect so DuckDB can accommodate default catalogs from all engines.
Background
- A SQLMesh project's main connection may specify a default catalog. If the catalog name is quoted, it will use the identifier quotes of the connection's own SQL dialect. 
- By default, SQLMesh executes model unit tests on a local DuckDB connection.
- The catalog name is part of a model's fully qualified name, which must be usable by DuckDB when it runs the test queries.
> Fix: transpile default catalog name for default DuckDB test connection

- sqlmesh/core/config/plan.py
- sqlmesh/core/context.py
- sqlmesh/core/context_diff.py
- sqlmesh/core/environment.py
- sqlmesh/core/plan/definition.py
- sqlmesh/core/state_sync/base.py
- sqlmesh/core/state_sync/engine_adapter.py
- sqlmesh/migrations/v0040_add_previous_finalized_snapshots.py
- sqlmesh/schedulers/airflow/api.py
- sqlmesh/schedulers/airflow/client.py
- sqlmesh/schedulers/airflow/state_sync.py
- tests/core/test_plan.py
- tests/core/test_state_sync.py
- tests/schedulers/airflow/test_client.py
Sometimes, when the main branch is ahead of production and changes are being deployed to production, other users iterating in their development environments might end up comparing their local state against a partial / unfinilized production state.
This may result in unnecessary evaluations, leading to a worse developer experience, even if comparing against the most recent state of production is technically more correct.
This update introduces an option to compare against the latest finalized state of the target environment and ignore the partial state.
> Feat!: Keep track of the previous finalized snapshots in the environment

- Makefile
- setup.py
Motherduck only supports `duckdb==0.9.2` as of 2024-02-16
https://motherduck.com/docs/getting-started/connect-query-from-python/installation-authentication/#installing-duckdb
> Fix: motherduck only supports duckdb==0.9.2

- sqlmesh/core/test/definition.py
- tests/core/test_test.py
SQLMesh unit tests currently require the rows returned by the test query to be in the same order as the output rows specified in the test definition. Different engines may return query rows in different orders, meaning the same unit test will pass on some engines and fail on others.
This PR makes SQL model unit tests row-order agnostic unless the model outer SELECT contains an `ORDER BY` clause (or a CTE's outer SELECT for CTE-specific tests).
Python model tests are order-dependent because there is no universally reliable way to determine whether the model orders the rows.
> Feat: ignore SQL model unit test row order unless query contains ORDER BY

- sqlmesh/core/context.py
- sqlmesh/core/plan/builder.py
- sqlmesh/core/plan/definition.py
- sqlmesh/core/plan/evaluator.py
- sqlmesh/core/scheduler.py
- sqlmesh/core/snapshot/definition.py
- sqlmesh/schedulers/airflow/client.py
- sqlmesh/schedulers/airflow/common.py
- sqlmesh/schedulers/airflow/plan.py
- tests/core/test_integration.py
- tests/core/test_plan.py
- tests/core/test_plan_evaluator.py
- tests/schedulers/airflow/test_client.py
- tests/schedulers/airflow/test_plan.py
Missing intervals might exceed the given end date in cases when the `allow_partials` or the `lookback` attribute is configured for a model. Even though, this behavior makes sense when executing the `sqlmesh run` command, it's confusing and undesirable when applying a plan (especially to a dev environment).
This update prevents unexpected backfills by bounding missing intervals to the target end date when applying a plan.
> Fix: Make sure that missing intervals don't exceed the target end date when applying plan

- docs/integrations/dbt.md
- sqlmesh/dbt/builtin.py
- sqlmesh/utils/jinja.py
- tests/dbt/test_transformation.py
This also introduces support for the `run_started_at` builtin.
Closes #2138
> Fix: Make sure that builtin dbt macros can be referenced using the 'dbt.' prefix

- sqlmesh/core/context.py
- sqlmesh/core/plan/builder.py
- sqlmesh/core/plan/definition.py
- sqlmesh/core/plan/evaluator.py
- sqlmesh/schedulers/airflow/client.py
- sqlmesh/schedulers/airflow/common.py
- sqlmesh/schedulers/airflow/dag_generator.py
- sqlmesh/schedulers/airflow/plan.py
- tests/core/test_plan.py
- tests/core/test_plan_evaluator.py
- tests/schedulers/airflow/test_client.py
- tests/schedulers/airflow/test_plan.py
This is to prevent a scenario when a new forward-only snapshot is unpaused too soon, forcing the previous snapshot to use the dev table when making changes in dev environments, even though this previous snapshot is still technically the latest "finalized" one.
> Fix: Defer unpausing snapshots to right before env finalization when ensuring finalized snapshots

- sqlmesh/core/selector.py
- sqlmesh/utils/git.py
- tests/core/test_selector.py
This improves the behavior in case when the dev branch hasn't been rebased against the main branch in awhile.
> Fix: Improve handling of branches that are behind the target branch in the git selector

- .gitignore
- Makefile
- docs/integrations/engines/trino.md
- pytest.ini
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/bigquery.py
- sqlmesh/core/engine_adapter/mixins.py
- sqlmesh/core/engine_adapter/trino.py
- tests/core/engine_adapter/config.yaml
- tests/core/engine_adapter/docker-compose.yaml
- tests/core/engine_adapter/test_integration.py
- tests/core/engine_adapter/test_trino.py
- tests/core/engine_adapter/trino/catalog/datalake_iceberg.properties
- tests/core/engine_adapter/trino/initdb.sql
- Add the Iceberg connector to the integration test Trino instance
- Add a configuration to run the integration tests against the Iceberg connector
- Add the ability to probe the type of a catalog within an EngineAdapter
- Use this ability to change how table properties are generated in the Trino adapter so it can use `partitioned_by` for Hive tables and `partitioning` for Iceberg tables
ref: Issue #1998
> Feat: Add support for Trino Iceberg tables

- sqlmesh/core/engine_adapter/base.py
- tests/core/engine_adapter/test_base.py
- tests/core/engine_adapter/test_spark.py
Prior to this change we would `select *` on the final selects to union the different CTEs together. This meant there was a unexpected assumption about column order of selects in the CTEs which was unnecessary since we know the column names within each of the selects and therefore we can not require an order to be maintained.
> fix: always set column order scd type 2

- sqlmesh/core/snapshot/definition.py
- tests/core/test_snapshot.py
The title is pretty self-explanatory. The `cron` expressions should be taken into account when the `end_bounded` is to true unless `ignore_cron` is also set to true.
> Fix: Cron shouldn't be ignored when missing intervals are bounded by the end date

- sqlmesh/core/context.py
- sqlmesh/core/test/definition.py
- sqlmesh/utils/date.py
- tests/integrations/jupyter/test_magics.py
**Problem/background**
- `generate_test()` creates a SQLMesh unit test YAML file based on a user-specified model name and input query
- When we fetchdf the query results to Pandas, all datetime columns are converted to `pd.Timestamp` type (at least when queries run on DuckDB)
- We use `ruamel.yaml` to serialize the data values returned by the query to YAML, and it does not support `pd.Timestamp` objects
**This PR**
- Converts pd.Timestamp to datetime objects before writing query result data values to YAML
- We want to maintain fidelity to the source column type. If it is `DATE`, we extract the date component from the `datetime` object before writing so a time component of `00:00:00` isn't included in the YAML.
> Fix: convert pandas timestamp to py datetime for unit test generation

- sqlmesh/utils/pydantic.py
Currently if you pass in a kwarg and it overlaps with a default value then the default will overwrite what you passed in. This makes it so that the default are just applied if a value is not passed in by the caller.
> chore: allow overriding pydantic defaults

- sqlmesh/dbt/target.py
We assume in the code that `database` is set by all connection configs to mean the catalog: https://github.com/TobikoData/sqlmesh/blob/b5926ab464a55f3c0a87fc159df0d2ada11b4d96/sqlmesh/dbt/loader.py#L153
So we just alias `catalog` to be `database` for Databricks since it doesn't support the `database` argument.
> fix: dbt alias databricks catalog to database

- setup.py
- sqlmesh/cli/main.py
- sqlmesh/core/config/connection.py
- sqlmesh/core/config/loader.py
- sqlmesh/core/config/scheduler.py
- sqlmesh/core/context.py
- sqlmesh/core/loader.py
- sqlmesh/dbt/loader.py
- sqlmesh/magics.py
- tests/core/engine_adapter/test_integration.py
- tests/core/test_config.py
- tests/core/test_context.py
- tests/integrations/github/cicd/test_config.py
This PR enables loading a different Config class that is derived from `Config` into the SQLMesh context, which enables storage of additional config parameters that are not directly used by SQLMesh.
> Feat: Support config class overriding in the loader and context

- web/client/src/library/components/plan/PlanApplyStageTracker.tsx
- web/client/src/library/components/plan/PlanChangePreview.tsx
- web/client/src/library/components/plan/PlanOptions.tsx
- web/client/src/library/components/plan/context.tsx
> Fix: Remove not allowed categories

- setup.py
Issue we see prior to pinning: 
```
tests/core/test_connection_config.py::test_snowflake_private_key_pass[snowflake_key_no_passphrase_path-snowflake_key_no_passphrase_pem-snowflake_key_no_passphrase_b64-snowflake_key_no_passphrase_bytes-None] - TypeError: Password was not given but private key is encrypted
```
Likely related to cryptography switching to rust: https://github.com/pyca/cryptography/pull/10064
> chore: pin cryptography

- sqlmesh/core/audit/definition.py
- sqlmesh/core/model/definition.py
- sqlmesh/core/model/meta.py
- sqlmesh/core/renderer.py
- sqlmesh/dbt/basemodel.py
- sqlmesh/dbt/test.py
- sqlmesh/migrations/v0041_remove_hash_raw_query_attribute.py
- tests/core/test_integration.py
- tests/core/test_snapshot.py
- tests/fixtures/dbt/sushi_test/models/simple_model_a.sql
- tests/fixtures/dbt/sushi_test/models/simple_model_b.sql
- tests/schedulers/airflow/test_client.py
Instead of unconditionally using raw queries to compute fingerprints for dbt models, we now try to use rendered queries / statements first and only fallback to raw values if the rendering couldn't be performed at parse / load time.
> Fix: Remove the 'hash_raw_query' attribute

- sqlmesh/core/engine_adapter/bigquery.py
This will log a clickable link to the BigQuery job within BigQuery Studio. This should help debugging queries within BigQuery directly.
> feat: log BigQuery job details link

- sqlmesh/core/snapshot/definition.py
- tests/core/test_integration.py
- tests/core/test_snapshot.py
Corrects the unexpected behavior of the parent snapshot being backfilled when the plan was applied after the intended run time (per its `cron` expression) but before sqlmesh run had the opportunity to catch up with this snapshot.
Fixed by bounding the execution time to the end date when computing missing intervals.
> Fix: Unexpected backfill when the parent model's cron is before its child's

- examples/sushi/models/customers.sql
- setup.py
- sqlmesh/core/audit/definition.py
- sqlmesh/core/engine_adapter/_typing.py
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/lineage.py
- sqlmesh/core/macros.py
- sqlmesh/core/model/definition.py
- sqlmesh/core/renderer.py
- sqlmesh/utils/errors.py
- sqlmesh/utils/pydantic.py
- tests/integrations/github/cicd/test_integration.py
- web/server/api/endpoints/lineage.py
This PR is early in anticipation of https://github.com/tobymao/sqlglot/commit/2507aa2dbad3304304558565f266a7f94acd9e98 (TL;DR merged `Subqueryable` and `Unionable` into `Query`).
Initial motivation was to fix #2137 but after discussion we decided it would be generally good to consolidate these two classes. I haven't fully investigated what this means for SQLMesh - these changes were made using search-and-replace, but I intend to audit them more closely soon. I verified that at least `make style && make fast-test` passed locally.
> Chore:! bump sqlglot to v22.0.1 (got rid of Subqueryable, Unionable)

- sqlmesh/integrations/slack.py
Previously, calling this helper method with `fields_section_block("a", "b", "c")` would produce the following dict:
```python
{'type': 'section', 'fields': {'type': 'mrkdwn', 'text': 'c'}}
```
This fixes things to produce the following (correct) format:
```python
{'type': 'section', 'fields': [{'type': 'mrkdwn', 'text': 'a'}, {'type': 'mrkdwn', 'text': 'b'}, {'type': 'mrkdwn', 'text': 'c'}]}
```
> fix: correct slack block with multiple fields

- sqlmesh/core/config/connection.py
- sqlmesh/dbt/target.py
- tests/core/test_connection_config.py
Support for execution_project (which is going to be the GCP project used for execution as in the resources used ... opposed to the storage). It's mandatory for organizations that split "storage project" vs "execution project" to enable fine grained resources management.
For reference, the similar change I made for dbt 3 years ago: https://github.com/dbt-labs/dbt-bigquery/commit/42cd89d08e38a871743ffd49716708475bb48d1f
I added the fallback to `project` for backward compatibility.
I couldn't find tests for bigquery related config... so I made one but it's not as useful as I'd like 🙄
> add bigquery execution project config support

- docs/integrations/engines/snowflake.md
- sqlmesh/core/_typing.py
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/bigquery.py
- sqlmesh/core/engine_adapter/snowflake.py
- sqlmesh/core/model/meta.py
- sqlmesh/core/snapshot/evaluator.py
- tests/core/engine_adapter/test_bigquery.py
- tests/core/engine_adapter/test_snowflake.py
- tests/core/test_integration.py
- tests/core/test_model.py
This update enables users to set a virtual warehouse on a per-model basis using the `session_properties` attribute of the model definition.
> Feat: Support custom Virtual Warehouses for Snowflake

- examples/sushi/models/customers.sql
- tests/integrations/github/cicd/test_integration.py
Even though https://github.com/TobikoData/sqlmesh/commit/3b970bdcecd41dd340d50ce14102b909285a5581 passed all tests in CI, @vchan came across a couple of issues when computing the lineage of `sushi.customers`. After chatting we realized it's a bit more involved to fix them, because we'll need to update either SQLGlot's lineage or scope module (or both), so I'm temporarily reverting this change to unblock new releases.
> Fix: temporarily unwrap sushi.customers's query again

- sqlmesh/core/plan/builder.py
It should only matter whether versions are the same. Whether the snapshot is in previous versions should be irrelevant to what we're trying to prevent here.
> Fix: Don't check previous versions when checking whether the snapshot is unrevertable

- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/bigquery.py
- sqlmesh/core/engine_adapter/mixins.py
- tests/core/engine_adapter/test_trino.py
Context: catalog name used to differentiate trino on hive from trino on iceberg
> Fix: correctly extract catalog name for table properties expression builder

- sqlmesh/core/context_diff.py
- sqlmesh/core/plan/builder.py
- sqlmesh/core/snapshot/__init__.py
- sqlmesh/core/snapshot/definition.py
- sqlmesh/core/state_sync/engine_adapter.py
- sqlmesh/migrations/v0042_trim_indirect_versions.py
Currently the memory footprint of the sqlmesh process during migration is way too high for large projects.
For example, it takes about 10-11GB of RAM to migrate ~10k snapshot records. 
During the investigation I've noticed that the raw snapshot payload doesn't consume that much memory. It's when we deserialize all snapshots at once the footprint grows drastically. 
This update ensures that we only keep a limited number of snapshots in deserialized form in memory during the migration.
> Fix: Reduce the memory footprint during the migration

- sqlmesh/core/state_sync/engine_adapter.py
These statements were added in this PR but did not quote identifiers which causes issues on at least Snowflake: https://github.com/TobikoData/sqlmesh/pull/2199
> fix: quote identifiers migration statements

- sqlmesh/core/test/definition.py
- tests/core/test_test.py
Small QOL addition - unit tests can now optionally have a description, which will be shown as part of the exception message in case the test fails.
> Feat: add unit test descriptions

- sqlmesh/core/config/connection.py
- sqlmesh/core/config/gateway.py
- sqlmesh/core/config/root.py
- tests/core/test_config.py
The serialization of abstract base classes has been intentionally broken in Pydantic V2. See https://docs.pydantic.dev/latest/concepts/serialization/#serializing-with-duck-typing for more details.
> Fix: Serialization of the ConnectionConfig objects

- sqlmesh/core/engine_adapter/redshift.py
- tests/core/engine_adapter/test_redshift.py
some redshift explain plans come in with unexpected blocks, ignore them and only parse blocks with RESULTS
> non standard redshift plans with limits

- sqlmesh/dbt/target.py
- tests/dbt/test_config.py
DuckDB doesn't support concurrent writes, so we automatically use 1 thread even if the dbt profile specifies >1
> Feat: use 1 thread for dbt duckdb targets

- sqlmesh/core/plan/builder.py
- tests/core/test_plan.py
Currently we might end up ignoring forward-only snapshots / models in dev, even though the resulting data will only be used for preview purposes.
This fix ensures that we never ignore forward-only models / snapshots when constructing a plan.
> Fix: Never ignore forward-only snapshots when building a plan

- sqlmesh/cli/main.py
- web/server/main.py
- web/server/settings.py
- web/server/watcher.py
Currently, the UI will not launch if a SQLMesh context cannot be created. If, for example, the SQLMesh project config file is wrong or has a typo, a user cannot use the UI to fix it. This PR enables the UI to somewhat function even without a SQLMesh context by allowing it to launch and load files.
> Chore: Return files even if there is no SQLMesh context

- sqlmesh/core/schema_diff.py
- sqlmesh/utils/__init__.py
- tests/core/engine_adapter/test_base.py
- tests/utils/test_helpers.py
Prior to this change you could have a struct with a unknown data type in it and we would consider this as having all the data types defined. This PR makes the data type check recursive so we will find unknown types in nested data types. 
`SchemaDiffer` was changed because I converted a classmethod it had into a utility function. No logic changes to that class or it's tests.
> fix!: recursively check for unknown data types

- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/bigquery.py
- sqlmesh/core/engine_adapter/mixins.py
- sqlmesh/core/engine_adapter/mysql.py
- sqlmesh/core/engine_adapter/spark.py
- tests/core/engine_adapter/test_bigquery.py
- tests/core/engine_adapter/test_mysql.py
- tests/core/engine_adapter/test_spark.py
- tests/core/engine_adapter/test_trino.py
Some engines error if comments are longer than a maximum length. With this PR they will be automatically truncated to the engine's max.
Some engines, like Spark and Trino, have modular compute, metadata, and storage layers. The max comment length may differ across choices of metadata layer, such as Hive (max 4000 chars) or Iceberg (no max). For modular engines, we handle truncation in the Hive mixin rather than the engine adapter itself.
> Feat: truncate comments to engine-specific maximum

- sqlmesh/integrations/github/cicd/config.py
- tests/integrations/github/cicd/test_config.py
- tests/integrations/github/cicd/test_integration.py
The Plan Builder correctly figures out the default start for the plan even when there forward-only changes. There's no reason to set the default to `1 day ago` since it sometimes leads to incorrect behavior when the prod is behind by a couple of days.
> Fix: The default start value in the CICD bot config

- web/client/openapi.json
- web/client/src/api/index.ts
- web/client/src/library/components/environmentDetails/SelectEnvironment.tsx
- web/client/src/library/components/graph/Graph.tsx
- web/client/src/library/components/graph/ModelNode.tsx
- web/client/src/library/components/modal/ModalConfirmation.tsx
- web/client/src/library/components/plan/Plan.tsx
- web/client/src/library/components/plan/PlanActions.tsx
- web/client/src/library/components/plan/PlanApplyStageTracker.tsx
- web/client/src/library/components/plan/PlanChangePreview.tsx
- web/client/src/library/components/plan/PlanOptions.tsx
- web/client/src/library/components/plan/context.tsx
- web/client/src/library/components/plan/hooks.ts
- web/client/src/library/components/report/ReportErrors.tsx
- web/client/src/library/pages/root/Root.tsx
- web/client/src/utils/index.ts
- web/server/api/endpoints/commands.py
- web/server/api/endpoints/plan.py
- web/server/models.py
I removed list of parents from indirectly modified to simplify
Added confirmation when user has uncategorized and trying to Apply
> Fix:  Manual categorization

- web/client/src/library/components/editor/EditorPreview.tsx
- web/client/src/library/components/plan/Plan.tsx
- web/client/src/library/components/plan/PlanApplyStageTracker.tsx
- web/client/src/library/components/plan/help.ts
- web/client/src/library/pages/root/context/notificationCenter.tsx
- web/server/api/endpoints/commands.py
- web/server/api/endpoints/plan.py
- web/server/console.py
- web/server/utils.py
Provide me details on plan errors as well as better display error state on UI during `plan` or `apply`
> Fix: Improve error display for failed plan

- sqlmesh/core/snapshot/evaluator.py
- sqlmesh/utils/concurrency.py
- tests/utils/test_concurrency.py
Make the listing of existing snapshot tables faster by running queries concurrently per unique schema.
> Fix: List existing data objects concurrently when creating snapshot tables

- sqlmesh/core/config/connection.py
- tests/core/test_connection_config.py
`duckdb.connect` does not properly parse config dicts that are passed into it, so instead set each config setting directly in duckdb when we init the cursor.
> Fix: configure duckdb with connector_config settings.

- sqlmesh/core/engine_adapter/shared.py
- tests/core/engine_adapter/test_integration.py
- tests/core/engine_adapter/test_postgres.py
Prior to this PR if we detected a single catalog engine (like Postgres) referred to another catalog then it would error. This is likely excessive since the single catalog would error on it's own anyways and it can potentially raise errors when they are needed. Therefore this PR switches this to log a warning instead.
> fix: warn instead of error single catalog multiple catalogs

- docs/integrations/engines/bigquery.md
Saw a typo in the BigQuery connection documentation, this corrects it!
> Fixing typo in BigQuery default connection method documentation

- setup.py
- sqlmesh/core/engine_adapter/base.py
- tests/core/engine_adapter/test_bigquery.py
- tests/core/test_model.py
- tests/dbt/test_transformation.py
@eakmanrq can you take a look at this change in `test_model.py` to verify it's correct?
```diff
-   HASH_WITH_CATALOG = "1074956187"
+   HASH_WITH_CATALOG = "1479069456"
```
> Chore!: bump sqlglot to v22.4.0

- sqlmesh/core/engine_adapter/bigquery.py
An "etag" is BQ versioning metadata that changes when an object is updated/modified. 
BQ's `update_table` method compares the etags of the table object passed to it and the remote table being updated, erroring if the etags don't match. That ensures the structure of the update aligns with the current structure of the table. 
A customer project encountered this error because the remote table's etag changed between when comment registration pulled the table object with `get_table` and updated it with `update_table`. 
It's unclear how this could occur - sqlmesh created the table in the same process just prior to comment registration, so no other process could even know the name of the newly created physical table. The most probable cause is latency between table creation and etag …
> Feat: disable bigquery comment registration table update metadata comparison

- web/client/openapi.json
- web/client/src/library/components/documentation/Documentation.tsx
- web/client/src/library/components/editor/Editor.tsx
- web/client/src/library/components/editor/EditorInspector.tsx
- web/client/src/library/components/editor/EditorPreview.tsx
- web/client/src/library/components/environmentDetails/EnvironmentDetails.tsx
- web/client/src/library/components/graph/ModelLineage.tsx
- web/client/src/library/components/search/SearchList.tsx
- web/client/src/library/pages/models/Models.tsx
- web/client/src/library/pages/root/Navigation.tsx
- web/client/src/library/pages/root/Page.tsx
- web/client/src/library/pages/root/Root.tsx
- web/client/src/models/sqlmesh-model.ts
- web/server/api/endpoints/models.py
- web/server/models.py
- web/server/watcher.py
Main purpose is to delegate figuring what has changed to `context.refresh`, so file watcher does not have to rely on context much. And change flow a bit to be:
-> file change
-> send SSE to UI 
-> send request to get models
-> refresh context
-> send new loaded models back
-> send request to plan to get changes and backfills
this also affects how we updating Lineage and Rendered Query on Docs page
> Fix: Optionally load context on models request

- sqlmesh/core/config/__init__.py
- sqlmesh/core/config/migration.py
- sqlmesh/core/config/root.py
- sqlmesh/core/context.py
- sqlmesh/core/state_sync/base.py
- sqlmesh/core/state_sync/engine_adapter.py
- sqlmesh/schedulers/airflow/state_sync.py
This update migrates snapshot records in the DFS order which lets us achieve the following benefits:
* The fingerprint cache is now reused per snapshot parent which leads to a higher number of cache hits.
* The DFS order allows us to efficiently evict parsed snapshots from the cache, since once the child is processed we can be sure we won't be needing its parsed record any longer.
Additionally, this update introduces a new migration config option: `promoted_snapshots_only`.  When set to `True` only snapshots that are part of at least one environment will be promoted, reducing the total number of migrated records substantially. This can be helpful for really big states. The tradeoff is that some snapshots will no longer be available for a quick rollback of changes immediately following the …
> Fix: Improve performance of migration

- tests/schedulers/airflow/operators/fixtures.py
- tests/schedulers/airflow/operators/test_hwm_sensor.py
- tests/schedulers/airflow/operators/test_targets.py
Airflow code: https://github.com/apache/airflow/blob/7bba05d782a64da0b5cce68ec92ac6f5c7b49221/airflow/__init__.py#L55-L61
We don't want to set this generally but for these tests it should be fine. We may need to later serialize other airflow tests, or have them also set this env var, but doing these for now since I know they are problematic. I don't have a repro for the issue currently.
> chore: set airflow as library for some tests

- .circleci/config.yml
- .circleci/update-pypirc.sh
- Makefile
- tests/core/test_state_sync.py
- tests/setup.py
Publishes to an internal repo within Tobiko SQLMesh core tests so they can be easily tested from other repos. 
Also includes some adjustments to http state sync tests to make them more portable.
> chore: publish sqlmesh tests

- tests/core/test_state_sync.py
The state sync maintains a model cache and without this change this model cache would be shared across tests which could potentially cause errors when run in parallel.
> chore: isolate state sync cache

- sqlmesh/core/snapshot/definition.py
Similar to SnapshotId: https://github.com/TobikoData/sqlmesh/blob/22544717d4e16aef1f65aba1ac3b0a8eb29f8bb0/sqlmesh/core/snapshot/definition.py#L122-L125
This will now ensure that if you use `SnapshotNameVersionLike` that all classes have a `name_version` property.
> chore: add name_version prop to name version class

- tests/setup.py
The goal is to publish a version of sqlmesh-tests that matches the version of core that it corresponds to.
> chore: fix version detection for sqlmesh_tests

- sqlmesh/core/context.py
- sqlmesh/core/selector.py
This fixes a scenario when the selector sources models from the unfinalized set of environment snapshots, while the `ContextDiff` uses the finalized set which leads to unexpected diffs and backfills when using selector.
> Fix: Use latest finalized environment snapshots in selector

- sqlmesh/core/snapshot/definition.py
- sqlmesh/core/snapshot/evaluator.py
- tests/core/test_snapshot_evaluator.py
> Fix: Make sure that the deployable table is used for pre-/post- statements during the snapshot table creation

- sqlmesh/dbt/manifest.py
Closes #2242.
There're numerous macros in the [Elementary](https://www.elementary-data.com/) package that reference other macros in the following fashion:
```
{% set type_bigint = dbt.type_bigint or dbt_utils.type_bigint %}
{{ type_bigint() }}
```
Manipulating references in this way leads to dbt core not properly detecting macro dependencies, resulting in the omission of such dependencies from the manifest.
Since SQLMesh relies on the manifest to load dbt projects, it ends up not including omitted macro dependencies which leads to failures at runtime (see #2242). 
This update excludes models provided by the `elementary` package, ensuring that users relying on it can still load their projects with SQLMesh.
A long-term solution would involve improving our own macro dependency detection …
> Fix: Ignore models from the 'elementary' package when loading a dbt project

- .circleci/config.yml
The project level has these env vars set which makes us ignore the values in pypirc when we publish. We unset them so we use pypirc when publishing.
Thanks @vchan for the help.
> chore: unset twine when exporting sqlmesh tests

- sqlmesh/dbt/test.py
- tests/dbt/test_test.py
dbt test kwargs can be multiline. According to the yaml standard, multiline values will end in a newline. This causes a problem with Jinja rendering, where it fails to parse when the trailing newline is present. This PR removes the trailing newline when building the test kwargs.
> Fix: Remove trailing newline from dbt  multiline test kwargs.

- sqlmesh/core/engine_adapter/trino.py
- tests/core/engine_adapter/test_trino.py
When running a bunch of incremental models with thousands of intervals across them, I noticed thousands of catalog type lookup queries being submitted (one for each interval).
It doesn't add a heap of load but I thought it was a bit unnecessary, so here's a patch to address it.
I notice other components within sqlmesh making use of `functools.lru_cache` so I wrapped `TrinoEngineAdapter.get_catalog_type` with it.
The core assumption is that the catalog type wont change within the same sqlmesh run. I think this is fine; to change a catalog type in Trino you have to restart the server, which would abort the current sqlmesh run anyway.
> Fix: Cache Trino catalog type lookup to reduce load

- sqlmesh/core/engine_adapter/mixins.py
- tests/core/engine_adapter/test_trino.py
- tests/core/test_model.py
Currently, using iceberg column transforms as the `partitioned_by` model property, eg:
```
MODEL (
name foo,
kind INCREMENTAL_BY_TIME_RANGE (
time_column transacttime,
),
partitioned_by day(transacttime),
....
)
```
throw a SQLMesh error:
`Error: partitioned_by field ''day(transacttime)'' does not contain a column`
A closer look at [the docs](https://trino.io/docs/current/connector/iceberg.html#partitioned-tables) reveal that, for an Iceberg table, the partition columns need to be defined as `ARRAY[varchar]`.
So this PR addresses that by wrapping the partition columns in `exp.Array` instead of `exp.Schema` and rendering them as varchar literals.
Note that Trino works with both the following syntax:
`partitioning = ARRAY['day("cola")', '"colb"']`
or
`partitioning = …
> Fix: Fix partitioning property for Trino iceberg tables

- sqlmesh/core/test/definition.py
~This was an oversight which probably surfaced with a delay, hopefully this fixes the CI in main.~ 
See comment below.
> Fix: convert lists, ndarrays to tuples when sorting unit test dataframes

- sqlmesh/core/loader.py
- web/client/src/library/components/documentation/Documentation.tsx
- web/client/src/library/components/editor/EditorInspector.tsx
- web/client/src/library/components/fileExplorer/Directory.tsx
- web/client/src/library/components/fileExplorer/File.tsx
- web/client/src/library/components/graph/ModelLineage.tsx
- web/client/src/library/components/loading/LoadingStatus.tsx
- web/client/src/library/pages/root/Navigation.tsx
- web/server/api/endpoints/directories.py
- web/server/api/endpoints/files.py
- web/server/settings.py
- web/server/utils.py
- web/server/watcher.py
- Optionally rely on `context` when working with files
- Reload `context` if `config.*` has changed
- Track newly added files to trigger `context.load()`
> Fix: Reload context on config change

- docs/reference/model_configuration.md
- sqlmesh/core/model/definition.py
- sqlmesh/core/node.py
- sqlmesh/core/snapshot/definition.py
- sqlmesh/schedulers/airflow/dag_generator.py
- tests/core/test_model.py
- tests/core/test_scheduler.py
This feature allows setting an explicit end date on an incremental model, rather than using the implicit end date of "right now".
The use-case is addressing historical / "archive" datasets that only have data for a certain date range (and typically these would be defined as forward-only as well).
In these cases, its there is no use in generating new intervals after a certain date.
> Feat: Add the ability to specify a model end date

- sqlmesh/__init__.py
- sqlmesh/cli/main.py
- sqlmesh/core/constants.py
- sqlmesh/magics.py
- tests/cli/test_cli.py
- tests/integrations/jupyter/test_magics.py
Currently we assume all logging should go to a relative directly of "logs". This change makes it so that users of CLI or Magics can change the logging directory to where they want but default still to "logs". 
Also included is a fix for tests so they use a function scoped path for the log files instead of sharing log directory with other tests.
> feat: add ability to configure logging dir

- sqlmesh/core/engine_adapter/mixins.py
pandas.io.sql generates a UserWarning for DBAPI2 connections that are not sqlite3:
```
sqlmesh/core/engine_adapter/mixins.py:84: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
```
This will suppress the warning within PandasNativeFetchDFSupportMixin._fetch_native_df().
> fix: suppress Pandas DBAPI2 connection warnings.

- examples/sushi/config.py
- sqlmesh/core/model/meta.py
- tests/core/test_model.py
- tests/dbt/test_transformation.py
There was a gap in `clustered_by` normalization where we didn't normalize if passed in a list. This PR adds normalization for list types.
Fixes #2293
> Fix!: Normalize dbt model cluster_by field

- sqlmesh/integrations/github/cicd/controller.py
- tests/fixtures/github/pull_request_synchronized_enterprise.json
- tests/integrations/github/cicd/test_github_event.py
Enterprise has a different URL start than non-enterprise but the tail of the URL is the same and that is all we care about so this updates the url parsing to be more flexible to accommodate enteprise.
> feat: support github enterprise url

- examples/sushi/models/marketing.sql
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/bigquery.py
- sqlmesh/core/engine_adapter/mixins.py
- sqlmesh/core/engine_adapter/postgres.py
- tests/core/engine_adapter/test_bigquery.py
- tests/core/engine_adapter/test_integration.py
- tests/core/engine_adapter/test_postgres.py
- Escape by default for all engines but Postgres
- Do not escape when directly modifying a BigQuery table object to create column comments
Closes #2290
> Fix: escape backslashes in comments

- sqlmesh/core/snapshot/definition.py
- sqlmesh/core/state_sync/engine_adapter.py
- tests/core/test_snapshot.py
If not reset, the next time the migrated snapshot is executed it'd detect that there are no intervals associated with its `identifier` after the `effective_from` timestamp and conclude that additional backfill is necessary in order to meet the configured `effective_from` setting.
> Fix: Reset the 'effective_from' attribute for migrated snapshots

- examples/airflow/Makefile
- setup.py
I realized that the Airflow library fix in this PR only works for Airflow 2.4+: https://github.com/TobikoData/sqlmesh/pull/2265
Therefore I just bumped to the latest bugfix of 2.4. I tested locally and it worked.
> chore: bump airflow version for testing

- docs/integrations/engines/bigquery.md
Added missing `execution_project` to BQ docs
> chore: document bq execution project

- sqlmesh/core/test/definition.py
- tests/core/test_test.py
Array columns in input queries are returned with the `np.ndarray` type from an engine adapter's fetchdf() function. This PR converts them into Python lists so ruamel and sqlglot can handle them.
> Fix: Handle arrays in test generation

- .circleci/continue_config.yml
This adds a job in the `main_pr` CircleCI workflow which emits a webhook to enterprise's pipeline endpoint to trigger testing ([PR #195](https://github.com/TobikoData/sqlmesh-enterprise/pull/195) in sqlmesh-enterprise repository)
> feat: Trigger enterprise testing on commit

- setup.py
- sqlmesh/dbt/seed.py
- tests/dbt/test_transformation.py
This ensures that the original dbt behavior is preserved for seeds. Otherwise, projects that heavily rely on seeds and dbt's method of inferring column types can't be easily run with SQLMesh.
> Feat!: Infer column types in the same manner as dbt does when converting dbt seeds

- Makefile
- docs/integrations/engines/trino.md
- pytest.ini
- sqlmesh/core/engine_adapter/mixins.py
- sqlmesh/core/engine_adapter/trino.py
- tests/core/engine_adapter/config.yaml
- tests/core/engine_adapter/docker-compose.yaml
- tests/core/engine_adapter/test_integration.py
- tests/core/engine_adapter/test_trino.py
- tests/core/engine_adapter/trino/catalog/datalake_delta.properties
- tests/core/engine_adapter/trino/initdb.sql
- Only tested with Hive catalog type
- Converts timestamp types in DDL schemas
- delta_lake only supports two timestamp data types. We convert other timestamp types to those two for use in DDL statements. Trino/delta automatically converts the data values to the correct type on write, so we only need to handle the column types in DDL. https://trino.io/docs/current/connector/delta-lake.html#delta-lake-to-trino-type-mapping
- `timestamp(6)` for non-timezone-aware
- `timestamp(3) with time zone` for timezone-aware
> Feat: support Trino Delta Lake connector

- sqlmesh/core/model/definition.py
Includes dialect when parsing SQL in case it contains dialect specific SQL inside. 
Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1711390457509869
Repro: `parse_one("select object_construct('key1', 'value1') as good_column").sql()` 
Error: `Error: Name needs to be a string or an Identifier, got: <class 'sqlglot.expressions.Literal'>`
Works: `parse_one("select object_construct('key1', 'value1') as good_column").sql(dialect="snowflake")`
> fix: include dialect when extracting macro references

- docs/concepts/tests.md
- sqlmesh/cli/example_project.py
- sqlmesh/core/test/definition.py
- sqlmesh/utils/date.py
- tests/core/test_test.py
- tests/web/test_main.py
Fixes sixth item in https://github.com/TobikoData/sqlmesh/issues/1637
> Feat: improve unit test failure reporting when rows are missing

- sqlmesh/core/model/definition.py
- tests/core/test_snapshot.py
Missed in the original PR: https://github.com/TobikoData/sqlmesh/pull/2287
Breaking because we need to calculate new fingerprints.
> fix!: include end in metadata hash

- sqlmesh/core/scheduler.py
I've realized that deployability index would be wrong when running the `sqlmesh run` command against non-prod environments.
> Fix: Use a correct deoployability index when running the scheduler against non-prod environments

- setup.py
- sqlmesh/core/model/kind.py
- tests/core/test_model.py
The bug described here is what would happen prior to this PR: https://github.com/TobikoData/sqlmesh/pull/2318
This PR is expected to fix this behavior. I was able to repro the bugged behavior locally and it did fix that. I also verified scd type 2 column BQ integration still passes. The added test would fail with past behavior but now works.
Breaking because it depends on a minor bump of SQLGlot. 
Depends on: https://github.com/tobymao/sqlglot/pull/3220
> fix!: fix time_data_type serialization/deserialization

- sqlmesh/core/context.py
- sqlmesh/integrations/github/cicd/controller.py
- tests/integrations/github/cicd/test_github_commands.py
Prior this to change test summaries in the CI/CD bot would have columns truncated. This matches plan behavior. In plan though I am in the CLI itself so it not a big deal to just run the test again from cli to get the full output. WIthin Github that interactivity is not available so it seems better to default to showing more than not enough. 
I decided to just make this the new default behavior and see if we can avoid a config flag to change it. Also I'm not calling this breaking, despite being a behavior change, since it is a non-functional behavior change.
> feat: make cicd bot output verbose

- sqlmesh/core/engine_adapter/base.py
Although this has not caused any known issues, the intent here is to make sure all columns are defined including the "managed" columns. Therefore adding a check to make sure column data types are known.
> fix: in scd type 2 also make sure all columns are known

- sqlmesh/core/node.py
- tests/core/test_model.py
Prior to this PR a user would get validation error if defining an end without start that wasn't clear on the issue. This validates prior to the actual value validation if an end is defined without a start and gives a more clear error.
I think requiring start with end seems reasonable. Open to other thoughts though.
> fix: ensure start if using end

- docs/concepts/tests.md
- sqlmesh/core/test/definition.py
- tests/core/test_test.py
This allows one to set `partial` in a single place and have it be applied to _every_ output fixture.
> Feat: allow partial to be for every output in a test

- .circleci/continue_config.yml
do not send text in body of commit
> chore: only include commit subject in webhook

- sqlmesh/core/snapshot/definition.py
- tests/core/test_scheduler.py
Prior to this PR if you had a plan that required loading beyond a model's end date, for example catching up a group of models when deploying to prod since they fell behind, you would get an error saying that start cannot exceed end. 
This PR makes it so that cases where start > end then we will just return that there are no missing intervals. This should preserve the intended behavior of allowing these models to be active in dags, and potentially have changes, but never exceeding their desired end date.
> fix: correctly skip loading archived snapshots

- docs/guides/incremental_time.md
- docs/guides/models.md
- sqlmesh/core/context.py
Documentation for the `sqlmesh dag` CLI on the models guide was incorrect and contradicted documentation for the command in other places. Also, a minor change to incremental time guide: in that sentence 'it' could refer to the model or the command so I made it explicit
> docs: fix docs for dag CLI

- sqlmesh/cli/main.py
- sqlmesh/core/context.py
- sqlmesh/core/test/definition.py
- sqlmesh/magics.py
- tests/core/test_test.py
Addresses the seventh item in https://github.com/TobikoData/sqlmesh/issues/1637. Was wondering whether we want to make the CTE generation optional. What do people think about this?
EDIT: went ahead and made it optional for the time being.
> Feat: generate CTE fixtures too when using the create_test command

- sqlmesh/core/snapshot/definition.py
- tests/core/test_context.py
- tests/core/test_snapshot.py
Prior to this PR if a start was set on a model that exceeded the max that had been loaded to prod then you would get an error that start > end. Although this would likely be uncommon in practice, while testing it could happen if you created a project without a start and had a daily model and then tested out adding an hourly model. 
This change checks if the node start exceeds the set end and if so we don't return any missing intervals. This does mean that you could end up with an empty table in production but I believe this is fine.
Example:
I have daily models in production that have been running for a bit and have loaded through until 2024-01-01. It is now 5 PM the next day and I add a new hourly model that starts at noon that day (2024-01-02 12:00:00). I deploy this to prod. Prod has …
> fix: don't load models if start is ahead of end

- docs/faq/faq.md
- docs/guides/configuration.md
- sqlmesh/core/config/connection.py
- sqlmesh/core/config/scheduler.py
- tests/cli/test_cli.py
- tests/core/test_connection_config.py
This PR improves the way we recommend that users use a separate state sync for production deployments in two ways:
* Moves information about this recommendation from FAQ to state connection configuration section
* More strongly emphasizes that this is recommended and explicitly lists what is recommended
* Warning log is output if not using the recommended state backend if in production
> chore: improve recommended state sync documentation

- docs/concepts/models/overview.md
- docs/integrations/dbt.md
- docs/reference/configuration.md
- sqlmesh/core/config/connection.py
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/shared.py
- sqlmesh/core/engine_adapter/snowflake.py
- tests/core/engine_adapter/config.yaml
- tests/core/engine_adapter/test_snowflake.py
Snowflake's documentation does not describe or demonstrate a way to alter/add column comments to VIEWs after creation, but `ALTER VIEW ... ALTER COLUMN ...` command does this. 
This PR:
- Adds the ability for snowflake to alter/add column comments to VIEWs after creation.
- Removes the `CommentCreationView.IN_SCHEMA_DEF_NO_COLUMN_COMMAND` enum value because it was only used by snowflake
- Makes comment registration `True` by default for Snowflake
> Fix!: expand snowflake VIEW column comments and make comment default true

- examples/sushi/models/order_items.py
- sqlmesh/core/model/definition.py
- sqlmesh/utils/metaprogramming.py
The upstream dependency are only captured if the `context.table` call is in the body of the `execute` function. This update makes sure that we also capture this calls in nested functions.
> Fix: Improve inference of upstream dependencies for python models

- setup.py
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/bigquery.py
- sqlmesh/core/engine_adapter/mixins.py
- sqlmesh/core/engine_adapter/postgres.py
> Chore!: bump sqlglot to v23.6.3

- setup.py
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/bigquery.py
- sqlmesh/core/engine_adapter/mixins.py
- sqlmesh/core/engine_adapter/postgres.py
Reverts TobikoData/sqlmesh#2382 to unblock releases. Will continue iterating locally to solved the CI issues.
> Revert "Chore!: bump sqlglot to v23.6.3"

- sqlmesh/core/plan/builder.py
- tests/core/test_plan.py
Using `snapshot.parents` was incorrect for this check since the removed model wouldn't be present in the list of Snapshot parents (since there's no more snapshot), but is still available in the model's `depends_on` set.
> Fix: Detection of broken model references when building a plan

- sqlmesh/core/macros.py
- tests/core/test_audit.py
- tests/core/test_macros.py
macro variables were not resolving additional macro references. also, we ensure conversion of sql to the right dialect when using string templates like `@sql`
cc @erindru
> fix: allow macros to recursively resolve closes #2399

- sqlmesh/core/context.py
- sqlmesh/core/test/context.py
- sqlmesh/core/test/definition.py
- tests/core/test_test.py
Addresses the 9th item in https://github.com/TobikoData/sqlmesh/issues/1637
> Fix: randomize unit test fixture names to avoid concurrency issues

- sqlmesh/core/console.py
Currently CLI always prints `...to backfill up until now`, which is inaccurate since, by default, we backfill up until the latest interval in prod.
This fixes the inaccuracy.
> Fix: The message used for prompting the backfill end date in CLI

- docs/concepts/tests.md
- docs/reference/cli.md
- docs/reference/notebook.md
- sqlmesh/cli/main.py
- sqlmesh/core/context.py
- sqlmesh/core/test/__init__.py
- sqlmesh/core/test/definition.py
- sqlmesh/magics.py
Addresses the tenth item in https://github.com/TobikoData/sqlmesh/issues/1637. I didn't address the CTE fixture item because creating views for CTEs may not be possible, e.g. if we don't have or can't correctly infer their `columns_to_types` mappings.
> Add support for "dumping" duckdb state on test failure to speed up debugging
As I mentioned in a reply in the above issue, I believe this PR should suffice because one can simply override the test connection database to "dump" the state for DuckDB, so the fixtures are not transient (due to creating them in-memory).
For example:
```yaml
gateways:
local:
connection:
type: duckdb
database: db.db
test_connection:
type: duckdb
catalogs:
db: test.db
default_gateway: local
dialect: duckdb
```
I'm using this config for the example …
> Feat: add flag for preserving unit test fixtures to improve debuggability

- sqlmesh/core/test/definition.py
Prior to this change, setting `partial: True` in a unit test could result in non-deterministic behavior because `referenced_columns` was created as a set, meaning that the column order would not necessarily be respected, thus causing issues when comparing the actual and expected dataframes.
> Fix: make partial setting in unit tests deterministic

- docs/concepts/macros/jinja_macros.md
- docs/concepts/macros/macro_variables.md
- docs/concepts/macros/sqlmesh_macros.md
- docs/concepts/models/python_models.md
- docs/reference/configuration.md
- sqlmesh/core/audit/definition.py
- sqlmesh/core/config/common.py
- sqlmesh/core/config/gateway.py
- sqlmesh/core/config/root.py
- sqlmesh/core/constants.py
- sqlmesh/core/context.py
- sqlmesh/core/loader.py
- sqlmesh/core/macros.py
- sqlmesh/core/model/decorator.py
- sqlmesh/core/model/definition.py
- sqlmesh/core/test/context.py
- sqlmesh/dbt/loader.py
- sqlmesh/dbt/manifest.py
- sqlmesh/utils/jinja.py
- sqlmesh/utils/metaprogramming.py
- tests/core/test_audit.py
- tests/core/test_config.py
- tests/core/test_context.py
- tests/core/test_model.py
- tests/core/test_snapshot.py
- tests/integrations/jupyter/test_magics.py
- tests/schedulers/airflow/test_client.py
This PR introduces support for user-defined variables to SQLMesh native projects. The variables can now be accessed in the following contexts:
* SQL model definitions
* Python model definitions
* Standalone audits
* Native macros
* Jinja macros
Additionally, SQLMesh intelligently detects variable names referenced in all aforementioned contexts and only includes values for referenced variables into snapshots. This means that if a variable changes, only models that actually use it will be impacted.
However, this capability comes with a few constraints, as the usage detection is performed statically by introspecting relevant SQL/Python/Jinja code.
* When using the `@VAR` macro in SQL, the first argument must always be a string literal. The same limitation applies to the `{{ var(...) }}` …
> Feat!: Support variables in native SQLMesh projects

- docs/integrations/engines/spark.md
- sqlmesh/core/engine_adapter/databricks.py
- sqlmesh/core/engine_adapter/spark.py
- tests/conftest.py
- tests/core/engine_adapter/test_spark.py
I've updated Spark's catalog operations to not rely solely on 3.4+. In general after testing it seems like Spark may only support a single catalog for managing SQLMesh models. 
For `set_catalog` override I tested and I couldn't find any reason why `create_schema` and `drop_schema` were to requiring set catalog to work and it seems like on both Spark and Databricks the full catalog.db reference is compatible. So I removed this entirely. 
Databricks does require the set catalog when getting objects outside of the default catalog. 
For Spark if I try to do this within my local environment I get an error about not being able to do this on v2 tables. So I think potentially our current implementation requires the use of `spark_catalog`?
> fix: widen spark support

- sqlmesh/core/lineage.py
- tests/web/test_lineage.py
this should significantly increase the perf of lineage, will require sqlglot 23.1
> feat: improve lineage perf

- sqlmesh/core/model/definition.py
- sqlmesh/core/model/seed.py
- web/server/watcher.py
Prior to this change, large seed files were chunked and so pandas' type inference would be incomplete, leading to users seeing [warnings](https://pandas.pydata.org/docs/reference/api/pandas.errors.DtypeWarning.html) related to data type mismatches.
This PR makes it so that seed files are not chunked, in order to avoid the mixed type inference issues. The tradeoff here is that this could potentially lead to memory consumption issues for larger seed files, but that should be ok since we don't really encourage users to have really large seed files where memory consumption would actually be a problem.
One workaround we discussed was to add both `low_memory` and `dtype` to `CsvSettings`, but the latter was involved because we'd need to allow the properties to be arbitrarily nested in order to …
> Fix: improve csv seed file type inference

- examples/ibis/models/ibis_full_model_python.py
- examples/ibis/models/ibis_full_model_sql.py
Previously, applying a plan in this project from an empty state would fail since the table `ibis.incremental_model` would not yet exist. This gets the physical table name from context and passes that into the ibis connection instead
> Fix: get physical table name in ibis example

- sqlmesh/core/model/definition.py
- tests/core/test_model.py
Prior to this change, if a projection had multiple comments attached to it, all of them would be joined and used as its description.
This PR makes it so that we'll only use the last comment in the projection's `comments` list for the description. That should make the behavior more consistent, because we can now say "to add a description, simply add a comment to the end of the line" and we'll not mix other comments in.
The motivation around this can be found in https://github.com/TobikoData/sqlmesh/pull/2383#discussion_r1551745475. TL;DR: we want to avoid having to deal with how SQLGlot attaches comments in expressions.
For example, `comment 1` in the following example could be a comment that we don't really intend to register in the db, but is there to only provide additional information: …
> Refactor: only use the last comment attached to a projection as its description

- sqlmesh/core/state_sync/common.py
- tests/core/test_state_sync.py
We should ignore `lookback` and `allow_partials` attributes when checking the missing intervals for gaps during the promotion process. Setting `end_bounded` to `True` achieves exactly this.
> Fix: Use end-bounded missing intervals when checking for gaps during the promotion

- docs/concepts/models/model_kinds.md
- docs/concepts/plans.md
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/trino.py
- sqlmesh/core/model/kind.py
- sqlmesh/core/snapshot/definition.py
- sqlmesh/core/snapshot/evaluator.py
- sqlmesh/dbt/model.py
- tests/core/engine_adapter/test_base.py
- tests/core/test_snapshot.py
- tests/core/test_snapshot_evaluator.py
- tests/dbt/test_transformation.py
This update adds ability to restate model kinds for which restatements weren't supported in the past: incremental by unique key, unmanaged incremental (dbt incremental), and SCD Type 2.
When restating models of the aforementioned types, the entire model history will be reprocessed from scratch, making this operation equivalent to the full-refresh command in dbt. Start/end dates specified by a user in the plan will be ignored for such models.
For dbt projects we now rely on the [full_refresh ](https://docs.getdbt.com/reference/resource-configs/full_refresh) model configuration to determine whether the restatement should be disabled or not.
> Feat: Support restatements for the incremental unmanaged model kind

- docs/concepts/tests.md
The addition is basically the following line:
> Note: the columns in each row of an expected output must appear in the same relative order as they are selected in the corresponding query.
> Chore: document expected column order in unit tests

- sqlmesh/core/engine_adapter/spark.py
- sqlmesh/engines/spark/db_api/spark_session.py
- tests/conftest.py
- tests/core/engine_adapter/test_spark.py
Prior to this change we were doing catalog setting in two different places (at connection level and at the adapter level) which made it easy to forget one of them when making changes like in https://github.com/TobikoData/sqlmesh/pull/2409. Therefore this consolidates to the connection level. Passes integration tests for both Spark and Databricks. 
An alternative change would be to remove setting catalog at the connection level. This is done to protect against ambiguous references to make sure the behavior is consistent. We shouldn't expect this internally within SQLMesh but users could use public facing methods like `fetchdf` and they would expect the catalog they set at the connection level to be applied when running those queries.
> fix: set catalog properly across connection and engine

- sqlmesh/core/engine_adapter/databricks.py
Prior to this change if someone was using Databricks without databricks-connect (so SQL only) they would get an error about missing pyspark dependency. Databricks-connect installs PySpark therefore we know that if they are using a spark session then they must have pyspark.
> fix: only import pyspark if using databricks connect

- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/base_postgres.py
- sqlmesh/core/snapshot/evaluator.py
- tests/core/engine_adapter/test_base_postgres.py
- tests/core/test_snapshot_evaluator.py
We always want a cascade delete for physical objects, as only other physical objects within SQLMesh can refer to it at the time of deletion.
When it comes to deleting views in the virtual layer, we still want to do this in a non-cascade fashion to prevent the accidental removal of views created outside SQLMesh that happen to reference a SQLMesh view model.
Reported in https://tobiko-data.slack.com/archives/C044BRE5W4S/p1712997673915609
> Fix: Always use CASCADE when deleting views in the physical layer for postgres and redshift

- sqlmesh/core/test/definition.py
- sqlmesh/utils/errors.py
- tests/core/test_test.py
This PR:
- Adds a new YAML setting, `columns`, which allows users to define schemas for upstream models ([context](https://tobiko-data.slack.com/archives/C044BRE5W4S/p1712872939106209))
- Refactors several pieces of the test definition module:
- Moves `TestError` to `sqlmesh.utils.errors` where it belongs (breaking)
- Moves most validations inside of `_validate_and_normalize_test` (previously `_normalize_test`)
- Introduces a couple new in-memory caches to avoid repeating the same normalization calls
> Feat!: allow overriding input fixture schema in unit tests

- sqlmesh/core/test/definition.py
- sqlmesh/utils/__init__.py
- tests/core/test_test.py
Prior to this change, if there was at least one unknown type in the schema of an input model we would try to infer all of its column types again using a combination of `convert` and `annotate_types`, thus ignoring the types that we'd previously correctly inferred.
However, relying solely on the `convert` and `annotate_types` approach is problematic, because the former is dialect/type-agnostic and thus it would always convert dictionaries into `MAP`s, which led to type mismatch errors (eg. when we would expect `STRUCT`s instead).
This PR ensures we leverage the inferred types, and only fall back to the above strategy for the columns that have unknown types. It also enforces that we'll only create an input fixture if its inferred schema contains known types.
This will open a path for users …
> Feat: allow partial schema inference in unit test

- sqlmesh/core/snapshot/definition.py
- tests/schedulers/airflow/test_client.py
selectors causes a lot of dag snapshot_id comparisons with upstream. pydantic is very slow with __eq__, i saw a 50 sec -> 7 sec drop.
> fix: performance for selectors

- sqlmesh/core/model/definition.py
- sqlmesh/core/snapshot/definition.py
- tests/core/test_integration.py
- tests/core/test_model.py
- tests/core/test_plan.py
- tests/core/test_snapshot.py
- tests/schedulers/airflow/test_plan.py
Previously we only considered the following models to be dependent on their past:
1. `INCREMENTAL_BY_UNIQUE_KEY` models.
2. Models that reference self in their queries.
There are, however, more cases when the model depends on its past, like eg. SCD2 and `IncrementalUnmanaged` models. This update extends the definition of the `depends_on_past` property to encompass these.
> Fix: Improve the depends_on_past definition

- sqlmesh/core/state_sync/engine_adapter.py
Prior to this PR we would validate that SQLMesh minor versions matched and migrate if they did not while with this change we will now only validate and not migrate.
> fix: remove migrate on sqlmesh minor bump

- docs/concepts/macros/sqlmesh_macros.md
- docs/integrations/engines/duckdb.md
- docs/reference/cli.md
- docs/reference/model_configuration.md
- Clarify global/gateway/local macro variable precedence
- Add info on DuckDB credentials management for reading from cloud services
- Add some context to the `sqlmesh rollback` CLI docs caution message
- Add missing `when_matched` argument to the INCREMENTAL_BY_UNIQUE_KEY configuration reference
> Docs: assorted minor updates

- sqlmesh/core/engine_adapter/databricks.py
Recent PR moved catalog related operations to the spark connection level: https://github.com/TobikoData/sqlmesh/pull/2428
This doesn't work then when calling super since Databricks does not use the same connection as spark. The default behavior is different anyways (Spark default catalog is `spark_catalog` while Databricks is `hive_metastore`) so it probably just makes sense to not share functionality between these two anymore.
I do assume that the user is using a Databricks release of Spark 3.4 or greater but that should be a safer assumption than it would be for Spark users.
> fix: databricks catalog with session support

- Makefile
- sqlmesh/core/test/definition.py
- tests/core/engine_adapter/test_integration.py
SQLMesh `test` input values are specified in YAML, so it is not possible to correctly infer all intended data types from the raw values.
`test`s work by creating an `expected` pandas dataframe from the YAML and creating an `actual` pandas dataframe from the query results returned by the database. We prevent type mismatches by converting the `expected` df columns to the `actual` df types.
If a test query returns `datetime.xxx` values, the `actual` pandas column type is generic `object` and the type conversion is a noop. Therefore, for pandas `object` columns we examine an `actual` sentinel value and, if it is `datetime.xxx`, manually convert the `expected` column to the correct type. It is safe to assume the `actual` column contains a single type because it is returned by a database call.
> Fix: manually convert test input string if db returns datetime.xxx

- sqlmesh/integrations/github/cicd/command.py
- sqlmesh/integrations/github/cicd/controller.py
- tests/integrations/github/cicd/test_github_commands.py
Prior to this PR if a test had an exception when executing, not a failure which means the tests didn't pass, the bot would incorrectly report this as "skipped" instead of a failure. Now the bot will properly categorize this as a failure and output the exception in the status summary.
Also updated another test to verify the error output upon failure.
> fix: Github action bot handle test exceptions

- sqlmesh/core/context_diff.py
This should also prevent the future "Seed model ... is not hydrated" issues.
> Fix: Print warning instead of crashing when failed to generate a model diff

- examples/sushi/tests/test_customer_revenue_lifetime.yaml
- sqlmesh/core/test/definition.py
- tests/core/test_test.py
- tests/integrations/github/cicd/test_integration.py
- tests/web/test_main.py
Fixes #2476
Prior to this fix we wouldn't create a fixture for the tested model if it referenced itself, leading to a crash when we'd run the query against the test connection. This PR addresses this issue, so that:
- when the model is included in the inputs, the fixture is created as always
- when it is not included, we add it as an empty table
> Fix: handle self-referencing models in unit tests

- sqlmesh/core/test/definition.py
- tests/core/test_test.py
We currently create unit test fixtures within the specified catalog of the corresponding models, which can lead to permission issues for some external models.
This PR:
- Sets each input's catalog to the default one, for which we should have write access
- Sets each input's schema to a new testing schema, to ensure consistency and environment isolation
To avoid name clashes, we now generate fixture names using the format: `[original_catalog__][original_shema__]name`.
>  Fix!: set default catalog for unit test fixtures, create new schema for them

- sqlmesh/core/macros.py
- tests/conftest.py
- tests/core/test_macros.py
Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1713786694499789
> Fix: use MacroEvaluator dialect in certain builtin macros

- sqlmesh/core/model/definition.py
- sqlmesh/magics.py
Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1713796905603349
Prior to this change, we would render the definition of the model targeted by the `%model` magic and then replace the cell with `%%model <name>\n<rendered definition>`. This was problematic because we were adding the default model property values to its definition, leading to (at least) visually unexpected results.
This PR makes it so that the first time we execute the `%model` magic, we read the model's definition directly from its file, so that the replaced cell then reflects the user's query more closely (auto-formatted appropriately).
> Fix: read model file for %model magic instead of rendering defn

- sqlmesh/core/state_sync/engine_adapter.py
Since we currently don't migrate snapshot records that are stored as part of plan DAG specs, we need to cleanup the old specs to make sure that the version upgrade doesn't cause Airflow scheduler to break.
> Fix: Cleanup plan DAG records when migrating snapshot records

- sqlmesh/core/snapshot/definition.py
- sqlmesh/core/state_sync/engine_adapter.py
- tests/core/test_state_sync.py
When the janitor deletes obsolete snapshots, intervals associated with them remain, since the deleted snapshot may have been sharing its version with other snapshots.
When we delete intervals for restatement purposes, we have to delete them for **all** unique (name, identifier) pairs that are associated with the same version, because the interval hydration happens on the version basis.
Before this update, we used to source snapshots with the shared version from the `_snapshots` table. This led to incomplete removal of intervals since only intervals for existing snapshots were considered, not for the garbage collected ones.
With this update, snapshots with shared versions are sourced directly from the `_intervals` table which is the source of truth in this case.
> Fix: When removing intervals also remove them for snapshots that have been deleted by the janitor process

- sqlmesh/core/plan/builder.py
- sqlmesh/core/state_sync/engine_adapter.py
- sqlmesh/migrations/v0049_replace_identifier_with_version_in_seeds_table.py
- tests/core/test_state_sync.py
The contents of the seed are only different if the snapshot's version is different too. Therefore, it doesn't make sense to store seed content by the (name, identifier) tuple since it leads to duplication and more complexity and inefficiencies downstream. For example, we don't need to migrate seed records if we were to store them by (name, version), since only identifiers change during the migration.
> Chore!: Use version instead of identifier in the seeds table

- tests/core/test_state_sync.py
Adding an interval for a snapshot that doesn't exist isn't valid so this updates the test to take a more realistic path to the scenario being tested.
> chore: update test remove snapshot

- .circleci/continue_config.yml
First we need to single quote the `$COMMIT_MESSAGE` definition so that bash does not actually execute the command during assignment but rather stores the entire string as-is in the env file. We then have to do a parameter expansion on `$COMMIT_MESSAGE` to properly replace any instances of double quotes with escaped double quotes. This allows the commit message to be safely passed into JSON. 
Note that when a commit is reverted, the default message is `Revert "<original_message>"`, and those double quotes will need to be escaped. Otherwise they get interpreted as special characters by bash.
> Fix: quote escape commit message during trigger private tests

- sqlmesh/core/state_sync/engine_adapter.py
- tests/core/test_state_sync.py
This may happen when a metadata change is applied to a seed model, in which case the version will remain the same.
Without this fix we may violate the primary key constraint for databases that support it, or otherwise create duplicated records.
> Fix: Make sure that we don't attempt to create two seed records with the same version in state

- sqlmesh/core/macros.py
- sqlmesh/core/model/definition.py
- tests/core/test_model.py
This update allow users to easily parameterize their model names and other attributes by using macros and variables inside the `MODEL` statement. Thus the following example is now a valid definition:
```
MODEL (
name @{gateway}.test_model
);
```
> Feat: Support macros in the MODEL statement

- sqlmesh/core/plan/evaluator.py
Prior to this we would add a reference to the intervals tables to a snapshot that doesn't exist when doing forward-only changes. This flips the order so we first add the snapshot and then start adding intervals.
> fix: push snapshots before updating intervals

- sqlmesh/core/engine_adapter/databricks.py
- sqlmesh/core/engine_adapter/mixins.py
- sqlmesh/core/engine_adapter/mysql.py
- sqlmesh/core/engine_adapter/snowflake.py
- sqlmesh/migrations/v0049_replace_identifier_with_version_in_seeds_table.py
- tests/core/engine_adapter/test_databricks.py
- tests/core/engine_adapter/test_mysql.py
- tests/core/engine_adapter/test_snowflake.py
Removing redundant code in favor of just specifying a full target table name when renaming and relying on SQLGLot to remove the schema portion of the name where applicable.
> Fix: Always use full target name when renaming tables and rely on SQLGLot to remove schema where needed

- sqlmesh/core/console.py
- sqlmesh/core/plan/definition.py
- sqlmesh/integrations/github/cicd/controller.py
- tests/integrations/github/cicd/test_github_commands.py
- tests/integrations/github/cicd/test_integration.py
Prior to this change the bot displayed changed by using the output generated when categorizing changes which would give you the directly modified snapshot and then the indirectly modified models in a subtree. The problem is that this doesn't cover all possible changes and therefore removed snapshots (and likely other things) were not being represented.
This change uses the normal output that is created instead which captures everything. This was actually already written but not used since we switched to the above approach so it just needed updated. I tested all the new output that is generated against this to make sure it formats properly: https://jbt.github.io/markdown-editor/
The main regression here is that users no longer see the directly modified and then below it what was indirectly …
> fix: action bot properly output all changes

- sqlmesh/core/engine_adapter/bigquery.py
- tests/core/engine_adapter/test_bigquery.py
BigQuery supports the `OPTIONS` clause when creating views. Previously we weren't propagating `table_properties` set at the model level into the view creation statement.
> Fix: Propagate table properties as options when creating views in BQ

- sqlmesh/core/audit/builtin.py
- tests/core/test_audit.py
This isn't strictly necessary since you can add the condition in the `criteria`. But there are several advantages to supporting `condition`:
1. it makes `forall` consistent with other audits
2. it is simpler to reason about, consider `foreall(criteria=[f != 42 OR a > b])` vs `forall(criteria=[a > b], condition=(f=42))`
3. more concise if you want to apply multiple criteria to the same subset of rows
> feat: support `condition` argument in `forall` audit

- docs/concepts/macros/sqlmesh_macros.md
- sqlmesh/core/macros.py
- tests/core/test_macros.py
Prior to this change Start macro required the types to be known since it always did a cast of the selected columns to their desired type. This change makes it so if we don't know the columns to types then we just put in the columns otherwise we will do the cast. Therefore now to use the macro we just have to know the columns of the model being referenced.
An alternative implementation would have been to check if each column has a type and if so cast, otherwise select but decided to just do an all or nothing approach. 
Consider this breaking because if someone starts using this feature then their models would not be compatible with someone using an earlier release.
> feat!: make star macro more flexible

- docs/concepts/macros/sqlmesh_macros.md
- sqlmesh/core/constants.py
- sqlmesh/core/loader.py
- sqlmesh/core/macros.py
- sqlmesh/core/model/definition.py
- sqlmesh/utils/metaprogramming.py
- tests/core/test_macros.py
hardcoding the module name of a macro func is brittle. this now labels any macro that is already loaded as builtin.
> fix: use more robust way of identifying std macros

- sqlmesh/core/macros.py
- sqlmesh/core/model/meta.py
- tests/core/test_model.py
This fixes a couple of bugs I came across while trying to get the sushi project to run in snowflake.
> Fix: force-lowercase dialect names, normalize macro columns_to_types

- sqlmesh/core/context.py
- sqlmesh/core/notification_target.py
- sqlmesh/core/plan/evaluator.py
- tests/core/test_notification_target.py
Makes changes to how apply notifications are called in context.py to include plan_id. Also modifies the Airflow plan_request_id to be the same as plan_id so that apply notifications can include links to the Airflow job. All of this will help our users find logs when they want to see what SQL queries SQL Mesh runs or track down an error.
Currently when a SQL Mesh apply fails with Airflow acting as scheduler, the stack trace sent to the notification integration doesn't include any information about why the apply failed. Getting the actual stack trace out of airflow and into the notification would be very complicated, so a good work around is just to include a link to the DAG so users can quickly explore the logs for their run.
> feat: adds plan id to apply notifications

- sqlmesh/core/test/definition.py
This is needed to correctly convert quoted catalogs like `'"foo"'` into `Identifier` expressions.
> Fix: use parse_identifier instead of to_identifier for catalog in tests

- sqlmesh/core/model/kind.py
Having a batch_size < lookback should be valid so removing this check. We couldn't think of a good reason why it was added in the first place (which was when lookback was first added: https://github.com/TobikoData/sqlmesh/pull/736)
> fix!: remove batch_size lookback check

- sqlmesh/dbt/manifest.py
- tests/dbt/test_config.py
- tests/dbt/test_manifest.py
- tests/fixtures/dbt/sushi_test/config.py
- tests/fixtures/dbt/sushi_test/dbt_project.yml
Previously we weren't passing variables into parsers for `profiles.yaml` and `dbt_project.yaml`.
> Fix: Pass variable overrides when parsing profiles and dbt_project yamls

- sqlmesh/core/loader.py
- sqlmesh/core/model/decorator.py
- sqlmesh/core/model/kind.py
- sqlmesh/utils/pydantic.py
- tests/core/test_model.py
- tests/core/test_snapshot.py
python models allow users to create various pydantic models that contain sql queries. these sql queries are by default parsed as sqlglot dialect which has unintended consequences.
we now set the config default dialect while loading these python models which allows the pydantic validators to set the expected dialect
> fix!: add implicit dialect to pydantic models in python

- examples/sushi/macros/utils.py
- examples/sushi/models/top_waiters.sql
- setup.py
- tests/core/engine_adapter/docker-compose.yaml
- tests/core/engine_adapter/test_integration.py
- tests/core/test_macros.py
- tests/core/test_model.py
- tests/integrations/jupyter/test_magics.py
the tests needed to be fixed because the were written with raw strings and parsed in each dialect. tsql doesn't have a real timestamp type.
the macros were resulting in a syntax error, so i cleaned them up and removed the ones with warnings
i also changed sql server to 2019 for linux compatibility
> fix: mssql integration tests

- sqlmesh/core/state_sync/base.py
- sqlmesh/core/state_sync/cache.py
- sqlmesh/core/state_sync/engine_adapter.py
- sqlmesh/schedulers/airflow/state_sync.py
Prior to this change the contract to add an interval was that you must provide a whole snapshot in order to add an interval when really intervals just need snapshot name, identifier, and version. This change provides an endpoint that just requires those minimal fields. Once split out, the functionality of `add_interval` is really just called `inclusive_exclusive` on a snapshot which would likely be universal across all state syncs. Therefore it was converted to not be abstract anymore and call the new `add_inclusive_exclusive_interval` method.
> chore: add interval inclusive/exclusive method

- sqlmesh/dbt/model.py
Make the messages more specific about which field caused the failure.
> Improve error message when the parsing of 'cluster_by' / 'partition_by' fields fails in the dbt loader

- sqlmesh/core/plan/builder.py
- tests/core/test_plan.py
Before this fix when transitioning from a non-materialized kind like `VIEW` to a materialized incremental kind for which the `forward_only` flag is set, SQLMesh would categorized change as `FORWARD_ONLY` and try to reuse the existing physical table which is actually a view which can't be reused.
> Fix: Model kind change should not be categorized as forward-only

- examples/wursthall/models/src/customer_details.py
- examples/wursthall/models/src/order_item_details.py
- sqlmesh/core/dialect.py
- sqlmesh/core/state_sync/engine_adapter.py
- tests/core/test_dialect.py
Fixes #2554
I went with the `any` approach instead of `.. and not args.get("safe")` to ensure we there are no future regressions if we were to add new args to `Cast`.
> Fix: format CAST as :: less aggressively

- sqlmesh/core/model/definition.py
- sqlmesh/core/model/meta.py
- sqlmesh/core/renderer.py
- tests/core/test_model.py
This reverts commit c48754f86e16c9ff3fafd5501a86dd099238ab4a.
the addition of model meta rendering (for dynamicsm) had the side effect
of normalizing audit calls. for snowflake this is problematic because it
makes kwargs uppercase causing a mismatch when trying to call audits.
> Reapply "fix!: dont normalize model meta and lower audit args"

- sqlmesh/core/engine_adapter/snowflake.py
USE SCHEMA fails when a seed is in a different db than the main project.
> Fix: Include catalog if available when calling USE SCHEMA in snowflake

- sqlmesh/core/config/connection.py
- tests/core/test_config.py
- tests/core/test_connection_config.py
This PR adds additional config surface to allow for DuckDB's attach options to be leveraged, similar to duckdb-dbt.
Ref: #2336
cc @eakmanrq
>  Feat: Full support for Duckdb attach options

- web/server/api/endpoints/lineage.py
I noticed, when selecting some columns CLL runs forever
> Fix: Track visited in cll to avoid infinite loop

- docs/concepts/tests.md
- docs/reference/cli.md
- sqlmesh/cli/main.py
- sqlmesh/core/context.py
- sqlmesh/core/test/__init__.py
- sqlmesh/core/test/definition.py
- sqlmesh/core/test/discovery.py
- sqlmesh/integrations/github/cicd/controller.py
- tests/core/test_test.py
- tests/integrations/jupyter/test_magics.py
- web/server/api/endpoints/commands.py
Addresses the 11th item in https://github.com/TobikoData/sqlmesh/issues/1637
> Feat!: add ability to override the engine adapter of a unit test

- sqlmesh/core/snapshot/definition.py
- tests/core/test_snapshot.py
This situation might occur when a child snapshot, which should have been ignored due to start date misalignment, is included in a development plan because it's non-deployable, even though its parents were deployable but haven't been included for the same reasons.
> Fix: Support missing parents when constructing the deployability index

- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/databricks.py
- tests/core/engine_adapter/test_databricks.py
Behavior Change: Prior to this change if using Databricks and doing an `INCREMENTAL_BY_TIME_RANGE` and lets say you were loading `2024-01-01` through `2024-01-10`. If your new data was missing `2024-01-02` then that partition would be untouched in the target table if it already exists. Now `2024-01-02` will be deleted. We don't document anywhere that users should expect this behavior and I don't anticipate this to be an issue.
As Databricks rolls out new products they seem to consistently lack support for dynamic insert overwrite support. Therefore we are going to switch Databricks to now do REPLACE WHERE by default.
In testing REPLACE WHERE behaves like DELETE FROM ... WHERE...; INSERT INTO...;. 
Example:
Table:
| id | ds                 |
|----|------------|
| 1  | 2024-01-01 |
Run …
> fix!: change databricks to replace where

- sqlmesh/core/notification_target.py
- tests/core/test_notification_target.py
This should properly format the plan id in this message:
> fix: monospace `plan_id`

- sqlmesh/core/test/definition.py
- tests/core/test_test.py
Fixes #2542, TL;DR this PR adds a new format for specifying unit test fixture/expected data: SQL. :-)
@erindru I ran your example against Trino and it seemed to work fine. I feel like the flexibility this feature provides will allow users to bypass conversion issues in unit tests pretty easily. Thanks for the idea!
EDIT: will make a followup PR to update the unit test documentation.
> Feat: allow user-supplied queries to generate unit test data

- sqlmesh/dbt/loader.py
Long model names can result in a cache entry name exceeding the limit allowed by the file system.
> Fix: Limit the file name length for the cache entry in the dbt loader

- sqlmesh/dbt/context.py
Previously we were rendering variables with an empty macro registry. This ensures that all loaded macros are available at the time of rendering.
> Fix: Support macros when rendering dbt variables

- sqlmesh/core/snapshot/evaluator.py
https://github.com/TobikoData/sqlmesh/pull/2584 accidentally added pyspark as a dependency. This PR removes the dependency again and refactors the branch that instance-checked the df against `pyspark.sql.dataframe.DataFrame`, so that there's no need to import pyspark in order to reference this type. It's achieved by ensuring `query_or_df`'s type doesn't match any other type in the `QueryOrDF` union, so we can conclude that it's a pyspark dataframe.
> Fix: remove accidental pyspark dependency added in ruff refactor

- sqlmesh/utils/cache.py
Prior to this change we had race conditions where we checked for the state of things on the filesystem and then based on that state took an action assuming that state remained true. https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use
This updates the cache to either remove the check or keep if it required but be ok if the the desired state has already been reached.
> fix: remove write race conditions in cache operations

- docs/guides/isolated_systems.md
- sqlmesh/core/model/definition.py
- tests/core/test_model.py
This should allow you to set session_properties on the project configuration which will then be propagated on the models. If custom properties are also set on the specific model, those will not be overwritten by the default ones. It might need some more work when adding the default props to handle quoted/unquoted identifiers better; right now, it sets them by default as quoted=False.
> #2335 Add support for session properties in model defaults

- sqlmesh/core/context.py
- sqlmesh/core/plan/builder.py
- tests/core/test_plan.py
Previously SQLMesh would fail the plan if the restatement list contained a model which couldn't be restated.
When this behavior is combined with selectors, it results in a subpar experience, as the selector expression may encompass a large set of models, only a small portion of which cannot be restated.
This update changes the behavior so that an error is printed out for models that are part of the restatement list but cannot be restated instead failing the plan. It also completely ignores symbolic and seed models, as restating those is a no-op
> Fix: Ignore non-restateable models and print out a warning instead of failing the plan

- sqlmesh/core/dialect.py
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/schema_diff.py
- sqlmesh/utils/pandas.py
- tests/core/test_schema_diff.py
Prior to this change the schema differ assumed all arrays had a type which isn't true for Snowflake. This adds proper support for "untyped" arrays.
Also did some cleanup where old `self` referenced weren't renamed when methods were changed to classmethods.
> fix: add support for untyped snowflake arrays

- sqlmesh/core/model/definition.py
- tests/core/test_model.py
Expression
```
session_properties (
'warehouse' = 'test_warehouse'
)
```
is being parsed into the `exp.Paren` expression instead of `exp.Tuple` which was not accounted for while merging the model's values with the default ones.
> Fix: Parsing of session properties when only one key-value pair is provided

- docs/concepts/macros/sqlmesh_macros.md
- sqlmesh/core/macros.py
- sqlmesh/dbt/relation.py
- tests/core/test_macros.py
Fixes #2599
Prior to this PR, we would bind macro arguments to the corresponding formal parameters **only** if annotations were present, and the existing logic for that case was brittle and complicated. This PR addresses these points:
- Parameter binding will now always happen, ensuring that macros will get called with the correct arguments
- The binding logic has been offloaded to [`inspect.Signature.bind`](https://docs.python.org/3/library/inspect.html#inspect.Signature.bind), which handles all sorts of edge cases for us that would otherwise be tedious and tricky to implement correctly (see added test cases).
>  Fix: make macro function argument resolution more robust

- docs/reference/configuration.md
- sqlmesh/cli/main.py
- sqlmesh/core/analytics/__init__.py
- sqlmesh/core/analytics/collector.py
- sqlmesh/core/analytics/dispatcher.py
- sqlmesh/core/config/root.py
- sqlmesh/core/config/scheduler.py
- sqlmesh/core/constants.py
- sqlmesh/core/context.py
- sqlmesh/core/plan/evaluator.py
- sqlmesh/core/state_sync/base.py
- sqlmesh/core/state_sync/engine_adapter.py
- sqlmesh/integrations/github/cicd/command.py
- sqlmesh/integrations/github/cicd/config.py
- sqlmesh/integrations/github/cicd/controller.py
- sqlmesh/magics.py
- sqlmesh/schedulers/airflow/client.py
- sqlmesh/schedulers/airflow/dag_generator.py
- sqlmesh/schedulers/airflow/state_sync.py
- sqlmesh/utils/errors.py
- sqlmesh/utils/hashing.py
- sqlmesh/utils/pydantic.py
- tests/__init__.py
- tests/core/analytics/test_collector.py
- tests/core/analytics/test_dispatcher.py
We prioritize our development work based on the needs of SQLMesh users. Some users share their needs via our Slack or Github communities, but many do not. We have added some simple anonymized usage information (telemetry) to SQLMesh to ensure the needs of all users are heard.
All information is anonymized with hash functions, so we could not link data to a specific company, user, or project even if we wanted to (which we don't!). No information is related to credentials or authentication.
We collect anonymized information about SQLMesh project complexity and usage - for example, number of models, count of model kinds, project load time, whether an error occurred during a plan/run (no stacktraces or error message), and names (but not values) of the arguments passed to CLI commands.
The …
> Feat: Enable anonymized analytics for the SQLMesh core

- sqlmesh/core/state_sync/engine_adapter.py
- tests/core/test_state_sync.py
Took two operations that `_get_snapshots` currently does, which are creating an expression to get the snapshots and parse the response into a snapshot, into a method and a function. This was done to make these operations accessible elsewhere without having to call the whole method.
> chore: split up get snapshots operations

- tests/web/test_lineage.py
- web/server/api/endpoints/lineage.py
Queries with constants for columns appear as leaf nodes in CLL but they don't have tables (after qualify), so we should stop the traversal.
> Fix: Do not visit nodes that are not tables during CLL generation

- sqlmesh/core/selector.py
- tests/core/test_selector.py
Prior to this change we would lower the selection and then return that lowered selection and use it to check for matching model fqns. This would result in case-sensitive model names not being correctly picked up.
The selector is overwritten by the returned value since part of getting the values is removing any prefix/postfix that exists. I'm not sure why it was lowered in the first place so just removed it.
> fix: don't lower selection

- examples/sushi/config.py
- examples/sushi/models/order_items.py
- examples/sushi/models/raw_marketing.py
Prior to this change, the `from_` builder would produce a `ParseError` when run against specific engines. The bug was spotted for BigQuery, because we'd pass a backtick-quoted name in the builder, which can't be parsed by the sqlglot base dialect.
> Chore: pass dialect in builders used within sushi python models

- sqlmesh/core/model/definition.py
- tests/core/test_snapshot.py
Without this changes to the `virtual_properties` attribute are not picked up by the `plan` command.
> Fix: Include virtual properties into the metadata hash

- docs/reference/configuration.md
- sqlmesh/core/config/connection.py
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/mysql.py
- tests/core/engine_adapter/test_base.py
- tests/core/engine_adapter/test_mysql.py
- tests/core/test_config.py
For long running plans, a state connection established at the beginning of a plan application might go stale by the end of it.
This update introduces a "pre-ping" mechanism, ensuring that the connection is not stale before initiating a new transaction. The ping implementation itself is dialect-specific but essentially comes down to executing a `SELECT 1` query in all cases except MySQL, which has a first-class API for this purpose.
The new behavior is configurable and is turned off by default for all engines except for those likely to be used to store the SQLMesh state: MySQL, MSSQL, and Postgres. This is also only supported for engines with transaction support.
> Feat: Introduce support for 'pre ping' to detect stale or lost connections

- tests/schedulers/airflow/test_dag_generator.py
This fixes the following warning when collecting tests:
```
PytestCollectionWarning: cannot collect test class 'TestSubmitOperator' because it has a __init__ constructor (from: tests/schedulers/airflow/test_dag_generator.py)
```
> Fix pytest warning on test fixture

- sqlmesh/core/lineage.py
If column description propagation ran into an external model and the project doesn't have a schema yaml file, an exception would be raised since a model would be expected but not found.
> Fix: Stop column description propagation if model cannot be found.

- docs/guides/tablediff.md
- docs/reference/cli.md
- sqlmesh/cli/main.py
- sqlmesh/core/console.py
- sqlmesh/core/context.py
- sqlmesh/core/table_diff.py
- sqlmesh/magics.py
- tests/core/test_table_diff.py
- tests/integrations/jupyter/test_magics.py
The following improvements have been introduced:
- Split `COMMON`, which represented the number of joined rows ,into `FULL MATCH` and `PARTIAL MATCH` to show the number of rows that are identical vs the number of rows with only  a partial match accordingly.
- Add percentage values for `FULL MATCHES` and `PARTIAL MATCHES`.
- Only display the number of rows if it's not 0.
- Add ability to set the number of decimal places to use when comparing floating point columns. This is set to 3 by default.
> Feat: Improve the CLI output of the table diff command

- tests/core/engine_adapter/test_integration.py
Remote engine connection configs may be stored in the local `.sqlmesh` directory. We get a key error for the gateway If that is the case and those configs aren't included in the context.
> Chore: include local sqlmesh configs in integration test context

- sqlmesh/core/test/result.py
Since the introduction of the custom method `addSuccess` for `ModelTextTestResult` in d8ff3fd4c8946ab756609fc38c6d43552aea103e, the test runner stopped displaying dots for successful test cases.
This is due to the logging being part of the base implementation itself:
self.stream.write('.')
self.stream.flush()
This patch adds a call the superclass implementation of `addSucess` to achieve the original behavior of reporting successes.
---
I actually wanted to add a test case for this change to ensure the behavior is maintained, but I couldn't find a reference point for tests that check the CLI output of `sqlmesh test`.  I can do so with some guidance. Thanks.
> fix: Fix test runner not displaying dots for successes (#2656)

- docs/concepts/tests.md
- sqlmesh/core/test/definition.py
- tests/core/test_test.py
This adds documentation for the support of file loading of inputs and extends the functionality of CSV loading with settings, as per @georgesittas suggestion!
> Feat: extend CSV support with settings; update test docs

- setup.py
- sqlmesh/core/config/connection.py
- sqlmesh/core/context.py
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/mysql.py
Prior to this change we had connection validation defined in two places. This brings them together. It also provides a way to do connection validation at the configuration level.
> chore: use ping to validate connections

- docs/concepts/tests.md
- sqlmesh/core/test/definition.py
- tests/core/test_test.py
This PR enables the following pattern:
```
sqlmesh_example.incremental_model:
query: |
SELECT 1 AS id, 1 AS item_id
UNION ALL
SELECT 2 AS id, 1 AS item_id
UNION ALL
SELECT 3 AS id, 2 AS item_id
```
Here, even though the query doesn't return `event_date` (a column in `incremental_model`), we don't mind and simply add it ourselves as `NULL`. This is consistent with how we treat missing columns in the YAML / CSV variants. Without this behavior, the `create_view` adapter call would fail at the engine level because the schema provided in the `CREATE VIEW` DDL doesn't match the top-level projections.
There are probably some rough edges related to normalization etc, but I think it's ok to deal with them later, if needed.
> Fix: allow partial query results in unit tests, update docs

- sqlmesh/core/dialect.py
- tests/core/test_model.py
> Fix: use exp.column when casting seed columns to avoid ParseError

- sqlmesh/core/model/kind.py
This update enables `start_*` / `end_*` macros in SCD 2 models.
When `invalidate_hard_deletes` is set to `false` and a user is confident that new records upstream are all within the `start_*` / `end_*` boundary, these macros can be used to significantly reduce the number of records scanned without negatively impacting the semantics of SCD2.
> Chore: Allow usage of start_* / end_* macros in SCD2 models

- sqlmesh/core/context_diff.py
- sqlmesh/core/model/definition.py
- sqlmesh/core/model/meta.py
- sqlmesh/core/scheduler.py
- sqlmesh/core/selector.py
- sqlmesh/core/snapshot/evaluator.py
- sqlmesh/core/state_sync/base.py
- sqlmesh/core/state_sync/cache.py
- sqlmesh/core/state_sync/common.py
- sqlmesh/core/state_sync/engine_adapter.py
- sqlmesh/migrations/v0050_drop_seeds_table.py
- sqlmesh/schedulers/airflow/api.py
- sqlmesh/schedulers/airflow/client.py
- sqlmesh/schedulers/airflow/operators/targets.py
- sqlmesh/schedulers/airflow/state_sync.py
- tests/core/test_integration.py
- tests/core/test_model.py
- tests/core/test_snapshot_evaluator.py
- tests/core/test_state_sync.py
- tests/integrations/github/cicd/test_integration.py
- tests/schedulers/airflow/operators/test_targets.py
Closes #2668
We only really need to store the seed's content in order for the diffing to work at plan time. It appears that this convenience feature cannot justify the storage and compute overhead it incurs, especially for larger seed files.
This update ensures that we no longer rely on the seed's content stored in the state.
> Chore: Don't store the seed's content in the state

- sqlmesh/core/model/seed.py
- tests/core/test_model.py
> Fix: unescape tabs and backslashes in CSV settings

- sqlmesh/core/engine_adapter/duckdb.py
SQLMesh determines which objects exist in an engine by querying its metadata.
In most engines, the metadata tables are scoped to the current database/catalog. For example, the metadata view `information_schema.tables` will only contain entries for the catalog returned by `SELECT CURRENT_CATALOG()`.
Unlike DuckDB, In Motherduck `information_schema.tables` is NOT scoped and returns objects for all databases/catalogs. If the same project has run in multiple catalogs, a table name collision can occur.
This PR adds the catalog name to the DuckDB _get_data_objects `WHERE` clause. This properly scopes the query for Motherduck and is a no-op for DuckDB.
> Fix(motherduck): filter on catalog name in DuckDB _get_data_objects query

- setup.py
- tests/core/test_dialect.py
May do another iteration make the property spacing consistent, i.e. don't generate `k = v` for some of them and `k=v` for others. This should be easy to fix as part of a patch, so I didn't want to prioritize it now.
> Chore!: bump sqlglot to v24.1.0

- sqlmesh/core/engine_adapter/base.py
- tests/core/engine_adapter/test_base.py
- tests/core/engine_adapter/test_mixins.py
For example, MSSQL requires 3 arguments to the CONCAT_WS function: https://learn.microsoft.com/en-us/sql/t-sql/functions/concat-ws-transact-sql?view=sql-server-ver15
> Fix: Avoid using concat_ws when there's only one key is present

- sqlmesh/core/audit/builtin.py
- tests/core/test_audit.py
- tests/core/test_snapshot_evaluator.py
The `@WHERE(@condition)` clauses weren't being rendered when eg. `condition` was `item_id IS NULL`, because the macro evaluator evaluated the condition as `exp.to_column('item_id') is None` which is false.
> Fix: render audit condition when used in a @WHERE(@condition) clause

- sqlmesh/core/dialect.py
- tests/core/test_macros.py
We were previously parsing the table here `COPY INTO @'....' ....` as a staged file path because of the preceding `@`. We want this to be treated as a string template and be rendered accordingly, so it was problematic.
Thankfully, Snowflake's spec shows that staged files can either be like `@var....` or `'@....'`, so `@'...'` can also be unambiguously treated as SQLMesh's syntax.
Reference: https://docs.snowflake.com/en/user-guide/querying-stage
> Fix: yet another edge case related to snowflake staged file syntax

- examples/ibis/models/ibis_full_model_python.py
- examples/ibis/models/ibis_full_model_sql.py
Came across a couple of warnings / errors when trying to run `sqlmesh plan` for the ibis example. I took a quick look and it seems like there was a breaking change in ibis (see [here](https://github.com/ibis-project/ibis/blob/03811a324f19d71863c873696dedc2b15f242aa4/ibis/expr/operations/relations.py#L363)). We also didn't update the example since refactoring how kinds are set for python models.
> Chore: update ibis example

- sqlmesh/dbt/builtin.py
This enables ability to override the `var` macro in individual projects.
> Fix: Add the dbt "var" macro to the "builtins" package

- sqlmesh/dbt/manifest.py
- tests/dbt/test_manifest.py
We need this in order to capture references to user-provided `ref`, `source`, `var` macros that override the builtin ones.
In older versions of dbt references to these macros are not reflected in the manifest.
> Fix: Capture bultin macro dependencies when loading dbt projects

- sqlmesh/core/plan/builder.py
- tests/core/test_plan.py
Otherwise, we risk generating too much noise due to false positive checks for indirectly modified models whose parents have been destructively changed.
With this change, we decide to act optimistically at plan time due to the absence of complete information, and let this check fail at runtime if necessary.
> Fix: Only check destructive changes for directly modified models at plan time

- sqlmesh/core/test/definition.py
- tests/core/test_test.py
- tests/integrations/jupyter/test_magics.py
Some `pd.DataFrame` methods such as `apply` are not supported by pyspark / snowpark dataframes, which caused issues in unit tests because we assumed we'd get back pandas dataframes from the python models, and that's not always the case.
This PR fixes the issue by converting pyspark / snowpark dataframes into pandas ones for unit tests, so that there's a single representation to work with => keep the implementation simpler.
> Fix: convert pyspark/snowpark dataframes into pandas when testing

- .circleci/continue_config.yml
Lots of timeouts recently when running engine adapter tests. This should fix it.
> Chore: increase timeout limit for engine adapter tests

- sqlmesh/core/plan/builder.py
- tests/core/test_integration.py
- tests/core/test_plan.py
Before this update SQLMesh would compute a preview for metadata-only changes in dev because those are categorized as forward-only.
With this fix we ensure that previews are only computed for directly / indirectly modified snapshots.
> Fix: Skip preview for metadata-only changes

- sqlmesh/integrations/github/cicd/controller.py
- tests/integrations/github/cicd/test_github_commands.py
- tests/integrations/github/cicd/test_github_controller.py
- tests/integrations/github/cicd/test_integration.py
Old format:
New format:
The bullet about issuing a `deploy` command will only show up if the project has the deploy command configured.
> Feat: improve cicd comment message format

- sqlmesh/core/plan/builder.py
- sqlmesh/core/snapshot/definition.py
- sqlmesh/core/snapshot/evaluator.py
- tests/core/test_integration.py
- tests/core/test_plan.py
Coupling metadata and forward-only changes was a design mistake.
The forward-only category has a bunch of implications on how data is computed and reused. For example, table deployability, data previews, etc decisions are directly linked to this category.
However, none of these features apply to metadata changes. I've already seen quite a few unexpected behaviors related to the fact that metadata updates were categorized as forward-only which led to redundant computations in both dev and prod. 
This update introduces a new category dedicated specifically to metadata-only changes.
> Fix: Add a category for metadata-only changes

- sqlmesh/core/snapshot/definition.py
- tests/core/test_snapshot.py
Before this change, SQLMesh would incorrectly classify a snapshot of a forward-only model as non-deployable, even though the change category assigned to that snapshot was `METADATA`.
> Fix: Deployability index calculation for forward-only models that have been already categorized

- sqlmesh/core/model/__init__.py
- sqlmesh/core/plan/builder.py
- tests/core/test_plan.py
External models are not technically managed by SQLMesh, and so if the reference is removed from the `schema.yaml` file we shouldn't fail the plan.
> Fix: The broken reference check shouldn't check removed external models

- sqlmesh/core/plan/builder.py
- tests/core/test_plan.py
When a dev plan contains only new models without any modifications to existing ones, the plan's start should be computed normally rather than being set to 1 day ago, even if the preview is enabled.
> Fix: Start date for dev plans with enabled previews in which a new forward-only model has been added

- sqlmesh/core/engine_adapter/base.py
- tests/core/engine_adapter/test_base.py
- tests/core/engine_adapter/test_spark.py
Prior to this change we a did a left/right join with a union as a replacement of doing a full outer since that isn't supported by MySQL. The issue is that this assumes all the columns are hashable to be able to run a distinct on it which may not be the case for things like arrays.
I believe a logically equivalent approach is to do a left/right and filter the right to only include what is unique to the right. So conceptually it does this:  Keep unique to left and all matches UNION just what is unique to right.
> feat: remove distinct and use filter on right join

- sqlmesh/core/model/definition.py
- tests/core/test_model.py
Context:
- https://tobiko-data.slack.com/archives/C044BRE5W4S/p1718294204075889
- https://stackoverflow.com/questions/41444396/psycopg2-acceptable-date-datetime-values
Was able to reproduce the issue for a postgres connection: `invalid input syntax for type timestamp: "NaT"`. I also verified that `sqlmesh plan` succeeds with this fix.
> Fix: convert NaN/NaT (np.nan) values to None

- sqlmesh/core/console.py
Missed this one in https://github.com/TobikoData/sqlmesh/commit/a2b4d9db9cf842dfcb9cf7aeb2a6e28182c2ca10.
> Fix: pass dialect to debug terminal console

- sqlmesh/core/snapshot/evaluator.py
- tests/core/test_snapshot_evaluator.py
When cloning a table for forward-only snapshots we first create a temporary table which serves as a source for the updated schema. 
As part of this step we also run the CTAS query from this snapshot as a dry run to validate it. 
The issue arises when the model query is self-referencing in which case we don't resolve the table mapping for it correctly, referencing a physical table which doesn't exist yet.
> Fix: Dry run for self-referencing model queries when creating a temp table during cloning

- sqlmesh/dbt/adapter.py
- tests/dbt/test_adapter.py
The redshift dbt adapter depends on the postgres adapter. For adapter dispatch, this means that postgres dispatch macros are valid when a corresponding redshift macro does not exist.
Note: The databricks adapter also depends on the spark adapter, so this fix applies there too.
> Fix: redshift leverages postgres adapter dispatch implementations for common functionality

- docs/concepts/models/external_models.md
- examples/sushi/config.py
- examples/sushi/external_models/prod.yaml
- sqlmesh/core/context.py
- sqlmesh/core/loader.py
- sqlmesh/core/model/definition.py
- sqlmesh/core/schema_loader.py
- sqlmesh/dbt/loader.py
- tests/core/test_context.py
- tests/core/test_schema_loader.py
Add an optional `gateway: ` key to the external models definitions which allows gateway-specific external models and addresses the problems highlighted in issue #2689 
After this change, the behaviour is as follows:
`sqlmesh create_external_models` - no change, current behaviour. Models get written without the new `gateway: ` key.
`sqlmesh --gateway dev create_external_models` - Models get written with `gateway: dev`
`sqlmesh --gateway prod create_external_models` - Models get written with `gateway: prod`. The `gateway: dev` models remain in the file.
When running plans:
`sqlmesh plan` - will pick up all external models with no `gateway: ` set, plus any external models with `gateway: <default gateway>`
`sqlmesh --gateway dev plan` - will pick up all external models with no `gateway: ` …
> Feat: Gateway-specific external models

- sqlmesh/cli/example_project.py
Setting the default start date in the config at project generation time. Otherwise the model start will be a relative value set to "1 day ago".
> Fix: Set the default model start when initializing a new project

- sqlmesh/core/engine_adapter/base.py
- tests/core/engine_adapter/test_base.py
- tests/core/engine_adapter/test_bigquery.py
- tests/core/engine_adapter/test_databricks.py
- tests/core/engine_adapter/test_mixins.py
- tests/core/engine_adapter/test_mysql.py
- tests/core/engine_adapter/test_snowflake.py
- tests/core/engine_adapter/test_spark.py
- tests/core/engine_adapter/test_trino.py
When user explicitly specifies the columns-to-types mapping in the `columns` attribute, SQLMesh respects it when creating the snapshot table for the first time.
However, for `FULL` models SQLMesh uses the `replace_query` API during model evaluation, which recreates the target table from scratch using the model's query.  If the upstream types are different from the ones specified in the `columns` attribute, the recreated table might end up having a different set of types than it had at creation time. 
The impact is not limited to just `FULL` models though. SQLMesh relies on the `replace_query` API when restating models that only support full history restatements (eg. `INCREMETNAL_BY_UNIQUE_KEY`, etc. models). Because of this, the column types may change unexpectedly for models of almost …
> Fix: Respect columns-to-types mapping provided by a user when replacing a table

- sqlmesh/core/console.py
This is an improvement to trim long indirectly modified trees in the output, fixes: #1992 
```
Summary of differences against `dev2`:
Models:
├── Directly Modified:
│   └── sushi__dev2.seed_model
└── Indirectly Modified:
├── sushi__dev2.full_model
├── ... 30 more ...
└── sushi__dev2.incremental_model
```
With this update, the names of indirectly modified models will be omitted once their total number exceeds a certain threshold, currently set to 20. This behavior can be overridden with the `verbose` flag, in which case all model names will be shown regardless of their total number.
> Feat: Limit long lists of indirectly modified models in CLI output

- sqlmesh/core/snapshot/definition.py
Minor fixup: if we didn't specify an environment name, the default schema wouldn't be normalized.
> Fix: normalize default schema name when targeting prod too

- sqlmesh/core/engine_adapter/base.py
- tests/core/test_context.py
- tests/dbt/test_integration.py
> Refactor!: error when trying to construct source queries from empty DFs

- sqlmesh/core/engine_adapter/bigquery.py
- sqlmesh/core/engine_adapter/databricks.py
- sqlmesh/core/engine_adapter/duckdb.py
- sqlmesh/core/engine_adapter/mssql.py
- sqlmesh/core/engine_adapter/mysql.py
- sqlmesh/core/engine_adapter/postgres.py
- sqlmesh/core/engine_adapter/redshift.py
- sqlmesh/core/engine_adapter/snowflake.py
- sqlmesh/core/engine_adapter/spark.py
- sqlmesh/core/engine_adapter/trino.py
- sqlmesh/core/schema_diff.py
- tests/core/test_schema_diff.py
Some data types can include user-specified precision parameters, such as decimal precision `DECIMAL(10,1)` or character length `VARCHAR(100)`. 
Currently, the SchemaDiffer outputs a DROP/ADD for all  precision changes, even though precision increases can be done with an ALTER. This PR makes the SchemaDiffer aware of precision such that it outputs ALTER statements when precision is increased.
Precision is implemented differently across engines and types:
- Some types have one parameter `VARCHAR(1)`, and others have two `DECIMAL(10,1)`.
- Sometimes a parameter is optional and has a default value (e.g., `VARCHAR` = `VARCHAR(256)`, `DECIMAL(10)` = `DECIMAL(10,0)`). The SchemaDiffer will automatically provide these default values where possible.
- Some engines/types allow explicitly making a …
> Feat: make SchemaDiffer precision aware

- sqlmesh/core/console.py
- Adjust `INDIRECTLY_MODIFIED_DISPLAY_THRESHOLD` to 10.
- Limit the output for backfill, as well as added and removed models.
> Fix: truncate backfill models and adjust threshold

- sqlmesh/core/context.py
- tests/core/test_context.py
Before this fix, the `get_model` method won't find a model if the model's dialect is set to eg. `snowflake` while the default dialect is something like `duckdb`.
> Fix: Check all dialects used in a project when retrieving a model by its name

- sqlmesh/utils/pydantic.py
- tests/core/test_context.py
pydantic models with nested sets of other pydantic models cannot be called with .dict(). we call dict() on equality checks in order to recursively check equality. this is trigger on stringify because we check that each field is not equal to the default value. this commit bypasses that check so we don't trigger the dict() calls.
related github issue https://github.com/pydantic/pydantic/issues/8016
> fix: issue with stringify pydantic models with sets

- sqlmesh/core/table_diff.py
Fixes #2821
Didn't add any tests for this because it's a relatively small change and it matches what we do [elsewhere](https://github.com/TobikoData/sqlmesh/blob/9087309155b1eae7641dc9359a35b4632fb143ec/sqlmesh/core/engine_adapter/base.py#L1350-L1351) in the codebase:
```python
>>> from sqlglot import exp
>>>
>>> exp.column("c").not_().is_(exp.Null()).sql()
'NOT c IS NULL'
>>> exp.column("c").not_().is_(exp.Null()).sql("tsql")
'NOT c <> 0 IS NULL'
>>>
>>> exp.column("c").is_(exp.Null()).not_().sql()
'NOT c IS NULL'
>>> exp.column("c").is_(exp.Null()).not_().sql("tsql")
'NOT c IS NULL'
```
> Fix: build table diff sqlglot expressions properly

- sqlmesh/core/context.py
- sqlmesh/core/context_diff.py
- tests/core/test_integration.py
- tests/core/test_plan.py
Before this change the `sqlmesh plan` command with the `--restate-model` argument(s) would fail if the state of the target environment is different from the local state.
This is really annoying to users since it essentially requires their local code repo to always be in sync with the target environment which may sometimes be outside of their control. This can happen when, for example, prod hasn't caught up with the main branch yet.
This update ensures that the local changes are ignored instead if a plan contains restatements.
> Fix: Ignore local changes when restating

- sqlmesh/core/snapshot/evaluator.py
- tests/core/test_snapshot_evaluator.py
This is a necessary cleanup step to make sure that next time the plan runs SQLMesh attempts to create and migrate the table again.
Fixes #2782
> Fix: Drop the dev table clone if the schema migration fails

- setup.py
Bumping to get a few of the latest patches in, see https://github.com/tobymao/sqlglot/commits/main/
> Chore: bump sqlglot to v25.3.3

- docs/integrations/engines/databricks.md
Users may need to set this property when using Databricks for certain changes and prior to this PR this wasn't documented.
Related to: https://github.com/TobikoData/sqlmesh/issues/2782
> chore: add databricks column mapping to docs

- sqlmesh/dbt/adapter.py
- tests/dbt/test_adapter.py
Reverts TobikoData/sqlmesh#2770
> Revert "Fix: redshift leverages postgres adapter dispatch implementations for common functionality"

- docs/guides/custom_materializations.md
- sqlmesh/core/snapshot/evaluator.py
Otherwise arguments that are specific to the creation process can accidentally make its way into the renderer and lead to unexpected results. This update ensures a clear separation between what's passed into the `create` method vs what has to be passed into the rendering method.
> Chore: Separate render kwargs from general kwargs in the creation API of the evaluation strategy

- sqlmesh/dbt/adapter.py
- sqlmesh/dbt/builtin.py
- tests/dbt/test_adapter.py
- tests/fixtures/dbt/sushi_test/packages/customers/macros/current_engine.sql
- tests/fixtures/dbt/sushi_test/packages/customers/models/customer_revenue_by_day.sql
When the package name is not specified the root package must be searched and not just the `dbt*` ones.
> Fix: Improve the dbt adapter dispatch resolution when the package name is not specified

- sqlmesh/core/constants.py
- sqlmesh/core/macros.py
- sqlmesh/core/model/definition.py
- sqlmesh/utils/metaprogramming.py
- tests/core/test_macros.py
- tests/core/test_model.py
- tests/schedulers/airflow/test_client.py
- tests/utils/test_metaprogramming.py
This PR allows flagging macro functions in a SQL model's pre and post hooks to be included in the model's metadata hash instead of its data hash.
> Feat: Introduce metadata only flag for macro functions

- sqlmesh/core/loader.py
- tests/core/test_schema_loader.py
Currently, the external model loading code expects that, if you want to load models relating to a specific gateway, you supply the `--gateway` flag when invoking the SQLMesh CLI.
However, some users override the default gateway in the config instead via setting the `SQLMESH__DEFAULT_GATEWAY` environment variable.
This change uses the config setting as a fallback when loading external models if the `--gateway` option is not supplied
> Fix: take the default_gateway into account when loading external models

- sqlmesh/dbt/manifest.py
Fixes the following exception:
```
...
File "/Users/sung/Desktop/git_repos/jaffle_shop_duckdb/venv/lib/python3.10/site-packages/sqlmesh/dbt/manifest.py", line 295, in _load_profile
return Profile.from_raw_profiles(
File "/Users/sung/Desktop/git_repos/jaffle_shop_duckdb/venv/lib/python3.10/site-packages/dbt/config/profile.py", line 369, in from_raw_profiles
return cls.from_raw_profile_info(
File "/Users/sung/Desktop/git_repos/jaffle_shop_duckdb/venv/lib/python3.10/site-packages/dbt/config/profile.py", line 315, in from_raw_profile_info
target_name, profile_data = cls.render_profile(
File "/Users/sung/Desktop/git_repos/jaffle_shop_duckdb/venv/lib/python3.10/site-packages/dbt/config/profile.py", line 284, in render_profile
profile_data = renderer.render_data(raw_profile_data)
File …
```
> Fix: Set the dbt invocation context before loading the profile

- docs/concepts/models/managed_models.md
- docs/concepts/models/model_kinds.md
- mkdocs.yml
- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/bigquery.py
- sqlmesh/core/engine_adapter/mixins.py
- sqlmesh/core/engine_adapter/redshift.py
- sqlmesh/core/engine_adapter/shared.py
- sqlmesh/core/engine_adapter/snowflake.py
- sqlmesh/core/engine_adapter/spark.py
- sqlmesh/core/model/definition.py
- sqlmesh/core/model/kind.py
- sqlmesh/core/snapshot/evaluator.py
- sqlmesh/utils/errors.py
- tests/core/engine_adapter/test_integration.py
- tests/core/engine_adapter/test_snowflake.py
- tests/core/test_model.py
- tests/core/test_snapshot_evaluator.py
Initial implementation of Managed models. This defines the general semantics and contains an implementation for Snowflake, based on Dynamic Tables.
As a side effect, this PR also fixes [issue 1049](https://github.com/TobikoData/sqlmesh/issues/1049).
Follow-up PR's:
- Support for other engines
- Cleanup / compaction support, essentially the ability for something like `sqlmesh clean` to drop any objects that aren't referenced in a specific environment. The assumption up until now is that storage is cheap so keeping old snapshots around for a while isn't a problem. However, costs could add up quickly with managed models because users would be paying for models to be refreshed that aren't actually being referenced
> Feat: Managed models

- sqlmesh/core/engine_adapter/bigquery.py
```
CREATE TABLE iaroslav.bignumeric_testing (cola BIGNUMERIC);
ALTER TABLE iaroslav.bignumeric_testing ALTER COLUMN cola SET DATA TYPE FLOAT64;
```
Results in:
```
Provided Schema does not match Table <project id>:iaroslav.bignumeric_testing. Field cola has changed type from BIGNUMERIC to FLOAT
> Fix: BIGNUMERIC column can't be altered into FLOAT64 in BigQuery

- sqlmesh/dbt/adapter.py
- tests/dbt/conftest.py
- tests/dbt/test_adapter.py
The keys in the mapping have been serialized using the default dialect so the same dialect should be used for lookup.
> Fix: Use the default dialect when constructing a table mapping key in the dbt adapter

- docs/reference/cli.md
- docs/reference/notebook.md
- sqlmesh/cli/main.py
- sqlmesh/core/console.py
- sqlmesh/core/context.py
- sqlmesh/core/state_sync/base.py
- sqlmesh/core/state_sync/cache.py
- sqlmesh/core/state_sync/engine_adapter.py
- sqlmesh/magics.py
- sqlmesh/schedulers/airflow/state_sync.py
- tests/core/test_state_sync.py
- tests/integrations/jupyter/test_magics.py
This exposes the janitor task to the CLI so that users may run it on-demand and not as part of `sqlmesh run`.
To trigger the janitor, just run `sqlmesh janitor` and it calls the janitor task in the exact same way that `sqlmesh run` would have.
The main benefit is being able to decouple the janitor process and the missing intervals process so they dont interfere with each other.
I've noticed that they can interfere with each other when there are many large tables to drop, particularly on systems like Trino / Iceberg where a `DROP TABLE` statement blocks until all the files have been removed from S3. This causes the main run to be blocked until the janitor is complete, which is undesirable when you want it to refresh data ASAP.
I also added an option `--ignore-ttl` to ignore the snapshot …
> Feat: Allow the janitor to be run on-demand

- sqlmesh/core/engine_adapter/mixins.py
- sqlmesh/core/engine_adapter/postgres.py
- sqlmesh/core/schema_diff.py
- tests/core/engine_adapter/test_mssql.py
- tests/core/engine_adapter/test_redshift.py
Redshift and MSSQL use the `VarcharSizeWorkaroundMixin` to infer the size of a varchar or other "max" column when it cannot be resolved from model code.
Data may be truncated if it is inferred to the default length (256 in Redshift, 1 in MSSQL) and that was not intended by the user, so this PR increases the length to "max" if a column with the default length is detected.
> Feat: increase default type precision in redshift/mssql view workaround

- sqlmesh/dbt/adapter.py
This method is specific to the Databricks dbt adapter implementation. We need it as well for compatibility with the Databricks dbt projects.
> Fix: Support the compare_dbr_version in the dbt adapter

- docs/integrations/engines/trino.md
Tested by a community member (also seems like it should work according to PRs): https://tobiko-data.slack.com/archives/C044BRE5W4S/p1719997095635039
> chore: update docs support rest catalog

- sqlmesh/core/dialect.py
- tests/core/test_dialect.py
Fixes #2684
Gave it a whirl. Not sure if this is too intrusive to fix the linked issue - happy to discuss and refactor if needed.
cc @z3z1ma
> Fix: cast NULLs in VALUES clause (df->values) to avoid coercion issues

- docs/guides/tablediff.md
- docs/reference/cli.md
- docs/reference/notebook.md
- sqlmesh/cli/main.py
- sqlmesh/core/console.py
- sqlmesh/core/context.py
- sqlmesh/core/table_diff.py
- sqlmesh/magics.py
- tests/core/test_table_diff.py
This adds a check for the uniqueness of the primary key (grain) or whether it contains null values and accordingly shows a warning to the user, fixes: #2810 
By default, this behavior is turned off due to the overhead of the additional query, but it can be enabled with the `check_grain` flag.
```
sqlmesh table_diff prod:dev sqlmesh_example.full_model --show-sample --check-grain
Grain should have unique and not-null audits for accurate results.
Row Counts:
└──  FULL MATCH: 3 rows (100.0%)
COMMON ROWS column comparison stats:
pct_match
num_orders      100.0
COMMON ROWS sample data differences:
All joined rows match
```
> Fix: Check for null or duplicate primary keys when running table_diff

- sqlmesh/core/renderer.py
- sqlmesh/migrations/v0054_fix_trailing_comments.py
- tests/core/test_model.py
Before this fix, the renderer would return a `Semicolon` expression, resulting in an empty SQL string and subsequent failure when evaluating in the engine adapter.
> Fix!: Support for trailing comments in SQL model definitions

- sqlmesh/core/context.py
- sqlmesh/core/table_diff.py
- tests/core/test_table_diff.py
This addresses an issue encountered when running table diff, fixes: #2869 
The proposed fix is to use the project dialect for normalization instead of the gateway dialect and also account for quoted names. `test_table_diff` has been adapted to test for both quoted and unquoted identifiers in snowflake.
> Fix: normalization issue in table diff

- sqlmesh/core/snapshot/definition.py
- tests/core/test_context.py
- tests/core/test_model.py
- tests/dbt/test_adapter.py
This addresses an issue with external models not found in Python models using Context.table(...), by relaxing the condition of the `to_table_mapping` function to include external models when detecting table names.
> Fix: include external models in mapping of context.table

- examples/sushi/models/disabled.py
- sqlmesh/core/loader.py
- tests/core/test_context.py
- tests/core/test_model.py
This fix ensures that models are not loaded when the 'enabled' flag in a Python model is false, mirroring the behaviour of sql models.
> Fix: control python model loading with enabled flag

- sqlmesh/dbt/util.py
- tests/dbt/test_util.py
The previous method was coercing string values into more specific types which was messing up dynamic queries in dbt models for some users.
> Fix: Avoid type coercion when converting pandas dataframes to agate tables in the dbt adapter

- docs/reference/cli.md
- docs/reference/overview.md
- sqlmesh/cli/main.py
- sqlmesh/core/context.py
- sqlmesh/core/dialect.py
- sqlmesh/magics.py
- tests/core/test_audit.py
- tests/core/test_format.py
This feature enhances the `sqlmesh format` functionality to include audits and format them as well, in a style consistent with models, fixes: #2889
> Feat: add support for audit formatting in sqlmesh format

- docs/reference/cli.md
- docs/reference/notebook.md
- sqlmesh/cli/main.py
- sqlmesh/core/context.py
- sqlmesh/core/table_diff.py
- sqlmesh/magics.py
- tests/core/test_table_diff.py
Sometimes we can't compare certain columns using the equality (`=`) operator. For example, in BigQuery we can't compare arrays, i.e. `SELECT [1, 2, 3] = [1, 2, 3]` is invalid. Such SQL is generated [here](https://github.com/TobikoData/sqlmesh/blob/main/sqlmesh/core/table_diff.py#L243), resulting in a crash when the query is executed.
This PR adds a flag that can be used to skip certain columns from being matched, so users can selectively discard array columns from the table diffing process.
> Feat: support skipping columns from being matched in table diff

- sqlmesh/core/snapshot/evaluator.py
- tests/core/test_integration.py
- tests/core/test_snapshot_evaluator.py
This fix ensures that the snapshot view doesn't get recreated unnecessarily when concurrent plans evaluate the same snapshot.
Even though the recreation of a view is not a significant issue for most engines, it leads to negative consequences in Postgres due to the lack of support for late schema binding. As a result, the only way to replace a view in Postgres is through the `DROP CASCADE` statement, which drops all dependent views downstream. When the same view snapshot is evaluated concurrently in different plans, the environment views can be unintentionally dropped (and not recreated).
> Fix: Make sure that views are not recreated unnecessarily in the face of concurrent plan application

- sqlmesh/core/selector.py
- tests/core/test_selector.py
Prior to this change the git branch selector didn't support upstream/downstream selection (using `+`) so this PR adds that functionality. This is part of work to allow the Github Action CI/CD bot to be able to compare against git main instead of prod. Slack context for that change: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1720792390212429
> feat: support upstream/downstream git selector

- sqlmesh/cli/main.py
- sqlmesh/core/context.py
- sqlmesh/core/schema_loader.py
- sqlmesh/magics.py
- tests/core/test_schema_loader.py
The strict mode ensures that the process fails if a referenced external table is missing in the target database.
Before this update, SQLMesh would emit a warning but ignore the missing table otherwise.
> Feat: Support the strict mode when creating external models

- tests/web/test_lineage.py
- web/server/api/endpoints/lineage.py
When the UI requests a column's lineage, if the column contains unsafe characters, the request fails because the column is not quoted. For example, the column `@foo` would be parsed as a MacroVar in this model query:`SELECT col AS "@foo" FROM my_table`. This PR quotes the specified column when generating the lineage so that it's properly parsed into an identifier.
> Fix: Quote columns when getting column level lineage

- sqlmesh/core/engine_adapter/snowflake.py
- tests/core/engine_adapter/test_snowflake.py
In snowflake, when creating managed models, the `warehouse` property was missed from the list of physical properties to exclude when creating dev preview tables.
This change adds it to the list.
Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1721168591596139
> Fix!: Ignore the warehouse property on non-dynamic tables

- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/snowflake.py
- sqlmesh/core/engine_adapter/spark.py
- tests/conftest.py
- tests/core/engine_adapter/test_integration.py
- tests/core/engine_adapter/test_snowflake.py
This fixes the Snowflake adapter so that the integration tests pass again (and `sushi` example compatibility is restored).
The main issue was the catalog from the Snowflake gateway config not being respected. This change modifies every query `Expression` before it gets converted to SQL to replace the default catalog references (which are almost always wrong in a multi-dialect project because they contain the catalog normalized against the source dialect, not Snowflake) with whatever the user supplied in the Gateway config.
There are also some other issues around how the `write_pandas()` function from the Snowflake python lib handles things as well as recent changes to normalizing environment names that broke the `SushiDataValidator` in the `test_sushi` integration test.
Note that the …
> Fix!: Snowflake adapter

- docs/integrations/engines/snowflake.md
- sqlmesh/core/config/connection.py
- tests/core/test_connection_config.py
This PR is to implement the features in this issue:
https://github.com/TobikoData/sqlmesh/issues/2829
Looking at the code it didn't seem like much was missing.
Tried it with this in my config:
session_parameters:
timezone: UTC
query_tag: state_test_tag
Not sure how to test it, but I checked in my query history that the queries are getting tagged.
From what I understand of the code this should get passed straight through to the connector.
https://docs.snowflake.com/en/developer-guide/python-connector/python-connector-connect
This would add support for all session parameters supported by Snowflake.
https://docs.snowflake.com/en/sql-reference/parameters
I see here it passes everything defined in the connection kwarg keys.
https://github.com/TobikoData/sqlmesh/blob/7c1ed838295a898da759e59379cd …
> Feat: pass session parameters for Snowflake

- sqlmesh/core/test/definition.py
- tests/core/test_test.py
This fixes a bug in #2898 where:
- Not all built-in time macro variables were included in `TIME_KWARG_KEYS`
- All variables in `TIME_KWARG_KEYS` that were NOT overridden by the user were set to a value of `None`
It also fixes a bug in the `partial` setting that allows omitting columns from the test output rows. The current implementation skips subsetting the output DF if there are no ROWS in the intersected input/ouput DFs. This PR corrects it to skip subsetting if there are no COLUMNS in the intersected DFs.
Closes #2914
> Fix: allow overriding built-in datetime vars in tests

- sqlmesh/dbt/seed.py
- tests/dbt/test_transformation.py
Previously, we assumed that the input value provided for casting always had the type string. This assumption turned out to be incorrect because the same set of type testers is used by the dbt implementation to convert arbitrary values to agate tables, not just csv.
> Fix: Coercion of string to integers when converting csv to agate tables

- sqlmesh/schedulers/airflow/plugin.py
Advanced use case to allow users to manually do state migrations instead of letting Airflow handle it. This should have very limited use cases so not planning on documenting it for now.
> feat: allow disabling airflow state migrations

- sqlmesh/core/context.py
- tests/core/test_integration.py
By explicitly setting backfill models to the set of modified and added models, we ensure that no models outside the modified sub-DAG will be backfilled as part of the development plan, even if the interval end moved ahead in other parts of the DAG.
> Fix: Only backfill modified models in the dev plan if unmodified models are not included

- docs/concepts/audits.md
- sqlmesh/core/audit/definition.py
- tests/core/test_audit.py
I was writing an audit and I figured it would be nice to have defaults for the variables.
I tried it and it almost already works, except it was loading the values as strings instead of expressions.
The goal is to be able to define an audit with defaults like this:
audit (
name generic_sums_add_up,
defaults (
percentage_absolute_difference_accepted=0.01,
)
);
Since defaults has to be a dictionary of string to Expression, it seems to make sense to parse the string values into Expression.
defaults: t.Dict[str, exp.Expression]
I tried the code and it works, but there are some points I'm not sure about.
1. Is it possible to support not needing a trailing comma when there's only one key in the dictionary?
2. Is sqlglot.parse the right way to do it? How would we get the audit's configured …
> Feat: Add support for defaults in user audits

- sqlmesh/core/test/definition.py
- tests/core/test_test.py
Currently, the order of columns in input data generated from a SQL query must be identical to the model definition. This update lifts that restriction, to allow to skip or declare columns in random order without issues. This is addressed by adapting the `_add_missing_columns` function, so that aside from filling with nulls the missing values, to maintain the correct order as well.
> Fix: Support unordered columns in test data generation query

- sqlmesh/core/console.py
Some `TerminalConsole` methods use the verbose attribute, so the debugger init method must set it
> Fix: set DebuggerTerminalConsole verbose to false

- docs/concepts/models/overview.md
- mkdocs.yml
- Add copy button to code blocks for easy copy/pasting
- Enable search suggestions and term highlighting
- Add underscore as search tokenizer separator so words like `runtime_stage` will be returned for a search "stage"
- Enable definition lists without bullets and use them for model concepts overview properties
> Docs: enable easy code copying, improve search

- sqlmesh/core/config/__init__.py
This commit adds two missing ConnectionConfig subclasses to the sqlmesh.core.config __init__.py file:
- BaseDuckDBConnectionConfig
- TrinoConnectionConfig
This allows for easier referencing of the above, and is consistent with the manner in which other ConnectionConfig subclasses are imported.
> Chore: Add Missing ConnectionConfigs to core.config init

- examples/sushi/config.py
- examples/wursthall/config.yaml
- tests/core/test_context.py
These changes allow wursthall to use a persistent duckdb database with the CLI `--gateway duckdb_persistent` option.
They also modify sushi so its persistent duckdb config is specified with the same `--gateway duckdb_persistent` option (rather than the current `--config local_config` option).
> Chore: add persistent duckdb gateway to sushi and wursthall examples

- docs/concepts/macros/macro_variables.md
- docs/concepts/macros/sqlmesh_macros.md
- mkdocs.yml
And revert change from mkdocs `tabbed` to `blocks` extension (which broke tabbed code blocks)
> Docs: clarify macro variables docs, add examples

- docs/concepts/macros/sqlmesh_macros.md
The sqlmesh macros concepts doc contained an example demonstrating typed macro arguments that returned a `str` type, when it should have returned an `exp.Literal` string type.
This PR updates the text to show why returning a `str` type does not work and demonstrates how to return the correct type. It also clarifies the user's responsibility for the macro returning a type that conforms to the semantic type expected in the SQL query.
> Docs: fix typed macro example

- sqlmesh/core/model/__init__.py
- sqlmesh/dbt/basemodel.py
- sqlmesh/dbt/model.py
- tests/dbt/test_transformation.py
The initial implementation of Managed Models was for sqlmesh projects only.
This maps `materialized: dynamic_table` for Snowflake DBT projects to a managed model so dynamic tables can be used in DBT projects
> Feat!: Expose Snowflake dynamic tables through the DBT adapter

- docs/concepts/audits.md
- docs/concepts/overview.md
- docs/reference/model_configuration.md
- sqlmesh/core/config/model.py
- sqlmesh/core/context.py
- sqlmesh/core/dialect.py
- sqlmesh/core/model/definition.py
- sqlmesh/core/model/meta.py
- sqlmesh/core/snapshot/definition.py
- tests/core/test_config.py
- tests/core/test_model.py
This update enables audits in model defaults and to be applied globally. The syntax for each respective audit is similar to the model definition, but is used in the YAML file:
```yaml
audits: 
- assert_positive_order_ids
- does_not_exceed_threshold(column := id, threshold := 1000)
```
fixes: #2567
> Feat: Support enabling audits in model defaults

- .circleci/test_migration.sh
#2938 removed `local_config` from sushi, but it is used in the migration test script. 
This PR updates the script to use the persistent duckdb gateway in the primary config.
> Chore: fix migration test

- sqlmesh/core/model/kind.py
- tests/core/test_model.py
`INCREMENTAL_BY_PARTITION` models are always `forward_only`. If a user specifies the forward_only key with true (or any other value), they currently receive a cryptic pydantic error. 
This PR adds a field validator that provides an error message telling the user not to specify the forward_only key.
> Feat: helpful err msg if forward_only specified in incremental by partition

- sqlmesh/core/notification_target.py
The GenericNotificationTarget object is a subclass of BaseNotificationTarget, and will offer users greater freedom in creating their own custom notifications.
This will be useful for users who do want to use the currently available methods (smtp, slack_webhook, slack_api).
> feat: add GenericNotificationTarget to NotificationTargets

- sqlmesh/dbt/builtin.py
Previously we were using an incorrect attribute name.
> Fix: Use correct attribute to fetch the dialect from a dbt target

- sqlmesh/dbt/manifest.py
This prevents dbt commands from invalidating the manifest cache produced by sqlmesh.
> Fix: Use a distinct name for the dbt manifest cache file

- docs/guides/observer.md
- docs/guides/ui.md
- docs/quickstart/notebook.md
- docs/quickstart/ui.md
- mkdocs.yml
This PR adds lazy image loading to the docs pages containing many images (annoyingly, it cannot be set as default so must be appended to every image inline).
> Docs: lazy load images

- .circleci/install-prerequisites.sh
- Makefile
- tests/core/engine_adapter/config.yaml
`databricks-connect` needs to be installed after the main python dependencies but before tests are run (if it's installed before the main python dependencies then I get a bunch of ImportError's)
this PR modifies its installation to be part of `make databricks-test` and adds an extra requirement for a `DATABRICKS_CONNECT_VERSION` environment variable to be present to allow the user to set the correct version for their cluster
> Chore!: Ensure databricks-connect is actually installed before running Databricks tests

- sqlmesh/core/dialect.py
- tests/core/test_dialect.py
This PR aims to fix the following case:
```
>>> from sqlmesh.core.dialect import parse_one
>>> parse_one("@IF(cond, VACUUM ANALYZE)", dialect="postgres")
'@IF(cond, VACUUM ANALYZE' contains unsupported syntax. Falling back to parsing as a 'Command'.
Alias(
this=MacroFunc(
this=Anonymous(
this=IF,
expressions=[
Column(
this=Identifier(this=cond, quoted=False)),
Command(this=VACUUM)])),
alias=Identifier(this=ANALYZE, quoted=False))
```
The problem is that we're currently producing an `Alias` node as shown above, which happens because SQLGlot tokenizes both `VACUUM` and `ANALYZE` as `TokenType.COMMAND`, instead of producing a `STRING` for the latter.
This is a SQLMesh-related edge case, since SQLGlot doesn't generally expect a statement to show within a function, such as `@IF` in this case.
> Fix: conditional statement parsing edge case

- sqlmesh/core/snapshot/definition.py
- tests/core/test_snapshot.py
Slack context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1721917406454879
This PR allows `lookback` to return the correct missing intervals if the execution date is beyond the model's end date. Prior this, `sqlmesh run` would always show a phantom interval for these models even if the current date was well beyond the model end date + lookback period.
Assuming an incremental model with an end date of `2023-01-05`, `@daily` intervals and a lookback of `2` days:
- The user does not want data from the source system beyond `2023-01-05` so they don't want _new_ intervals after 2023-01-05
- However, they do want already run intervals to re-run after `2023-01-05` if they are within the lookback period
- So the following intervals would run on the following days:
- `2023-01-05` -> …
> Fix!: Handle lookback correctly on incremental models with an end date defined

- .circleci/continue_config.yml
The cloud engine tests are slower and more expensive to run than the docker engine tests.
If a docker engine fails, then the issue has a high chance of affecting a cloud engine as well.
Therefore, we should run the cloud engines after the docker engines. This does have the downside of increasing the overall execution time slightly but the docker engine tests are reasonably fast anyway
> Chore!: Run cloud engines after docker engines

- sqlmesh/core/dialect.py
- tests/core/test_model.py
Right now, Snowflake models that contain queries like:
```sql
SELECT ... FROM @mystage2/data1.json.gz
```
or
```sql
SELECT ... FROM @path.to/some/serialized_dag.csv(FILE_FORMAT => 'foo.bar')
```
can't be loaded by SQLMesh, because:
1. Staged file paths are [subclasses](https://github.com/TobikoData/sqlmesh/blob/ad7edce4f825fc677179b464efd861d617890e8a/sqlmesh/core/dialect.py#L104) of `Table`, meaning that [they're picked up as dependencies](https://github.com/TobikoData/sqlmesh/blob/ad7edce4f825fc677179b464efd861d617890e8a/sqlmesh/core/dialect.py#L995-L1000) (`depends_on`) in models
2. This [line](https://github.com/TobikoData/sqlmesh/blob/ad7edce4f825fc677179b464efd861d617890e8a/sqlmesh/core/model/definition.py#L552) is reached and we fail to parse the staged file path syntax because …
> Fix!: enable loading of Snowflake models that use staged file paths

- sqlmesh/core/table_diff.py
- tests/core/test_table_diff.py
Prior to this change, running `sqlmesh table_diff` with something like `--where "foo = 'bar'"` would throw an error like:
```
duckdb.duckdb.BinderException: Binder Error: Ambiguous reference to column name "foo" (use: "t.foo" or "s.foo")
```
This was because the where clause was injected verbatim without automatically qualifying the columns. The user had to know that table_diff used a subselect internally and supply `--where "s.foo = 'bar' and t.foo = 'bar'"` in order to get this to work.
This PR refactors the generated table_diff query to use CTE's to build the source / target / stats datasets so the `--where` clause can still be injected verbatim but it's now scoped to each dataset so there are no more ambiguous column references
> Fix!: Improve handling of the `--where` option in table_diff

- sqlmesh/core/scheduler.py
- tests/core/test_scheduler.py
Currently, the builtin-scheduler only sends notifications when the `SnapshotEvaluator` raises an `AuditError` exception, which only happens for failing, blocking audits.
This PR addresses two things. First, it delays when the `AuditError` is raised, so that all of the snapshot's audits execute first and second, it sends notifications for all audits that failed, blocking or non-blocking.
> Fix!: Send notifications for failing non-blocking audits from the builtin scheduler

- sqlmesh/core/loader.py
- sqlmesh/core/model/definition.py
- sqlmesh/dbt/loader.py
- tests/core/test_model.py
This update addresses an issue, where macros can't be resolved when called inside audits, fixes: #2948 
It involves scanning the audits as well for macro references and including these macros when constructing the model's Python environment.
> Feat: Support macros within audits

- sqlmesh/core/context.py
- tests/cli/test_cli.py
@treysp noticed that `sqlmesh info` triggers all migrations in a fresh project (e.g. `sqlmesh init duckdb`), which is weird. This happens because the CLI calls `close()` on the instantiated context and in turn that results in doing `self.state_sync` within that method, which creates a new state sync and populates it. We only need to do that if `_state_sync` actually exists.
> Fix: ensure Context.close doesn't unnecessarily create a state sync db

- docs/guides/multi_repo.md
Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1722630215473949
> chore: improve docs multi repo isolated systems

- setup.py
- sqlmesh/core/engine_adapter/snowflake.py
- tests/core/engine_adapter/test_snowflake.py
- tests/core/test_snapshot.py
Prior to this change, attempting to create a Python model on Snowflake utilising a Snowpark DataFrame would produce the following error:
```
snowflake.connector.errors.ProgrammingError: SQL compilation error:  Object found is of type 'VIEW', not specified type 'TABLE'.
```
This is because for Snowpark, the DataFrame is made available via `CREATE TEMPORARY VIEW` but the cleanup logic in the Snowflake engine adapter assumed a Table (because Pandas DataFrames use Tables) and tried to issue `DROP TABLE` instead of `DROP VIEW`.
Now the cleanup logic will issue `DROP VIEW` if a Snowpark DataFrame is in use.
In order to add a test for this, I had to re-introduce a dependency on `snowflake-snowpark-python` (first introduced in #2666 and then removed in #2761)
Since Snowpark doesnt work on Python …
> Fix!: Regression in Snowflake Python models using Snowpark DataFrame's

- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/mysql.py
And move MySQL `try` block inside the column registration loop
> Feat: include column name in failed column registration warning

- sqlmesh/core/loader.py
- tests/core/test_context.py
- tests/core/test_model.py
Model definitions are cached by the SQLMesh loader. Currently, the cached model ID consists of the latest time any project files were modified, a fingerprint of the context config object, and the context's default catalog. 
If a model uses the `@gateway` macro variable, its value will be stored in the model's python environment and included in the cache. If the project is run with a different gateway, a cache hit can occur with the wrong gateway value being rendered into the model.
This PR fixes this by adding the gateway name to the model cache ID. 
Implications:
- All project models will have a cache miss when the gateway changes. The miss will be unnecessary for all models that do not use the `@gateway` macro variable.
- An alternative approach is to leave the cache ID as-is, and after …
> Fix: add gateway name to model cache identifier

- sqlmesh/core/loader.py
- sqlmesh/core/model/decorator.py
- sqlmesh/core/model/definition.py
- tests/core/test_model.py
- tests/core/test_snapshot_evaluator.py
- tests/integrations/jupyter/test_magics.py
This update introduces the ability to enable pre- and post-statements in python models that can be executed during the table creation phase, fixes: #2866 
The SqlBased model renderers has been moved to the `_Model` class, so that the logic can be reused by python models. Also to support macro calls in the pre- and post-statements, the python environment is updated with the referenced macros (similarly to sql models).
> Feat!: Support pre-post statements in python models at creation time

- sqlmesh/core/engine_adapter/snowflake.py
- tests/core/engine_adapter/test_snowflake.py
Snowflake adapter creates comments on tables/views one by one (the default behavior) which can get really slow when working with wide tables (upwards of 5 mins for the update step, which took 20s after the change). 
The `ALTER TABLE` syntax in snowflake supports adding multiple column comments at once, which we use here. The `ALTER VIEW` syntax doc doesn't mention it, but it works there too. 
1 - https://docs.snowflake.com/en/sql-reference/sql/alter-table-column#syntax
2 - https://docs.snowflake.com/en/sql-reference/sql/alter-view#syntax
Please let me know if this needs more testing. I tested this works in my project, and by manually running the sql generated in the added test routine.
> create snowflake comments in bulk

- examples/sushi/models/items.py
- examples/sushi/models/order_items.py
- examples/sushi/models/orders.py
- examples/sushi/models/raw_marketing.py
- examples/sushi/models/waiters.py
And address pandas warnings by resetting DF indexes in sushi python models
Context:
- Snowflake normalizes unquoted object names to uppercase, which can cause case mismatches with default_catalog due to sqlmesh's default normalization behavior. 
- SQLMesh addresses this by rewriting the default catalog name on the fly in snowflake `_to_sql()`. 
- Sushi's waiters.py model code manually extracts default_catalog name prior to the rewriting, so we must manually lowercase the default_catalog if the parent catalog name is an uppercase version of the default catalog name.
> Chore: fix sushi waiters default_catalog capitalization

- sqlmesh/core/engine_adapter/snowflake.py
The snowflake `_build_create_comment_column_exp` method is only called in base `_create_column_comments`, but we now override base `_create_column_comments` in snowflake and no longer call snowflake build anywhere (#2991)
> Chore: remove dead snowflake comment code

- sqlmesh/core/snapshot/definition.py
- sqlmesh/utils/date.py
- tests/core/test_snapshot.py
refactor of how lookback works. the current implementation has some weird interactions with cron that makes non standard crons and lookback always backfill no matter what.
this refactors missing_intervals to only check for lookback when there are any missing intervals to begin with, otherwise we don't bother with lookback.
> fix: make lookback conditional on missing intervals closes #2985

- examples/sushi/macros/macros.py
- examples/sushi/models/marketing.sql
- sqlmesh/core/macros.py
- tests/core/test_context.py
- tests/integrations/jupyter/test_magics.py
This PR makes the `columns_to_types` method more lenient by leveraging any existing snapshots in the evaluator's context as a fallback to fetch the target model's schema.
The motivation can be found [here](https://tobiko-data.slack.com/archives/C044BRE5W4S/p1723568953070039?thread_ts=1723562831.081849&cid=C044BRE5W4S): one real-world example is executing `ALTER` statements for the physical table of a model after it's created, for which we need to know the model's schema. This is not possible today, because the model's own schema is not included in its `mapping_schema` -- it only includes its dependencies' schemas.
I also added a guard that protects from returning the dummy schema unless we're at the loading runtime stage, to avoid cryptic errors such as "Column …
> Feat: make MacroEvaluator.columns_to_types more lenient

- sqlmesh/core/audit/builtin.py
- tests/core/test_audit.py
Fix for the generated queries of the built-in pattern matching audits: `match_regex_pattern_list` and `match_like_pattern_list` by switching the operators in the query from `or` to `and`.
> Fix: Builtin pattern matching audits operators

- sqlmesh/core/config/scheduler.py
- sqlmesh/core/constants.py
- sqlmesh/core/context.py
- sqlmesh/core/loader.py
- sqlmesh/core/scheduler.py
- tests/core/test_scheduler.py
This is a follow-up to https://github.com/TobikoData/sqlmesh/pull/2822 to allow loading a `signal_factory` from the sqlmesh project structure instead of having to specify it to the `Context`. This allows using built-in signals without any extra configuration in `config.py` or similar.
> feat: automatically load signals from the `signals/` subfolder

- sqlmesh/core/model/definition.py
- tests/core/test_seed.py
This update fixes an issue when reading from `csv` files that contain booleans doesn't convert individual elements of the column
> Fix: Converting boolean columns from CSV files

- sqlmesh/core/engine_adapter/base.py
- tests/core/engine_adapter/test_base.py
- tests/core/engine_adapter/test_integration.py
- tests/core/test_model.py
Prior to this change when converting a pandas dataframe to SQL we would use the full columns to types, which included managed columns `valid_from` and `valid_to`, when selecting from the values created from the dataframe. There is actually a test that exposes this bug that I didn't catch: https://github.com/TobikoData/sqlmesh/blob/f9d5880429465149d9b613b606a436259803e571/tests/core/engine_adapter/test_base.py#L1395-L1407
Now we remove the managed columns from converting the dataframe. Also updated the integration test to properly reflect how the method gets called (before it was being called with unmanaged columns instead of all columns which is why the test passed).
> fix: properly handle panda columns scd type 2

- sqlmesh/dbt/builtin.py
- sqlmesh/dbt/source.py
- tests/dbt/test_config.py
- tests/dbt/test_manifest.py
- tests/fixtures/dbt/sushi_test/models/schema.yml
An update to the dbt adapter to resolve sources' tables from an external location when specified in the source metadata, rather than using schema and table names, fixes: #2988
> Feat: Add support for dbt sources external location defined in meta

- sqlmesh/core/notification_target.py
- sqlmesh/integrations/slack.py
Each time the SQLMesh CI bot runs, we see these warnings:
```
/home/runner/.cache/pypoetry/virtualenvs/pipe-dwh-Jd5RneRz-py3.11/lib/python3.11/site-packages/slack_sdk/web/internal_utils.py:288: UserWarning: The top-level `text` argument is missing in the request payload for a chat.postMessage call - It's a best practice to always provide a `text` argument when posting a message. The `text` argument is used in places where content cannot be rendered such as: system push notifications, assistive technology such as screen readers, etc.
warnings.warn(missing_text_message, UserWarning)
/home/runner/.cache/pypoetry/virtualenvs/pipe-dwh-Jd5RneRz-py3.11/lib/python3.11/site-packages/slack_sdk/web/internal_utils.py:289: UserWarning: Additionally, the attachment-level `fallback` argument is missing …
```
> fix: slack user warning :: the top level `text` argument is missing in the request payload

- sqlmesh/core/config/scheduler.py
- sqlmesh/core/context.py
- sqlmesh/core/plan/builder.py
- sqlmesh/core/plan/definition.py
- sqlmesh/core/plan/evaluator.py
- sqlmesh/core/scheduler.py
- sqlmesh/core/snapshot/definition.py
- sqlmesh/core/state_sync/base.py
- sqlmesh/core/state_sync/engine_adapter.py
- sqlmesh/schedulers/airflow/api.py
- sqlmesh/schedulers/airflow/client.py
- sqlmesh/schedulers/airflow/common.py
- sqlmesh/schedulers/airflow/plan.py
- sqlmesh/schedulers/airflow/state_sync.py
- tests/core/test_context.py
- tests/core/test_integration.py
- tests/core/test_plan.py
- tests/core/test_plan_evaluator.py
- tests/core/test_state_sync.py
- tests/schedulers/airflow/test_client.py
- tests/schedulers/airflow/test_plan.py
Previously we were using one end date per plan for all models that are part of the plan. This approach has proven problematic because, at times, SQLMesh derived incorrect missing intervals for some models when making changes in dev, especially when the cron expression didn't align with day / hour boundaries.
This update ensures that each individual model receives its own end date value, ensuring that SQLMesh correctly backfills changes up to what is already available in the target environment.
> Chore!: Set interval end per model in plan

- sqlmesh/core/state_sync/engine_adapter.py
- sqlmesh/migrations/v0055_add_updated_ts_unpaused_ts_ttl_ms_unrestorable_to_snapshot.py
Fix for:
```
>>> from sqlmesh.core.context import Context
>>>
>>> ctx = Context()
>>> ctx.migrate()
File "/Users/georgesittas/Code/tobiko/sqlmesh/sqlmesh/core/state_sync/engine_adapter.py", line 1218, in migrate
self._migrate_rows(promoted_snapshots_only)
File "/Users/georgesittas/Code/tobiko/sqlmesh/sqlmesh/core/state_sync/engine_adapter.py", line 1317, in _migrate_rows
snapshot_mapping = self._migrate_snapshot_rows(snapshots_to_migrate)
File "/Users/georgesittas/Code/tobiko/sqlmesh/sqlmesh/core/state_sync/engine_adapter.py", line 1462, in _migrate_snapshot_rows
_visit(root_snapshot_id, {})
File "/Users/georgesittas/Code/tobiko/sqlmesh/sqlmesh/core/state_sync/engine_adapter.py", line 1380, in _visit
snapshot = parsed_snapshots[snapshot_id]
File …
```
> Fix: Snapshot parsing during migration

- sqlmesh/core/plan/builder.py
- sqlmesh/core/plan/definition.py
- tests/core/test_integration.py
- tests/core/test_plan.py
This resolves the issue where a DAG has a structure like A <- B (B is downstream of A) and the model A is modified and selected (using `--select-model`) in a dev plan. A user then creates a follow-up plan and selects model B (again using `--select-model`) in order to backfill it. SQLMesh used to backfill B in the second plan but didn't create a view for it in the virtual layer, which rendered the changed model's output inaccessible.
> Fix: Include models selected for backfill in the virtual layer even if they haven't been changed directly

- sqlmesh/utils/metaprogramming.py
- tests/utils/test_metaprogramming.py
`sqlmesh.core.dialect.normalize_model_name` uses lru_cache. 
https://github.com/z3z1ma/sqlmesh/blob/0b3aeac041b280cb79bee51613648a9fce4c5646/sqlmesh/core/dialect.py#L960-L981
Serialization fails on this object when calling inspect.getfile
This is a common import. This bug would've been introduced by #3008 as I don't think there was an lru cache there before
I added a failing test by simply referencing the function in question in the main_func in test_metaprogramming
---
I fixed it by using `inspect.unwrap` to safely unwrap to func specifically in the getfile call. This returns the correct file path.
https://docs.python.org/3/library/inspect.html#inspect.unwrap
I have confirmed tests pass and this works on my production project too (whereas before it was bugged/un-runnable). 
---
In the …
> Fix: serialization regression with sqlmesh.core.dialect.normalize_model_name

- sqlmesh/core/engine_adapter/base.py
- sqlmesh/core/engine_adapter/bigquery.py
- sqlmesh/core/engine_adapter/trino.py
- tests/core/engine_adapter/test_integration.py
Prior to this PR some engines provided a connection while others did not. This makes the property consistent across all engine adapters and since it uses the connection created at the connection pool layer it can be done consistently across engines.
> chore: make connection creation consistent

- sqlmesh/utils/metaprogramming.py
- tests/core/test_model.py
- tests/utils/test_metaprogramming.py
Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1724232161253179
In current main, having a macro like the following doesn't work because we don't walk the function parameters to extract global references, such as modules and the like.
```
from sqlglot import exp
from sqlmesh import macro
@macro()
def test_default_param(evaluator, boolean_var: exp.Boolean = exp.true()):
return boolean_var
```
> Fix: introspect function defaults to extract global refs for serialization

- sqlmesh/core/model/definition.py
- sqlmesh/core/renderer.py
- tests/core/test_model.py
This is a QOL improvement to allow some models to be more dynamic. For example, it could be used to easily define models that are based on a templated query (defined within the macro) and only need specific clauses of that query to be parameterized.
Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1722466563283509
cc: @crericha
> Feat: allow a single macro function call in model definitions

- sqlmesh/dbt/context.py
- tests/dbt/test_transformation.py
Previously we introduced a regression by including redundant references. 
For example, if a model references another model with `ref('some_model')`, we included both `some_model` and `model_package.some_model` entries in the Jinja macro registry, even though only `some_model` was necessary.
> Fix: Only include used refs into jinja globals when converting dbt models

- sqlmesh/core/console.py
This update aims to improve the readability of table diff CLI output, fixes: #2645 
This format will print the columns being compared individually along with their associated keys in source and target tables side by side:
Column: num_orders
| item_id | PROD | DEV |
|---------|------|-----|
| 1       | 5    | 26  |
| 2       | 1    | 22  |
| 3       | 1    | 22  |
> Feat: Improve table diff sample output in CLI

- sqlmesh/core/snapshot/cache.py
- sqlmesh/core/snapshot/definition.py
- tests/core/test_snapshot.py
Intervals should never be cached so that they can be hydrated correctly after snapshots are loaded from cache.
> Fix: Don't cache snapshot intervals

- sqlmesh/core/context.py
- sqlmesh/core/plan/builder.py
- sqlmesh/core/snapshot/definition.py
- tests/core/test_integration.py
- tests/core/test_plan.py
- tests/core/test_snapshot.py
The last backfilled interval for each model should only be take into account if no explicit end date was provided by a user. Otherwise the user provided value should always take precedence.
This resolves the issue for seed models that have been backfilled once, models with an end date, and models with a broad execution cadence (e.g., monthly) where the start date value ends up being greater than the end date value.
```
ValueError: Start date / time (2024-08-20 00:00:00+00:00) can't be greater than end date / time (1715126400000)
```
> Fix: User-provided plan end must take precedence over the max interval end per model

- sqlmesh/core/context.py
- tests/core/test_integration.py
It should use the minimum value among the maximum interval end values to make a more accurate estimate for models whose cron is not aligned with a day boundary.
> Fix: Heuristics that determine the default start date of the forward-only preview plan

- sqlmesh/core/context.py
- sqlmesh/core/dialect.py
- sqlmesh/core/model/definition.py
- tests/core/test_model.py
Since model name inference is now [supported](https://sqlmesh.readthedocs.io/en/stable/guides/configuration/?h=#model-naming), the `MODEL` meta may not be needed when defining models. This PR relaxes some constraints in order to support models that only contain a query and optional pre/post-statements.
Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1724422066768009
> Fix: allow omitting the MODEL (...) block when name inference is activated

- sqlmesh/core/context.py
- sqlmesh/core/context_diff.py
- sqlmesh/core/environment.py
- sqlmesh/core/state_sync/engine_adapter.py
- tests/core/test_integration.py
- tests/core/test_state_sync.py
With this update, whenever the plan command targets an environment that has expired, it will behave as if it were missing instead.
> Chore: Treat the target environment as missing during planning if it's expired

- sqlmesh/core/model/definition.py
- tests/core/test_model.py
This update aims to resolve a lookup issue in `render_seed` by renaming the columns that are looked up and can't be resolved (due to being [normalised](https://github.com/TobikoData/sqlmesh/blob/aa3ee94e1d41c18d41d95565dc1b7d0d4e331921/sqlmesh/core/model/seed.py#L78C9-L78C16)) with the names from the model definition columns, fixes: #2698
> Fix: Seed and model column mismatch due to normalization

- sqlmesh/core/console.py
- sqlmesh/core/table_diff.py
- tests/core/test_table_diff.py
This update adds placeholder environment source and target names to the joined sample (when `source_alias` and `target_alias` are not defined during the construction of the TableDiff) in order to differentiate the output results in row_diff and display results when calling `show_row_diff`.
> Fix: Handle missing source target aliases in sample data diff

- sqlmesh/core/config/connection.py
- sqlmesh/core/engine_adapter/bigquery.py
- sqlmesh/dbt/model.py
- tests/core/engine_adapter/test_bigquery.py
- tests/core/test_connection_config.py
Biquery "projects" are associated with both object location (catalog in 3-level names) and with computation (computations are executed by a specific project).
Our BQ connection configuration provides an [`execution_project` field](#2181) that allows users to execute the computations with a different project than the location of the objects.
Bigquery's default catalog is the user-specified connection field `project`, if present. Otherwise, it is the project to which the BQ client is connected (which is `execution_project` when present).
In the `incremental_by_partition` model kind, we manually construct a query of the BQ partitions metadata view. Because that query is manually constructed it does not pass through the `@set_catalog()` decorator and was incorrectly using the client …
> Fix(bigquery): do not use execution_project as default catalog in partitions query

- sqlmesh/core/selector.py
- tests/core/test_selector.py
Otherwise the plan produces unexpected diffs since expired environments are ignored in `context_diff`.
> Fix: Ignore expired environments in the selector
